//! `// <<< CUSTOM` block merger for Rust source files.
//!
//! Files generated by the schema command can contain user-authored regions
//! that survive regeneration. Two marker styles are recognised:
//!
//! - **Single-line markers** — a `// <<< CUSTOM` line followed by zero or
//!   more code lines. The block ends at the next blank line OR at a paired
//!   `// END CUSTOM`. Handled in [`single_marker`].
//! - **Paired `// <<< CUSTOM METHODS START >>>` / `// <<< CUSTOM METHODS END >>>`**
//!   blocks — every line between the markers is preserved verbatim.
//!   Handled in [`paired_methods`].
//!
//! [`merge_rust_mod_custom`] is the entry point that runs both phases in
//! order. Shared marker predicates live in [`markers`]; the
//! [`unprotected`] scanner is exposed separately so the write loop can
//! warn users about lines that would be lost.

mod markers;
mod paired_methods;
mod single_marker;
mod unprotected;

pub(in crate::commands::schema) use unprotected::detect_unprotected_custom_code;

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use paired_methods::merge_custom_methods_block;
use single_marker::{collect_custom_blocks, insert_custom_blocks};

/// Merge Rust files (typically `mod.rs`, but the strategy applies to any
/// generated `.rs` file), preserving `// <<< CUSTOM` regions.
///
/// Two phases:
///
/// 1. **Paired `CUSTOM METHODS` blocks** ([`paired_methods`]) — extract
///    from the existing file and substitute into the generated content,
///    verbatim.
/// 2. **Single-line `// <<< CUSTOM` markers** ([`single_marker`]) —
///    collect with their anchors and re-insert using the inside-vs-after
///    container placement heuristic.
pub(in crate::commands::schema) fn merge_rust_mod_custom(
    generated_content: &str,
    existing_path: &Path,
) -> Result<String> {
    if !existing_path.exists() {
        return Ok(generated_content.to_string());
    }

    let existing_content = fs::read_to_string(existing_path)
        .with_context(|| format!("Failed to read existing mod file: {:?}", existing_path))?;

    let result = merge_custom_methods_block(generated_content, &existing_content);

    let custom_blocks = collect_custom_blocks(&existing_content, &result);
    if custom_blocks.is_empty() {
        return Ok(result);
    }

    let mut result_lines: Vec<String> = result.lines().map(|l| l.to_string()).collect();
    insert_custom_blocks(&mut result_lines, &custom_blocks);
    Ok(result_lines.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_temp(content: &str) -> (tempfile::NamedTempFile, std::path::PathBuf) {
        let mut f = tempfile::NamedTempFile::with_suffix(".rs").unwrap();
        f.write_all(content.as_bytes()).unwrap();
        let path = f.path().to_path_buf();
        (f, path)
    }

    #[test]
    fn test_inline_custom_marker_preserved() {
        let existing = "mod foo;\nmod foo_custom; // <<< CUSTOM - Extension\nmod bar;\n";
        let generated = "mod foo;\nmod bar;\n";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        assert!(result.contains("foo_custom"), "custom mod declaration should be preserved");
        assert!(result.contains("// <<< CUSTOM"), "custom marker should be preserved");
    }

    #[test]
    fn test_paired_custom_block_preserved() {
        let existing = "let x = 1;\n// <<< CUSTOM - Custom init\nlet y = 2;\nlet z = 3;\n// END CUSTOM\nlet w = 4;\n";
        let generated = "let x = 1;\nlet w = 4;\n";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        assert!(result.contains("let y = 2;"), "custom line y should be preserved");
        assert!(result.contains("let z = 3;"), "custom line z should be preserved");
        assert!(result.contains("// END CUSTOM"), "END CUSTOM marker should be present");
    }

    /// Regression: the named paired format `// <<< CUSTOM <SECTION> START >>>` ...
    /// `// <<< CUSTOM <SECTION> END >>>` (emitted by the exports/handlers/seeder
    /// generators) was wiped on regen — the END line contains `// <<< CUSTOM`,
    /// so it was misread as a START and the block never closed. The predicates
    /// now disambiguate by the ` START >>>` / ` END >>>` suffix.
    #[test]
    fn test_named_custom_block_preserved() {
        let existing = "\
let x = 1;
// <<< CUSTOM SERVICES START >>>
fn port() -> u64 { 42 }
// <<< CUSTOM SERVICES END >>>
let w = 4;
";
        let generated = "let x = 1;\nlet w = 4;\n";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        assert!(
            result.contains("fn port() -> u64 { 42 }"),
            "named CUSTOM block content should be preserved, got:\n{result}"
        );
        assert!(
            result.contains("<<< CUSTOM SERVICES END >>>"),
            "named END marker should be recognised as a close, got:\n{result}"
        );
    }

    /// Regression: a CUSTOM block whose first line is a template-placeholder
    /// comment ("// Add custom services here") was dedup-skipped because that
    /// comment also appears in the generated output — wiping the real code
    /// beneath it. Dedup now keys on the first CODE line, not the first comment.
    #[test]
    fn test_custom_block_with_leading_placeholder_comment_preserved() {
        let existing = "\
let x = 1;
// <<< CUSTOM SERVICES START >>>
// Add custom public services here
fn port() -> u64 { 42 }
// <<< CUSTOM SERVICES END >>>
let w = 4;
";
        let generated = "\
let x = 1;
// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
let w = 4;
";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        assert!(
            result.contains("fn port() -> u64 { 42 }"),
            "block with a leading placeholder comment should preserve the real code, got:\n{result}"
        );
    }

    /// Regression: when the generated CUSTOM block ships EXAMPLE content (e.g. a
    /// `health_check` handler the template emits inside CUSTOM HANDLERS), the
    /// user's filled block must REPLACE it — not be dedup-skipped because the
    /// example's first code line also appears in the generated output. The user
    /// owns a CUSTOM region; their content wins.
    #[test]
    fn test_generated_custom_block_with_example_is_replaced_by_user_block() {
        let existing = "\
use super::AppState;
// <<< CUSTOM HANDLERS START >>>
pub async fn my_handler() -> u64 { 42 }
// <<< CUSTOM HANDLERS END >>>
";
        let generated = "\
use super::AppState;
// <<< CUSTOM HANDLERS START >>>
#[allow(dead_code)]
pub async fn health_check() {}
// <<< CUSTOM HANDLERS END >>>
";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        assert!(
            result.contains("pub async fn my_handler() -> u64 { 42 }"),
            "user's CUSTOM block must replace the generated example, got:\n{result}"
        );
        assert!(
            !result.contains("health_check"),
            "generated example must be replaced (user content wins in CUSTOM), got:\n{result}"
        );
    }

    /// Regression: a comment-only CUSTOM block (a template placeholder like
    /// "// Add custom X here", no real code) must NOT be collected and re-inserted
    /// on regen — otherwise the placeholder is duplicated on every run. Only
    /// blocks containing real code are preserved.
    #[test]
    fn test_comment_only_custom_block_not_duplicated() {
        let existing = "\
use super::AppState;
// <<< CUSTOM HANDLERS START >>>
// Add custom handlers here
// <<< CUSTOM HANDLERS END >>>
";
        let generated = "\
use super::AppState;
// <<< CUSTOM HANDLERS START >>>
// Add custom handlers here
// <<< CUSTOM HANDLERS END >>>
";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        let count = result.matches("// <<< CUSTOM HANDLERS START >>>").count();
        assert_eq!(
            count, 1,
            "comment-only placeholder block must not be duplicated, got:\n{result}"
        );
    }

    #[test]
    fn test_no_duplicate_custom_blocks() {
        let existing = "mod foo;\n// <<< CUSTOM - Extension\nmod bar;\n";
        let generated = "mod foo;\nmod bar;\n";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        let count = result.lines().filter(|l| l.trim() == "mod bar;").count();
        assert_eq!(count, 1, "mod bar; should appear only once after dedup");
    }

    #[test]
    fn test_fuzzy_anchor_matching_with_clone() {
        let existing = "\
let repo = Arc::new(Repo::new(pool.clone()));
let service = Arc::new(Service::new(repo.clone()));
// <<< CUSTOM
let custom = CustomService::new(repo);
// END CUSTOM
";
        let generated = "\
let repo = Arc::new(Repo::new(pool.clone()));
let service = Arc::new(Service::new(repo));
";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        assert!(result.contains("CustomService"), "custom block should be placed via fuzzy anchor");
        let svc_pos = result.find("let service").unwrap();
        let custom_pos = result.find("CustomService").unwrap();
        assert!(svc_pos < custom_pos, "custom block should come after anchor line");
    }

    /// Regression: an earlier implementation capped paired CUSTOM blocks
    /// at 200 lines, which silently truncated legitimate large blocks
    /// (e.g. multi-line `matches!` macros). Commit 11723ed removed the cap
    /// once a paired `END CUSTOM` is confirmed. This test pins that
    /// behaviour: every line between the markers survives the merge.
    /// Regression: when the codegen template is upgraded between regens, it can rename a CUSTOM marker
    /// (`// <<< CUSTOM` → `// <<< CUSTOM FIELDS`) AND change the surrounding lines (e.g. `pub` →
    /// `pub(crate)` on service fields). The merge then can't anchor the user's struct-field block — it
    /// must relocate into the generated `// <<< CUSTOM FIELDS` slot inside the struct, not strand at
    /// EOF (which broke backbone-integrations' build on 2026-08-05).
    #[test]
    fn test_unanchored_field_block_relocates_into_custom_fields_slot() {
        let existing = "\
pub struct FooModule {
    pub connector_service: Arc<ConnectorService>,
    // <<< CUSTOM
    pub write_service: Arc<WriteService>,
    // END CUSTOM
}
";
        let generated = "\
pub struct FooModule {
    pub(crate) connector_service: Arc<ConnectorService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}
";
        let (_tmp, path) = write_temp(existing);
        let result = merge_rust_mod_custom(generated, &path).unwrap();

        let field_pos = result
            .find("pub write_service")
            .expect("the write-service field should be present");
        let struct_close = result.rfind('}').expect("struct should close");
        assert!(
            field_pos < struct_close,
            "field must land INSIDE the struct, got:\n{result}"
        );
        let after_close = &result[struct_close..];
        assert!(
            !after_close.contains("write_service"),
            "field must not strand at EOF after the struct, got:\n{result}"
        );
    }

    #[test]
    fn test_large_paired_custom_block_preserved_in_full() {
        let mut existing = String::from("let x = 1;\n// <<< CUSTOM\n");
        for i in 0..250 {
            existing.push_str(&format!("let line_{} = {};\n", i, i));
        }
        existing.push_str("// END CUSTOM\n");
        let generated = "let x = 1;\n";
        let (_tmp, path) = write_temp(&existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        let custom_lines: Vec<&str> = result
            .lines()
            .filter(|l| l.starts_with("let line_"))
            .collect();
        assert_eq!(
            custom_lines.len(),
            250,
            "all 250 lines inside a paired CUSTOM block should be preserved verbatim, got {}",
            custom_lines.len()
        );
    }

    #[test]
    fn test_no_custom_markers_returns_generated() {
        let existing = "mod foo;\nmod bar;\n";
        let generated = "mod foo;\nmod baz;\n";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        assert_eq!(result, generated, "should return generated content unchanged");
    }

    #[test]
    fn test_empty_existing_file() {
        let existing = "";
        let generated = "mod foo;\nmod bar;\n";
        let (_tmp, path) = write_temp(existing);

        let result = merge_rust_mod_custom(generated, &path).unwrap();
        assert_eq!(result, generated, "should return generated content for empty existing file");
    }

    /// Regression: when the generator flips from type-alias output (else-branch)
    /// to struct+impl output (if-branch), the old anchor line (`pub type ...`)
    /// must not leak into the new file. Previously the empty `// <<< CUSTOM`
    /// block was preserved with its anchor, appending the stale alias lines.
    #[test]
    fn test_branch_flip_does_not_leak_old_alias() {
        let existing = "\
//! Domain policy for CustomerLoyaltyAccount aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::CustomerLoyaltyAccount;

/// Domain policy for CustomerLoyaltyAccount — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<CustomerLoyaltyAccount>` in the `// <<< CUSTOM` zone.
pub type CustomerLoyaltyAccountDomainPolicy = PermitAllPolicy<CustomerLoyaltyAccount>;

// <<< CUSTOM
// END CUSTOM
";
        let generated = "\
//! Domain policy for CustomerLoyaltyAccount aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.

use async_trait::async_trait;
use backbone_core::{DomainPolicy, PolicyDecision};
use crate::domain::entity::CustomerLoyaltyAccount;

/// Domain policy for CustomerLoyaltyAccount — enforces business invariants.
pub struct CustomerLoyaltyAccountDomainPolicy;

#[async_trait]
impl DomainPolicy<CustomerLoyaltyAccount> for CustomerLoyaltyAccountDomainPolicy {
    // <<< CUSTOM
    // Add entity-specific invariant checks here.
    // END CUSTOM
}
";
        let (_tmp, path) = write_temp(existing);
        let result = merge_rust_mod_custom(generated, &path).unwrap();

        assert!(
            !result.contains("pub type CustomerLoyaltyAccountDomainPolicy = PermitAllPolicy"),
            "old type alias must not leak into merged output; got:\n{}",
            result
        );
        assert!(
            !result.contains("in the `// <<< CUSTOM` zone."),
            "stale else-branch doc line must not be appended; got:\n{}",
            result
        );
        assert!(result.contains("pub struct CustomerLoyaltyAccountDomainPolicy;"));
        assert!(result.contains("impl DomainPolicy<CustomerLoyaltyAccount>"));
    }
}
