//! Application layer generators
//!
//! Generates:
//! - Use case implementations
//! - Application services
//! - DTOs and mappers

mod usecase;
mod app_service;

pub use usecase::UseCaseGenerator;
pub use app_service::AppServiceGenerator;

use std::fs;

use crate::webgen::ast::entity::{EntityDefinition, EnumDefinition};
use crate::webgen::ast::HookSchema;
use crate::webgen::config::Config;
use crate::webgen::error::Result;
use crate::webgen::generators::domain::DomainGenerationResult;
use crate::webgen::parser::to_pascal_case;

/// Application layer generator
pub struct ApplicationGenerator {
    usecase_gen: UseCaseGenerator,
    app_service_gen: AppServiceGenerator,
    config: Config,
}

impl ApplicationGenerator {
    /// Create a new application generator
    pub fn new(config: Config) -> Self {
        Self {
            usecase_gen: UseCaseGenerator::new(config.clone()),
            app_service_gen: AppServiceGenerator::new(config.clone()),
            config,
        }
    }

    /// Generate all application layer components
    pub fn generate_all(
        &self,
        entities: &[EntityDefinition],
        enums: &[EnumDefinition],
        hooks: &[HookSchema],
    ) -> Result<DomainGenerationResult> {
        let mut result = DomainGenerationResult::new();

        // Find hook for entity by name matching
        let find_hook = |entity_name: &str| -> Option<&HookSchema> {
            hooks.iter().find(|h| h.model.eq_ignore_ascii_case(entity_name))
        };

        // Generate for each entity
        for entity in entities {
            let hook_schema = find_hook(&entity.name);

            // Use case implementations
            let usecase_result = self.usecase_gen.generate(entity, enums, hook_schema)?;
            self.merge_result(&mut result, usecase_result);

            // Application service
            let service_result = self.app_service_gen.generate(entity, enums)?;
            self.merge_result(&mut result, service_result);
        }

        // Generate index files
        self.generate_index_files(entities, &mut result)?;

        Ok(result)
    }

    /// Merge a sub-result into the main result
    fn merge_result(&self, main: &mut DomainGenerationResult, sub: DomainGenerationResult) {
        main.files_generated.extend(sub.files_generated);
        main.dry_run_files.extend(sub.dry_run_files);
    }

    /// Generate index files for application layer
    fn generate_index_files(
        &self,
        entities: &[EntityDefinition],
        result: &mut DomainGenerationResult,
    ) -> Result<()> {
        let base_dir = self.config.output_dir
            .join("application")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&base_dir).ok();
        }

        // Generate main index
        let index_content = self.generate_index_content(entities);
        let index_path = base_dir.join("index.ts");

        result.add_file(index_path.clone(), self.config.dry_run);
        if !self.config.dry_run {
            fs::write(&index_path, index_content).ok();
        }

        Ok(())
    }

    fn generate_index_content(&self, entities: &[EntityDefinition]) -> String {
        let exports: Vec<String> = entities.iter()
            .map(|e| {
                let pascal = to_pascal_case(&e.name);
                format!(
                    "export * from './usecases/{pascal}UseCases';\nexport * from './services/{pascal}AppService';",
                    pascal = pascal
                )
            })
            .collect();

        // Scan for existing mapper files and include them in exports
        let mapper_exports = self.collect_mapper_exports();

        let mut content = format!(
            "// Application layer exports for {} module\n// Generated by metaphor-webgen\n\n{}\n",
            self.config.module,
            exports.join("\n")
        );

        if !mapper_exports.is_empty() {
            content.push_str(&format!("\n// Mappers\n{}\n", mapper_exports.join("\n")));
        }

        content
    }

    /// Collect export statements for existing mapper files in the mappers/ directory
    fn collect_mapper_exports(&self) -> Vec<String> {
        let mappers_dir = self.config.output_dir
            .join("application")
            .join(&self.config.module)
            .join("mappers");

        let mut exports = Vec::new();

        if mappers_dir.exists() {
            if let Ok(entries) = fs::read_dir(&mappers_dir) {
                let mut file_names: Vec<String> = entries
                    .filter_map(|entry| entry.ok())
                    .filter_map(|entry| {
                        let path = entry.path();
                        if path.extension().and_then(|e| e.to_str()) == Some("ts")
                            && !path.file_name()
                                .and_then(|f| f.to_str())
                                .map(|f| f.starts_with("index"))
                                .unwrap_or(false)
                        {
                            path.file_stem()
                                .and_then(|s| s.to_str())
                                .map(|s| s.to_string())
                        } else {
                            None
                        }
                    })
                    .collect();

                file_names.sort();

                for name in file_names {
                    exports.push(format!("export * from './mappers/{name}';"));
                }
            }
        }

        exports
    }
}
