//! AppState Generator
//!
//! Generates the AppState dependency injection container for HTTP handlers.
//! This enables stateful route handling with access to all module services.
//!
//! ## Generated Files
//!
//! - `src/handlers/mod.rs` - AppState struct with all service dependencies

use super::{GenerateError, GeneratedOutput, Generator};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates AppState dependency injection container
pub struct AppStateGenerator;

impl AppStateGenerator {
    pub fn new() -> Self {
        Self
    }
}

impl Default for AppStateGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for AppStateGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        let handlers_mod = self.generate_handlers_mod(schema)?;
        output.add_file(PathBuf::from("src/handlers/mod.rs"), handlers_mod);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "app_state"
    }
}

impl AppStateGenerator {
    fn generate_handlers_mod(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        // Header
        writeln!(output, "//! {} Module Handlers", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This module provides:").unwrap();
        writeln!(output, "//! - AppState dependency injection container").unwrap();
        writeln!(output, "//! - Custom handler integration points").unwrap();
        writeln!(output).unwrap();

        // Imports
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// Import all services").unwrap();

        // Import services for each model
        for model in &schema.schema.models {
            let service_name = format!("{}Service", to_pascal_case(&model.name));
            writeln!(output, "use crate::application::service::{};", service_name).unwrap();
        }
        writeln!(output).unwrap();

        // AppState struct
        writeln!(output, "/// Application state for dependency injection.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// This struct holds references to all module services").unwrap();
        writeln!(output, "/// and is passed to HTTP handlers via Axum's State extractor.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// # Example").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ```ignore").unwrap();
        writeln!(output, "/// use axum::extract::State;").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// async fn custom_handler(").unwrap();
        writeln!(output, "///     State(state): State<AppState>,").unwrap();
        writeln!(output, "/// ) -> impl IntoResponse {{").unwrap();
        writeln!(output, "///     // Access services via state").unwrap();
        writeln!(output, "/// }}").unwrap();
        writeln!(output, "/// ```").unwrap();
        writeln!(output, "#[derive(Clone)]").unwrap();
        writeln!(output, "pub struct AppState {{").unwrap();

        // Service fields
        for model in &schema.schema.models {
            let field_name = to_snake_case(&model.name);
            let service_name = format!("{}Service", to_pascal_case(&model.name));
            writeln!(output, "    /// {} service", to_pascal_case(&model.name)).unwrap();
            writeln!(output, "    pub {}_service: Arc<{}>,", field_name, service_name).unwrap();
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // AppState implementation
        writeln!(output, "impl AppState {{").unwrap();

        // Constructor
        writeln!(output, "    /// Create a new AppState with all services.").unwrap();
        writeln!(output, "    pub fn new(").unwrap();
        for (i, model) in schema.schema.models.iter().enumerate() {
            let field_name = to_snake_case(&model.name);
            let service_name = format!("{}Service", to_pascal_case(&model.name));
            let comma = if i < schema.schema.models.len() - 1 { "," } else { "" };
            writeln!(output, "        {}_service: Arc<{}>{}", field_name, service_name, comma).unwrap();
        }
        writeln!(output, "    ) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        for model in &schema.schema.models {
            let field_name = to_snake_case(&model.name);
            writeln!(output, "            {}_service,", field_name).unwrap();
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // from_module helper
        writeln!(output, "    /// Create AppState from module instance.").unwrap();
        writeln!(output, "    pub fn from_module(module: &crate::{}Module) -> Self {{", pascal_name).unwrap();
        writeln!(output, "        Self {{").unwrap();
        for model in &schema.schema.models {
            let field_name = to_snake_case(&model.name);
            writeln!(output, "            {}_service: module.{}_service.clone(),", field_name, field_name).unwrap();
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // AppStateBuilder
        writeln!(output, "/// Builder for AppState.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Allows incremental construction of AppState.").unwrap();
        writeln!(output, "#[derive(Default)]").unwrap();
        writeln!(output, "pub struct AppStateBuilder {{").unwrap();
        for model in &schema.schema.models {
            let field_name = to_snake_case(&model.name);
            let service_name = format!("{}Service", to_pascal_case(&model.name));
            writeln!(output, "    {}_service: Option<Arc<{}>>,", field_name, service_name).unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl AppStateBuilder {{").unwrap();
        writeln!(output, "    /// Create a new builder.").unwrap();
        writeln!(output, "    pub fn new() -> Self {{").unwrap();
        writeln!(output, "        Self::default()").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // Builder methods for each service
        for model in &schema.schema.models {
            let field_name = to_snake_case(&model.name);
            let service_name = format!("{}Service", to_pascal_case(&model.name));
            writeln!(output, "    /// Set the {} service.", to_pascal_case(&model.name)).unwrap();
            writeln!(output, "    pub fn with_{}_service(mut self, service: Arc<{}>) -> Self {{", field_name, service_name).unwrap();
            writeln!(output, "        self.{}_service = Some(service);", field_name).unwrap();
            writeln!(output, "        self").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output).unwrap();
        }

        // Build method
        writeln!(output, "    /// Build the AppState.").unwrap();
        writeln!(output, "    ///").unwrap();
        writeln!(output, "    /// # Panics").unwrap();
        writeln!(output, "    ///").unwrap();
        writeln!(output, "    /// Panics if any required service is not set.").unwrap();
        writeln!(output, "    pub fn build(self) -> AppState {{").unwrap();
        writeln!(output, "        AppState {{").unwrap();
        for model in &schema.schema.models {
            let field_name = to_snake_case(&model.name);
            writeln!(output, "            {}_service: self.{}_service.expect(\"{}_service is required\"),",
                     field_name, field_name, field_name).unwrap();
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();

        writeln!(output, "}}").unwrap();

        Ok(output)
    }
}

/// Convert string to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

/// Convert string to snake_case
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("user"), "User");
        assert_eq!(to_pascal_case("user_profile"), "UserProfile");
        assert_eq!(to_pascal_case("organization_address"), "OrganizationAddress");
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("User"), "user");
        assert_eq!(to_snake_case("UserProfile"), "user_profile");
        assert_eq!(to_snake_case("user"), "user");
    }
}
