//! Audit Triggers Generator
//!
//! Generates a standalone migration file for adding audit timestamp triggers
//! to existing tables. This allows triggers to be added to already-migrated
//! databases without requiring a full database recreate.

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates standalone audit trigger migrations
pub struct AuditTriggersGenerator;

impl AuditTriggersGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate the audit triggers migration file content
    fn generate_audit_triggers_migration(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = crate::utils::to_snake_case(&schema.schema.name);

        // Header
        writeln!(output, "-- Audit Triggers Migration for {} module", module_name).unwrap();
        writeln!(output, "-- Generated by metaphor-schema").unwrap();
        writeln!(output, "--").unwrap();
        writeln!(output, "-- This migration adds automatic timestamp management triggers").unwrap();
        writeln!(output, "-- to all tables with audit metadata fields.").unwrap();
        writeln!(output, "--").unwrap();
        writeln!(output, "-- Triggers automatically set:").unwrap();
        writeln!(output, "--   - metadata->'created_at' on INSERT").unwrap();
        writeln!(output, "--   - metadata->'updated_at' on INSERT and UPDATE").unwrap();
        writeln!(output).unwrap();

        // Generate triggers for each model with audit_metadata
        let mut has_triggers = false;
        for model in &schema.schema.models {
            if let Some(field_name) = self.audit_metadata_field(model) {
                has_triggers = true;
                writeln!(output, "-- ==============================================================================").unwrap();
                writeln!(output, "-- Table: {} ({})", model.name, model.qualified_table_name()).unwrap();
                writeln!(output, "-- ==============================================================================").unwrap();
                writeln!(output).unwrap();
                self.generate_trigger_sql(&mut output, model, field_name)?;
                writeln!(output).unwrap();
            }
        }

        if !has_triggers {
            writeln!(output, "-- No tables with audit metadata found in this module.").unwrap();
        }

        Ok(output)
    }

    /// Get the audit metadata field name for a model, if any.
    fn audit_metadata_field<'a>(&self, model: &'a Model) -> Option<&'a str> {
        model
            .fields
            .iter()
            .find(|f| f.has_attribute("audit_metadata"))
            .map(|f| f.name.as_str())
    }

    /// Generate trigger SQL for a single table.
    ///
    /// The table reference is schema-qualified and the audit function is
    /// qualified into the table's schema (so two same-named tables in different
    /// schemas don't collide on one `public` function). Trigger *names* stay
    /// bare — Postgres scopes them to their table. This mirrors
    /// `SqlGenerator::generate_audit_triggers` so the standalone migration and
    /// the inline CREATE TABLE migration agree.
    fn generate_trigger_sql(&self, output: &mut String, model: &Model, field_name: &str) -> Result<(), GenerateError> {
        let qualified_table = model.qualified_table_name();
        let bare = model.collection_name();
        let trigger_func_name = model.audit_function_name();
        let insert_trigger_name = format!("{}_insert_audit", bare);
        let update_trigger_name = format!("{}_update_audit", bare);

        writeln!(output, "-- Function to set {} timestamps", field_name).unwrap();
        writeln!(output, "CREATE OR REPLACE FUNCTION {}() RETURNS trigger AS $$", trigger_func_name).unwrap();
        writeln!(output, "BEGIN").unwrap();
        writeln!(output, "    IF TG_OP = 'INSERT' THEN").unwrap();
        writeln!(output, "        NEW.{} = jsonb_set(NEW.{}::jsonb, '{{created_at}}', to_jsonb(NOW()));", field_name, field_name).unwrap();
        writeln!(output, "        NEW.{} = jsonb_set(NEW.{}::jsonb, '{{updated_at}}', to_jsonb(NOW()));", field_name, field_name).unwrap();
        writeln!(output, "    ELSIF TG_OP = 'UPDATE' THEN").unwrap();
        writeln!(output, "        NEW.{} = jsonb_set(NEW.{}::jsonb, '{{updated_at}}', to_jsonb(NOW()));", field_name, field_name).unwrap();
        writeln!(output, "    END IF;").unwrap();
        writeln!(output, "    RETURN NEW;").unwrap();
        writeln!(output, "END;").unwrap();
        writeln!(output, "$$ LANGUAGE plpgsql;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "-- Trigger to set timestamps on INSERT").unwrap();
        writeln!(output, "DROP TRIGGER IF EXISTS {} ON {};", insert_trigger_name, qualified_table).unwrap();
        writeln!(output, "CREATE TRIGGER {} BEFORE INSERT ON {}", insert_trigger_name, qualified_table).unwrap();
        writeln!(output, "    FOR EACH ROW EXECUTE FUNCTION {}();", trigger_func_name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "-- Trigger to set updated_at on UPDATE").unwrap();
        writeln!(output, "DROP TRIGGER IF EXISTS {} ON {};", update_trigger_name, qualified_table).unwrap();
        writeln!(output, "CREATE TRIGGER {} BEFORE UPDATE ON {}", update_trigger_name, qualified_table).unwrap();
        writeln!(output, "    FOR EACH ROW EXECUTE FUNCTION {}();", trigger_func_name).unwrap();

        Ok(())
    }

    /// Build the migration filename prefix using the shared timestamp scheme.
    ///
    /// Must slot AFTER every SQL-generator migration so that triggers attach
    /// to tables that already exist. SQL gen's emission order is:
    ///   index 0           : enums (if any)
    ///   indices 1..=N     : one per model (N = model_count)
    ///   index N+1         : join tables (if any)
    ///   index N+2         : deferred foreign keys (if any)
    ///
    /// We reserve slots for join-tables and deferred-FKs unconditionally —
    /// gaps in the timestamp sequence are harmless, but landing on an
    /// already-used slot would collide.
    fn get_migration_timestamp(&self, schema: &ResolvedSchema) -> String {
        let model_count = schema.schema.models.len();
        let enum_slot = if schema.schema.enums.is_empty() { 0 } else { 1 };
        // enum + models + join_tables_reserve + deferred_fks_reserve
        let index = enum_slot + model_count + 2;
        super::migration_timestamp_for(index)
    }
}

impl Default for AuditTriggersGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for AuditTriggersGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Generate the audit triggers migration
        let migration_content = self.generate_audit_triggers_migration(schema)?;

        // Add the migration file
        let _module_name = crate::utils::to_snake_case(&schema.schema.name);
        let migration_ts = self.get_migration_timestamp(schema);
        let path = PathBuf::from(format!(
            "migrations/{}_add_audit_triggers.up.sql",
            migration_ts
        ));

        output.add_file(path, migration_content);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "audit_triggers"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};
    use crate::resolver::ResolvedSchema;

    fn create_test_schema_with_audit_metadata() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");

        schema.models.push(Model {
            name: "User".to_string(),
            collection: Some("users".to_string()),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    attributes: vec![Attribute::new("id")],
                    ..Default::default()
                },
                Field {
                    name: "name".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
                Field {
                    name: "metadata".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Json),
                    attributes: vec![Attribute::new("audit_metadata")],
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        schema.models.push(Model {
            name: "Post".to_string(),
            collection: Some("posts".to_string()),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    attributes: vec![Attribute::new("id")],
                    ..Default::default()
                },
                Field {
                    name: "title".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
                Field {
                    name: "metadata".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Json),
                    attributes: vec![Attribute::new("audit_metadata")],
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        ResolvedSchema { schema }
    }

    #[test]
    fn test_audit_triggers_generator_creates_migration() {
        let schema = create_test_schema_with_audit_metadata();
        let generator = AuditTriggersGenerator::new();
        let output = generator.generate(&schema).unwrap();

        // 2 models + 0 enums => index = 0 + 2 + 2 = 4 => 20260426220004
        assert!(output.files.contains_key(&PathBuf::from("migrations/20260426220004_add_audit_triggers.up.sql")));
    }

    #[test]
    fn test_audit_triggers_migration_contains_trigger_sql() {
        let schema = create_test_schema_with_audit_metadata();
        let generator = AuditTriggersGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("migrations/20260426220004_add_audit_triggers.up.sql")).unwrap();

        // Check that trigger functions are created
        assert!(content.contains("CREATE OR REPLACE FUNCTION users_audit_timestamp()"));
        assert!(content.contains("CREATE OR REPLACE FUNCTION posts_audit_timestamp()"));

        // Check that triggers are created
        assert!(content.contains("CREATE TRIGGER users_insert_audit"));
        assert!(content.contains("CREATE TRIGGER users_update_audit"));
        assert!(content.contains("CREATE TRIGGER posts_insert_audit"));
        assert!(content.contains("CREATE TRIGGER posts_update_audit"));

        // Check that jsonb_set is used for timestamps
        assert!(content.contains("jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()))"));
        assert!(content.contains("jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()))"));
    }

    #[test]
    fn test_audit_triggers_schema_qualified_table_and_function() {
        // A schema-scoped model must emit a function qualified into its schema
        // and trigger ON clauses against the qualified table, while the trigger
        // *names* stay bare — matching SqlGenerator::generate_audit_triggers.
        let mut schema = ModuleSchema::new("test");
        schema.models.push(Model {
            name: "Doc".to_string(),
            collection: Some("docs".to_string()),
            schema: Some("sapiens".to_string()),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    attributes: vec![Attribute::new("id")],
                    ..Default::default()
                },
                Field {
                    name: "metadata".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Json),
                    attributes: vec![Attribute::new("audit_metadata")],
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        let resolved = ResolvedSchema { schema };
        let output = AuditTriggersGenerator::new().generate(&resolved).unwrap();
        // 1 model + 0 enums => index = 0 + 1 + 2 = 3.
        let content = output
            .files
            .get(&PathBuf::from("migrations/20260426220003_add_audit_triggers.up.sql"))
            .unwrap();

        // Function lives in the table's schema (no public collision).
        assert!(content.contains("CREATE OR REPLACE FUNCTION sapiens.docs_audit_timestamp()"), "got:\n{}", content);
        assert!(content.contains("EXECUTE FUNCTION sapiens.docs_audit_timestamp()"), "got:\n{}", content);
        // Trigger names stay bare; ON target is qualified.
        assert!(content.contains("CREATE TRIGGER docs_insert_audit BEFORE INSERT ON sapiens.docs"), "got:\n{}", content);
        assert!(content.contains("CREATE TRIGGER docs_update_audit BEFORE UPDATE ON sapiens.docs"), "got:\n{}", content);
        // No bare, unqualified function/ON references leak through.
        assert!(!content.contains("FUNCTION docs_audit_timestamp()"), "function must be schema-qualified, got:\n{}", content);
        assert!(!content.contains("ON docs;"), "trigger ON target must be qualified, got:\n{}", content);
    }

    #[test]
    fn test_audit_triggers_generator_skips_non_audit_tables() {
        let mut schema = ModuleSchema::new("test");

        // Model without audit metadata
        schema.models.push(Model {
            name: "Simple".to_string(),
            collection: Some("simples".to_string()),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    attributes: vec![Attribute::new("id")],
                    ..Default::default()
                },
                Field {
                    name: "value".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        let resolved = ResolvedSchema { schema };
        let generator = AuditTriggersGenerator::new();
        let output = generator.generate(&resolved).unwrap();

        // 1 model + 0 enums => index = 0 + 1 + 2 = 3 => 20260426220003
        let content = output.files.get(&PathBuf::from("migrations/20260426220003_add_audit_triggers.up.sql")).unwrap();

        // Should indicate no audit metadata tables found
        assert!(content.contains("No tables with audit metadata found"));
    }
}
