//! Auth generator
//!
//! Phase 1: Emits a `ResourcePolicy<E>` implementation containing entity-specific
//! permission string constants, plus a `PermissionGuard` type alias.
//! The guard middleware logic is no longer duplicated per entity.
//!
//! ## Before (was 200+ generated lines per entity):
//! ```rust,ignore
//! pub struct OrderPermissionGuard { auth_ctx: Arc<AuthContext>, service: Arc<OrderService> }
//! impl OrderPermissionGuard {
//!     pub async fn check_list(&self, ...) -> Result<(), StatusCode> { /* middleware logic */ }
//!     // ... × 10 operations
//! }
//! ```
//!
//! ## After (15 lines per entity):
//! ```rust,ignore
//! pub struct OrderPolicy;
//! impl ResourcePolicy<Order> for OrderPolicy {
//!     fn create_permission() -> &'static str { "order:create" }
//!     fn read_permission()   -> &'static str { "order:read" }
//!     fn update_permission() -> &'static str { "order:update" }
//!     fn delete_permission() -> &'static str { "order:delete" }
//! }
//! pub type OrderGuard = PermissionGuard<Order, OrderService, OrderPolicy>;
//! ```

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use crate::utils::to_snake_case;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates auth policy implementations from schema
pub struct AuthGenerator {
    group_by_domain: bool,
}

impl AuthGenerator {
    pub fn new() -> Self {
        Self { group_by_domain: false }
    }

    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Generate the auth/permission file for a single entity.
    fn generate_auth(&self, model: &Model) -> Result<String, GenerateError> {
        let mut output = String::new();
        let name = &model.name;
        let snake_name = to_snake_case(name);

        writeln!(output, "//! Auth configuration for {} handlers", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Implements `ResourcePolicy<{}>` with entity-specific permission", name).unwrap();
        writeln!(output, "//! string constants. Guard middleware logic lives in backbone-auth.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use backbone_auth::{{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard}};").unwrap();
        writeln!(output, "use async_trait::async_trait;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use crate::application::service::{}Service;", name).unwrap();
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output).unwrap();

        // Permission constants module (entity-specific — correct to keep here).
        writeln!(output, "/// Permission string constants for {} operations.", name).unwrap();
        writeln!(output, "pub mod permissions {{").unwrap();
        writeln!(output, "    pub const LIST:        &str = \"{}:list\";", snake_name).unwrap();
        writeln!(output, "    pub const READ:        &str = \"{}:read\";", snake_name).unwrap();
        writeln!(output, "    pub const CREATE:      &str = \"{}:create\";", snake_name).unwrap();
        writeln!(output, "    pub const UPDATE:      &str = \"{}:update\";", snake_name).unwrap();
        writeln!(output, "    pub const DELETE:      &str = \"{}:delete\";", snake_name).unwrap();
        writeln!(output, "    pub const RESTORE:     &str = \"{}:restore\";", snake_name).unwrap();
        writeln!(output, "    pub const TRASH:       &str = \"{}:trash\";", snake_name).unwrap();
        writeln!(output, "    pub const EMPTY_TRASH: &str = \"{}:empty_trash\";", snake_name).unwrap();
        writeln!(output, "    pub const BULK_CREATE: &str = \"{}:bulk_create\";", snake_name).unwrap();
        writeln!(output, "    pub const UPSERT:      &str = \"{}:upsert\";", snake_name).unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Policy struct — permission constants are entity-specific, guard logic is generic.
        writeln!(output, "/// Resource policy for {} — maps CRUD actions to permission strings.", name).unwrap();
        writeln!(output, "pub struct {}Policy;", name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "impl ResourcePolicy<{}> for {}Policy {{", name, name).unwrap();
        writeln!(output, "    async fn can(").unwrap();
        writeln!(output, "        &self,").unwrap();
        writeln!(output, "        action: ResourceAction,").unwrap();
        writeln!(output, "        _entity: &{},", name).unwrap();
        writeln!(output, "        ctx: &backbone_auth::middleware::AuthContext,").unwrap();
        writeln!(output, "    ) -> bool {{").unwrap();
        writeln!(output, "        let required = match action {{").unwrap();
        writeln!(output, "            ResourceAction::Read   => permissions::READ,").unwrap();
        writeln!(output, "            ResourceAction::Create => permissions::CREATE,").unwrap();
        writeln!(output, "            ResourceAction::Update => permissions::UPDATE,").unwrap();
        writeln!(output, "            ResourceAction::Delete => permissions::DELETE,").unwrap();
        writeln!(output, "        }};").unwrap();
        writeln!(output, "        ctx.has_permission(required)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // PermissionGuard type alias.
        writeln!(output, "/// Permission guard for {} handlers.", name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Wraps `{}Service` and checks `{}Policy` before delegating.", name, name).unwrap();
        writeln!(output, "pub type {}Guard = PermissionGuard<{}>;", name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "/// Service-integrated permission guard for {} (for use in generated handlers).", name).unwrap();
        writeln!(output, "pub type {}ServiceGuard = ServicePermissionGuard<{}, {}Service, {}Policy>;",
            name, name, name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();

        Ok(output)
    }
}

impl Default for AuthGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for AuthGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();
        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            let content = self.generate_auth(model)?;

            if self.group_by_domain {
                let path = build_generated_path(
                    "src/application/auth",
                    &model.name,
                    &format!("{}_auth.rs", snake_name),
                    true,
                );
                output.add_file(path, content);

                let sub_mod_path = PathBuf::from(format!(
                    "src/application/auth/{}/mod.rs", snake_name
                ));
                let sub_mod = build_subdirectory_mod(
                    &model.name,
                    &format!("{}_auth", snake_name),
                );
                output.add_file(sub_mod_path, sub_mod);
            } else {
                let path = PathBuf::from(format!(
                    "src/application/auth/{}_auth.rs",
                    snake_name
                ));
                output.add_file(path, content);
            }
        }

        // mod.rs
        if !model_names.is_empty() {
            let mut mod_content = String::new();
            writeln!(mod_content, "//! Auth policies and guards").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
            writeln!(mod_content).unwrap();
            for name in &model_names {
                writeln!(mod_content, "pub mod {}_auth;", to_snake_case(name)).unwrap();
            }
            writeln!(mod_content).unwrap();
            for name in &model_names {
                let snake = to_snake_case(name);
                writeln!(mod_content, "pub use {snake}_auth::{{{name}Policy, {name}Guard, {name}ServiceGuard}};",
                    snake = snake, name = name).unwrap();
            }
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "// <<< CUSTOM").unwrap();
            writeln!(mod_content, "// END CUSTOM").unwrap();
            output.add_file(PathBuf::from("src/application/auth/mod.rs"), mod_content);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "auth"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![Field {
            name: "id".to_string(),
            type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
            attributes: vec![Attribute::new("id")],
            ..Default::default()
        }];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_auth_creates_files() {
        let schema = create_test_schema();
        let gen = AuthGenerator::new();
        let out = gen.generate(&schema).unwrap();

        assert!(out.files.contains_key(&PathBuf::from("src/application/auth/order_auth.rs")));
        assert!(out.files.contains_key(&PathBuf::from("src/application/auth/mod.rs")));
    }

    #[test]
    fn test_auth_emits_resource_policy_impl() {
        let schema = create_test_schema();
        let gen = AuthGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/application/auth/order_auth.rs"))
            .unwrap();

        assert!(content.contains("impl ResourcePolicy<Order> for OrderPolicy"));
        assert!(content.contains("pub type OrderGuard = PermissionGuard<"));
        assert!(content.contains("ResourceAction"));
        assert!(content.contains("order:create"));
        assert!(content.contains("order:delete"));
    }
}
