//! Bulk Operations generator
//!
//! Phase 1: Emits a **type alias** over `GenericBulkService` instead of duplicating
//! `BulkOperationConfig`, `BulkOperationProgress`, and handler logic per entity.
//!
//! ## Before (was 150+ generated lines per entity):
//! ```rust,ignore
//! pub struct BulkOperationConfig { batch_size, max_concurrency, ... }
//! pub struct BulkOperationProgress { total, processed, succeeded, ... }
//! pub struct OrderBulkOperations { service: Arc<OrderService>, config: BulkOperationConfig }
//! impl OrderBulkOperations { pub async fn bulk_create(...) { ... } }
//! ```
//!
//! ## After (1 line per entity):
//! ```rust,ignore
//! pub type OrderBulkService = GenericBulkService<Order, CreateOrderDto, OrderService>;
//! ```

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use crate::utils::to_snake_case;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates bulk operation type aliases from schema
pub struct BulkOperationsGenerator {
    group_by_domain: bool,
}

impl BulkOperationsGenerator {
    pub fn new() -> Self {
        Self { group_by_domain: false }
    }

    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Generate a single-entity bulk service alias file.
    fn generate_bulk_alias(&self, model: &Model) -> String {
        let mut output = String::new();
        let name = &model.name;
        let snake_name = to_snake_case(name);

        writeln!(output, "//! Bulk operations for {} entities", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Type alias over `GenericBulkService` — config, progress tracking, and").unwrap();
        writeln!(output, "//! batch execution logic live in backbone-core.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use backbone_core::GenericBulkService;").unwrap();
        writeln!(output, "pub use backbone_core::{{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult}};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use crate::presentation::dto::Create{}Dto;", name).unwrap();
        writeln!(output, "use crate::application::service::{}Service;", name).unwrap();
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "/// Bulk operation handler for {} entities.", name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Wraps `{}Service` with configurable batch size, concurrency,", name).unwrap();
        writeln!(output, "/// and `ContinueOnError` / `AbortOnFirstError` failure modes.").unwrap();
        writeln!(output, "pub type {}BulkService = GenericBulkService<{}, Create{}Dto, {}Service>;",
            name, name, name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();

        output
    }

    /// Generate the shared types mod.rs — now just a re-export from backbone-core.
    fn generate_shared_types_mod(&self) -> String {
        let mut output = String::new();
        writeln!(output, "//! Bulk operation shared types — re-exported from backbone-core.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub use backbone_core::{{").unwrap();
        writeln!(output, "    BulkOperationConfig, BulkFailureMode,").unwrap();
        writeln!(output, "    BulkItemResult, BulkOperationResult,").unwrap();
        writeln!(output, "    BulkOperationProgress, BulkCapableService, GenericBulkService,").unwrap();
        writeln!(output, "}};").unwrap();
        output
    }
}

impl Default for BulkOperationsGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for BulkOperationsGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();
        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        // shared_types.rs — re-export from backbone-core
        output.add_file(
            PathBuf::from("src/application/bulk_operations/shared_types.rs"),
            self.generate_shared_types_mod(),
        );

        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            let content = self.generate_bulk_alias(model);

            if self.group_by_domain {
                let path = build_generated_path(
                    "src/application/bulk_operations",
                    &model.name,
                    &format!("{}_bulk.rs", snake_name),
                    true,
                );
                output.add_file(path, content);

                let sub_mod_path = PathBuf::from(format!(
                    "src/application/bulk_operations/{}/mod.rs", snake_name
                ));
                let sub_mod = build_subdirectory_mod(
                    &model.name,
                    &format!("{}_bulk", snake_name),
                );
                output.add_file(sub_mod_path, sub_mod);
            } else {
                let path = PathBuf::from(format!(
                    "src/application/bulk_operations/{}_bulk.rs",
                    snake_name
                ));
                output.add_file(path, content);
            }
        }

        // mod.rs
        if !model_names.is_empty() {
            let mut mod_content = String::new();
            writeln!(mod_content, "//! Bulk operations").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "pub mod shared_types;").unwrap();
            writeln!(mod_content, "pub use shared_types::*;").unwrap();
            writeln!(mod_content).unwrap();
            for name in &model_names {
                writeln!(mod_content, "pub mod {}_bulk;", to_snake_case(name)).unwrap();
            }
            writeln!(mod_content).unwrap();
            for name in &model_names {
                writeln!(mod_content, "pub use {}_bulk::{}BulkService;",
                    to_snake_case(name), name).unwrap();
            }
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "// <<< CUSTOM").unwrap();
            writeln!(mod_content, "// END CUSTOM").unwrap();
            output.add_file(PathBuf::from("src/application/bulk_operations/mod.rs"), mod_content);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "bulk_operations"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![Field {
            name: "id".to_string(),
            type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
            attributes: vec![Attribute::new("id")],
            ..Default::default()
        }];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_bulk_creates_files() {
        let schema = create_test_schema();
        let gen = BulkOperationsGenerator::new();
        let out = gen.generate(&schema).unwrap();

        assert!(out.files.contains_key(&PathBuf::from("src/application/bulk_operations/order_bulk.rs")));
        assert!(out.files.contains_key(&PathBuf::from("src/application/bulk_operations/shared_types.rs")));
        assert!(out.files.contains_key(&PathBuf::from("src/application/bulk_operations/mod.rs")));
    }

    #[test]
    fn test_bulk_emits_type_alias() {
        let schema = create_test_schema();
        let gen = BulkOperationsGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/application/bulk_operations/order_bulk.rs"))
            .unwrap();

        assert!(content.contains("GenericBulkService"));
        assert!(content.contains("pub type OrderBulkService"));
        assert!(content.contains("CreateOrderDto"));
        assert!(content.contains("OrderService"));
    }

    #[test]
    fn test_shared_types_re_exports_backbone_core() {
        let schema = create_test_schema();
        let gen = BulkOperationsGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/application/bulk_operations/shared_types.rs"))
            .unwrap();

        assert!(content.contains("backbone_core"));
        assert!(content.contains("BulkOperationConfig"));
    }
}
