//! Computed fields generator
//!
//! Generates Rust computed field implementations from hook definitions.
//! Creates the HasComputedFields trait implementations for entities.

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::hook::{ComputedField, Hook};
use crate::ast::model::Model;
use crate::ast::expressions::{Expression, Literal, FieldRef, BinaryOp, UnaryOp};
use crate::parser::parse_expression_str;
use crate::resolver::ResolvedSchema;
use std::collections::HashSet;
use std::fmt::Write;
use std::path::PathBuf;

/// Field name patterns that indicate integer types
const INT_FIELD_PATTERNS: &[&str] = &["port", "count", "id", "num", "number", "sessions"];
/// Type name suffixes that indicate enum types
const ENUM_TYPE_SUFFIXES: &[&str] = &["Type", "Status", "Kind"];
/// Duration suffix patterns for expressions like 24.hours, 7.days, etc.
const DURATION_SUFFIXES: &[&str] = &["hours", "hour", "days", "day", "minutes", "minute", "seconds", "second"];

/// Check if a member name is a duration suffix (e.g., "hours", "days", "minutes")
fn is_duration_suffix(member: &str) -> bool {
    DURATION_SUFFIXES.contains(&member)
}

/// Convert duration suffix to chrono::Duration function name
/// e.g., "hours" -> "hours", "day" -> "days"
fn duration_fn_name(member: &str) -> &str {
    match member {
        "hours" | "hour" => "hours",
        "days" | "day" => "days",
        "minutes" | "minute" => "minutes",
        "seconds" | "second" => "seconds",
        _ => "seconds", // fallback
    }
}

/// Result of analyzing an expression for code generation
#[derive(Debug, Clone)]
enum ExpressionAnalysis {
    /// Simple expression that can be generated inline
    Simple(String),
    /// Expression requires async/repository access (count, exists, etc.)
    RequiresAsync { _field_name: String, _description: String },
    /// Expression couldn't be parsed - fallback to raw string
    Fallback(String),
}

/// Generates computed field implementations from hook definitions
pub struct ComputedGenerator {
    /// Fields available on the current entity being processed (for future validation)
    _entity_fields: HashSet<String>,
    /// Name of the current entity being processed (for enum type generation)
    current_entity: String,
    /// Field type mappings from the model (field_name -> type_name)
    field_types: std::collections::HashMap<String, String>,
    /// Optional fields from the model (field_name -> is_optional)
    optional_fields: HashSet<String>,
}

impl ComputedGenerator {
    pub fn new() -> Self {
        Self {
            _entity_fields: HashSet::new(),
            current_entity: String::new(),
            field_types: std::collections::HashMap::new(),
            optional_fields: HashSet::new(),
        }
    }

    /// Create a generator with entity context for expression analysis
    pub fn with_entity_context(entity_name: &str, entity_fields: HashSet<String>, field_types: std::collections::HashMap<String, String>, optional_fields: HashSet<String>) -> Self {
        Self {
            _entity_fields: entity_fields,
            current_entity: entity_name.to_string(),
            field_types,
            optional_fields,
        }
    }

    /// Generate computed fields module (legacy, no model validation)
    fn _generate_computed_module(&self, hooks: &[&Hook]) -> Result<String, GenerateError> {
        // Convert to pairs with None models for backward compatibility
        let pairs: Vec<(&Hook, Option<&Model>)> = hooks.iter().map(|h| (*h, None)).collect();
        self.generate_computed_module_with_models(&pairs)
    }

    /// Generate computed fields module with model validation
    fn generate_computed_module_with_models(&self, hooks_with_models: &[(&Hook, Option<&Model>)]) -> Result<String, GenerateError> {
        let mut output = String::new();

        // Module header
        writeln!(output, "//! Computed Fields Module").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Provides virtual/computed fields for entities based on their data and relationships.").unwrap();
        writeln!(output, "//! These fields are not stored in the database but calculated on-demand.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use std::collections::HashMap;").unwrap();
        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output, "#[allow(unused_imports)]").unwrap();
        writeln!(output, "use chrono::{{DateTime, Utc, NaiveDate}};").unwrap();
        writeln!(output).unwrap();

        // Generate entity imports - use wildcard to get all entities and their enums
        writeln!(output, "use crate::domain::entity::*;").unwrap();
        writeln!(output).unwrap();

        // Generate trait definition
        self.generate_trait(&mut output)?;

        // Generate ComputedFieldValues
        self.generate_computed_field_values(&mut output)?;

        // Generate implementations for each entity with model validation
        for (hook, model) in hooks_with_models {
            if !hook.computed_fields.is_empty() {
                self.generate_entity_impl_with_model(&mut output, hook, *model)?;
            }
        }

        // Generate tests
        let hooks: Vec<&Hook> = hooks_with_models.iter().map(|(h, _)| *h).collect();
        self.generate_tests(&mut output, &hooks)?;

        Ok(output)
    }

    /// Get the set of field names available on a model
    fn get_model_fields(&self, model: &Model) -> HashSet<String> {
        model.fields.iter().map(|f| f.name.clone()).collect()
    }

    /// Get field type mappings from a model (field_name -> type_name for custom types)
    fn get_model_field_types(&self, model: &Model) -> std::collections::HashMap<String, String> {
        let mut field_types = std::collections::HashMap::new();
        for field in &model.fields {
            // Extract custom type name from the TypeRef
            let type_name = Self::extract_custom_type(&field.type_ref);
            if let Some(name) = type_name {
                field_types.insert(field.name.clone(), name);
            } else {
                // Also record primitive types so we know a field is NOT an enum
                let primitive_type = Self::extract_primitive_type(&field.type_ref);
                if let Some(ptype) = primitive_type {
                    field_types.insert(field.name.clone(), ptype);
                }
            }
        }
        field_types
    }

    /// Get optional fields from a model (fields that are not required)
    fn get_optional_fields(&self, model: &Model) -> HashSet<String> {
        model.fields.iter()
            .filter(|f| !f.is_required())
            .map(|f| f.name.clone())
            .collect()
    }

    /// Extract custom type name from a TypeRef (handles Optional wrapper)
    fn extract_custom_type(type_ref: &crate::ast::TypeRef) -> Option<String> {
        use crate::ast::TypeRef;
        match type_ref {
            TypeRef::Custom(name) => Some(name.clone()),
            TypeRef::Optional(inner) => Self::extract_custom_type(inner),
            _ => None,
        }
    }

    /// Extract primitive type name from a TypeRef (handles Optional wrapper)
    /// Returns a type string like "String", "i32", "bool", etc.
    fn extract_primitive_type(type_ref: &crate::ast::TypeRef) -> Option<String> {
        use crate::ast::{TypeRef, PrimitiveType};
        match type_ref {
            TypeRef::Primitive(p) => {
                let name = match p {
                    PrimitiveType::String | PrimitiveType::Slug
                    | PrimitiveType::Email | PrimitiveType::Phone | PrimitiveType::Url
                    | PrimitiveType::Markdown | PrimitiveType::Html | PrimitiveType::Json => "String",
                    PrimitiveType::Int | PrimitiveType::Int32 => "i32",
                    PrimitiveType::Int64 => "i64",
                    PrimitiveType::Float | PrimitiveType::Float64 => "f64",
                    PrimitiveType::Bool => "bool",
                    PrimitiveType::Uuid => "Uuid",
                    PrimitiveType::DateTime | PrimitiveType::Timestamp => "DateTime",
                    _ => return None,
                };
                Some(name.to_string())
            }
            TypeRef::Optional(inner) => Self::extract_primitive_type(inner),
            _ => None,
        }
    }

    /// Check if an expression references fields that don't exist on the entity
    fn find_missing_fields(&self, expr: &Expression, entity_fields: &HashSet<String>) -> Vec<String> {
        let mut missing = Vec::new();
        self.collect_field_refs(expr, entity_fields, &mut missing);
        missing.sort();
        missing.dedup();
        missing
    }

    /// Recursively collect field references that don't exist in entity_fields
    fn collect_field_refs(&self, expr: &Expression, entity_fields: &HashSet<String>, missing: &mut Vec<String>) {
        match expr {
            Expression::FieldRef(field_ref) => {
                match field_ref {
                    FieldRef::Simple(name) => {
                        // Check if this is a simple field that doesn't exist
                        if !entity_fields.contains(name) && !self.is_computed_field_name(name) {
                            missing.push(name.clone());
                        }
                    }
                    FieldRef::Path(parts) => {
                        // For paths like a.b.c, check if the first part exists
                        if let Some(first) = parts.first() {
                            if !entity_fields.contains(first) && !self.is_computed_field_name(first) {
                                missing.push(first.clone());
                            }
                        }
                    }
                    FieldRef::CrossRef { .. } => {
                        // Cross-entity references always require async
                    }
                }
            }
            Expression::Binary { left, right, .. } => {
                self.collect_field_refs(left, entity_fields, missing);
                self.collect_field_refs(right, entity_fields, missing);
            }
            Expression::Unary { expr, .. } => {
                self.collect_field_refs(expr, entity_fields, missing);
            }
            Expression::Conditional { condition, then_expr, else_expr } => {
                self.collect_field_refs(condition, entity_fields, missing);
                self.collect_field_refs(then_expr, entity_fields, missing);
                self.collect_field_refs(else_expr, entity_fields, missing);
            }
            Expression::FunctionCall { args, .. } => {
                for arg in args {
                    self.collect_field_refs(arg, entity_fields, missing);
                }
            }
            Expression::MemberAccess { object, .. } => {
                self.collect_field_refs(object, entity_fields, missing);
            }
            Expression::MethodCall { object, args, .. } => {
                self.collect_field_refs(object, entity_fields, missing);
                for arg in args {
                    self.collect_field_refs(arg, entity_fields, missing);
                }
            }
            Expression::Array(items) => {
                for item in items {
                    self.collect_field_refs(item, entity_fields, missing);
                }
            }
            Expression::Aggregate { collection, predicate, .. } => {
                self.collect_field_refs(collection, entity_fields, missing);
                if let Some(pred) = predicate {
                    self.collect_field_refs(pred, entity_fields, missing);
                }
            }
            Expression::Raw(raw) => {
                // Try to parse and check the raw expression
                if let Ok(parsed) = parse_expression_str(raw) {
                    self.collect_field_refs(&parsed, entity_fields, missing);
                }
            }
            _ => {}
        }
    }

    /// Check if a name is a known computed field helper (not a real entity field)
    fn is_computed_field_name(&self, name: &str) -> bool {
        // Built-in functions and context variables
        matches!(name, "$old" | "$this" | "$actor" | "$context" | "true" | "false" | "null")
    }

    fn generate_trait(&self, output: &mut String) -> Result<(), GenerateError> {
        writeln!(output, "/// Trait for entities that have computed fields").unwrap();
        writeln!(output, "pub trait HasComputedFields {{").unwrap();
        writeln!(output, "    /// Get all computed field values").unwrap();
        writeln!(output, "    fn computed_fields(&self) -> ComputedFieldValues;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    /// Get a specific computed field value").unwrap();
        writeln!(output, "    fn computed_field(&self, name: &str) -> Option<serde_json::Value>;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
        Ok(())
    }

    fn generate_computed_field_values(&self, output: &mut String) -> Result<(), GenerateError> {
        writeln!(output, "/// Collection of computed field values").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Default, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct ComputedFieldValues {{").unwrap();
        writeln!(output, "    pub fields: HashMap<String, serde_json::Value>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl ComputedFieldValues {{").unwrap();
        writeln!(output, "    pub fn new() -> Self {{").unwrap();
        writeln!(output, "        Self {{ fields: HashMap::new() }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    pub fn set(&mut self, name: impl Into<String>, value: serde_json::Value) {{").unwrap();
        writeln!(output, "        self.fields.insert(name.into(), value);").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    pub fn get(&self, name: &str) -> Option<&serde_json::Value> {{").unwrap();
        writeln!(output, "        self.fields.get(name)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    pub fn get_bool(&self, name: &str) -> Option<bool> {{").unwrap();
        writeln!(output, "        self.fields.get(name).and_then(|v| v.as_bool())").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    pub fn get_str(&self, name: &str) -> Option<&str> {{").unwrap();
        writeln!(output, "        self.fields.get(name).and_then(|v| v.as_str())").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    pub fn get_i64(&self, name: &str) -> Option<i64> {{").unwrap();
        writeln!(output, "        self.fields.get(name).and_then(|v| v.as_i64())").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
        Ok(())
    }

    fn _generate_entity_impl(&self, output: &mut String, hook: &Hook) -> Result<(), GenerateError> {
        self.generate_entity_impl_with_model(output, hook, None)
    }

    fn generate_entity_impl_with_model(&self, output: &mut String, hook: &Hook, model: Option<&Model>) -> Result<(), GenerateError> {
        let entity_name = &hook.name;

        // Get model fields, field types, and optional fields if available
        let entity_fields = model.map(|m| self.get_model_fields(m)).unwrap_or_default();
        let field_types = model.map(|m| self.get_model_field_types(m)).unwrap_or_default();
        let optional_fields = model.map(|m| self.get_optional_fields(m)).unwrap_or_default();

        // Create a context-aware generator for this entity
        let entity_generator = Self::with_entity_context(entity_name, entity_fields.clone(), field_types, optional_fields);

        writeln!(output, "/// Computed fields for {} entity", entity_name).unwrap();
        writeln!(output, "impl HasComputedFields for {} {{", entity_name).unwrap();
        writeln!(output, "    fn computed_fields(&self) -> ComputedFieldValues {{").unwrap();
        writeln!(output, "        let mut fields = ComputedFieldValues::new();").unwrap();
        writeln!(output).unwrap();

        for field in &hook.computed_fields {
            entity_generator.generate_computed_field_with_validation(output, field, &entity_fields)?;
        }

        writeln!(output, "        fields").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    fn computed_field(&self, name: &str) -> Option<serde_json::Value> {{").unwrap();
        writeln!(output, "        self.computed_fields().fields.get(name).cloned()").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        Ok(())
    }

    fn _generate_computed_field(&self, output: &mut String, field: &ComputedField) -> Result<(), GenerateError> {
        self.generate_computed_field_with_validation(output, field, &HashSet::new())
    }

    fn generate_computed_field_with_validation(&self, output: &mut String, field: &ComputedField, entity_fields: &HashSet<String>) -> Result<(), GenerateError> {
        writeln!(output, "        // {}", field.name).unwrap();

        // First check if the expression references missing fields
        if !entity_fields.is_empty() {
            let missing = self.find_missing_fields(&field.expression, entity_fields);
            if !missing.is_empty() {
                // Output as async/requires-repository since fields are missing
                writeln!(output, "        // WARNING: Expression references fields not on this entity: {:?}", missing).unwrap();
                writeln!(output, "        // These may be on a related entity or junction table.").unwrap();
                writeln!(output, "        // Implement via AsyncComputedFields trait or repository query.").unwrap();
                writeln!(output, "        fields.set(\"{}\", serde_json::json!(null));", field.name).unwrap();
                writeln!(output).unwrap();
                return Ok(());
            }
        }

        // Analyze and generate expression
        let analysis = self.analyze_expression(&field.name, &field.expression);

        match analysis {
            ExpressionAnalysis::Simple(code) => {
                let fixed_code = self.fix_common_rust_issues(&code);
                writeln!(output, "        fields.set(\"{}\", serde_json::json!({}));", field.name, fixed_code).unwrap();
            }
            ExpressionAnalysis::RequiresAsync { _description, .. } => {
                writeln!(output, "        // NOTE: {} - requires repository access", _description).unwrap();
                writeln!(output, "        // Implement via async computed field trait or cache").unwrap();
                writeln!(output, "        fields.set(\"{}\", serde_json::json!(null));", field.name).unwrap();
            }
            ExpressionAnalysis::Fallback(raw) => {
                // Truncate long expressions to avoid multi-line comment issues
                let truncated = Self::truncate_expression_for_comment(&raw);
                writeln!(output, "        // Expression: {}", truncated).unwrap();
                writeln!(output, "        // NOTE: Computed via AsyncComputedFields trait").unwrap();
                writeln!(output, "        fields.set(\"{}\", serde_json::json!(null));", field.name).unwrap();
            }
        }
        writeln!(output).unwrap();

        Ok(())
    }

    /// Truncate long expressions for safe inclusion in comments
    fn truncate_expression_for_comment(expr: &str) -> String {
        // Remove newlines and normalize whitespace
        let normalized: String = expr
            .chars()
            .map(|c| if c.is_whitespace() { ' ' } else { c })
            .collect();
        let normalized = normalized.split_whitespace().collect::<Vec<_>>().join(" ");

        // Truncate if too long (max 60 chars for readability)
        if normalized.len() > 60 {
            format!("{}...", &normalized[..57])
        } else {
            normalized
        }
    }

    /// Fix common Rust API issues in generated code
    /// This handles patterns from JavaScript-style hook syntax
    fn fix_common_rust_issues(&self, code: &str) -> String {
        let mut fixed = code.to_string();

        // Fix DateTime field access issues
        // .total_days → .num_days() on DateTime types
        // Note: These are heuristic fixes - proper type analysis would be better

        // Fix .total_days → .num_days()
        fixed = fixed.replace(".total_days", ".num_days()");

        fixed
    }

    /// Analyze an expression and determine how to generate code for it
    fn analyze_expression(&self, field_name: &str, expr: &Expression) -> ExpressionAnalysis {
        match expr {
            Expression::Raw(raw_str) => {
                // Check for known async patterns BEFORE parsing
                // This catches patterns like metadata['field'] that parse incorrectly
                if self.is_async_expression(raw_str) {
                    return ExpressionAnalysis::RequiresAsync {
                        _field_name: field_name.to_string(),
                        _description: self.describe_async_expression(raw_str),
                    };
                }
                // Try to parse the raw expression string
                match parse_expression_str(raw_str) {
                    Ok(parsed) => self.analyze_expression(field_name, &parsed),
                    Err(_) => {
                        // Check for known patterns that couldn't be parsed
                        ExpressionAnalysis::Fallback(raw_str.clone())
                    }
                }
            }
            Expression::FunctionCall { name, args: _ } => {
                // Check if this is a repository-dependent function
                match name.as_str() {
                    "count" | "exists" | "select" | "find" | "sum" | "avg" | "min" | "max" => {
                        ExpressionAnalysis::RequiresAsync {
                            _field_name: field_name.to_string(),
                            _description: format!("{}() function requires database query", name),
                        }
                    }
                    "build_industry_path" | "calculate_level"
                    | "calculate_system_health_score" | "calculate_configuration_score"
                    | "calculate_average_execution_time" | "calculate_workflow_completion_rate"
                    | "parse_certificate_expiry" => {
                        ExpressionAnalysis::RequiresAsync {
                            _field_name: field_name.to_string(),
                            _description: format!("{}() is a custom function requiring implementation", name),
                        }
                    }
                    _ => {
                        // Try to generate code for other function calls
                        let code = self.expression_to_rust(expr);
                        ExpressionAnalysis::Simple(code)
                    }
                }
            }
            _ => {
                // Check if the expression contains any async dependencies
                if self.contains_async_call(expr) {
                    ExpressionAnalysis::RequiresAsync {
                        _field_name: field_name.to_string(),
                        _description: "Contains repository-dependent function".to_string(),
                    }
                } else {
                    let code = self.expression_to_rust(expr);
                    ExpressionAnalysis::Simple(code)
                }
            }
        }
    }

    /// Check if a raw string contains async function calls or context variables
    fn is_async_expression(&self, raw: &str) -> bool {
        let async_patterns = [
            "count(", "exists(", "select(", "find(",
            "sum(", "avg(", "min(", "max(",
            "build_industry_path", "calculate_level",
        ];
        // Check for async function calls
        if async_patterns.iter().any(|p| raw.contains(p)) {
            return true;
        }
        // Check for context variables that require runtime context
        if raw.contains("$actor") || raw.contains("$context") || raw.contains("$old") {
            return true;
        }
        // Check for optional chaining (?.)
        if raw.contains("?.") {
            return true;
        }
        // Check for complex patterns that require special handling
        // JsonValue field access (metadata.xxx or metadata['xxx'])
        if raw.contains("metadata.") || raw.contains("metadata[") {
            return true;
        }
        // DateTime arithmetic with .total_days (requires special handling)
        // Note: .minutes, .hours, .days on numeric literals are handled as duration suffixes
        if raw.contains(".total_days") {
            return true;
        }
        // DateTime arithmetic: now() + X, now() - X, expires_at - now()
        // Note: Duration suffix patterns (24.hours) are handled in binary_to_rust()
        if raw.contains("now() - ") && !raw.contains(".minutes") && !raw.contains(".hours") && !raw.contains(".days") {
            // now() - field where field might be optional DateTime
            return true;
        }
        // .days() function call (not the suffix pattern)
        if raw.contains(".days(") {
            return true;
        }
        // String concatenation with mixed types (integer + string)
        // Pattern: "string" + port where port is integer
        if raw.contains("+ port") || raw.contains(":\" + ") {
            return true;
        }
        // .as_i64(), .as_str() on JsonValue (needs .get() first)
        if raw.contains(".as_i64()") || raw.contains(".as_str()") || raw.contains(".as_bool()") {
            return true;
        }
        false
    }

    /// Describe what makes an expression async
    fn describe_async_expression(&self, raw: &str) -> String {
        if raw.contains("$actor") || raw.contains("$context") {
            "Expression requires runtime context ($actor)".to_string()
        } else if raw.contains("metadata.") || raw.contains("metadata[") {
            "Expression requires JsonValue field access".to_string()
        } else if raw.contains(".total_days") {
            "Expression requires DateTime arithmetic".to_string()
        } else if raw.contains(" + ") {
            "Expression requires string concatenation".to_string()
        } else if raw.contains("count(") {
            "count() requires database query".to_string()
        } else if raw.contains("exists(") {
            "exists() requires database query".to_string()
        } else if raw.contains("select(") {
            "select() requires database query".to_string()
        } else if raw.contains("build_industry_path") {
            "build_industry_path() requires hierarchy traversal".to_string()
        } else {
            "Expression requires external data".to_string()
        }
    }

    /// Check if an expression tree contains async calls or context variables
    fn contains_async_call(&self, expr: &Expression) -> bool {
        match expr {
            Expression::FunctionCall { name, args } => {
                let async_funcs = ["count", "exists", "select", "find", "sum", "avg", "min", "max"];
                if async_funcs.contains(&name.as_str()) {
                    return true;
                }
                args.iter().any(|a| self.contains_async_call(a))
            }
            Expression::Binary { left, right, op } => {
                // Check for DateTime subtraction with optional field
                if matches!(op, BinaryOp::Sub) {
                    // Pattern: now() - optional_field (even if there's a null check)
                    if let Expression::FunctionCall { name, .. } = left.as_ref() {
                        if name == "now" {
                            if let Expression::FieldRef(FieldRef::Simple(field_name)) = right.as_ref() {
                                if self.optional_fields.contains(field_name) {
                                    return true;  // now() - Option<DateTime> needs unwrap
                                }
                            }
                        }
                    }
                    // Pattern: optional_field - now()
                    if let Expression::FunctionCall { name, .. } = right.as_ref() {
                        if name == "now" {
                            if let Expression::FieldRef(FieldRef::Simple(field_name)) = left.as_ref() {
                                if self.optional_fields.contains(field_name) {
                                    return true;  // Option<DateTime> - now() needs unwrap
                                }
                            }
                        }
                    }
                    // Pattern: now() - metadata.created_at (metadata.created_at is optional)
                    if let Expression::FunctionCall { name, .. } = left.as_ref() {
                        if name == "now" {
                            if let Expression::MemberAccess { object, member } = right.as_ref() {
                                if let Expression::FieldRef(FieldRef::Simple(obj_name)) = object.as_ref() {
                                    if obj_name == "metadata" && member == "created_at" {
                                        return true;  // now() - metadata.created_at needs unwrap
                                    }
                                }
                            }
                        }
                    }
                }
                // Check for arithmetic on optional fields (requires unwrap)
                if matches!(op, BinaryOp::Mul | BinaryOp::Div | BinaryOp::Mod) {
                    // Check if left is optional field
                    if let Expression::FieldRef(FieldRef::Simple(field_name)) = left.as_ref() {
                        if self.optional_fields.contains(field_name) {
                            return true;  // Optional<T> op T needs unwrap
                        }
                    }
                    // Check if right is optional field
                    if let Expression::FieldRef(FieldRef::Simple(field_name)) = right.as_ref() {
                        if self.optional_fields.contains(field_name) {
                            return true;  // T op Optional<T> needs unwrap
                        }
                    }
                }
                // Check for int * float (needs cast)
                if matches!(op, BinaryOp::Mul) {
                    let left_is_int_field = if let Expression::FieldRef(FieldRef::Simple(name)) = left.as_ref() {
                        INT_FIELD_PATTERNS.iter().any(|p| name.contains(p))
                    } else { false };
                    let right_is_float = matches!(right.as_ref(), Expression::Literal(Literal::Float(_)));
                    if left_is_int_field && right_is_float {
                        return true;  // i32 * f64 needs cast
                    }
                }
                // Check for integer + string concatenation (type mismatch)
                if matches!(op, BinaryOp::Add) {
                    // Pattern: string_expr + int_field or int_field + string_expr
                    let left_is_int = matches!(left.as_ref(), Expression::Literal(Literal::Int(_)));
                    let right_is_int = matches!(right.as_ref(), Expression::Literal(Literal::Int(_)));
                    let left_is_int_field = if let Expression::FieldRef(FieldRef::Simple(name)) = left.as_ref() {
                        // Check if field is an integer type (heuristic: name contains "port", "count", etc.)
                        INT_FIELD_PATTERNS.iter().any(|p| name.contains(p))
                    } else { false };
                    let right_is_int_field = if let Expression::FieldRef(FieldRef::Simple(name)) = right.as_ref() {
                        INT_FIELD_PATTERNS.iter().any(|p| name.contains(p))
                    } else { false };

                    // If one side is clearly int and the other is string, mark as async
                    let left_is_string = matches!(left.as_ref(), Expression::Literal(Literal::String(_)));
                    let right_is_string = matches!(right.as_ref(), Expression::Literal(Literal::String(_)));

                    if (left_is_int || left_is_int_field) && right_is_string {
                        return true;
                    }
                    if (right_is_int || right_is_int_field) && left_is_string {
                        return true;
                    }
                }
                self.contains_async_call(left) || self.contains_async_call(right)
            }
            Expression::Unary { expr, .. } => self.contains_async_call(expr),
            Expression::Conditional { condition, then_expr, else_expr } => {
                self.contains_async_call(condition)
                    || self.contains_async_call(then_expr)
                    || self.contains_async_call(else_expr)
            }
            Expression::MemberAccess { object, member } => {
                // Check for metadata.xxx access - requires JsonValue field access
                if let Expression::FieldRef(FieldRef::Simple(name)) = object.as_ref() {
                    if name == "metadata" {
                        return true;
                    }
                }
                // Check for .length on strings - requires special handling
                if member == "length" {
                    return true;
                }
                // Check for .total_days on DateTime - requires special handling
                // Note: .minutes on Duration (DateTime subtraction) is handled in expression_to_rust()
                if member == "total_days" {
                    return true;
                }
                // Check for .minutes/.hours/.days on DateTime subtraction result (Duration)
                // This is handled in expression_to_rust() via .num_minutes()
                if member == "minutes" || member == "hours" || member == "days" {
                    if let Expression::Binary { op: BinaryOp::Sub, left, right } = object.as_ref() {
                        // Check if the subtraction involves optional DateTime fields
                        // Pattern: now() - optional_datetime_field
                        if let Expression::FunctionCall { name, .. } = left.as_ref() {
                            if name == "now" {
                                if let Expression::FieldRef(FieldRef::Simple(field_name)) = right.as_ref() {
                                    if self.optional_fields.contains(field_name) {
                                        return true;  // now() - Option<DateTime> needs unwrap
                                    }
                                }
                                // Also check for metadata.created_at
                                if let Expression::MemberAccess { object: obj, member: m } = right.as_ref() {
                                    if m == "created_at" {
                                        if let Expression::FieldRef(FieldRef::Simple(name)) = obj.as_ref() {
                                            if name == "metadata" {
                                                return true;  // now() - metadata.created_at needs unwrap
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        // If the subtraction is safe (no optional fields), mark as handled
                        return false;  // Handled as .num_minutes(), etc.
                    }
                }
                // Check for duration suffix patterns on integer literals (24.hours, 7.days, etc.)
                // These are handled in binary_to_rust(), so don't mark as async
                if let Expression::Literal(Literal::Int(_)) = object.as_ref() {
                    if matches!(member.as_str(), "minutes" | "hours" | "days" | "seconds" | "minute" | "hour" | "day" | "second") {
                        return false;  // Duration suffix - will be converted to Duration::X()
                    }
                }
                // Recursively check the object
                self.contains_async_call(object)
            }
            Expression::MethodCall { object, args, .. } => {
                self.contains_async_call(object) || args.iter().any(|a| self.contains_async_call(a))
            }
            Expression::Array(items) => items.iter().any(|i| self.contains_async_call(i)),
            Expression::Context(_) => {
                // Context variables like $actor require runtime context, so mark as async
                true
            }
            _ => false,
        }
    }

    /// Convert an expression to Rust code
    fn expression_to_rust(&self, expr: &Expression) -> String {
        match expr {
            Expression::FieldRef(field_ref) => {
                match field_ref {
                    FieldRef::Simple(name) => format!("self.{}", name),
                    FieldRef::Path(parts) => format!("self.{}", parts.join(".")),
                    FieldRef::CrossRef { model, field } => format!("{}.{}", model, field),
                }
            }
            Expression::Literal(literal) => {
                match literal {
                    Literal::String(s) => format!("\"{}\"", s),
                    Literal::Int(n) => n.to_string(),
                    Literal::Float(n) => n.to_string(),
                    Literal::Bool(b) => b.to_string(),
                    Literal::Null => "None".to_string(),
                }
            }
            Expression::Binary { left, op, right } => {
                self.binary_to_rust(left, *op, right)
            }
            Expression::Unary { op, expr } => {
                let expr_code = self.expression_to_rust(expr);
                match op {
                    UnaryOp::Not => format!("!{}", expr_code),
                    UnaryOp::Neg => format!("-{}", expr_code),
                }
            }
            Expression::FunctionCall { name, args } => {
                self.translate_function_call(name, args)
            }
            Expression::Conditional { condition, then_expr, else_expr } => {
                let cond_code = self.expression_to_rust(condition);
                let then_code = self.expression_to_rust_with_type_hint(then_expr, else_expr);
                let else_code = self.expression_to_rust_with_type_hint(else_expr, then_expr);
                format!("if {} {{ {} }} else {{ {} }}", cond_code, then_code, else_code)
            }
            Expression::Array(items) => {
                let items_code: Vec<String> = items.iter()
                    .map(|i| self.expression_to_rust(i))
                    .collect();
                format!("vec![{}]", items_code.join(", "))
            }
            Expression::MemberAccess { object, member } => {
                let object_code = self.expression_to_rust(object);
                // Special handling: .minutes/.hours/.days on DateTime arithmetic results (Duration)
                // Pattern: (now() - last_sync_at).minutes → (chrono::Utc::now() - self.last_sync_at).num_minutes()
                if matches!(member.as_str(), "minutes" | "hours" | "days" | "seconds") {
                    // Check if the object is a binary operation that produces a Duration
                    if let Expression::Binary { .. } = object.as_ref() {
                        // Need parentheses to ensure correct precedence
                        return format!("({}).num_{}()", object_code, member);
                    }
                }
                // Special handling: .days on DateTime field (not subtraction)
                // Pattern: expires_at.days → expires_at.timestamp() / 86400 (approximate)
                // This is likely a mistake in the hook, but let's handle it gracefully
                if member == "days" {
                    if let Expression::FieldRef(FieldRef::Simple(_)) = object.as_ref() {
                        // Accessing .days on a DateTime doesn't make sense in Rust
                        // Mark as async for manual implementation
                        return format!("/* TODO: {} is not valid in Rust */", object_code);
                    }
                }
                format!("{}.{}", object_code, member)
            }
            Expression::MethodCall { object, method, args } => {
                let object_code = self.expression_to_rust(object);
                let args_code: Vec<String> = args.iter()
                    .map(|a| self.expression_to_rust(a))
                    .collect();
                // Special handling: trim() on optional fields
                let is_optional = if let Some(field_name) = object_code.strip_prefix("self.") {
                    self.optional_fields.contains(field_name)
                } else {
                    false
                };
                if method == "trim" && args.is_empty() && is_optional {
                    format!("{}.as_deref().unwrap_or(\"\").trim()", object_code)
                } else {
                    format!("{}.{}({})", object_code, method, args_code.join(", "))
                }
            }
            Expression::Aggregate { function, collection, predicate } => {
                let collection_code = self.expression_to_rust(collection);
                let func_name = function.as_str();
                if let Some(pred) = predicate {
                    let pred_code = self.expression_to_rust(pred);
                    format!("{}.{}(|item| {})", collection_code, func_name, pred_code)
                } else {
                    format!("{}.{}()", collection_code, func_name)
                }
            }
            Expression::Context(name) => {
                format!("ctx.{}", name.trim_start_matches('$'))
            }
            Expression::Raw(raw) => {
                // Try to parse and convert, or return as-is
                match parse_expression_str(raw) {
                    Ok(parsed) => self.expression_to_rust(&parsed),
                    Err(_) => format!("/* {} */", raw),
                }
            }
        }
    }

    /// Convert an expression to Rust code suitable for string context (format! macro)
    /// Handles integer to string conversion, enum to string conversion, etc.
    pub fn expression_to_rust_for_string_context(&self, expr: &Expression) -> String {
        match expr {
            Expression::FieldRef(FieldRef::Simple(name)) => {
                // Check if this is an optional field
                let is_optional = self.optional_fields.contains(name);
                // Check if this is an integer field that needs conversion
                // Check if any pattern is contained within the field name (e.g., "item_count" contains "count")
                let is_int_field = INT_FIELD_PATTERNS.iter().any(|pattern| name.contains(pattern));
                // Check if this is an enum field that needs conversion
                let is_enum_field = if let Some(type_name) = self.field_types.get(name) {
                    ENUM_TYPE_SUFFIXES.iter().any(|suffix| type_name.ends_with(suffix))
                } else {
                    false
                };
                // Check if this is a String field (not &str) - needs reference for format!
                let is_string_field = if let Some(type_name) = self.field_types.get(name) {
                    type_name == "String"
                } else {
                    false
                };

                if is_optional {
                    // Optional field - use unwrap_or_default() for format!
                    // This handles Option<String>, Option<i32>, etc.
                    format!("self.{}.as_deref().unwrap_or(\"\")", name)
                } else if is_int_field {
                    // Integer to string conversion
                    format!("format!(\"{{}}\", self.{})", name)
                } else if is_enum_field {
                    // Enum to string conversion - use format! or Debug
                    // For enums, we can use format! with {:?} for debug or implement Display
                    // Using as_str() if the enum has it, otherwise format!("{:?}", ...)
                    format!("format!(\"{{:?}}\", self.{})", name)
                } else if is_string_field {
                    // String field - take reference for format!
                    format!("&self.{}", name)
                } else {
                    format!("self.{}", name)
                }
            }
            // For literals and other expressions, use the standard conversion
            _ => self.expression_to_rust(expr)
        }
    }

    /// Convert expression to Rust code with type hint from the other branch
    /// Used for conditional expressions to ensure type compatibility
    fn expression_to_rust_with_type_hint(&self, expr: &Expression, other_branch: &Expression) -> String {
        let this_is_string_literal = matches!(expr, Expression::Literal(Literal::String(_)));
        let other_is_format_call = matches!(other_branch, Expression::FunctionCall { name, .. } if name == "format");
        // Check if the other branch is a Binary Add (likely string concatenation)
        let other_is_binary_add = matches!(other_branch, Expression::Binary { op: BinaryOp::Add, .. });

        let other_produces_string = other_is_format_call || other_is_binary_add;

        // If this is a string literal and the other branch produces a String,
        // convert the string literal to String for type compatibility
        if this_is_string_literal && other_produces_string {
            // String::from("...") or "...".to_string() converts &str to String
            // For string literals in the code, we need to wrap them
            if let Expression::Literal(Literal::String(s)) = expr {
                return format!("String::from(\"{}\")", s);
            }
        }

        self.expression_to_rust(expr)
    }

    /// Convert binary expression to Rust with special handling for null comparisons
    fn binary_to_rust(&self, left: &Expression, op: BinaryOp, right: &Expression) -> String {
        // Special case: field == null → self.field.is_none()
        if matches!(op, BinaryOp::Eq) {
            if let Expression::Literal(Literal::Null) = right {
                if let Expression::FieldRef(FieldRef::Simple(name)) = left {
                    return format!("self.{}.is_none()", name);
                }
            }
            if let Expression::Literal(Literal::Null) = left {
                if let Expression::FieldRef(FieldRef::Simple(name)) = right {
                    return format!("self.{}.is_none()", name);
                }
            }
            // Special case: field == true → self.field
            if let Expression::Literal(Literal::Bool(true)) = right {
                if let Expression::FieldRef(FieldRef::Simple(name)) = left {
                    return format!("self.{}", name);
                }
            }
            // Special case: field == false → !self.field
            if let Expression::Literal(Literal::Bool(false)) = right {
                if let Expression::FieldRef(FieldRef::Simple(name)) = left {
                    return format!("!self.{}", name);
                }
            }
            // Special case: enum_field == "EnumVariant" → self.enum_field == EnumType::Variant
            if let Expression::Literal(Literal::String(variant)) = right {
                if let Expression::FieldRef(FieldRef::Simple(name)) = left {
                    if let Some(enum_code) = self.try_generate_enum_comparison(name, variant) {
                        return enum_code;
                    }
                }
            }
        }

        // Special case: field != null → self.field.is_some() (ONLY if field is actually optional)
        if matches!(op, BinaryOp::Ne) {
            if let Expression::Literal(Literal::Null) = right {
                if let Expression::FieldRef(FieldRef::Simple(name)) = left {
                    // Only generate .is_some() if the field is actually optional
                    if self.optional_fields.contains(name) {
                        return format!("self.{}.is_some()", name);
                    } else {
                        // For non-optional fields, field != null is always true
                        return "true".to_string();
                    }
                }
            }
            if let Expression::Literal(Literal::Null) = left {
                if let Expression::FieldRef(FieldRef::Simple(name)) = right {
                    // Only generate .is_some() if the field is actually optional
                    if self.optional_fields.contains(name) {
                        return format!("self.{}.is_some()", name);
                    } else {
                        // For non-optional fields, null != field is always true
                        return "true".to_string();
                    }
                }
            }
            // Special case: enum_field != "EnumVariant"
            if let Expression::Literal(Literal::String(variant)) = right {
                if let Expression::FieldRef(FieldRef::Simple(name)) = left {
                    if let Some(enum_code) = self.try_generate_enum_comparison(name, variant) {
                        return format!("!({})", enum_code);
                    }
                }
            }
        }

        // Special case: optional field comparisons with function calls (e.g., optional_expires_at > now())
        // Need to wrap non-optional values in Some() when comparing with optional fields
        if matches!(op, BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge) {
            if let Expression::FieldRef(FieldRef::Simple(field_name)) = left {
                // Check if the left field is actually optional
                if self.optional_fields.contains(field_name) {
                    // Check if the right side is a time function call OR now() + Duration
                    // Note: right is already a reference (&Expression), so we match directly
                    let right_is_datetime = match right {
                        Expression::FunctionCall { name, .. } => {
                            name == "now" || name == "today"
                        }
                        Expression::Binary { left: inner_left, op: BinaryOp::Add | BinaryOp::Sub, .. } => {
                            // Check if it's now() + Duration or now() - Duration
                            match inner_left.as_ref() {
                                Expression::FunctionCall { name, .. } => {
                                    name == "now" || name == "today"
                                }
                                _ => false
                            }
                        }
                        _ => false
                    };

                    if right_is_datetime {
                        let left_code = self.expression_to_rust(left);
                        let right_code = self.expression_to_rust(right);
                        let op_str = match op {
                            BinaryOp::Lt => "<",
                            BinaryOp::Le => "<=",
                            BinaryOp::Gt => ">",
                            BinaryOp::Ge => ">=",
                            _ => unreachable!(),
                        };
                        // Wrap the time expression in Some() for optional field comparison
                        return format!("{} {} Some({})", left_code, op_str, right_code);
                    }
                    // Also handle raw expressions that contain now()
                    if let Expression::Raw(raw) = right {
                        if raw.contains("now()") || raw.contains("today()") {
                            let left_code = self.expression_to_rust(left);
                            let right_code = self.expression_to_rust(right);
                            let op_str = match op {
                                BinaryOp::Lt => "<",
                                BinaryOp::Le => "<=",
                                BinaryOp::Gt => ">",
                                BinaryOp::Ge => ">=",
                                _ => unreachable!(),
                            };
                            return format!("{} {} Some({})", left_code, op_str, right_code);
                        }
                    }
                }
            }
        }

        // Special case: Duration suffix pattern (24.hours, 7.days, 1.hour, etc.)
        // Handle this BEFORE any other processing, for ALL operators
        // Pattern: now() + 24.hours → chrono::Utc::now() + chrono::Duration::hours(24)
        // Pattern: x < 5.minutes → x < chrono::Duration::minutes(5)

        // Check if right side is a duration pattern
        if let Expression::MemberAccess { object, member } = right {
            if let Expression::Literal(Literal::Int(amount)) = object.as_ref() {
                if is_duration_suffix(member) {
                    let duration_fn = duration_fn_name(member);
                    let left_code = self.expression_to_rust(left);
                    // Special case for addition/subtraction with DateTime
                    if matches!(op, BinaryOp::Add | BinaryOp::Sub) {
                        let op_str = match op {
                            BinaryOp::Add => "+",
                            BinaryOp::Sub => "-",
                            _ => unreachable!(),
                        };
                        return format!("{} {} chrono::Duration::{}({})", left_code, op_str, duration_fn, amount);
                    }
                    // For all other operators (comparisons, etc.), just generate the duration
                    let right_code = format!("chrono::Duration::{}({})", duration_fn, amount);
                    let op_str = match op {
                        BinaryOp::Lt => "<",
                        BinaryOp::Le => "<=",
                        BinaryOp::Gt => ">",
                        BinaryOp::Ge => ">=",
                        BinaryOp::Eq => "==",
                        BinaryOp::Ne => "!=",
                        _ => return format!("{} {:?} {}", left_code, op, right_code),
                    };
                    return format!("{} {} {}", left_code, op_str, right_code);
                }
            }
        }
        // Check if left side is a duration pattern (only for addition/subtraction)
        if matches!(op, BinaryOp::Add | BinaryOp::Sub) {
            if let Expression::MemberAccess { object, member } = left {
                if let Expression::Literal(Literal::Int(amount)) = object.as_ref() {
                    if is_duration_suffix(member) {
                        let duration_fn = duration_fn_name(member);
                        let right_code = self.expression_to_rust(right);
                        let op_str = match op {
                            BinaryOp::Add => "+",
                            BinaryOp::Sub => "-",
                            _ => unreachable!(),
                        };
                        return format!("chrono::Duration::{}({}) {} {}", duration_fn, amount, op_str, right_code);
                    }
                }
            }
        }

        // Special handling for string concatenation: "a" + "b" + c → format!("{}{}{}", a, b, c)
        // We need to collect all parts of the concatenation chain
        if op == BinaryOp::Add && self.is_string_concatenation(left, right) {
            let parts = self.collect_concat_parts(left, right);
            if parts.len() > 2 {
                // Multi-part concatenation - use format! with all parts
                let placeholders: Vec<&str> = parts.iter().map(|_| "{}").collect();
                let parts_code: Vec<String> = parts.iter()
                    .map(|expr| self.expression_to_rust_for_string_context(expr))
                    .collect();
                return format!("format!(\"{}\", {})", placeholders.join(""), parts_code.join(", "));
            }
            // Simple two-part concatenation
            let left_code = self.expression_to_rust_for_string_context(left);
            let right_code = self.expression_to_rust_for_string_context(right);
            return format!("format!(\"{{}}{{}}\", {}, {})", left_code, right_code);
        }

        // Standard binary expression
        let left_code = self.expression_to_rust(left);
        let right_code = self.expression_to_rust(right);

        // Handle Option-wrapping for comparison operators
        let is_comparison = matches!(op, BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge);
        let left_is_optional = if let Expression::FieldRef(FieldRef::Simple(name)) = left {
            self.optional_fields.contains(name)
        } else {
            false
        };
        let right_is_optional = if let Expression::FieldRef(FieldRef::Simple(name)) = right {
            self.optional_fields.contains(name)
        } else {
            false
        };
        let left_is_none_or_some = left_code == "None" || left_code.starts_with("Some(");
        let right_is_none_or_some = right_code == "None" || right_code.starts_with("Some(");
        let left_is_field = matches!(left, Expression::FieldRef(_));
        let right_is_field = matches!(right, Expression::FieldRef(_));

        // Wrap non-Optional side in Some() when comparing Optional vs non-Optional
        let right_code = if is_comparison && left_is_optional && !right_is_optional && !right_is_none_or_some {
            format!("Some({})", right_code)
        } else {
            right_code
        };

        let left_code = if is_comparison && right_is_optional && !left_is_optional && !left_is_none_or_some {
            format!("Some({})", left_code)
        } else {
            left_code
        };

        // If right side ends with .trim() it returns &str, not bool — add .is_empty() check
        let right_code = if matches!(op, BinaryOp::And | BinaryOp::Or)
            && right_code.ends_with(".trim()")
        {
            format!("!{}.is_empty()", right_code)
        } else {
            right_code
        };
        let left_code = if matches!(op, BinaryOp::And | BinaryOp::Or)
            && left_code.ends_with(".trim()")
        {
            format!("!{}.is_empty()", left_code)
        } else {
            left_code
        };

        match op {
            BinaryOp::And => format!("{} && {}", left_code, right_code),
            BinaryOp::Or => format!("{} || {}", left_code, right_code),
            BinaryOp::Eq => format!("{} == {}", left_code, right_code),
            BinaryOp::Ne => format!("{} != {}", left_code, right_code),
            BinaryOp::Lt => format!("{} < {}", left_code, right_code),
            BinaryOp::Le => format!("{} <= {}", left_code, right_code),
            BinaryOp::Gt => format!("{} > {}", left_code, right_code),
            BinaryOp::Ge => format!("{} >= {}", left_code, right_code),
            BinaryOp::Add => format!("{} + {}", left_code, right_code),
            BinaryOp::Sub => format!("{} - {}", left_code, right_code),
            BinaryOp::Mul => format!("{} * {}", left_code, right_code),
            BinaryOp::Div => format!("{} / {}", left_code, right_code),
            BinaryOp::Mod => format!("{} % {}", left_code, right_code),
            BinaryOp::Contains => format!("{}.contains({})", left_code, right_code),
            BinaryOp::StartsWith => format!("{}.starts_with({})", left_code, right_code),
            BinaryOp::EndsWith => format!("{}.ends_with({})", left_code, right_code),
            BinaryOp::Matches => format!("{}.matches({})", left_code, right_code),
            BinaryOp::In => format!("{}.contains(&{})", right_code, left_code),
            BinaryOp::NotIn => format!("!{}.contains(&{})", right_code, left_code),
        }
    }

    /// Collect all parts of a string concatenation chain
    /// Returns the expressions in order (left-to-right) that should be concatenated
    fn collect_concat_parts<'a>(&self, left: &'a Expression, right: &'a Expression) -> Vec<&'a Expression> {
        let mut parts = Vec::new();

        // Recursively collect left side if it's also a concatenation
        if let Expression::Binary { op: BinaryOp::Add, left: inner_left, right: inner_right } = left {
            if self.is_string_concatenation(inner_left, inner_right) {
                parts.extend(self.collect_concat_parts(inner_left, inner_right));
            } else {
                parts.push(left);
            }
        } else {
            parts.push(left);
        }

        // Add right side
        parts.push(right);

        parts
    }

    /// Check if this binary operation is string concatenation
    /// Heuristics: if either operand is a string literal or a field with string type
    fn is_string_concatenation(&self, left: &Expression, right: &Expression) -> bool {
        // If either is a string literal, it's likely string concat
        if matches!(left, Expression::Literal(Literal::String(_))) {
            return true;
        }
        if matches!(right, Expression::Literal(Literal::String(_))) {
            return true;
        }

        // If left is a Binary expression (likely previous concat), check if it was string concat
        // This handles chains like: "a" + b + c + d
        if let Expression::Binary { op: BinaryOp::Add, .. } = left {
            // Assume a Binary Add was string concatenation if we got here
            // (since it would have been processed earlier in the chain)
            return true;
        }
        // Check if field references have string types
        if let Expression::FieldRef(FieldRef::Simple(name)) = left {
            if let Some(type_name) = self.field_types.get(name) {
                if type_name == "String" || type_name == "str" {
                    return true;
                }
            }
        }
        if let Expression::FieldRef(FieldRef::Simple(name)) = right {
            if let Some(type_name) = self.field_types.get(name) {
                if type_name == "String" || type_name == "str" {
                    return true;
                }
            }
        }
        // Check for format! call (produces String) + integer field or vice versa
        // Pattern: format!(...) + port where port is i32
        let left_is_format_call = matches!(left, Expression::FunctionCall { name, .. } if name == "format");
        let right_is_format_call = matches!(right, Expression::FunctionCall { name, .. } if name == "format");

        // Check for integer field (by name heuristic)
        let left_is_int_field = if let Expression::FieldRef(FieldRef::Simple(name)) = left {
            INT_FIELD_PATTERNS.iter().any(|p| name.contains(p))
        } else { false };
        let right_is_int_field = if let Expression::FieldRef(FieldRef::Simple(name)) = right {
            INT_FIELD_PATTERNS.iter().any(|p| name.contains(p))
        } else { false };

        // If one side produces string (format! or string literal or string field)
        // and the other is an integer field, it's string concatenation
        if (left_is_format_call || matches!(left, Expression::Literal(Literal::String(_)))) && right_is_int_field {
            return true;
        }
        if (right_is_format_call || matches!(right, Expression::Literal(Literal::String(_)))) && left_is_int_field {
            return true;
        }

        // Check for enum type field being concatenated (enum to string conversion)
        // Pattern: device_type (enum) + "string" or "string" + device_type
        if let Expression::FieldRef(FieldRef::Simple(name)) = left {
            if let Some(type_name) = self.field_types.get(name) {
                // If it's an enum type (likely ends with "Type" or in known enum list)
                // and the other side is a string, it's string concatenation
                if ENUM_TYPE_SUFFIXES.iter().any(|suffix| type_name.ends_with(suffix)) {
                    if matches!(right, Expression::Literal(Literal::String(_))) {
                        return true;
                    }
                }
            }
        }
        if let Expression::FieldRef(FieldRef::Simple(name)) = right {
            if let Some(type_name) = self.field_types.get(name) {
                if ENUM_TYPE_SUFFIXES.iter().any(|suffix| type_name.ends_with(suffix)) {
                    if matches!(left, Expression::Literal(Literal::String(_))) {
                        return true;
                    }
                }
            }
        }

        // Check for string + String field (String fields need & for concat)
        // Pattern: "prefix" + self.field where field is String (not &str)
        if let Expression::FieldRef(FieldRef::Simple(name)) = left {
            if let Some(type_name) = self.field_types.get(name) {
                if type_name == "String" && matches!(right, Expression::Literal(Literal::String(_))) {
                    return true;
                }
            }
        }

        false
    }

    /// Try to generate enum comparison code for known enum field patterns
    /// Returns Some(code) if the field is recognized as an enum type, None otherwise
    fn try_generate_enum_comparison(&self, field_name: &str, variant: &str) -> Option<String> {
        // First priority: use actual field type from the model if available
        if let Some(type_name) = self.field_types.get(field_name) {
            // If the field is a primitive type (String, i32, bool, etc.), don't generate enum comparison
            let primitive_types = ["String", "i32", "i64", "f64", "bool", "Uuid", "DateTime"];
            if primitive_types.contains(&type_name.as_str()) {
                return None;  // Fall through to default string comparison
            }
            let rust_variant = Self::to_pascal_case(variant);
            let enum_value = format!("{}::{}", type_name, rust_variant);
            // Wrap in Some() if the field is Optional
            if self.optional_fields.contains(field_name) {
                return Some(format!("self.{} == Some({})", field_name, enum_value));
            }
            return Some(format!("self.{} == {}", field_name, enum_value));
        }

        // Known enum field patterns and their corresponding type names
        // Format: (field_name_suffix or exact_name, enum_type_name)
        let enum_mappings: &[(&str, &str)] = &[
            // Exact field names with known types
            ("structure_type", "OrganizationStructureType"),
            ("organization_type", "OrganizationType"),
            ("organization_size", "OrganizationSize"),
            ("branch_type", "BranchType"),
            ("address_type", "AddressType"),
            ("contact_type", "ContactType"),
            ("subscription_tier", "SubscriptionTier"),
            // Common suffixes
            ("_type", ""),  // Will derive type name from field
            ("_status", ""),
            ("_kind", ""),
            ("_tier", ""),
            ("_level", ""),
            ("_state", ""),
            ("_mode", ""),
            ("_role", ""),
        ];

        // Fields that are likely enums even without suffix patterns
        let common_enum_fields: &[&str] = &[
            "status", "visibility", "priority", "severity", "category", "tier",
            "level", "mode", "state", "role", "permission", "action",
        ];

        let is_optional = self.optional_fields.contains(field_name);

        // First check for exact matches
        for (field_pattern, enum_type) in enum_mappings {
            if field_name == *field_pattern && !enum_type.is_empty() {
                let rust_variant = Self::to_pascal_case(variant);
                let enum_value = format!("crate::domain::entity::{}::{}", enum_type, rust_variant);
                if is_optional {
                    return Some(format!("self.{} == Some({})", field_name, enum_value));
                }
                return Some(format!("self.{} == {}", field_name, enum_value));
            }
        }

        // Check for suffix patterns and derive enum type from field name
        for (suffix, _) in enum_mappings {
            if suffix.starts_with('_') && field_name.ends_with(suffix) {
                let enum_type = Self::to_pascal_case(field_name);
                let rust_variant = Self::to_pascal_case(variant);
                let enum_value = format!("crate::domain::entity::{}::{}", enum_type, rust_variant);
                if is_optional {
                    return Some(format!("self.{} == Some({})", field_name, enum_value));
                }
                return Some(format!("self.{} == {}", field_name, enum_value));
            }
        }

        // Check for common enum field names (without suffix patterns)
        if common_enum_fields.contains(&field_name) {
            if !self.current_entity.is_empty() && !self.field_types.contains_key(field_name) {
                let enum_type = format!("{}{}", self.current_entity, Self::to_pascal_case(field_name));
                let rust_variant = Self::to_pascal_case(variant);
                let enum_value = format!("{}::{}", enum_type, rust_variant);
                if is_optional {
                    return Some(format!("self.{} == Some({})", field_name, enum_value));
                }
                return Some(format!("self.{} == {}", field_name, enum_value));
            }
            return None;
        }

        None
    }

    /// Convert snake_case or lowercase string to PascalCase
    fn to_pascal_case(s: &str) -> String {
        s.split(['_', '-', ' '])
            .filter(|part| !part.is_empty())
            .map(|part| {
                let mut chars = part.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => {
                        first.to_uppercase().chain(chars.flat_map(|c| c.to_lowercase())).collect()
                    }
                }
            })
            .collect()
    }

    /// Translate DSL function calls to Rust code
    fn translate_function_call(&self, name: &str, args: &[Expression]) -> String {
        match name {
            // String concatenation: concat(a, b, c) -> format!("{}{}{}", a, b, c)
            "concat" => {
                if args.is_empty() {
                    return "String::new()".to_string();
                }
                let format_placeholders: Vec<&str> = args.iter().map(|_| "{}").collect();
                let args_code: Vec<String> = args.iter()
                    .map(|a| self.expression_to_rust(a))
                    .collect();
                format!("format!(\"{}\", {})", format_placeholders.join(""), args_code.join(", "))
            }

            // Concat with separator: concat_ws(", ", a, b, c) -> [a, b, c].into_iter().filter(|s| !s.is_empty()).collect::<Vec<_>>().join(", ")
            "concat_ws" => {
                if args.len() < 2 {
                    return "String::new()".to_string();
                }
                let separator = self.expression_to_rust(&args[0]);
                let parts: Vec<String> = args[1..].iter()
                    .map(|a| {
                        // Use string context to correctly handle optional vs non-optional fields
                        // Wrap in .to_string() to normalize all items to String,
                        // avoiding type mismatches between &str, &String, and String
                        let s = self.expression_to_rust_for_string_context(a);
                        format!("({}).to_string()", s)
                    })
                    .collect();
                format!(
                    "[{}].into_iter().filter(|s: &String| !s.is_empty()).collect::<Vec<_>>().join({})",
                    parts.join(", "),
                    separator
                )
            }

            // Coalesce: coalesce(a, b, c) -> a.or(b).or(c) or a.unwrap_or(b)
            "coalesce" => {
                if args.is_empty() {
                    return "None".to_string();
                }
                if args.len() == 1 {
                    return self.expression_to_rust(&args[0]);
                }
                // For two args with the second being a literal, use unwrap_or
                if args.len() == 2 {
                    let first = self.expression_to_rust(&args[0]);
                    let second = self.expression_to_rust(&args[1]);
                    return format!("{}.unwrap_or({})", first, second);
                }
                // For multiple args, chain with or()
                let mut result = self.expression_to_rust(&args[0]);
                for arg in &args[1..] {
                    let code = self.expression_to_rust(arg);
                    result = format!("{}.or({})", result, code);
                }
                result
            }

            // Length/count of string or array
            "len" | "length" => {
                if args.is_empty() {
                    return "0".to_string();
                }
                let arg = self.expression_to_rust(&args[0]);
                // If arg is an optional field, use as_deref to get &str or map for Vec
                let is_optional = if let Some(field_name) = arg.strip_prefix("self.") {
                    self.optional_fields.contains(field_name)
                } else {
                    false
                };
                if is_optional {
                    format!("{}.as_deref().map(|s| s.len()).unwrap_or(0)", arg)
                } else {
                    format!("{}.len()", arg)
                }
            }

            // Trim whitespace
            "trim" => {
                if args.is_empty() {
                    return "\"\"".to_string();
                }
                let arg = self.expression_to_rust(&args[0]);
                // If arg is an optional field (self.foo where foo is optional), use as_deref
                let is_optional = if let Some(field_name) = arg.strip_prefix("self.") {
                    self.optional_fields.contains(field_name)
                } else {
                    false
                };
                if is_optional {
                    format!("{}.as_deref().unwrap_or(\"\").trim()", arg)
                } else {
                    format!("{}.trim()", arg)
                }
            }

            // Upper/lower case
            "upper" | "to_upper" | "uppercase" => {
                if args.is_empty() {
                    return "String::new()".to_string();
                }
                let arg = self.expression_to_rust(&args[0]);
                format!("{}.to_uppercase()", arg)
            }

            "lower" | "to_lower" | "lowercase" => {
                if args.is_empty() {
                    return "String::new()".to_string();
                }
                let arg = self.expression_to_rust(&args[0]);
                format!("{}.to_lowercase()", arg)
            }

            // is_empty check
            "is_empty" | "empty" => {
                if args.is_empty() {
                    return "true".to_string();
                }
                let arg = self.expression_to_rust(&args[0]);
                format!("{}.is_empty()", arg)
            }

            // not_empty check
            "is_not_empty" | "not_empty" => {
                if args.is_empty() {
                    return "false".to_string();
                }
                let arg = self.expression_to_rust(&args[0]);
                format!("!{}.is_empty()", arg)
            }

            // Current timestamp: now() -> chrono::Utc::now()
            "now" => "chrono::Utc::now()".to_string(),

            // Today's date: today() -> chrono::Utc::now().date_naive()
            "today" => "chrono::Utc::now().date_naive()".to_string(),

            // Default fallback - check if this looks like a self method call
            // (snake_case function with no args that could be a computed field or entity method)
            _ => {
                let args_code: Vec<String> = args.iter()
                    .map(|a| self.expression_to_rust(a))
                    .collect();
                // If the function name is snake_case and starts with is_/has_/can_/get_,
                // it's likely a method on self (entity method or computed field)
                let is_self_method = name.contains('_') && (
                    name.starts_with("is_") || name.starts_with("has_") ||
                    name.starts_with("can_") || name.starts_with("get_")
                );
                if is_self_method {
                    format!("self.{}({})", name, args_code.join(", "))
                } else {
                    // Unknown custom function - cannot call undefined functions in generated code.
                    // These require custom implementation (repository access or utility functions).
                    // Using null as placeholder; implement via AsyncComputedFields trait.
                    let _ = args_code; // suppress unused warning
                    "null".to_string()
                }
            }
        }
    }

    fn generate_tests(&self, output: &mut String, hooks: &[&Hook]) -> Result<(), GenerateError> {
        writeln!(output, "#[cfg(test)]").unwrap();
        writeln!(output, "mod tests {{").unwrap();
        writeln!(output, "    #[allow(unused_imports)]").unwrap();
        writeln!(output, "    use super::*;").unwrap();
        writeln!(output).unwrap();

        for hook in hooks {
            if !hook.computed_fields.is_empty() {
                writeln!(output, "    #[test]").unwrap();
                writeln!(output, "    fn test_{}_computed_fields() {{", to_snake_case(&hook.name)).unwrap();
                writeln!(output, "        // TODO: Add test implementation for {}", hook.name).unwrap();
                writeln!(output, "    }}").unwrap();
                writeln!(output).unwrap();
            }
        }

        writeln!(output, "}}").unwrap();
        Ok(())
    }
}

impl Default for ComputedGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for ComputedGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Collect all hooks with computed fields, paired with their models
        let hooks_with_computed: Vec<(&Hook, Option<&Model>)> = schema.schema.hooks.iter()
            .filter(|h| !h.computed_fields.is_empty())
            .map(|hook| {
                // Find the corresponding model by name or model_ref
                let model = schema.schema.models.iter()
                    .find(|m| m.name == hook.name || m.name == hook.model_ref);
                (hook, model)
            })
            .collect();

        if hooks_with_computed.is_empty() {
            return Ok(output);
        }

        // Generate the computed module
        let content = self.generate_computed_module_with_models(&hooks_with_computed)?;
        output.add_file(
            PathBuf::from("src/domain/computed/mod.rs"),
            content,
        );

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "computed"
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_null_comparison() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("parent_id".to_string()))),
            op: BinaryOp::Eq,
            right: Box::new(Expression::Literal(Literal::Null)),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "self.parent_id.is_none()");
    }

    #[test]
    fn test_not_null_comparison() {
        // Create generator with parent_id marked as optional
        let mut optional_fields = HashSet::new();
        optional_fields.insert("parent_id".to_string());
        let gen = ComputedGenerator::with_entity_context(
            "TestEntity",
            HashSet::new(),
            std::collections::HashMap::new(),
            optional_fields,
        );
        let expr = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("parent_id".to_string()))),
            op: BinaryOp::Ne,
            right: Box::new(Expression::Literal(Literal::Null)),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "self.parent_id.is_some()");
    }

    #[test]
    fn test_boolean_true_comparison() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("is_active".to_string()))),
            op: BinaryOp::Eq,
            right: Box::new(Expression::Literal(Literal::Bool(true))),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "self.is_active");
    }

    #[test]
    fn test_and_expression() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Binary {
            left: Box::new(Expression::Binary {
                left: Box::new(Expression::FieldRef(FieldRef::Simple("is_active".to_string()))),
                op: BinaryOp::Eq,
                right: Box::new(Expression::Literal(Literal::Bool(true))),
            }),
            op: BinaryOp::And,
            right: Box::new(Expression::Binary {
                left: Box::new(Expression::FieldRef(FieldRef::Simple("is_verified".to_string()))),
                op: BinaryOp::Eq,
                right: Box::new(Expression::Literal(Literal::Bool(true))),
            }),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "self.is_active && self.is_verified");
    }

    #[test]
    fn test_parse_raw_expression() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Raw("parent_id == null".to_string());
        let analysis = gen.analyze_expression("is_root", &expr);
        match analysis {
            ExpressionAnalysis::Simple(code) => {
                assert_eq!(code, "self.parent_id.is_none()");
            }
            _ => panic!("Expected Simple expression"),
        }
    }

    #[test]
    fn test_async_expression_detection() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Raw("count(Organization, parent_id == id)".to_string());
        let analysis = gen.analyze_expression("branch_count", &expr);
        match analysis {
            ExpressionAnalysis::RequiresAsync { _description, .. } => {
                assert!(_description.contains("count"));
            }
            _ => panic!("Expected RequiresAsync expression"),
        }
    }

    #[test]
    fn test_enum_comparison() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("structure_type".to_string()))),
            op: BinaryOp::Eq,
            right: Box::new(Expression::Literal(Literal::String("Department".to_string()))),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(
            code,
            "self.structure_type == crate::domain::entity::OrganizationStructureType::Department"
        );
    }

    #[test]
    fn test_enum_comparison_generic_type() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("contact_type".to_string()))),
            op: BinaryOp::Eq,
            right: Box::new(Expression::Literal(Literal::String("primary".to_string()))),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(
            code,
            "self.contact_type == crate::domain::entity::ContactType::Primary"
        );
    }

    #[test]
    fn test_concat_function() {
        let gen = ComputedGenerator::new();
        let expr = Expression::FunctionCall {
            name: "concat".to_string(),
            args: vec![
                Expression::FieldRef(FieldRef::Simple("first_name".to_string())),
                Expression::Literal(Literal::String(" ".to_string())),
                Expression::FieldRef(FieldRef::Simple("last_name".to_string())),
            ],
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "format!(\"{}{}{}\", self.first_name, \" \", self.last_name)");
    }

    #[test]
    fn test_coalesce_function() {
        let gen = ComputedGenerator::new();
        let expr = Expression::FunctionCall {
            name: "coalesce".to_string(),
            args: vec![
                Expression::FieldRef(FieldRef::Simple("nickname".to_string())),
                Expression::FieldRef(FieldRef::Simple("name".to_string())),
            ],
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "self.nickname.unwrap_or(self.name)");
    }

    #[test]
    fn test_truncate_long_expression() {
        let long_expr = "(name != null ? 10 : 0) + (description != null ? 15 : 0) + (logo != null ? 15 : 0) + (url != null ? 10 : 0)";
        let truncated = ComputedGenerator::truncate_expression_for_comment(long_expr);
        assert!(truncated.len() <= 60);
        assert!(truncated.ends_with("..."));
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(ComputedGenerator::to_pascal_case("structure_type"), "StructureType");
        assert_eq!(ComputedGenerator::to_pascal_case("department"), "Department");
        assert_eq!(ComputedGenerator::to_pascal_case("my_enum_value"), "MyEnumValue");
    }

    #[test]
    fn test_enum_comparison_with_entity_context() {
        // Create generator with entity context (no model field types - uses fallback)
        let mut fields = std::collections::HashSet::new();
        fields.insert("status".to_string());
        fields.insert("visibility".to_string());
        let gen = ComputedGenerator::with_entity_context("Listing", fields, std::collections::HashMap::new(), std::collections::HashSet::new());

        // Test "status" field with entity context -> ListingStatus (fallback when no field_types)
        let expr = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("status".to_string()))),
            op: BinaryOp::Eq,
            right: Box::new(Expression::Literal(Literal::String("active".to_string()))),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "self.status == ListingStatus::Active");

        // Test "visibility" field with entity context -> ListingVisibility
        let expr2 = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("visibility".to_string()))),
            op: BinaryOp::Eq,
            right: Box::new(Expression::Literal(Literal::String("public".to_string()))),
        };
        let code2 = gen.expression_to_rust(&expr2);
        assert_eq!(code2, "self.visibility == ListingVisibility::Public");
    }

    #[test]
    fn test_enum_comparison_with_model_field_types() {
        // Create generator with actual model field types
        let mut fields = std::collections::HashSet::new();
        fields.insert("status".to_string());

        let mut field_types = std::collections::HashMap::new();
        field_types.insert("status".to_string(), "ReviewStatus".to_string());

        let gen = ComputedGenerator::with_entity_context("ListingReview", fields, field_types, std::collections::HashSet::new());

        // Test "status" field with actual type from model -> ReviewStatus (not ListingReviewStatus)
        let expr = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("status".to_string()))),
            op: BinaryOp::Eq,
            right: Box::new(Expression::Literal(Literal::String("approved".to_string()))),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "self.status == ReviewStatus::Approved");
    }

    #[test]
    fn test_enum_comparison_combined_expression() {
        // Test combined expression: status == "active" && visibility == "public"
        let mut fields = std::collections::HashSet::new();
        fields.insert("status".to_string());
        fields.insert("visibility".to_string());

        let mut field_types = std::collections::HashMap::new();
        field_types.insert("status".to_string(), "ListingStatus".to_string());
        field_types.insert("visibility".to_string(), "ListingVisibility".to_string());

        let gen = ComputedGenerator::with_entity_context("Listing", fields, field_types, std::collections::HashSet::new());

        let expr = Expression::Binary {
            left: Box::new(Expression::Binary {
                left: Box::new(Expression::FieldRef(FieldRef::Simple("status".to_string()))),
                op: BinaryOp::Eq,
                right: Box::new(Expression::Literal(Literal::String("active".to_string()))),
            }),
            op: BinaryOp::And,
            right: Box::new(Expression::Binary {
                left: Box::new(Expression::FieldRef(FieldRef::Simple("visibility".to_string()))),
                op: BinaryOp::Eq,
                right: Box::new(Expression::Literal(Literal::String("public".to_string()))),
            }),
        };
        let code = gen.expression_to_rust(&expr);
        assert_eq!(code, "self.status == ListingStatus::Active && self.visibility == ListingVisibility::Public");
    }

    // Tests for expression_to_rust_for_string_context()

    #[test]
    fn test_expression_to_rust_for_string_context_integer_field() {
        let mut field_types = std::collections::HashMap::new();
        field_types.insert("port".to_string(), "i32".to_string());
        let gen = ComputedGenerator::with_entity_context(
            "TestEntity",
            std::collections::HashSet::new(),
            field_types,
            std::collections::HashSet::new(),
        );

        let expr = Expression::FieldRef(FieldRef::Simple("port".to_string()));
        let code = gen.expression_to_rust_for_string_context(&expr);
        assert_eq!(code, "format!(\"{}\", self.port)");
    }

    #[test]
    fn test_expression_to_rust_for_string_context_count_field() {
        let mut field_types = std::collections::HashMap::new();
        field_types.insert("item_count".to_string(), "i32".to_string());
        let gen = ComputedGenerator::with_entity_context(
            "TestEntity",
            std::collections::HashSet::new(),
            field_types,
            std::collections::HashSet::new(),
        );

        let expr = Expression::FieldRef(FieldRef::Simple("item_count".to_string()));
        let code = gen.expression_to_rust_for_string_context(&expr);
        assert_eq!(code, "format!(\"{}\", self.item_count)");
    }

    #[test]
    fn test_expression_to_rust_for_string_context_enum_field() {
        let mut field_types = std::collections::HashMap::new();
        field_types.insert("status_type".to_string(), "StatusType".to_string());
        let gen = ComputedGenerator::with_entity_context(
            "TestEntity",
            std::collections::HashSet::new(),
            field_types,
            std::collections::HashSet::new(),
        );

        let expr = Expression::FieldRef(FieldRef::Simple("status_type".to_string()));
        let code = gen.expression_to_rust_for_string_context(&expr);
        assert_eq!(code, "format!(\"{:?}\", self.status_type)");
    }

    #[test]
    fn test_expression_to_rust_for_string_context_optional_string_field() {
        let mut field_types = std::collections::HashMap::new();
        field_types.insert("description".to_string(), "String".to_string());
        let mut optional_fields = std::collections::HashSet::new();
        optional_fields.insert("description".to_string());

        let gen = ComputedGenerator::with_entity_context(
            "TestEntity",
            std::collections::HashSet::new(),
            field_types,
            optional_fields,
        );

        let expr = Expression::FieldRef(FieldRef::Simple("description".to_string()));
        let code = gen.expression_to_rust_for_string_context(&expr);
        assert_eq!(code, "self.description.as_deref().unwrap_or(\"\")");
    }

    #[test]
    fn test_expression_to_rust_for_string_context_string_field() {
        let mut field_types = std::collections::HashMap::new();
        field_types.insert("name".to_string(), "String".to_string());

        let gen = ComputedGenerator::with_entity_context(
            "TestEntity",
            std::collections::HashSet::new(),
            field_types,
            std::collections::HashSet::new(),
        );

        let expr = Expression::FieldRef(FieldRef::Simple("name".to_string()));
        let code = gen.expression_to_rust_for_string_context(&expr);
        assert_eq!(code, "&self.name");
    }

    #[test]
    fn test_expression_to_rust_for_string_context_regular_field() {
        let gen = ComputedGenerator::with_entity_context(
            "TestEntity",
            std::collections::HashSet::new(),
            std::collections::HashMap::new(),
            std::collections::HashSet::new(),
        );

        let expr = Expression::FieldRef(FieldRef::Simple("email".to_string()));
        let code = gen.expression_to_rust_for_string_context(&expr);
        assert_eq!(code, "self.email");
    }

    #[test]
    fn test_expression_to_rust_for_string_context_literal() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Literal(Literal::String("hello".to_string()));
        let code = gen.expression_to_rust_for_string_context(&expr);
        assert_eq!(code, "\"hello\"");
    }

    #[test]
    fn test_expression_to_rust_for_string_context_string_concatenation() {
        let gen = ComputedGenerator::new();
        let expr = Expression::Binary {
            left: Box::new(Expression::FieldRef(FieldRef::Simple("first_name".to_string()))),
            op: BinaryOp::Add,
            right: Box::new(Expression::Literal(Literal::String(" ".to_string()))),
        };
        let code = gen.expression_to_rust_for_string_context(&expr);
        assert_eq!(code, "format!(\"{}{}\", self.first_name, \" \")");
    }
}
