//! Configuration generator
//!
//! Generates YAML configuration files for the module:
//! - application.yml - Main configuration file
//! - application-dev.yml - Development overrides
//! - application-prod.yml - Production overrides
//!
//! ## Generated Configuration
//!
//! The generated configuration follows Spring Boot-style YAML configuration
//! with environment-specific overrides.

use super::{GenerateError, GeneratedOutput, Generator};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates configuration files from schema
pub struct ConfigGenerator;

impl ConfigGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate main application.yml
    fn generate_application_yml(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;

        writeln!(output, "# {} Module Configuration", to_pascal_case(module_name)).unwrap();
        writeln!(output, "#").unwrap();
        writeln!(output, "# Generated by metaphor-schema. Customize as needed.").unwrap();
        writeln!(output, "#").unwrap();
        writeln!(output, "# Override settings per environment:").unwrap();
        writeln!(output, "#   - application-dev.yml for development").unwrap();
        writeln!(output, "#   - application-prod.yml for production").unwrap();
        writeln!(output).unwrap();

        // Server configuration
        writeln!(output, "server:").unwrap();
        writeln!(output, "  host: 0.0.0.0").unwrap();
        writeln!(output, "  port: 3000").unwrap();
        writeln!(output, "  grpc_port: 50051").unwrap();
        writeln!(output).unwrap();

        // Database configuration
        writeln!(output, "database:").unwrap();
        writeln!(output, "  # PostgreSQL connection").unwrap();
        writeln!(output, "  url: postgresql://root:password@localhost:5432/{}", module_name).unwrap();
        writeln!(output, "  max_connections: 20").unwrap();
        writeln!(output, "  min_connections: 5").unwrap();
        writeln!(output, "  connect_timeout: 30").unwrap();
        writeln!(output, "  idle_timeout: 600").unwrap();
        writeln!(output).unwrap();

        // Module configuration
        writeln!(output, "module:").unwrap();
        writeln!(output, "  name: {}", module_name).unwrap();
        writeln!(output, "  enabled: true").unwrap();
        writeln!(output).unwrap();

        // Feature flags based on schema
        writeln!(output, "features:").unwrap();

        // Check if any model has soft delete
        let has_soft_delete = schema.schema.models.iter().any(|m| m.has_soft_delete());
        writeln!(output, "  soft_delete: {}", has_soft_delete).unwrap();

        // Check for state machines (from hooks)
        let has_hooks = !schema.schema.hooks.is_empty();
        writeln!(output, "  state_machines: {}", has_hooks).unwrap();

        // Check for workflows (business processes)
        let has_workflows = !schema.schema.workflows.is_empty();
        writeln!(output, "  workflows: {}", has_workflows).unwrap();

        writeln!(output).unwrap();

        // Entity-specific configuration
        if !schema.schema.models.is_empty() {
            writeln!(output, "entities:").unwrap();
            for model in &schema.schema.models {
                let snake_name = to_snake_case(&model.name);
                let collection = model.collection.as_deref().unwrap_or(&snake_name);

                writeln!(output, "  {}:", snake_name).unwrap();
                writeln!(output, "    collection: {}", collection).unwrap();
                writeln!(output, "    enabled: true").unwrap();
                writeln!(output, "    cache_ttl: 300  # seconds").unwrap();

                // Check for pagination settings
                writeln!(output, "    pagination:").unwrap();
                writeln!(output, "      default_limit: 20").unwrap();
                writeln!(output, "      max_limit: 100").unwrap();
            }
            writeln!(output).unwrap();
        }

        // Logging configuration
        writeln!(output, "logging:").unwrap();
        writeln!(output, "  level: info").unwrap();
        writeln!(output, "  format: json").unwrap();
        writeln!(output, "  file: logs/{}.log", module_name).unwrap();
        writeln!(output).unwrap();

        // Tracing configuration
        writeln!(output, "tracing:").unwrap();
        writeln!(output, "  enabled: true").unwrap();
        writeln!(output, "  exporter: otlp").unwrap();
        writeln!(output, "  endpoint: http://localhost:4317").unwrap();
        writeln!(output).unwrap();

        // Metrics configuration
        writeln!(output, "metrics:").unwrap();
        writeln!(output, "  enabled: true").unwrap();
        writeln!(output, "  endpoint: /metrics").unwrap();
        writeln!(output, "  port: 9090").unwrap();

        Ok(output)
    }

    /// Generate development configuration
    fn generate_dev_yml(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;

        writeln!(output, "# {} Development Configuration", to_pascal_case(module_name)).unwrap();
        writeln!(output, "#").unwrap();
        writeln!(output, "# Overrides for local development").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "server:").unwrap();
        writeln!(output, "  host: 127.0.0.1").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "database:").unwrap();
        writeln!(output, "  url: postgresql://root:password@localhost:5432/{}_dev", module_name).unwrap();
        writeln!(output, "  max_connections: 5").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "logging:").unwrap();
        writeln!(output, "  level: debug").unwrap();
        writeln!(output, "  format: pretty").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "tracing:").unwrap();
        writeln!(output, "  enabled: false  # Disable in development").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "metrics:").unwrap();
        writeln!(output, "  enabled: false  # Disable in development").unwrap();

        Ok(output)
    }

    /// Generate production configuration
    fn generate_prod_yml(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;

        writeln!(output, "# {} Production Configuration", to_pascal_case(module_name)).unwrap();
        writeln!(output, "#").unwrap();
        writeln!(output, "# Production settings - use environment variables for secrets").unwrap();
        writeln!(output, "#").unwrap();
        writeln!(output, "# Environment variables:").unwrap();
        writeln!(output, "#   DATABASE_URL - PostgreSQL connection string").unwrap();
        writeln!(output, "#   SERVER_PORT - Server port (default 3000)").unwrap();
        writeln!(output, "#   GRPC_PORT - gRPC port (default 50051)").unwrap();
        writeln!(output, "#   OTEL_EXPORTER_OTLP_ENDPOINT - OpenTelemetry endpoint").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "server:").unwrap();
        writeln!(output, "  host: 0.0.0.0").unwrap();
        writeln!(output, "  port: ${{SERVER_PORT:3000}}").unwrap();
        writeln!(output, "  grpc_port: ${{GRPC_PORT:50051}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "database:").unwrap();
        writeln!(output, "  url: ${{DATABASE_URL}}").unwrap();
        writeln!(output, "  max_connections: ${{DB_MAX_CONNECTIONS:50}}").unwrap();
        writeln!(output, "  min_connections: ${{DB_MIN_CONNECTIONS:10}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "logging:").unwrap();
        writeln!(output, "  level: ${{LOG_LEVEL:info}}").unwrap();
        writeln!(output, "  format: json").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "tracing:").unwrap();
        writeln!(output, "  enabled: true").unwrap();
        writeln!(output, "  endpoint: ${{OTEL_EXPORTER_OTLP_ENDPOINT}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "metrics:").unwrap();
        writeln!(output, "  enabled: true").unwrap();

        Ok(output)
    }

    /// Generate Rust configuration struct
    fn generate_config_rs(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        // Header
        writeln!(output, "//! Configuration types for {} module", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output, "use std::path::Path;").unwrap();
        writeln!(output).unwrap();

        // Main config struct
        writeln!(output, "/// Main configuration for {} module", pascal_name).unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct {}Config {{", pascal_name).unwrap();
        writeln!(output, "    pub server: ServerConfig,").unwrap();
        writeln!(output, "    pub database: DatabaseConfig,").unwrap();
        writeln!(output, "    pub module: ModuleConfig,").unwrap();
        writeln!(output, "    pub features: FeaturesConfig,").unwrap();
        writeln!(output, "    pub logging: LoggingConfig,").unwrap();
        writeln!(output, "    pub tracing: TracingConfig,").unwrap();
        writeln!(output, "    pub metrics: MetricsConfig,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Server config
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct ServerConfig {{").unwrap();
        writeln!(output, "    pub host: String,").unwrap();
        writeln!(output, "    pub port: u16,").unwrap();
        writeln!(output, "    pub grpc_port: u16,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Database config
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct DatabaseConfig {{").unwrap();
        writeln!(output, "    pub url: String,").unwrap();
        writeln!(output, "    pub max_connections: u32,").unwrap();
        writeln!(output, "    pub min_connections: u32,").unwrap();
        writeln!(output, "    pub connect_timeout: u64,").unwrap();
        writeln!(output, "    pub idle_timeout: u64,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Module config
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct ModuleConfig {{").unwrap();
        writeln!(output, "    pub name: String,").unwrap();
        writeln!(output, "    pub enabled: bool,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Features config
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct FeaturesConfig {{").unwrap();
        writeln!(output, "    pub soft_delete: bool,").unwrap();
        writeln!(output, "    pub state_machines: bool,").unwrap();
        writeln!(output, "    pub flows: bool,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Logging config
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct LoggingConfig {{").unwrap();
        writeln!(output, "    pub level: String,").unwrap();
        writeln!(output, "    pub format: String,").unwrap();
        writeln!(output, "    pub file: Option<String>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Tracing config
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct TracingConfig {{").unwrap();
        writeln!(output, "    pub enabled: bool,").unwrap();
        writeln!(output, "    pub exporter: Option<String>,").unwrap();
        writeln!(output, "    pub endpoint: Option<String>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Metrics config
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct MetricsConfig {{").unwrap();
        writeln!(output, "    pub enabled: bool,").unwrap();
        writeln!(output, "    pub endpoint: Option<String>,").unwrap();
        writeln!(output, "    pub port: Option<u16>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Config loading implementation
        writeln!(output, "impl {}Config {{", pascal_name).unwrap();
        writeln!(output, "    /// Load configuration from YAML files").unwrap();
        writeln!(output, "    ///").unwrap();
        writeln!(output, "    /// Loads configuration with environment-specific overrides:").unwrap();
        writeln!(output, "    /// 1. application.yml (base)").unwrap();
        writeln!(output, "    /// 2. application-{{env}}.yml (environment override)").unwrap();
        writeln!(output, "    pub fn load(config_dir: &Path, environment: &str) -> anyhow::Result<Self> {{").unwrap();
        writeln!(output, "        let base_path = config_dir.join(\"application.yml\");").unwrap();
        writeln!(output, "        let env_path = config_dir.join(format!(\"application-{{}}.yml\", environment));").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Load base configuration").unwrap();
        writeln!(output, "        let base_content = std::fs::read_to_string(&base_path)").unwrap();
        writeln!(output, "            .map_err(|e| anyhow::anyhow!(\"Failed to read base config: {{}}\", e))?;").unwrap();
        writeln!(output, "        let mut config: serde_yaml::Value = serde_yaml::from_str(&base_content)?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Load environment overrides if exists").unwrap();
        writeln!(output, "        if env_path.exists() {{").unwrap();
        writeln!(output, "            let env_content = std::fs::read_to_string(&env_path)?;").unwrap();
        writeln!(output, "            let env_config: serde_yaml::Value = serde_yaml::from_str(&env_content)?;").unwrap();
        writeln!(output, "            merge_yaml(&mut config, env_config);").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Apply environment variable overrides").unwrap();
        writeln!(output, "        let config_str = serde_yaml::to_string(&config)?;").unwrap();
        writeln!(output, "        let config_str = expand_env_vars(&config_str);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(serde_yaml::from_str(&config_str)?)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Load from default location with auto-detected environment").unwrap();
        writeln!(output, "    pub fn load_default() -> anyhow::Result<Self> {{").unwrap();
        writeln!(output, "        let config_dir = std::env::current_dir()?.join(\"config\");").unwrap();
        writeln!(output, "        let environment = std::env::var(\"APP_ENV\").unwrap_or_else(|_| \"dev\".to_string());").unwrap();
        writeln!(output, "        Self::load(&config_dir, &environment)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Default implementations
        writeln!(output, "impl Default for ServerConfig {{").unwrap();
        writeln!(output, "    fn default() -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            host: \"0.0.0.0\".to_string(),").unwrap();
        writeln!(output, "            port: 3000,").unwrap();
        writeln!(output, "            grpc_port: 50051,").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl Default for DatabaseConfig {{").unwrap();
        writeln!(output, "    fn default() -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            url: \"postgresql://root:password@localhost:5432/{}\".to_string(),", module_name).unwrap();
        writeln!(output, "            max_connections: 20,").unwrap();
        writeln!(output, "            min_connections: 5,").unwrap();
        writeln!(output, "            connect_timeout: 30,").unwrap();
        writeln!(output, "            idle_timeout: 600,").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Helper functions
        writeln!(output, "/// Merge two YAML values, with the second taking precedence").unwrap();
        writeln!(output, "fn merge_yaml(base: &mut serde_yaml::Value, overlay: serde_yaml::Value) {{").unwrap();
        writeln!(output, "    if let (serde_yaml::Value::Mapping(base_map), serde_yaml::Value::Mapping(overlay_map)) =").unwrap();
        writeln!(output, "        (base, overlay)").unwrap();
        writeln!(output, "    {{").unwrap();
        writeln!(output, "        for (key, value) in overlay_map {{").unwrap();
        writeln!(output, "            if let Some(base_value) = base_map.get_mut(&key) {{").unwrap();
        writeln!(output, "                if value.is_mapping() && base_value.is_mapping() {{").unwrap();
        writeln!(output, "                    merge_yaml(base_value, value);").unwrap();
        writeln!(output, "                }} else {{").unwrap();
        writeln!(output, "                    *base_value = value;").unwrap();
        writeln!(output, "                }}").unwrap();
        writeln!(output, "            }} else {{").unwrap();
        writeln!(output, "                base_map.insert(key, value);").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Expand environment variable references in config").unwrap();
        writeln!(output, "fn expand_env_vars(content: &str) -> String {{").unwrap();
        writeln!(output, "    let mut result = content.to_string();").unwrap();
        writeln!(output, "    let re = regex::Regex::new(r\"\\$\\{{([A-Z_][A-Z0-9_]*)(?::([^}}]*))?\\}}\").unwrap();").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    for cap in re.captures_iter(content) {{").unwrap();
        writeln!(output, "        let full_match = cap.get(0).unwrap().as_str();").unwrap();
        writeln!(output, "        let var_name = cap.get(1).unwrap().as_str();").unwrap();
        writeln!(output, "        let default_value = cap.get(2).map(|m| m.as_str()).unwrap_or(\"\");").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let value = std::env::var(var_name).unwrap_or_else(|_| default_value.to_string());").unwrap();
        writeln!(output, "        result = result.replace(full_match, &value);").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    result").unwrap();
        writeln!(output, "}}").unwrap();

        Ok(output)
    }
}

impl Default for ConfigGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for ConfigGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Generate YAML configuration files
        let app_yml = self.generate_application_yml(schema)?;
        output.add_file(PathBuf::from("config/application.yml"), app_yml);

        let dev_yml = self.generate_dev_yml(schema)?;
        output.add_file(PathBuf::from("config/application-dev.yml"), dev_yml);

        let prod_yml = self.generate_prod_yml(schema)?;
        output.add_file(PathBuf::from("config/application-prod.yml"), prod_yml);

        // Generate Rust configuration types
        let config_rs = self.generate_config_rs(schema)?;
        output.add_file(PathBuf::from("src/config.rs"), config_rs);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "config"
    }
}

use crate::utils::to_snake_case;


fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};
    use crate::ast::workflow::Workflow;
    use crate::ast::hook::Hook;

    fn create_test_model() -> crate::ast::Model {
        let mut model = crate::ast::Model::new("User");
        model.collection = Some("users".to_string());
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "deleted_at".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("orders");
        schema.models.push(create_test_model());
        schema.workflows.push(Workflow::new("UserWorkflow"));
        // Add a hook to test state_machines feature
        schema.hooks.push(Hook::new("UserHook", "User"));
        ResolvedSchema { schema }
    }

    #[test]
    fn test_config_generator_creates_yaml_files() {
        let schema = create_test_schema();
        let generator = ConfigGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("config/application.yml")));
        assert!(output.files.contains_key(&PathBuf::from("config/application-dev.yml")));
        assert!(output.files.contains_key(&PathBuf::from("config/application-prod.yml")));
    }

    #[test]
    fn test_config_generator_creates_rust_types() {
        let schema = create_test_schema();
        let generator = ConfigGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/config.rs")));

        let config_rs = output.files.get(&PathBuf::from("src/config.rs")).unwrap();
        assert!(config_rs.contains("pub struct OrdersConfig"));
        assert!(config_rs.contains("pub struct ServerConfig"));
        assert!(config_rs.contains("pub struct DatabaseConfig"));
    }

    #[test]
    fn test_application_yml_has_module_name() {
        let schema = create_test_schema();
        let generator = ConfigGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let app_yml = output.files.get(&PathBuf::from("config/application.yml")).unwrap();
        assert!(app_yml.contains("# Orders Module Configuration"));
        assert!(app_yml.contains("name: orders"));
    }

    #[test]
    fn test_features_reflect_schema() {
        let schema = create_test_schema();
        let generator = ConfigGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let app_yml = output.files.get(&PathBuf::from("config/application.yml")).unwrap();

        // Should have soft_delete: true (model has deleted_at)
        assert!(app_yml.contains("soft_delete: true"));

        // Should have state_machines: true (schema has hook)
        assert!(app_yml.contains("state_machines: true"));
    }

    #[test]
    fn test_prod_yml_uses_env_vars() {
        let schema = create_test_schema();
        let generator = ConfigGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let prod_yml = output.files.get(&PathBuf::from("config/application-prod.yml")).unwrap();
        assert!(prod_yml.contains("${DATABASE_URL}"));
        assert!(prod_yml.contains("${SERVER_PORT:3000}"));
    }

    #[test]
    fn test_dev_yml_has_debug_settings() {
        let schema = create_test_schema();
        let generator = ConfigGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let dev_yml = output.files.get(&PathBuf::from("config/application-dev.yml")).unwrap();
        assert!(dev_yml.contains("level: debug"));
        assert!(dev_yml.contains("format: pretty"));
    }
}
