//! CQRS generator
//!
//! Phase 1: Emits **type aliases** over the generic CQRS types in backbone-core
//! instead of full command/query struct + handler implementations per entity.
//!
//! ## Before (was hundreds of generated lines per entity):
//! ```rust,ignore
//! pub struct CreateOrderCommand { pub customer_id: Uuid, pub notes: Option<String> }
//! pub struct UpdateOrderCommand { pub id: Uuid, pub notes: Option<String> }
//! impl CommandHandler<CreateOrderCommand> for OrderCommandHandler { ... }
//! ```
//!
//! ## After (7 lines per entity):
//! ```rust,ignore
//! pub type CreateOrderCommand  = GenericCreateCommand<Order, CreateOrderDto>;
//! pub type UpdateOrderCommand  = GenericUpdateCommand<Order, UpdateOrderDto>;
//! pub type DeleteOrderCommand  = GenericDeleteCommand<Order>;
//! pub type RestoreOrderCommand = GenericRestoreCommand<Order>;
//! pub type GetOrderQuery       = GenericGetQuery<Order>;
//! pub type ListOrderQuery      = GenericListQuery<Order>;
//! pub type OrderCommandHandler = GenericCommandHandler<Order, CreateOrderDto, UpdateOrderDto, OrderService>;
//! pub type OrderQueryHandler   = GenericQueryHandler<Order, OrderService>;
//! ```

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates CQRS type aliases from schema
pub struct CqrsGenerator {
    group_by_domain: bool,
}

impl CqrsGenerator {
    pub fn new() -> Self {
        Self { group_by_domain: false }
    }

    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Generate command type aliases for a single entity.
    fn generate_commands(&self, model: &Model) -> String {
        let mut output = String::new();
        let name = &model.name;
        let snake_name = to_snake_case(name);

        writeln!(output, "//! CQRS command type aliases for {} aggregate", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Commands are type aliases over the generic CQRS types in backbone-core.").unwrap();
        writeln!(output, "//! Add entity-specific commands in the `// <<< CUSTOM` zone.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use backbone_core::{{").unwrap();
        writeln!(output, "    GenericCreateCommand, GenericUpdateCommand,").unwrap();
        writeln!(output, "    GenericDeleteCommand, GenericRestoreCommand,").unwrap();
        writeln!(output, "    GenericCommandHandler,").unwrap();
        writeln!(output, "}};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use crate::presentation::dto::{{Create{}Dto, Update{}Dto}};",
            name, name).unwrap();
        writeln!(output, "use crate::application::service::{}Service;", name).unwrap();
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// ─── Command type aliases ────────────────────────────────────────────────────").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub type Create{}Command  = GenericCreateCommand<{}, Create{}Dto>;",
            name, name, name).unwrap();
        writeln!(output, "pub type Update{}Command  = GenericUpdateCommand<{}, Update{}Dto>;",
            name, name, name).unwrap();
        writeln!(output, "pub type Delete{}Command  = GenericDeleteCommand<{}>;",
            name, name).unwrap();
        writeln!(output, "pub type Restore{}Command = GenericRestoreCommand<{}>;",
            name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// ─── Command handler ─────────────────────────────────────────────────────────").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub type {}CommandHandler = GenericCommandHandler<{}, Create{}Dto, Update{}Dto, {}Service>;",
            name, name, name, name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();

        output
    }

    /// Generate query type aliases for a single entity.
    fn generate_queries(&self, model: &Model) -> String {
        let mut output = String::new();
        let name = &model.name;

        writeln!(output, "//! CQRS query type aliases for {} aggregate", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Queries are type aliases over the generic CQRS types in backbone-core.").unwrap();
        writeln!(output, "//! Add entity-specific queries in the `// <<< CUSTOM` zone.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use backbone_core::{{").unwrap();
        writeln!(output, "    GenericGetQuery, GenericListQuery, GenericListDeletedQuery,").unwrap();
        writeln!(output, "    GenericQueryHandler,").unwrap();
        writeln!(output, "}};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use crate::application::service::{}Service;", name).unwrap();
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// ─── Query type aliases ──────────────────────────────────────────────────────").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub type Get{}Query         = GenericGetQuery<{}>;", name, name).unwrap();
        writeln!(output, "pub type List{}Query        = GenericListQuery<{}>;", name, name).unwrap();
        writeln!(output, "pub type ListDeleted{}Query = GenericListDeletedQuery<{}>;", name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// ─── Query handler ───────────────────────────────────────────────────────────").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub type {}QueryHandler = GenericQueryHandler<{}, {}Service>;",
            name, name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();

        output
    }

    fn generate_commands_mod(&self, models: &[Model]) -> String {
        let mut output = String::new();
        writeln!(output, "//! CQRS commands").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub use backbone_core::{{CqrsService, CqrsReadService}};").unwrap();
        writeln!(output).unwrap();
        for model in models {
            writeln!(output, "pub mod {}_commands;", to_snake_case(&model.name)).unwrap();
        }
        writeln!(output).unwrap();
        for model in models {
            let snake = to_snake_case(&model.name);
            let name = &model.name;
            writeln!(output, "pub use {snake}_commands::{{Create{n}Command, Update{n}Command, Delete{n}Command, Restore{n}Command, {n}CommandHandler}};",
                snake = snake, n = name).unwrap();
        }
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();
        output
    }

    fn generate_queries_mod(&self, models: &[Model]) -> String {
        let mut output = String::new();
        writeln!(output, "//! CQRS queries").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        for model in models {
            writeln!(output, "pub mod {}_queries;", to_snake_case(&model.name)).unwrap();
        }
        writeln!(output).unwrap();
        for model in models {
            let snake = to_snake_case(&model.name);
            let name = &model.name;
            writeln!(output, "pub use {snake}_queries::{{Get{n}Query, List{n}Query, ListDeleted{n}Query, {n}QueryHandler}};",
                snake = snake, n = name).unwrap();
        }
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();
        output
    }
}

impl Default for CqrsGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for CqrsGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();
        let models: Vec<&Model> = schema.schema.models.iter().collect();

        for model in &models {
            let snake_name = to_snake_case(&model.name);
            let commands_content = self.generate_commands(model);
            let queries_content = self.generate_queries(model);

            let commands_path = PathBuf::from(format!(
                "src/application/commands/{}_commands.rs",
                snake_name
            ));
            let queries_path = PathBuf::from(format!(
                "src/application/queries/{}_queries.rs",
                snake_name
            ));
            output.add_file(commands_path, commands_content);
            output.add_file(queries_path, queries_content);
        }

        let owned: Vec<Model> = schema.schema.models.clone();
        output.add_file(
            PathBuf::from("src/application/commands/mod.rs"),
            self.generate_commands_mod(&owned),
        );
        output.add_file(
            PathBuf::from("src/application/queries/mod.rs"),
            self.generate_queries_mod(&owned),
        );

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "cqrs"
    }
}

use crate::utils::to_snake_case;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![Field {
            name: "id".to_string(),
            type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
            attributes: vec![Attribute::new("id")],
            ..Default::default()
        }];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_cqrs_creates_files() {
        let schema = create_test_schema();
        let gen = CqrsGenerator::new();
        let out = gen.generate(&schema).unwrap();

        assert!(out.files.contains_key(&PathBuf::from("src/application/commands/order_commands.rs")));
        assert!(out.files.contains_key(&PathBuf::from("src/application/queries/order_queries.rs")));
        assert!(out.files.contains_key(&PathBuf::from("src/application/commands/mod.rs")));
        assert!(out.files.contains_key(&PathBuf::from("src/application/queries/mod.rs")));
    }

    #[test]
    fn test_commands_emits_type_aliases() {
        let schema = create_test_schema();
        let gen = CqrsGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/application/commands/order_commands.rs"))
            .unwrap();

        assert!(content.contains("pub type CreateOrderCommand"));
        assert!(content.contains("pub type UpdateOrderCommand"));
        assert!(content.contains("pub type DeleteOrderCommand"));
        assert!(content.contains("pub type RestoreOrderCommand"));
        assert!(content.contains("pub type OrderCommandHandler"));
        assert!(content.contains("GenericCreateCommand"));
        assert!(content.contains("GenericCommandHandler"));
    }

    #[test]
    fn test_queries_emits_type_aliases() {
        let schema = create_test_schema();
        let gen = CqrsGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/application/queries/order_queries.rs"))
            .unwrap();

        assert!(content.contains("pub type GetOrderQuery"));
        assert!(content.contains("pub type ListOrderQuery"));
        assert!(content.contains("pub type OrderQueryHandler"));
        assert!(content.contains("GenericQueryHandler"));
    }
}
