//! Data-Change Audit Generator (ADR-0025 trigger lane)
//!
//! For every model carrying the `audited` attribute (`audited: true` in the
//! model YAML, or `@audited`), emits ONE migration per audited table
//! attaching the row-level trigger that calls the composed backbone-auditlog
//! module's shared capture function:
//!
//! ```sql
//! CREATE TRIGGER <table>_data_change_audit
//!     AFTER INSERT OR UPDATE OR DELETE ON <schema>.<table>
//!     FOR EACH ROW EXECUTE FUNCTION auditlog.capture_data_change('<pk>');
//! ```
//!
//! The capture semantics (diff shapes, GUC attribution, fallbacks) live in
//! the module, defined once — this generator only wires tables to it, with
//! the table's primary-key column name as the single trigger argument.
//!
//! Per-table migrations, not one combined file: applied migrations are
//! immutable history, so enrolling a NEW audited model must produce a NEW
//! migration — never a rewrite of an already-applied combined one. The
//! stabilizer keys on the base name (`add_data_change_audit_<table>`), so
//! regeneration reuses each table's existing timestamp (idempotent) and a
//! newly audited table gets a fresh one after the current maximum.
//!
//! Composing backbone-auditlog is a hard requirement: the trigger calls
//! `auditlog.capture_data_change()`, so applying this migration on a
//! database without the module fails loudly at CREATE TRIGGER time — the
//! correct failure mode for an audit contract (never silently un-audited).

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Emits per-table data-change audit trigger migrations for `@audited` models.
pub struct DataChangeAuditGenerator;

impl DataChangeAuditGenerator {
    pub fn new() -> Self {
        Self
    }

    /// The audited models of this schema, in declaration order. The pipeline
    /// hands the generator a schema already filtered by per-model generator
    /// config, so `disabled: [data-change-audit]` opts a single model out.
    fn audited_models<'a>(&self, schema: &'a ResolvedSchema) -> Vec<&'a Model> {
        schema
            .schema
            .models
            .iter()
            .filter(|m| m.has_attribute("audited"))
            .collect()
    }

    /// The subject's primary-key column name, passed to the capture function
    /// as the single trigger argument (`TG_ARGV[0]`). Models are declared
    /// with an `@id` field; `id` is the fallback for models that reach this
    /// lane without one.
    fn primary_key_column(model: &Model) -> String {
        model
            .primary_key()
            .map(|f| f.name.clone())
            .unwrap_or_else(|| "id".to_string())
    }

    fn generate_up(&self, model: &Model) -> Result<String, GenerateError> {
        let qualified_table = model.qualified_table_name();
        let bare = model.collection_name();
        let trigger_name = format!("{bare}_data_change_audit");
        let pk = Self::primary_key_column(model);

        let mut out = String::new();
        writeln!(
            out,
            "-- Data-change audit capture for {} (@audited, ADR-0025).",
            model.name
        )
        .unwrap();
        writeln!(out, "-- Generated by metaphor-schema").unwrap();
        writeln!(out, "--").unwrap();
        writeln!(
            out,
            "-- Row-level AFTER trigger calling the composed backbone-auditlog"
        )
        .unwrap();
        writeln!(
            out,
            "-- module's shared capture function, with the primary-key column"
        )
        .unwrap();
        writeln!(
            out,
            "-- name as the single trigger argument. One audit row per affected"
        )
        .unwrap();
        writeln!(
            out,
            "-- row, in the same transaction as the write. Requires"
        )
        .unwrap();
        writeln!(
            out,
            "-- backbone-auditlog composed (its migrations own the trail table"
        )
        .unwrap();
        writeln!(out, "-- and the capture function this trigger calls).").unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "DROP TRIGGER IF EXISTS {trigger_name} ON {qualified_table};"
        )
        .unwrap();
        writeln!(out).unwrap();
        writeln!(
            out,
            "CREATE TRIGGER {trigger_name}"
        )
        .unwrap();
        writeln!(
            out,
            "    AFTER INSERT OR UPDATE OR DELETE ON {qualified_table}"
        )
        .unwrap();
        writeln!(
            out,
            "    FOR EACH ROW EXECUTE FUNCTION auditlog.capture_data_change('{pk}');"
        )
        .unwrap();
        Ok(out)
    }

    fn generate_down(&self, model: &Model) -> Result<String, GenerateError> {
        let qualified_table = model.qualified_table_name();
        let trigger_name = format!("{}_data_change_audit", model.collection_name());
        let mut out = String::new();
        writeln!(out, "-- Generated by metaphor-schema").unwrap();
        writeln!(
            out,
            "DROP TRIGGER IF EXISTS {trigger_name} ON {qualified_table};"
        )
        .unwrap();
        Ok(out)
    }

    /// Timestamp slots for this generator's migrations. They must attach to
    /// tables that already exist, so they slot strictly AFTER every
    /// SQL-generator migration and AFTER the audit-metadata trigger
    /// generator's reserved slot. SQL gen's emission order is:
    ///   index 0           : enums (if any)
    ///   indices 1..=N     : one per model (N = model_count)
    ///   index N+1         : join tables (if any)
    ///   index N+2         : deferred foreign keys (if any)
    ///   index N+2         : audit-metadata timestamp triggers (always, one file)
    /// This generator takes N+3, N+4, … — one per audited table, in model
    /// order. Gaps are harmless; landing on a used slot would collide.
    fn slot_for(schema: &ResolvedSchema, audited_index: usize) -> usize {
        let model_count = schema.schema.models.len();
        let enum_slot = if schema.schema.enums.is_empty() { 0 } else { 1 };
        enum_slot + model_count + 3 + audited_index
    }
}

impl Default for DataChangeAuditGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for DataChangeAuditGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        for (i, model) in self.audited_models(schema).into_iter().enumerate() {
            let ts = super::migration_timestamp_for(Self::slot_for(schema, i));
            output.add_file(
                PathBuf::from(format!(
                    "migrations/{ts}_add_data_change_audit_{}.up.sql",
                    model.collection_name()
                )),
                self.generate_up(model)?,
            );
            output.add_file(
                PathBuf::from(format!(
                    "migrations/{ts}_add_data_change_audit_{}.down.sql",
                    model.collection_name()
                )),
                self.generate_down(model)?,
            );
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "data_change_audit"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, EnumDef, Field, ModuleSchema, PrimitiveType, TypeRef};
    use crate::resolver::ResolvedSchema;

    fn model(name: &str, collection: &str, audited: bool) -> Model {
        let mut m = Model {
            name: name.to_string(),
            collection: Some(collection.to_string()),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    attributes: vec![Attribute::new("id")],
                    ..Default::default()
                },
                Field {
                    name: "label".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
            ],
            ..Default::default()
        };
        if audited {
            m.attributes.push(Attribute::new("audited"));
        }
        m
    }

    fn schema_with(models: Vec<Model>) -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models = models;
        ResolvedSchema { schema }
    }

    #[test]
    fn emits_one_migration_pair_per_audited_model() {
        let resolved = schema_with(vec![
            model("Quote", "quotes", true),
            model("Draft", "drafts", false),
            model("Order", "orders", true),
        ]);
        let output = DataChangeAuditGenerator::new().generate(&resolved).unwrap();

        // 3 models + 0 enums: slots N+3=6, N+4=7 (declaration order).
        let up = "migrations/20260426220006_add_data_change_audit_quotes.up.sql";
        let down = "migrations/20260426220006_add_data_change_audit_quotes.down.sql";
        let up2 = "migrations/20260426220007_add_data_change_audit_orders.up.sql";
        assert!(output.files.contains_key(&PathBuf::from(up)));
        assert!(output.files.contains_key(&PathBuf::from(down)));
        assert!(output.files.contains_key(&PathBuf::from(up2)));

        // The non-audited model gets nothing.
        assert!(output
            .files
            .keys()
            .all(|p| !p.to_string_lossy().contains("drafts")));

        let content = output.files.get(&PathBuf::from(up)).unwrap();
        assert!(content.contains(
            "CREATE TRIGGER quotes_data_change_audit"
        ));
        assert!(content.contains("AFTER INSERT OR UPDATE OR DELETE"));
        assert!(
            content.contains("FOR EACH ROW EXECUTE FUNCTION auditlog.capture_data_change('id');"),
            "the pk column name is the single trigger argument, got:\n{content}"
        );
        assert!(
            content.contains("DROP TRIGGER IF EXISTS quotes_data_change_audit"),
            "re-applying must be idempotent"
        );
        // The stabilizer owns generator-authored files through this marker.
        assert!(content.contains("-- Generated by metaphor-schema"));
    }

    #[test]
    fn emits_nothing_when_no_model_is_audited() {
        let resolved = schema_with(vec![model("Draft", "drafts", false)]);
        let output = DataChangeAuditGenerator::new().generate(&resolved).unwrap();
        assert!(
            output.files.is_empty(),
            "no @audited models → no migration files at all, got {:?}",
            output.files.keys().collect::<Vec<_>>()
        );
    }

    #[test]
    fn schema_scoped_model_gets_qualified_trigger_target() {
        let mut m = model("Doc", "docs", true);
        m.schema = Some("sapiens".to_string());
        let resolved = schema_with(vec![m]);
        let output = DataChangeAuditGenerator::new().generate(&resolved).unwrap();
        let content = output
            .files
            .values()
            .next()
            .expect("one audited model → one file pair");
        let content = if content.contains("CREATE TRIGGER") {
            content
        } else {
            // first key order is a HashMap — find the up file
            output
                .files
                .values()
                .find(|c| c.contains("CREATE TRIGGER"))
                .unwrap()
        };
        assert!(
            content.contains("AFTER INSERT OR UPDATE OR DELETE ON sapiens.docs"),
            "the ON target must be schema-qualified, got:\n{content}"
        );
    }

    #[test]
    fn primary_key_argument_follows_the_models_id_field() {
        let mut m = model("Ledger", "ledger_lines", true);
        m.fields[0] = Field {
            name: "ledger_id".to_string(),
            type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
            attributes: vec![Attribute::new("id")],
            ..Default::default()
        };
        let resolved = schema_with(vec![m]);
        let output = DataChangeAuditGenerator::new().generate(&resolved).unwrap();
        let up = output
            .files
            .values()
            .find(|c| c.contains("CREATE TRIGGER"))
            .unwrap();
        assert!(
            up.contains("auditlog.capture_data_change('ledger_id');"),
            "the declared pk column name travels as the trigger argument, got:\n{up}"
        );
    }

    #[test]
    fn slots_clear_the_sql_and_audit_metadata_reservations() {
        // 2 models + enums present: sql gen ends at N+2 (join/deferred
        // reserves), audit-metadata triggers take N+2 — ours start at N+3.
        let mut resolved = schema_with(vec![model("Quote", "quotes", true)]);
        resolved.schema.enums.push(EnumDef::new("kind"));
        let output = DataChangeAuditGenerator::new().generate(&resolved).unwrap();
        let names: Vec<String> = output
            .files
            .keys()
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        assert!(
            names.iter().any(|n| n.starts_with("20260426220005_add_data_change_audit")),
            "enum(1)+models(1)+3 = slot 5, got {names:?}"
        );
    }
}
