//! Domain Service generator
//!
//! Phase 1: Emits a **type alias** over `PermitAllPolicy<E>` when no domain rules
//! are defined in the schema, or a scaffold struct with `// <<< CUSTOM` marker when
//! the schema declares domain hooks.
//!
//! ## Before (was 100+ generated lines per entity):
//! ```rust,ignore
//! pub struct OrderDomainService { ... }
//! impl OrderDomainService {
//!     pub fn validate(&self, entity: &Order) -> Result<()> { Ok(()) }
//!     pub fn can_create(&self, entity: &Order) -> Result<bool> { Ok(true) }
//!     pub fn can_update(&self, ...) -> Result<bool> { Ok(true) }
//!     pub fn can_delete(&self, entity: &Order) -> Result<bool> { Ok(true) }
//! }
//! ```
//!
//! ## After (1–10 generated lines per entity):
//! ```rust,ignore
//! // No domain rules:
//! pub type OrderDomainPolicy = backbone_core::policy::PermitAllPolicy<Order>;
//!
//! // With domain rules:
//! pub struct OrderDomainPolicy;
//! #[async_trait::async_trait]
//! impl backbone_core::DomainPolicy<Order> for OrderDomainPolicy { /* <<< CUSTOM */ }
//! ```

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::{hook::Hook, Model};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates domain policy type aliases (or scaffolds) from schema
pub struct DomainServiceGenerator {
    /// Group generated files by model/domain
    group_by_domain: bool,
}

impl DomainServiceGenerator {
    pub fn new() -> Self {
        Self {
            group_by_domain: false,
        }
    }

    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Returns true when the schema defines any validation rules for this model.
    ///
    /// Rules are stored on `ModuleSchema.hooks` (not on `Model`), so the caller
    /// supplies the relevant hooks slice already filtered to this model.
    fn has_domain_rules(hooks: &[&Hook]) -> bool {
        hooks.iter().any(|h| !h.rules.is_empty())
    }

    /// Generate domain policy file for a model.
    fn generate_domain_policy(&self, model: &Model, model_hooks: &[&Hook]) -> Result<String, GenerateError> {
        let mut output = String::new();
        let name = &model.name;
        let snake_name = to_snake_case(name);

        writeln!(output, "//! Domain policy for {} aggregate", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! `DomainPolicy` enforces pure business invariants (state-based rules).").unwrap();
        writeln!(output, "//! Identity-based rules live in `backbone_auth::ResourcePolicy`.").unwrap();
        writeln!(output).unwrap();

        if Self::has_domain_rules(model_hooks) {
            // Scaffold: entity has declared domain rules — emit a struct with CUSTOM marker.
            writeln!(output, "use async_trait::async_trait;").unwrap();
            writeln!(output, "use backbone_core::{{DomainPolicy, PolicyDecision}};").unwrap();
            writeln!(output, "use crate::domain::entity::{};", name).unwrap();
            writeln!(output).unwrap();
            writeln!(output, "/// Domain policy for {} — enforces business invariants.", name).unwrap();
            writeln!(output, "pub struct {}DomainPolicy;", name).unwrap();
            writeln!(output).unwrap();
            writeln!(output, "#[async_trait]").unwrap();
            writeln!(output, "impl DomainPolicy<{}> for {}DomainPolicy {{", name, name).unwrap();
            writeln!(output, "    // <<< CUSTOM").unwrap();
            writeln!(output, "    // Add entity-specific invariant checks here.").unwrap();
            writeln!(output, "    // Example:").unwrap();
            writeln!(output, "    // async fn can_delete(&self, entity: &{}) -> PolicyDecision {{", name).unwrap();
            writeln!(output, "    //     if entity.is_locked {{").unwrap();
            writeln!(output, "    //         Err(\"locked {} cannot be deleted\".into())", snake_name).unwrap();
            writeln!(output, "    //     }} else {{ Ok(true) }}").unwrap();
            writeln!(output, "    // }}").unwrap();
            writeln!(output, "    // END CUSTOM").unwrap();
            writeln!(output, "}}").unwrap();
        } else {
            // No domain rules: alias to PermitAllPolicy.
            writeln!(output, "use backbone_core::PermitAllPolicy;").unwrap();
            writeln!(output, "use crate::domain::entity::{};", name).unwrap();
            writeln!(output).unwrap();
            writeln!(output, "/// Domain policy for {} — permits all operations (no business invariants).", name).unwrap();
            writeln!(output, "///").unwrap();
            writeln!(output, "/// To add domain rules, replace this alias with a struct implementing").unwrap();
            writeln!(output, "/// `backbone_core::DomainPolicy<{}>` in the `// <<< CUSTOM` zone.", name).unwrap();
            writeln!(output, "pub type {}DomainPolicy = PermitAllPolicy<{}>;", name, name).unwrap();
            writeln!(output).unwrap();
            writeln!(output, "// <<< CUSTOM").unwrap();
            writeln!(output, "// END CUSTOM").unwrap();
        }

        Ok(output)
    }
}

impl Default for DomainServiceGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for DomainServiceGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();
        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            // Find hooks that belong to this model
            let model_hooks: Vec<&Hook> = schema.schema.hooks.iter()
                .filter(|h| h.model_ref == model.name || h.name == model.name)
                .collect();
            let content = self.generate_domain_policy(model, &model_hooks)?;

            if self.group_by_domain {
                let path = build_generated_path(
                    "src/domain/services",
                    &model.name,
                    &format!("{}_domain_policy.rs", snake_name),
                    true,
                );
                output.add_file(path, content);

                let sub_mod_path = PathBuf::from(format!(
                    "src/domain/services/{}/mod.rs", snake_name
                ));
                let sub_mod = build_subdirectory_mod(
                    &model.name,
                    &format!("{}_domain_policy", snake_name),
                );
                output.add_file(sub_mod_path, sub_mod);
            } else {
                let path = PathBuf::from(format!(
                    "src/domain/services/{}_domain_policy.rs",
                    snake_name
                ));
                output.add_file(path, content);
            }
        }

        // mod.rs
        if !model_names.is_empty() {
            let mut mod_content = String::new();
            writeln!(mod_content, "//! Domain policies").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
            writeln!(mod_content).unwrap();
            for name in &model_names {
                writeln!(mod_content, "pub mod {}_domain_policy;", to_snake_case(name)).unwrap();
            }
            writeln!(mod_content).unwrap();
            for name in &model_names {
                writeln!(mod_content, "pub use {snake}_domain_policy::{name}DomainPolicy;",
                    snake = to_snake_case(name), name = name).unwrap();
            }
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "// <<< CUSTOM").unwrap();
            writeln!(mod_content, "// END CUSTOM").unwrap();
            output.add_file(PathBuf::from("src/domain/services/mod.rs"), mod_content);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "domain_service"
    }
}

use crate::utils::to_snake_case;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![Field {
            name: "id".to_string(),
            type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
            attributes: vec![Attribute::new("id")],
            ..Default::default()
        }];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_domain_service_creates_files() {
        let schema = create_test_schema();
        let gen = DomainServiceGenerator::new();
        let out = gen.generate(&schema).unwrap();

        assert!(out.files.contains_key(
            &PathBuf::from("src/domain/services/order_domain_policy.rs")
        ));
        assert!(out.files.contains_key(
            &PathBuf::from("src/domain/services/mod.rs")
        ));
    }

    #[test]
    fn test_no_rules_emits_permit_all_alias() {
        let schema = create_test_schema();
        let gen = DomainServiceGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/domain/services/order_domain_policy.rs"))
            .unwrap();

        assert!(content.contains("PermitAllPolicy"));
        assert!(content.contains("pub type OrderDomainPolicy"));
        assert!(!content.contains("pub struct OrderDomainPolicy"));
    }
}
