//! Event Store generator
//!
//! Generates event store infrastructure for event sourcing.
//! The event store is the persistence mechanism for domain events.
//!
//! ## Event Sourcing
//!
//! Event stores:
//! - Persist all domain events immutably
//! - Support event replay for aggregate reconstruction
//! - Enable temporal queries (state at any point in time)
//! - Provide event streaming for projections
//!
//! ## Generated Output
//!
//! For each module, generates:
//! - `event_envelope.rs` - Event wrapper with metadata
//! - `event_store.rs` - Event store trait and implementation
//! - `snapshot_store.rs` - Snapshot storage for optimization

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::{Model, EventSourcedConfig, SnapshotConfig};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates event store infrastructure from schema
pub struct EventStoreGenerator;

impl EventStoreGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Collect all snapshot configurations from event sourced entities
    fn collect_snapshot_configs<'a>(
        &self,
        event_sourced: &'a [EventSourcedConfig],
    ) -> Vec<(&'a String, &'a SnapshotConfig)> {
        event_sourced
            .iter()
            .filter_map(|es| {
                es.snapshot.as_ref().map(|sc| (&es.entity_name, sc))
            })
            .collect()
    }

    /// Generate event envelope
    fn generate_event_envelope(&self, _models: &[&Model]) -> String {
        let mut output = String::new();

        writeln!(output, "//! Event Envelope").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Wraps domain events with metadata for persistence.").unwrap();
        writeln!(output).unwrap();

        // Imports
        writeln!(output, "use chrono::{{DateTime, Utc}};").unwrap();
        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output, "use uuid::Uuid;").unwrap();
        writeln!(output).unwrap();

        // Event envelope struct
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// EVENT ENVELOPE").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Wraps a domain event with metadata for persistence").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct EventEnvelope<T> {{").unwrap();
        writeln!(output, "    /// Unique event ID").unwrap();
        writeln!(output, "    pub event_id: Uuid,").unwrap();
        writeln!(output, "    /// Aggregate ID this event belongs to").unwrap();
        writeln!(output, "    pub aggregate_id: Uuid,").unwrap();
        writeln!(output, "    /// Type of aggregate").unwrap();
        writeln!(output, "    pub aggregate_type: String,").unwrap();
        writeln!(output, "    /// Sequence number within the aggregate stream").unwrap();
        writeln!(output, "    pub sequence: i64,").unwrap();
        writeln!(output, "    /// Event type name (for deserialization)").unwrap();
        writeln!(output, "    pub event_type: String,").unwrap();
        writeln!(output, "    /// Event version (for schema evolution)").unwrap();
        writeln!(output, "    pub event_version: i32,").unwrap();
        writeln!(output, "    /// The actual event payload").unwrap();
        writeln!(output, "    pub payload: T,").unwrap();
        writeln!(output, "    /// Event metadata (correlation ID, causation ID, etc.)").unwrap();
        writeln!(output, "    pub metadata: EventMetadata,").unwrap();
        writeln!(output, "    /// When the event occurred").unwrap();
        writeln!(output, "    pub occurred_at: DateTime<Utc>,").unwrap();
        writeln!(output, "    /// When the event was stored").unwrap();
        writeln!(output, "    pub stored_at: Option<DateTime<Utc>>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl<T> EventEnvelope<T> {{").unwrap();
        writeln!(output, "    /// Create a new event envelope").unwrap();
        writeln!(output, "    pub fn new(").unwrap();
        writeln!(output, "        aggregate_id: Uuid,").unwrap();
        writeln!(output, "        aggregate_type: impl Into<String>,").unwrap();
        writeln!(output, "        sequence: i64,").unwrap();
        writeln!(output, "        event_type: impl Into<String>,").unwrap();
        writeln!(output, "        payload: T,").unwrap();
        writeln!(output, "    ) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            event_id: Uuid::new_v4(),").unwrap();
        writeln!(output, "            aggregate_id,").unwrap();
        writeln!(output, "            aggregate_type: aggregate_type.into(),").unwrap();
        writeln!(output, "            sequence,").unwrap();
        writeln!(output, "            event_type: event_type.into(),").unwrap();
        writeln!(output, "            event_version: 1,").unwrap();
        writeln!(output, "            payload,").unwrap();
        writeln!(output, "            metadata: EventMetadata::default(),").unwrap();
        writeln!(output, "            occurred_at: Utc::now(),").unwrap();
        writeln!(output, "            stored_at: None,").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Add correlation ID for tracing").unwrap();
        writeln!(output, "    pub fn with_correlation_id(mut self, id: Uuid) -> Self {{").unwrap();
        writeln!(output, "        self.metadata.correlation_id = Some(id);").unwrap();
        writeln!(output, "        self").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Add causation ID for event chaining").unwrap();
        writeln!(output, "    pub fn with_causation_id(mut self, id: Uuid) -> Self {{").unwrap();
        writeln!(output, "        self.metadata.causation_id = Some(id);").unwrap();
        writeln!(output, "        self").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Add user ID who triggered the event").unwrap();
        writeln!(output, "    pub fn with_user_id(mut self, id: Uuid) -> Self {{").unwrap();
        writeln!(output, "        self.metadata.user_id = Some(id);").unwrap();
        writeln!(output, "        self").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Event metadata
        writeln!(output, "/// Metadata attached to events").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Default, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct EventMetadata {{").unwrap();
        writeln!(output, "    /// Correlation ID for distributed tracing").unwrap();
        writeln!(output, "    pub correlation_id: Option<Uuid>,").unwrap();
        writeln!(output, "    /// ID of the event that caused this event").unwrap();
        writeln!(output, "    pub causation_id: Option<Uuid>,").unwrap();
        writeln!(output, "    /// User who triggered the action").unwrap();
        writeln!(output, "    pub user_id: Option<Uuid>,").unwrap();
        writeln!(output, "    /// Custom metadata as JSON").unwrap();
        writeln!(output, "    #[serde(default)]").unwrap();
        writeln!(output, "    pub custom: std::collections::HashMap<String, serde_json::Value>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Stored event (for database)
        writeln!(output, "/// Event as stored in the database").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]").unwrap();
        writeln!(output, "pub struct StoredEvent {{").unwrap();
        writeln!(output, "    pub event_id: Uuid,").unwrap();
        writeln!(output, "    pub aggregate_id: Uuid,").unwrap();
        writeln!(output, "    pub aggregate_type: String,").unwrap();
        writeln!(output, "    pub sequence: i64,").unwrap();
        writeln!(output, "    pub event_type: String,").unwrap();
        writeln!(output, "    pub event_version: i32,").unwrap();
        writeln!(output, "    pub payload: serde_json::Value,").unwrap();
        writeln!(output, "    pub metadata: serde_json::Value,").unwrap();
        writeln!(output, "    pub occurred_at: DateTime<Utc>,").unwrap();
        writeln!(output, "    pub stored_at: DateTime<Utc>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Custom section
        writeln!(output, "// <<< CUSTOM ENVELOPE START >>>").unwrap();
        writeln!(output, "// Add custom event envelope extensions here").unwrap();
        writeln!(output, "// <<< CUSTOM ENVELOPE END >>>").unwrap();

        output
    }

    /// Generate event store trait and implementation
    fn generate_event_store(&self, _models: &[&Model]) -> String {
        let mut output = String::new();

        writeln!(output, "//! Event Store").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Provides persistence for domain events.").unwrap();
        writeln!(output).unwrap();

        // Imports
        writeln!(output, "use std::pin::Pin;").unwrap();
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use anyhow::Result;").unwrap();
        writeln!(output, "use async_trait::async_trait;").unwrap();
        writeln!(output, "use chrono::{{DateTime, Utc}};").unwrap();
        writeln!(output, "use futures::Stream;").unwrap();
        writeln!(output, "use sqlx::PgPool;").unwrap();
        writeln!(output, "use uuid::Uuid;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use super::event_envelope::{{EventEnvelope, StoredEvent}};").unwrap();
        writeln!(output).unwrap();

        // Event store trait
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// EVENT STORE TRAIT").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Trait for event store implementations").unwrap();
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "pub trait EventStore: Send + Sync {{").unwrap();
        writeln!(output, "    /// Append events to an aggregate stream").unwrap();
        writeln!(output, "    async fn append(").unwrap();
        writeln!(output, "        &self,").unwrap();
        writeln!(output, "        aggregate_id: Uuid,").unwrap();
        writeln!(output, "        aggregate_type: &str,").unwrap();
        writeln!(output, "        events: Vec<StoredEvent>,").unwrap();
        writeln!(output, "        expected_version: Option<i64>,").unwrap();
        writeln!(output, "    ) -> Result<i64>;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Load all events for an aggregate").unwrap();
        writeln!(output, "    async fn load(&self, aggregate_id: Uuid) -> Result<Vec<StoredEvent>>;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Load events from a specific version").unwrap();
        writeln!(output, "    async fn load_from(&self, aggregate_id: Uuid, from_version: i64) -> Result<Vec<StoredEvent>>;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Get the current version of an aggregate").unwrap();
        writeln!(output, "    async fn get_version(&self, aggregate_id: Uuid) -> Result<i64>;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Stream all events (for projections)").unwrap();
        writeln!(output, "    async fn stream_all(&self, from_position: i64) -> Result<Pin<Box<dyn Stream<Item = StoredEvent> + Send>>>;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Stream events by type").unwrap();
        writeln!(output, "    async fn stream_by_type(&self, event_type: &str, from_position: i64) -> Result<Pin<Box<dyn Stream<Item = StoredEvent> + Send>>>;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    /// Stream events by aggregate type (for projectors)").unwrap();
        writeln!(output, "    async fn stream_by_aggregate_type(&self, aggregate_type: &str, from_position: i64) -> Result<Pin<Box<dyn Stream<Item = StoredEvent> + Send>>>;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    /// Get the last processed sequence for a projector").unwrap();
        writeln!(output, "    async fn get_projector_position(&self, projector_name: &str) -> Result<i64>;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    /// Save the last processed sequence for a projector").unwrap();
        writeln!(output, "    async fn save_projector_position(&self, projector_name: &str, position: i64) -> Result<()>;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // PostgreSQL implementation
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// POSTGRESQL EVENT STORE").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// PostgreSQL-based event store implementation").unwrap();
        writeln!(output, "pub struct PostgresEventStore {{").unwrap();
        writeln!(output, "    pool: PgPool,").unwrap();
        writeln!(output, "    table_name: String,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl PostgresEventStore {{").unwrap();
        writeln!(output, "    /// Create a new PostgreSQL event store").unwrap();
        writeln!(output, "    pub fn new(pool: PgPool) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            pool,").unwrap();
        writeln!(output, "            table_name: \"domain_events\".to_string(),").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Create with custom table name").unwrap();
        writeln!(output, "    pub fn with_table_name(pool: PgPool, table_name: impl Into<String>) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            pool,").unwrap();
        writeln!(output, "            table_name: table_name.into(),").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Get the database pool").unwrap();
        writeln!(output, "    pub fn pool(&self) -> &PgPool {{").unwrap();
        writeln!(output, "        &self.pool").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "impl EventStore for PostgresEventStore {{").unwrap();

        // append implementation
        writeln!(output, "    async fn append(").unwrap();
        writeln!(output, "        &self,").unwrap();
        writeln!(output, "        aggregate_id: Uuid,").unwrap();
        writeln!(output, "        aggregate_type: &str,").unwrap();
        writeln!(output, "        events: Vec<StoredEvent>,").unwrap();
        writeln!(output, "        expected_version: Option<i64>,").unwrap();
        writeln!(output, "    ) -> Result<i64> {{").unwrap();
        writeln!(output, "        // Check optimistic concurrency if expected_version provided").unwrap();
        writeln!(output, "        if let Some(expected) = expected_version {{").unwrap();
        writeln!(output, "            let current = self.get_version(aggregate_id).await?;").unwrap();
        writeln!(output, "            if current != expected {{").unwrap();
        writeln!(output, "                anyhow::bail!(\"Concurrency conflict: expected version {{}}, got {{}}\", expected, current);").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let mut tx = self.pool.begin().await?;").unwrap();
        writeln!(output, "        let mut last_sequence = 0i64;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        for event in events {{").unwrap();
        writeln!(output, "            let query = format!(").unwrap();
        writeln!(output, "                \"INSERT INTO {{}} (event_id, aggregate_id, aggregate_type, sequence, event_type, event_version, payload, metadata, occurred_at, stored_at) ").unwrap();
        writeln!(output, "                 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()) RETURNING sequence\",").unwrap();
        writeln!(output, "                self.table_name").unwrap();
        writeln!(output, "            );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "            last_sequence = sqlx::query_scalar::<_, i64>(&query)").unwrap();
        writeln!(output, "                .bind(event.event_id)").unwrap();
        writeln!(output, "                .bind(aggregate_id)").unwrap();
        writeln!(output, "                .bind(aggregate_type)").unwrap();
        writeln!(output, "                .bind(event.sequence)").unwrap();
        writeln!(output, "                .bind(&event.event_type)").unwrap();
        writeln!(output, "                .bind(event.event_version)").unwrap();
        writeln!(output, "                .bind(&event.payload)").unwrap();
        writeln!(output, "                .bind(&event.metadata)").unwrap();
        writeln!(output, "                .bind(event.occurred_at)").unwrap();
        writeln!(output, "                .fetch_one(&mut *tx)").unwrap();
        writeln!(output, "                .await?;").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        tx.commit().await?;").unwrap();
        writeln!(output, "        Ok(last_sequence)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // load implementation
        writeln!(output, "    async fn load(&self, aggregate_id: Uuid) -> Result<Vec<StoredEvent>> {{").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"SELECT * FROM {{}} WHERE aggregate_id = $1 ORDER BY sequence ASC\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let events = sqlx::query_as::<_, StoredEvent>(&query)").unwrap();
        writeln!(output, "            .bind(aggregate_id)").unwrap();
        writeln!(output, "            .fetch_all(&self.pool)").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(events)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // load_from implementation
        writeln!(output, "    async fn load_from(&self, aggregate_id: Uuid, from_version: i64) -> Result<Vec<StoredEvent>> {{").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"SELECT * FROM {{}} WHERE aggregate_id = $1 AND sequence > $2 ORDER BY sequence ASC\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let events = sqlx::query_as::<_, StoredEvent>(&query)").unwrap();
        writeln!(output, "            .bind(aggregate_id)").unwrap();
        writeln!(output, "            .bind(from_version)").unwrap();
        writeln!(output, "            .fetch_all(&self.pool)").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(events)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // get_version implementation
        writeln!(output, "    async fn get_version(&self, aggregate_id: Uuid) -> Result<i64> {{").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"SELECT COALESCE(MAX(sequence), 0) FROM {{}} WHERE aggregate_id = $1\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let version = sqlx::query_scalar::<_, i64>(&query)").unwrap();
        writeln!(output, "            .bind(aggregate_id)").unwrap();
        writeln!(output, "            .fetch_one(&self.pool)").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(version)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // stream_all implementation with proper cursor-based streaming
        writeln!(output, "    async fn stream_all(&self, from_position: i64) -> Result<Pin<Box<dyn Stream<Item = StoredEvent> + Send>>> {{").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"SELECT * FROM {{}} WHERE sequence > $1 ORDER BY sequence ASC\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Use sqlx's native streaming with fetch() for memory-efficient processing").unwrap();
        writeln!(output, "        let stream = sqlx::query_as::<_, StoredEvent>(&query)").unwrap();
        writeln!(output, "            .bind(from_position)").unwrap();
        writeln!(output, "            .fetch(&self.pool);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Map Result<StoredEvent> to StoredEvent, logging errors").unwrap();
        writeln!(output, "        use futures::StreamExt;").unwrap();
        writeln!(output, "        let mapped = stream.filter_map(|result| async move {{").unwrap();
        writeln!(output, "            match result {{").unwrap();
        writeln!(output, "                Ok(event) => Some(event),").unwrap();
        writeln!(output, "                Err(e) => {{").unwrap();
        writeln!(output, "                    tracing::error!(\"Error streaming event: {{}}\", e);").unwrap();
        writeln!(output, "                    None").unwrap();
        writeln!(output, "                }}").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }});").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(Box::pin(mapped))").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // stream_by_type implementation with proper cursor-based streaming
        writeln!(output, "    async fn stream_by_type(&self, event_type: &str, from_position: i64) -> Result<Pin<Box<dyn Stream<Item = StoredEvent> + Send>>> {{").unwrap();
        writeln!(output, "        let event_type = event_type.to_string();").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"SELECT * FROM {{}} WHERE event_type = $1 AND sequence > $2 ORDER BY sequence ASC\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Use sqlx's native streaming with fetch() for memory-efficient processing").unwrap();
        writeln!(output, "        let stream = sqlx::query_as::<_, StoredEvent>(&query)").unwrap();
        writeln!(output, "            .bind(&event_type)").unwrap();
        writeln!(output, "            .bind(from_position)").unwrap();
        writeln!(output, "            .fetch(&self.pool);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Map Result<StoredEvent> to StoredEvent, logging errors").unwrap();
        writeln!(output, "        use futures::StreamExt;").unwrap();
        writeln!(output, "        let mapped = stream.filter_map(|result| async move {{").unwrap();
        writeln!(output, "            match result {{").unwrap();
        writeln!(output, "                Ok(event) => Some(event),").unwrap();
        writeln!(output, "                Err(e) => {{").unwrap();
        writeln!(output, "                    tracing::error!(\"Error streaming event: {{}}\", e);").unwrap();
        writeln!(output, "                    None").unwrap();
        writeln!(output, "                }}").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }});").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(Box::pin(mapped))").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // stream_by_aggregate_type implementation
        writeln!(output, "    async fn stream_by_aggregate_type(&self, aggregate_type: &str, from_position: i64) -> Result<Pin<Box<dyn Stream<Item = StoredEvent> + Send>>> {{").unwrap();
        writeln!(output, "        let aggregate_type = aggregate_type.to_string();").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"SELECT * FROM {{}} WHERE aggregate_type = $1 AND sequence > $2 ORDER BY sequence ASC\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let stream = sqlx::query_as::<_, StoredEvent>(&query)").unwrap();
        writeln!(output, "            .bind(&aggregate_type)").unwrap();
        writeln!(output, "            .bind(from_position)").unwrap();
        writeln!(output, "            .fetch(&self.pool);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        use futures::StreamExt;").unwrap();
        writeln!(output, "        let mapped = stream.filter_map(|result| async move {{").unwrap();
        writeln!(output, "            match result {{").unwrap();
        writeln!(output, "                Ok(event) => Some(event),").unwrap();
        writeln!(output, "                Err(e) => {{").unwrap();
        writeln!(output, "                    tracing::error!(\"Error streaming event: {{}}\", e);").unwrap();
        writeln!(output, "                    None").unwrap();
        writeln!(output, "                }}").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }});").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(Box::pin(mapped))").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // get_projector_position implementation
        writeln!(output, "    async fn get_projector_position(&self, projector_name: &str) -> Result<i64> {{").unwrap();
        writeln!(output, "        let query = \"SELECT COALESCE(").unwrap();
        writeln!(output, "            (SELECT last_position FROM projector_positions WHERE projector_name = $1),").unwrap();
        writeln!(output, "            0").unwrap();
        writeln!(output, "        )\";").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let position = sqlx::query_scalar::<_, i64>(query)").unwrap();
        writeln!(output, "            .bind(projector_name)").unwrap();
        writeln!(output, "            .fetch_one(&self.pool)").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(position)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // save_projector_position implementation
        writeln!(output, "    async fn save_projector_position(&self, projector_name: &str, position: i64) -> Result<()> {{").unwrap();
        writeln!(output, "        let query = \"INSERT INTO projector_positions (projector_name, last_position, updated_at)").unwrap();
        writeln!(output, "            VALUES ($1, $2, NOW())").unwrap();
        writeln!(output, "            ON CONFLICT (projector_name) DO UPDATE SET").unwrap();
        writeln!(output, "            last_position = EXCLUDED.last_position,").unwrap();
        writeln!(output, "            updated_at = EXCLUDED.updated_at\";").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        sqlx::query(query)").unwrap();
        writeln!(output, "            .bind(projector_name)").unwrap();
        writeln!(output, "            .bind(position)").unwrap();
        writeln!(output, "            .execute(&self.pool)").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(())").unwrap();
        writeln!(output, "    }}").unwrap();

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Custom section
        writeln!(output, "// <<< CUSTOM EVENT STORE START >>>").unwrap();
        writeln!(output, "// Add custom event store implementations here").unwrap();
        writeln!(output, "// <<< CUSTOM EVENT STORE END >>>").unwrap();

        output
    }

    /// Generate snapshot store
    fn generate_snapshot_store(
        &self,
        _models: &[&Model],
        snapshot_configs: &[(&String, &SnapshotConfig)],
    ) -> String {
        let mut output = String::new();

        writeln!(output, "//! Snapshot Store").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Provides snapshot persistence for aggregate optimization.").unwrap();
        writeln!(output).unwrap();

        // Imports
        writeln!(output, "use anyhow::Result;").unwrap();
        writeln!(output, "use async_trait::async_trait;").unwrap();
        writeln!(output, "use chrono::{{DateTime, Utc}};").unwrap();
        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output, "use sqlx::PgPool;").unwrap();
        writeln!(output, "use uuid::Uuid;").unwrap();
        writeln!(output).unwrap();

        // Snapshot struct
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// SNAPSHOT").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Snapshot of aggregate state at a point in time").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]").unwrap();
        writeln!(output, "pub struct Snapshot {{").unwrap();
        writeln!(output, "    pub aggregate_id: Uuid,").unwrap();
        writeln!(output, "    pub aggregate_type: String,").unwrap();
        writeln!(output, "    pub version: i64,").unwrap();
        writeln!(output, "    pub state: serde_json::Value,").unwrap();
        writeln!(output, "    pub created_at: DateTime<Utc>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Snapshot store trait
        writeln!(output, "/// Trait for snapshot store implementations").unwrap();
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "pub trait SnapshotStore: Send + Sync {{").unwrap();
        writeln!(output, "    /// Save a snapshot").unwrap();
        writeln!(output, "    async fn save(&self, snapshot: &Snapshot) -> Result<()>;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    /// Load the latest snapshot for an aggregate").unwrap();
        writeln!(output, "    async fn load(&self, aggregate_id: Uuid) -> Result<Option<Snapshot>>;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    /// Delete snapshots for an aggregate").unwrap();
        writeln!(output, "    async fn delete(&self, aggregate_id: Uuid) -> Result<()>;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // PostgreSQL implementation
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// POSTGRESQL SNAPSHOT STORE").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// PostgreSQL-based snapshot store implementation").unwrap();
        writeln!(output, "pub struct PostgresSnapshotStore {{").unwrap();
        writeln!(output, "    pool: PgPool,").unwrap();
        writeln!(output, "    table_name: String,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl PostgresSnapshotStore {{").unwrap();
        writeln!(output, "    /// Create a new PostgreSQL snapshot store").unwrap();
        writeln!(output, "    pub fn new(pool: PgPool) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            pool,").unwrap();
        writeln!(output, "            table_name: \"aggregate_snapshots\".to_string(),").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Create with custom table name").unwrap();
        writeln!(output, "    pub fn with_table_name(pool: PgPool, table_name: impl Into<String>) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            pool,").unwrap();
        writeln!(output, "            table_name: table_name.into(),").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "impl SnapshotStore for PostgresSnapshotStore {{").unwrap();

        // save implementation
        writeln!(output, "    async fn save(&self, snapshot: &Snapshot) -> Result<()> {{").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"INSERT INTO {{}} (aggregate_id, aggregate_type, version, state, created_at) ").unwrap();
        writeln!(output, "             VALUES ($1, $2, $3, $4, $5) ").unwrap();
        writeln!(output, "             ON CONFLICT (aggregate_id) DO UPDATE SET ").unwrap();
        writeln!(output, "             version = EXCLUDED.version, state = EXCLUDED.state, created_at = EXCLUDED.created_at\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        sqlx::query(&query)").unwrap();
        writeln!(output, "            .bind(snapshot.aggregate_id)").unwrap();
        writeln!(output, "            .bind(&snapshot.aggregate_type)").unwrap();
        writeln!(output, "            .bind(snapshot.version)").unwrap();
        writeln!(output, "            .bind(&snapshot.state)").unwrap();
        writeln!(output, "            .bind(snapshot.created_at)").unwrap();
        writeln!(output, "            .execute(&self.pool)").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(())").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // load implementation
        writeln!(output, "    async fn load(&self, aggregate_id: Uuid) -> Result<Option<Snapshot>> {{").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"SELECT * FROM {{}} WHERE aggregate_id = $1\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let snapshot = sqlx::query_as::<_, Snapshot>(&query)").unwrap();
        writeln!(output, "            .bind(aggregate_id)").unwrap();
        writeln!(output, "            .fetch_optional(&self.pool)").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(snapshot)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // delete implementation
        writeln!(output, "    async fn delete(&self, aggregate_id: Uuid) -> Result<()> {{").unwrap();
        writeln!(output, "        let query = format!(").unwrap();
        writeln!(output, "            \"DELETE FROM {{}} WHERE aggregate_id = $1\",").unwrap();
        writeln!(output, "            self.table_name").unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        sqlx::query(&query)").unwrap();
        writeln!(output, "            .bind(aggregate_id)").unwrap();
        writeln!(output, "            .execute(&self.pool)").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(())").unwrap();
        writeln!(output, "    }}").unwrap();

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Snapshot configuration
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// SNAPSHOT STRATEGY").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Configuration for when to create snapshots").unwrap();
        writeln!(output, "#[derive(Debug, Clone)]").unwrap();
        writeln!(output, "pub struct SnapshotStrategy {{").unwrap();
        writeln!(output, "    /// Whether snapshots are enabled").unwrap();
        writeln!(output, "    pub enabled: bool,").unwrap();
        writeln!(output, "    /// Create snapshot every N events").unwrap();
        writeln!(output, "    pub every_n_events: u32,").unwrap();
        writeln!(output, "    /// Maximum age before creating new snapshot").unwrap();
        writeln!(output, "    pub max_age_seconds: Option<u64>,").unwrap();
        writeln!(output, "    /// Storage backend (e.g., \"postgres\", \"redis\")").unwrap();
        writeln!(output, "    pub storage: Option<String>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl Default for SnapshotStrategy {{").unwrap();
        writeln!(output, "    fn default() -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            enabled: true,").unwrap();
        writeln!(output, "            every_n_events: 100,").unwrap();
        writeln!(output, "            max_age_seconds: Some(86400), // 24 hours").unwrap();
        writeln!(output, "            storage: None,").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl SnapshotStrategy {{").unwrap();
        writeln!(output, "    /// Create a new snapshot strategy").unwrap();
        writeln!(output, "    pub fn new(enabled: bool, every_n_events: u32) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            enabled,").unwrap();
        writeln!(output, "            every_n_events,").unwrap();
        writeln!(output, "            max_age_seconds: None,").unwrap();
        writeln!(output, "            storage: None,").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Set max age before new snapshot").unwrap();
        writeln!(output, "    pub fn with_max_age(mut self, seconds: u64) -> Self {{").unwrap();
        writeln!(output, "        self.max_age_seconds = Some(seconds);").unwrap();
        writeln!(output, "        self").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Set storage backend").unwrap();
        writeln!(output, "    pub fn with_storage(mut self, storage: impl Into<String>) -> Self {{").unwrap();
        writeln!(output, "        self.storage = Some(storage.into());").unwrap();
        writeln!(output, "        self").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Check if a snapshot should be created").unwrap();
        writeln!(output, "    pub fn should_snapshot(&self, current_version: i64, last_snapshot_version: i64) -> bool {{").unwrap();
        writeln!(output, "        self.enabled && (current_version - last_snapshot_version) as u32 >= self.every_n_events").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Generate aggregate-specific snapshot strategies from schema config
        if !snapshot_configs.is_empty() {
            writeln!(output, "// ============================================================================").unwrap();
            writeln!(output, "// AGGREGATE-SPECIFIC SNAPSHOT STRATEGIES").unwrap();
            writeln!(output, "// ============================================================================").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "/// Pre-configured snapshot strategies from schema definitions").unwrap();
            writeln!(output, "pub mod strategies {{").unwrap();
            writeln!(output, "    use super::SnapshotStrategy;").unwrap();
            writeln!(output).unwrap();

            for (entity_name, config) in snapshot_configs {
                let fn_name = crate::utils::to_snake_case(entity_name);
                writeln!(output, "    /// Snapshot strategy for {} aggregate", entity_name).unwrap();
                writeln!(output, "    pub fn {}() -> SnapshotStrategy {{", fn_name).unwrap();

                let enabled = config.enabled;
                let every_n = config.every_n_events;

                match (config.max_age_seconds, &config.storage) {
                    (Some(max_age), Some(storage)) => {
                        writeln!(output, "        SnapshotStrategy::new({}, {})", enabled, every_n).unwrap();
                        writeln!(output, "            .with_max_age({})", max_age).unwrap();
                        writeln!(output, "            .with_storage(\"{}\")", storage).unwrap();
                    }
                    (Some(max_age), None) => {
                        writeln!(output, "        SnapshotStrategy::new({}, {})", enabled, every_n).unwrap();
                        writeln!(output, "            .with_max_age({})", max_age).unwrap();
                    }
                    (None, Some(storage)) => {
                        writeln!(output, "        SnapshotStrategy::new({}, {})", enabled, every_n).unwrap();
                        writeln!(output, "            .with_storage(\"{}\")", storage).unwrap();
                    }
                    (None, None) => {
                        writeln!(output, "        SnapshotStrategy::new({}, {})", enabled, every_n).unwrap();
                    }
                }

                writeln!(output, "    }}").unwrap();
                writeln!(output).unwrap();
            }

            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();
        }

        // Custom section
        writeln!(output, "// <<< CUSTOM SNAPSHOT STORE START >>>").unwrap();
        writeln!(output, "// Add custom snapshot implementations here").unwrap();
        writeln!(output, "// <<< CUSTOM SNAPSHOT STORE END >>>").unwrap();

        output
    }

    /// Generate module file
    fn generate_mod(&self) -> String {
        let mut output = String::new();

        writeln!(output, "//! Event Store Infrastructure").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Provides event sourcing infrastructure.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "mod event_envelope;").unwrap();
        writeln!(output, "mod event_store;").unwrap();
        writeln!(output, "mod snapshot_store;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// Re-exports").unwrap();
        writeln!(output, "pub use event_envelope::{{EventEnvelope, EventMetadata, StoredEvent}};").unwrap();
        writeln!(output, "pub use event_store::{{EventStore, PostgresEventStore}};").unwrap();
        writeln!(output, "pub use snapshot_store::{{Snapshot, SnapshotStore, PostgresSnapshotStore, SnapshotStrategy}};").unwrap();

        output
    }
}

impl Default for EventStoreGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for EventStoreGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        if schema.schema.models.is_empty() {
            return Ok(output);
        }

        let models: Vec<&Model> = schema.schema.models.iter().collect();

        // Collect snapshot configs from EventSourcedConfig
        let snapshot_configs = self.collect_snapshot_configs(&schema.schema.event_sourced);

        // Generate event envelope
        output.add_file(
            PathBuf::from("src/infrastructure/event_store/event_envelope.rs"),
            self.generate_event_envelope(&models),
        );

        // Generate event store
        output.add_file(
            PathBuf::from("src/infrastructure/event_store/event_store.rs"),
            self.generate_event_store(&models),
        );

        // Generate snapshot store with snapshot configs from DDD AST
        output.add_file(
            PathBuf::from("src/infrastructure/event_store/snapshot_store.rs"),
            self.generate_snapshot_store(&models, &snapshot_configs),
        );

        // Generate mod.rs
        output.add_file(
            PathBuf::from("src/infrastructure/event_store/mod.rs"),
            self.generate_mod(),
        );

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "event_store"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::Uuid))),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "status".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "total".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Decimal),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_event_store_generator_creates_files() {
        let schema = create_test_schema();
        let generator = EventStoreGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/event_store/event_envelope.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/event_store/event_store.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/event_store/snapshot_store.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/event_store/mod.rs")));
    }

    #[test]
    fn test_event_envelope_has_metadata() {
        let schema = create_test_schema();
        let generator = EventStoreGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/infrastructure/event_store/event_envelope.rs")).unwrap();

        assert!(content.contains("EventEnvelope"));
        assert!(content.contains("EventMetadata"));
        assert!(content.contains("correlation_id"));
        assert!(content.contains("causation_id"));
    }

    #[test]
    fn test_event_store_has_postgres_impl() {
        let schema = create_test_schema();
        let generator = EventStoreGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/infrastructure/event_store/event_store.rs")).unwrap();

        assert!(content.contains("PostgresEventStore"));
        assert!(content.contains("async fn append"));
        assert!(content.contains("async fn load"));
        assert!(content.contains("async fn stream_all"));
    }

    #[test]
    fn test_snapshot_store_has_strategy() {
        let schema = create_test_schema();
        let generator = EventStoreGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/infrastructure/event_store/snapshot_store.rs")).unwrap();

        assert!(content.contains("SnapshotStrategy"));
        assert!(content.contains("every_n_events"));
        assert!(content.contains("should_snapshot"));
    }
}
