//! Events generator
//!
//! Phase 1: Emits a **type alias** over `CrudEvent<E>` for standard CRUD-only entities,
//! or a wrapper enum with a `Crud(CrudEvent<E>)` variant when the schema declares
//! custom domain events.
//!
//! ## Before (was 200+ generated lines per entity):
//! ```rust,ignore
//! pub enum OrderEvent { Created(Order), Updated(...), Deleted { id }, Restored(...) }
//! impl DomainEvent for OrderEvent { ... }  // identical across all entities
//! ```
//!
//! ## After:
//! ```rust,ignore
//! // CRUD only:
//! pub type OrderEvent = backbone_messaging::CrudEvent<Order>;
//!
//! // With custom events:
//! pub enum OrderEvent {
//!     Crud(backbone_messaging::CrudEvent<Order>),
//!     // <<< CUSTOM EVENTS
//!     // END CUSTOM EVENTS
//! }
//! ```

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::{Model, EventSourcedConfig};
use crate::resolver::ResolvedSchema;
use crate::utils::to_snake_case;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates domain event type aliases from schema
pub struct EventsGenerator {
    group_by_domain: bool,
}

impl EventsGenerator {
    pub fn new() -> Self {
        Self { group_by_domain: false }
    }

    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    fn find_event_sourced_for_model<'a>(
        &self,
        model: &Model,
        event_sourced_configs: &'a [EventSourcedConfig],
    ) -> Option<&'a EventSourcedConfig> {
        event_sourced_configs.iter().find(|es| es.entity_name == model.name)
    }

    /// Returns true when the schema declares domain events beyond the 4 standard CRUD ones.
    fn has_custom_events(event_sourced: Option<&EventSourcedConfig>) -> bool {
        event_sourced.map(|es| es.events.iter().any(|e| {
            !e.ends_with("Created")
                && !e.ends_with("Updated")
                && !e.ends_with("Deleted")
                && !e.ends_with("Restored")
        })).unwrap_or(false)
    }

    /// Generate the event file for a single entity.
    fn generate_events(
        &self,
        model: &Model,
        event_sourced: Option<&EventSourcedConfig>,
    ) -> Result<String, GenerateError> {
        let mut output = String::new();
        let name = &model.name;

        writeln!(output, "//! Domain events for {} entity", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();

        if Self::has_custom_events(event_sourced) {
            // Wrapper enum: preserve Crud variant + CUSTOM zone for entity-specific events.
            writeln!(output, "use backbone_messaging::CrudEvent;").unwrap();
            writeln!(output, "use crate::domain::entity::{};", name).unwrap();
            writeln!(output).unwrap();
            writeln!(output, "/// Domain events for {} aggregate.", name).unwrap();
            writeln!(output, "///").unwrap();
            writeln!(output, "/// `Crud` wraps the standard create/update/delete/restore events.").unwrap();
            writeln!(output, "/// Entity-specific events go in the `// <<< CUSTOM EVENTS` zone.").unwrap();
            writeln!(output, "pub enum {}Event {{", name).unwrap();
            writeln!(output, "    /// Standard CRUD events (create, update, delete, restore).").unwrap();
            writeln!(output, "    Crud(CrudEvent<{}>),", name).unwrap();
            writeln!(output, "    // <<< CUSTOM EVENTS").unwrap();
            writeln!(output, "    // Add entity-specific event variants here. Example:").unwrap();
            writeln!(output, "    // Cancelled {{ reason: String }},").unwrap();
            writeln!(output, "    // Refunded {{ amount: rust_decimal::Decimal }},").unwrap();
            writeln!(output, "    // END CUSTOM EVENTS").unwrap();
            writeln!(output, "}}").unwrap();
        } else {
            // Simple alias — no custom events.
            writeln!(output, "use backbone_messaging::CrudEvent;").unwrap();
            writeln!(output, "use crate::domain::entity::{};", name).unwrap();
            writeln!(output).unwrap();
            writeln!(output, "/// Domain events for {} — type alias over the generic CrudEvent.", name).unwrap();
            writeln!(output, "///").unwrap();
            writeln!(output, "/// To add entity-specific events, replace this alias with a wrapper").unwrap();
            writeln!(output, "/// enum containing a `Crud(CrudEvent<{}>)` variant.", name).unwrap();
            writeln!(output, "pub type {}Event = CrudEvent<{}>;", name, name).unwrap();
            writeln!(output).unwrap();
            writeln!(output, "// <<< CUSTOM").unwrap();
            writeln!(output, "// END CUSTOM").unwrap();
        }

        // EventPublisher type alias (used by service layer).
        writeln!(output).unwrap();
        writeln!(output, "use backbone_messaging::{{CrudEventPublisher, NoOpCrudEventPublisher}};").unwrap();
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "/// Publisher alias for {} events.", name).unwrap();
        writeln!(output, "pub type {}EventPublisher = Arc<dyn CrudEventPublisher<{}> + Send + Sync>;", name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "/// No-op publisher — discards events silently (useful in tests).", ).unwrap();
        writeln!(output, "pub type Noop{}EventPublisher = NoOpCrudEventPublisher<{}>;", name, name).unwrap();

        Ok(output)
    }

    /// Generate event_handlers.rs — now a thin re-export file.
    fn generate_event_handlers(&self, model: &Model) -> String {
        let mut output = String::new();
        let name = &model.name;

        writeln!(output, "//! Event handler trait for {} events", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use backbone_messaging::EventHandler;").unwrap();
        writeln!(output, "use super::{name}Event;", name = name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "/// Event handler for {} events.", name).unwrap();
        writeln!(output, "/// Implement this trait to react to {} lifecycle events.", name).unwrap();
        writeln!(output, "pub trait {}EventHandler: EventHandler<{}Event> {{}}", name, name).unwrap();
        output
    }
}

impl Default for EventsGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for EventsGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();
        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            let event_sourced = self.find_event_sourced_for_model(model, &schema.schema.event_sourced);
            let events_content = self.generate_events(model, event_sourced)?;
            let handlers_content = self.generate_event_handlers(model);

            if self.group_by_domain {
                let events_path = build_generated_path(
                    "src/domain/event",
                    &model.name,
                    &format!("{}_events.rs", snake_name),
                    true,
                );
                output.add_file(events_path, events_content);

                let handlers_path = build_generated_path(
                    "src/domain/event",
                    &model.name,
                    &format!("{}_event_handlers.rs", snake_name),
                    true,
                );
                output.add_file(handlers_path, handlers_content);

                let sub_mod_path = PathBuf::from(format!(
                    "src/domain/event/{}/mod.rs", snake_name
                ));
                let sub_mod = build_subdirectory_mod(
                    &model.name,
                    &format!("{}_events", snake_name),
                );
                output.add_file(sub_mod_path, sub_mod);
            } else {
                output.add_file(
                    PathBuf::from(format!("src/domain/event/{}_events.rs", snake_name)),
                    events_content,
                );
                output.add_file(
                    PathBuf::from(format!("src/domain/event/{}_event_handlers.rs", snake_name)),
                    handlers_content,
                );
            }
        }

        // mod.rs
        if !model_names.is_empty() {
            let mut mod_content = String::new();
            writeln!(mod_content, "//! Domain events").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
            writeln!(mod_content).unwrap();
            for name in &model_names {
                writeln!(mod_content, "pub mod {}_events;", to_snake_case(name)).unwrap();
                writeln!(mod_content, "pub mod {}_event_handlers;", to_snake_case(name)).unwrap();
            }
            writeln!(mod_content).unwrap();
            for name in &model_names {
                let snake = to_snake_case(name);
                writeln!(mod_content, "pub use {snake}_events::{{{name}Event, {name}EventPublisher, Noop{name}EventPublisher}};",
                    snake = snake, name = name).unwrap();
                writeln!(mod_content, "pub use {snake}_event_handlers::{name}EventHandler;",
                    snake = snake, name = name).unwrap();
            }
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "// <<< CUSTOM").unwrap();
            writeln!(mod_content, "// END CUSTOM").unwrap();
            output.add_file(PathBuf::from("src/domain/event/mod.rs"), mod_content);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "events"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![Field {
            name: "id".to_string(),
            type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
            attributes: vec![Attribute::new("id")],
            ..Default::default()
        }];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_events_creates_files() {
        let schema = create_test_schema();
        let gen = EventsGenerator::new();
        let out = gen.generate(&schema).unwrap();

        assert!(out.files.contains_key(&PathBuf::from("src/domain/event/order_events.rs")));
        assert!(out.files.contains_key(&PathBuf::from("src/domain/event/order_event_handlers.rs")));
        assert!(out.files.contains_key(&PathBuf::from("src/domain/event/mod.rs")));
    }

    #[test]
    fn test_events_emits_type_alias_for_crud_only() {
        let schema = create_test_schema();
        let gen = EventsGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/domain/event/order_events.rs"))
            .unwrap();

        assert!(content.contains("pub type OrderEvent = CrudEvent<Order>"));
        assert!(content.contains("CrudEventPublisher"));
        assert!(content.contains("OrderEventPublisher"));
    }
}
