//! Export generator
//!
//! Generates module public API exports for cross-module communication.
//! Exports define what a module exposes to other modules in a bounded context.
//!
//! ## Module Exports
//!
//! Exports provide:
//! - Public types (DTOs for external consumption)
//! - Public services (facades for other modules)
//! - Event types (for event-driven integration)
//! - Query interfaces (read-only access)
//!
//! ## Generated Output
//!
//! - `exports/mod.rs` - Module exports entry point
//! - `exports/types.rs` - Public DTOs
//! - `exports/services.rs` - Public service facades
//! - `exports/events.rs` - Public event types

use super::{GenerateError, GeneratedOutput, Generator};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates module exports from schema
pub struct ExportGenerator;

impl ExportGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate exports module entry point
    fn generate_mod(&self, schema: &ResolvedSchema) -> String {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        writeln!(output, "//! {} Module Exports", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This module defines the public API that {} exposes to other modules.", pascal_name).unwrap();
        writeln!(output, "//! Other modules should ONLY depend on types defined here, not internal types.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! ## Usage from other modules").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! ```text").unwrap();
        writeln!(output, "//! use {}::exports::{{{}Dto, {}QueryService}};", module_name, schema.schema.models.first().map(|m| &m.name).unwrap_or(&"Entity".to_string()), pascal_name).unwrap();
        writeln!(output, "//! ```").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "mod types;").unwrap();
        writeln!(output, "mod services;").unwrap();
        writeln!(output, "mod events;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// Re-export all public types").unwrap();
        writeln!(output, "pub use types::*;").unwrap();
        writeln!(output, "pub use services::*;").unwrap();
        writeln!(output, "pub use events::*;").unwrap();
        writeln!(output).unwrap();

        // Export summary
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// EXPORT SUMMARY").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "/// Summary of what this module exports").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ## Public Types").unwrap();
        for model in &schema.schema.models {
            writeln!(output, "/// - `{}Dto` - Data transfer object for {}", model.name, model.name).unwrap();
            writeln!(output, "/// - `{}Summary` - Summary view of {}", model.name, model.name).unwrap();
            writeln!(output, "/// - `{}Id` - Type-safe ID wrapper", model.name).unwrap();
        }
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ## Public Services").unwrap();
        writeln!(output, "/// - `{}QueryService` - Read-only queries", pascal_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ## Public Events").unwrap();
        for model in &schema.schema.models {
            writeln!(output, "/// - `{}CreatedEvent` - Published when {} is created", model.name, model.name).unwrap();
            writeln!(output, "/// - `{}UpdatedEvent` - Published when {} is updated", model.name, model.name).unwrap();
            writeln!(output, "/// - `{}DeletedEvent` - Published when {} is deleted", model.name, model.name).unwrap();
        }
        writeln!(output, "pub struct ExportSummary;").unwrap();

        output
    }

    /// Generate public types (DTOs)
    fn generate_types(&self, schema: &ResolvedSchema) -> String {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        writeln!(output, "//! Public types for {} module", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! These DTOs are the ONLY types other modules should use.").unwrap();
        writeln!(output, "//! They are decoupled from internal domain entities.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output, "use uuid::Uuid;").unwrap();
        writeln!(output, "use chrono::{{DateTime, Utc}};").unwrap();
        writeln!(output).unwrap();

        for model in &schema.schema.models {
            let name = &model.name;

            // Type-safe ID wrapper
            writeln!(output, "// ============================================================================").unwrap();
            writeln!(output, "// {} TYPES", name.to_uppercase()).unwrap();
            writeln!(output, "// ============================================================================").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "/// Type-safe ID for {}", name).unwrap();
            writeln!(output, "///").unwrap();
            writeln!(output, "/// Use this instead of raw Uuid for type safety across modules.").unwrap();
            writeln!(output, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]").unwrap();
            writeln!(output, "pub struct {}Id(pub Uuid);", name).unwrap();
            writeln!(output).unwrap();

            writeln!(output, "impl {}Id {{", name).unwrap();
            writeln!(output, "    pub fn new(id: Uuid) -> Self {{").unwrap();
            writeln!(output, "        Self(id)").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output).unwrap();
            writeln!(output, "    pub fn into_inner(self) -> Uuid {{").unwrap();
            writeln!(output, "        self.0").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "impl From<Uuid> for {}Id {{", name).unwrap();
            writeln!(output, "    fn from(id: Uuid) -> Self {{").unwrap();
            writeln!(output, "        Self(id)").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "impl From<{}Id> for Uuid {{", name).unwrap();
            writeln!(output, "    fn from(id: {}Id) -> Self {{", name).unwrap();
            writeln!(output, "        id.0").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            // Full DTO
            writeln!(output, "/// Data transfer object for {}", name).unwrap();
            writeln!(output, "///").unwrap();
            writeln!(output, "/// This is the public representation of {} for other modules.", name).unwrap();
            writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
            writeln!(output, "pub struct {}Dto {{", name).unwrap();
            writeln!(output, "    pub id: {}Id,", name).unwrap();

            for field in &model.fields {
                if field.name == "id" {
                    continue;
                }
                let rust_type = self.field_to_dto_type(&field.name, &field.type_ref);
                writeln!(output, "    pub {}: {},", field.name, rust_type).unwrap();
            }

            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            // Summary DTO (for lists)
            writeln!(output, "/// Summary view of {} for list displays", name).unwrap();
            writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
            writeln!(output, "pub struct {}Summary {{", name).unwrap();
            writeln!(output, "    pub id: {}Id,", name).unwrap();

            // Include only key fields
            for field in &model.fields {
                if field.name == "id" {
                    continue;
                }
                if field.name.ends_with("_name") ||
                   field.name == "name" ||
                   field.name == "title" ||
                   field.name == "email" ||
                   field.name == "status" ||
                   field.name == "created_at" {
                    let rust_type = self.field_to_dto_type(&field.name, &field.type_ref);
                    writeln!(output, "    pub {}: {},", field.name, rust_type).unwrap();
                }
            }

            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            // Reference type (for foreign keys)
            writeln!(output, "/// Reference to {} for foreign key relationships", name).unwrap();
            writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
            writeln!(output, "pub struct {}Ref {{", name).unwrap();
            writeln!(output, "    pub id: {}Id,", name).unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();
        }

        // Custom types section
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// CUSTOM TYPES").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM TYPES START >>>").unwrap();
        writeln!(output, "// Add custom public types here").unwrap();
        writeln!(output, "// <<< CUSTOM TYPES END >>>").unwrap();

        output
    }

    /// Generate public services (facades)
    fn generate_services(&self, schema: &ResolvedSchema) -> String {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        writeln!(output, "//! Public services for {} module", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! These services provide the public API for other modules.").unwrap();
        writeln!(output, "//! They only expose read operations - writes go through events.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use anyhow::Result;").unwrap();
        writeln!(output, "use async_trait::async_trait;").unwrap();
        writeln!(output, "use uuid::Uuid;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use super::types::*;").unwrap();
        writeln!(output).unwrap();

        // Query service trait
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// QUERY SERVICE TRAIT").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Public query service for {} module", pascal_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// This trait defines read-only operations that other modules can use.").unwrap();
        writeln!(output, "/// Implementations should NOT expose internal domain logic.").unwrap();
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "pub trait {}QueryService: Send + Sync {{", pascal_name).unwrap();

        for model in &schema.schema.models {
            let name = &model.name;
            let snake_name = to_snake_case(name);

            writeln!(output, "    /// Get {} by ID", name).unwrap();
            writeln!(output, "    async fn get_{}(&self, id: {}Id) -> Result<Option<{}Dto>>;", snake_name, name, name).unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    /// Get {} summary by ID", name).unwrap();
            writeln!(output, "    async fn get_{}_summary(&self, id: {}Id) -> Result<Option<{}Summary>>;", snake_name, name, name).unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    /// Check if {} exists", name).unwrap();
            writeln!(output, "    async fn {}_exists(&self, id: {}Id) -> Result<bool>;", snake_name, name).unwrap();
            writeln!(output).unwrap();
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Query service implementation
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// QUERY SERVICE IMPLEMENTATION").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Default implementation of {}QueryService", pascal_name).unwrap();
        writeln!(output, "pub struct {}QueryServiceImpl<R> {{", pascal_name).unwrap();
        writeln!(output, "    repository: Arc<R>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl<R> {}QueryServiceImpl<R> {{", pascal_name).unwrap();
        writeln!(output, "    pub fn new(repository: Arc<R>) -> Self {{").unwrap();
        writeln!(output, "        Self {{ repository }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Custom services section
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// CUSTOM SERVICES").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM SERVICES START >>>").unwrap();
        writeln!(output, "// Add custom public services here").unwrap();
        writeln!(output, "// <<< CUSTOM SERVICES END >>>").unwrap();

        output
    }

    /// Generate public events
    fn generate_events(&self, schema: &ResolvedSchema) -> String {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        writeln!(output, "//! Public events for {} module", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! These events are published by this module for other modules to subscribe to.").unwrap();
        writeln!(output, "//! Events are the primary mechanism for cross-module communication.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output, "use chrono::{{DateTime, Utc}};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use super::types::*;").unwrap();
        writeln!(output).unwrap();

        for model in &schema.schema.models {
            let name = &model.name;

            writeln!(output, "// ============================================================================").unwrap();
            writeln!(output, "// {} EVENTS", name.to_uppercase()).unwrap();
            writeln!(output, "// ============================================================================").unwrap();
            writeln!(output).unwrap();

            // Created event
            writeln!(output, "/// Event published when a {} is created", name).unwrap();
            writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
            writeln!(output, "pub struct {}CreatedEvent {{", name).unwrap();
            writeln!(output, "    pub id: {}Id,", name).unwrap();
            writeln!(output, "    pub data: {}Dto,", name).unwrap();
            writeln!(output, "    pub occurred_at: DateTime<Utc>,").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            // Updated event
            writeln!(output, "/// Event published when a {} is updated", name).unwrap();
            writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
            writeln!(output, "pub struct {}UpdatedEvent {{", name).unwrap();
            writeln!(output, "    pub id: {}Id,", name).unwrap();
            writeln!(output, "    pub data: {}Dto,", name).unwrap();
            writeln!(output, "    pub occurred_at: DateTime<Utc>,").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            // Deleted event
            writeln!(output, "/// Event published when a {} is deleted", name).unwrap();
            writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
            writeln!(output, "pub struct {}DeletedEvent {{", name).unwrap();
            writeln!(output, "    pub id: {}Id,", name).unwrap();
            writeln!(output, "    pub occurred_at: DateTime<Utc>,").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();
        }

        // Event enum for all module events
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// MODULE EVENT ENUM").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// All events published by {} module", pascal_name).unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "#[serde(tag = \"type\")]").unwrap();
        writeln!(output, "pub enum {}Event {{", pascal_name).unwrap();

        for model in &schema.schema.models {
            let name = &model.name;
            writeln!(output, "    {}Created({}CreatedEvent),", name, name).unwrap();
            writeln!(output, "    {}Updated({}UpdatedEvent),", name, name).unwrap();
            writeln!(output, "    {}Deleted({}DeletedEvent),", name, name).unwrap();
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Event metadata
        writeln!(output, "/// Metadata for module events").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "pub struct {}EventMetadata {{", pascal_name).unwrap();
        writeln!(output, "    pub module: &'static str,").unwrap();
        writeln!(output, "    pub version: &'static str,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl Default for {}EventMetadata {{", pascal_name).unwrap();
        writeln!(output, "    fn default() -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            module: \"{}\",", module_name).unwrap();
        writeln!(output, "            version: \"1.0\",").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Custom events section
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// CUSTOM EVENTS").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM EVENTS START >>>").unwrap();
        writeln!(output, "// Add custom public events here").unwrap();
        writeln!(output, "// <<< CUSTOM EVENTS END >>>").unwrap();

        output
    }

    /// Convert field type to DTO type (simplified external representation)
    fn field_to_dto_type(&self, _name: &str, type_ref: &crate::ast::TypeRef) -> String {
        use crate::ast::TypeRef;

        match type_ref {
            TypeRef::Primitive(p) => p.rust_type().to_string(),
            TypeRef::Custom(name) => name.clone(),
            TypeRef::Array(inner) => format!("Vec<{}>", self.field_to_dto_type("", inner)),
            TypeRef::Optional(inner) => format!("Option<{}>", self.field_to_dto_type("", inner)),
            TypeRef::Map { key, value } => {
                format!("std::collections::HashMap<{}, {}>",
                    self.field_to_dto_type("", key),
                    self.field_to_dto_type("", value))
            }
            TypeRef::ModuleRef { module, name } => format!("{}::{}", module, name),
        }
    }
}

impl Default for ExportGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for ExportGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        if schema.schema.models.is_empty() {
            return Ok(output);
        }

        // Generate exports module
        output.add_file(
            PathBuf::from("src/exports/mod.rs"),
            self.generate_mod(schema),
        );

        // Generate public types
        output.add_file(
            PathBuf::from("src/exports/types.rs"),
            self.generate_types(schema),
        );

        // Generate public services
        output.add_file(
            PathBuf::from("src/exports/services.rs"),
            self.generate_services(schema),
        );

        // Generate public events
        output.add_file(
            PathBuf::from("src/exports/events.rs"),
            self.generate_events(schema),
        );

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "export"
    }
}

use crate::utils::to_snake_case;

fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, Model, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("User");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::Uuid))),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "email".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Email),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "name".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "status".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "created_at".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("sapiens");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_export_generator_creates_files() {
        let schema = create_test_schema();
        let generator = ExportGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/exports/mod.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/exports/types.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/exports/services.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/exports/events.rs")));
    }

    #[test]
    fn test_export_types_has_dto() {
        let schema = create_test_schema();
        let generator = ExportGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/exports/types.rs")).unwrap();

        assert!(content.contains("pub struct UserDto"));
        assert!(content.contains("pub struct UserSummary"));
        assert!(content.contains("pub struct UserId"));
    }

    #[test]
    fn test_export_services_has_query_service() {
        let schema = create_test_schema();
        let generator = ExportGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/exports/services.rs")).unwrap();

        assert!(content.contains("SapiensQueryService"));
        assert!(content.contains("async fn get_user"));
        assert!(content.contains("async fn user_exists"));
    }

    #[test]
    fn test_export_events_has_crud_events() {
        let schema = create_test_schema();
        let generator = ExportGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/exports/events.rs")).unwrap();

        assert!(content.contains("UserCreatedEvent"));
        assert!(content.contains("UserUpdatedEvent"));
        assert!(content.contains("UserDeletedEvent"));
        assert!(content.contains("SapiensEvent"));
    }
}
