//! gRPC Handler generator
//!
//! Generates Tonic gRPC service implementations for the 11 standard Backbone CRUD operations.
//! This includes proto service definitions and Rust implementations.

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::{Model, Hook};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates gRPC service implementations using Tonic
pub struct GrpcGenerator;

impl GrpcGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate proto service definition for a model
    fn generate_proto_service(&self, model: &Model) -> Result<String, GenerateError> {
        let mut output = String::new();
        let model_snake = to_snake_case(&model.name);

        // Proto file header
        writeln!(output, "// {} gRPC service definition", model.name).unwrap();
        writeln!(output, "// Auto-generated by backbone-cli. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "syntax = \"proto3\";").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "package {}.v1;", model_snake).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "import \"google/protobuf/timestamp.proto\";").unwrap();
        writeln!(output, "import \"google/protobuf/empty.proto\";").unwrap();
        writeln!(output, "import \"buf/validate/validate.proto\";").unwrap();
        writeln!(output).unwrap();

        // Service definition
        writeln!(output, "// {} CRUD service with 11 standard operations", model.name).unwrap();
        writeln!(output, "service {}Service {{", model.name).unwrap();
        writeln!(output, "    // List {} (paginated, filtered, sorted)", pluralize(&model.name)).unwrap();
        writeln!(output, "    rpc List(List{}Request) returns (List{}Response);", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Create a new {}", model.name).unwrap();
        writeln!(output, "    rpc Create(Create{}Request) returns ({});", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Get {} by ID", model.name).unwrap();
        writeln!(output, "    rpc Get(Get{}Request) returns ({});", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Update {} (full replacement)", model.name).unwrap();
        writeln!(output, "    rpc Update(Update{}Request) returns ({});", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Partial update {}", model.name).unwrap();
        writeln!(output, "    rpc Patch(Patch{}Request) returns ({});", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Soft delete {} by ID", model.name).unwrap();
        writeln!(output, "    rpc Delete(Delete{}Request) returns (google.protobuf.Empty);", model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Bulk create multiple {}", pluralize(&model.name)).unwrap();
        writeln!(output, "    rpc BulkCreate(BulkCreate{}Request) returns (BulkCreate{}Response);", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Upsert {} (create or update)", model.name).unwrap();
        writeln!(output, "    rpc Upsert(Upsert{}Request) returns ({});", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // List soft-deleted {}", pluralize(&model.name)).unwrap();
        writeln!(output, "    rpc ListTrash(List{}TrashRequest) returns (List{}Response);", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Restore soft-deleted {} by ID", model.name).unwrap();
        writeln!(output, "    rpc Restore(Restore{}Request) returns ({});", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Permanently delete all soft-deleted {}", pluralize(&model.name)).unwrap();
        writeln!(output, "    rpc EmptyTrash(Empty{}TrashRequest) returns (Empty{}TrashResponse);", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // ===========================================").unwrap();
        writeln!(output, "    // Streaming RPCs").unwrap();
        writeln!(output, "    // ===========================================").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Server streaming: Stream all {} matching criteria", pluralize(&model.name)).unwrap();
        writeln!(output, "    rpc StreamList(Stream{}Request) returns (stream {});", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Client streaming: Bulk create {} from stream", pluralize(&model.name)).unwrap();
        writeln!(output, "    rpc StreamBulkCreate(stream Create{}Request) returns (BulkCreate{}Response);", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Bidirectional streaming: Sync {} changes", pluralize(&model.name)).unwrap();
        writeln!(output, "    rpc SyncStream(stream Sync{}Request) returns (stream Sync{}Response);", model.name, model.name).unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Server streaming: Watch for {} changes (real-time updates)", model.name).unwrap();
        writeln!(output, "    rpc Watch(Watch{}Request) returns (stream {}Event);", model.name, model.name).unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Message definitions
        self.write_proto_messages(&mut output, model)?;

        Ok(output)
    }

    fn write_proto_messages(&self, output: &mut String, model: &Model) -> Result<(), GenerateError> {
        // Main entity message
        writeln!(output, "// {} entity", model.name).unwrap();
        writeln!(output, "message {} {{", model.name).unwrap();

        for (i, field) in model.fields.iter().enumerate() {
            let proto_type = self.field_to_proto_type(field);
            let field_num = i + 1;

            // Add validation annotations based on field attributes
            let validations = self.get_proto_validations(field);
            if !validations.is_empty() {
                writeln!(output, "    {} {} = {} [{}];", proto_type, field.name, field_num, validations).unwrap();
            } else {
                writeln!(output, "    {} {} = {};", proto_type, field.name, field_num).unwrap();
            }
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // List request/response
        writeln!(output, "message List{}Request {{", model.name).unwrap();
        writeln!(output, "    int32 page = 1;").unwrap();
        writeln!(output, "    int32 per_page = 2;").unwrap();
        writeln!(output, "    string sort_by = 3;").unwrap();
        writeln!(output, "    string sort_order = 4;").unwrap();
        writeln!(output, "    map<string, string> filters = 5;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "message List{}Response {{", model.name).unwrap();
        writeln!(output, "    repeated {} items = 1;", model.name).unwrap();
        writeln!(output, "    int64 total = 2;").unwrap();
        writeln!(output, "    int32 page = 3;").unwrap();
        writeln!(output, "    int32 per_page = 4;").unwrap();
        writeln!(output, "    int32 total_pages = 5;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Create request
        writeln!(output, "message Create{}Request {{", model.name).unwrap();
        for (i, field) in model.fields.iter().enumerate() {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            let proto_type = self.field_to_proto_type(field);
            let validations = self.get_proto_validations(field);
            if !validations.is_empty() {
                writeln!(output, "    {} {} = {} [{}];", proto_type, field.name, i + 1, validations).unwrap();
            } else {
                writeln!(output, "    {} {} = {};", proto_type, field.name, i + 1).unwrap();
            }
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Get request
        writeln!(output, "message Get{}Request {{", model.name).unwrap();
        writeln!(output, "    string id = 1 [(buf.validate.field).string.uuid = true];").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Update request
        writeln!(output, "message Update{}Request {{", model.name).unwrap();
        writeln!(output, "    string id = 1 [(buf.validate.field).string.uuid = true];").unwrap();
        let mut field_num = 2;
        for field in &model.fields {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            let proto_type = self.field_to_proto_type(field);
            writeln!(output, "    {} {} = {};", proto_type, field.name, field_num).unwrap();
            field_num += 1;
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Patch request (all fields optional)
        writeln!(output, "message Patch{}Request {{", model.name).unwrap();
        writeln!(output, "    string id = 1 [(buf.validate.field).string.uuid = true];").unwrap();
        let mut field_num = 2;
        for field in &model.fields {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            let proto_type = self.field_to_optional_proto_type(field);
            writeln!(output, "    {} {} = {};", proto_type, field.name, field_num).unwrap();
            field_num += 1;
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Delete request
        writeln!(output, "message Delete{}Request {{", model.name).unwrap();
        writeln!(output, "    string id = 1 [(buf.validate.field).string.uuid = true];").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Bulk create
        writeln!(output, "message BulkCreate{}Request {{", model.name).unwrap();
        writeln!(output, "    repeated Create{}Request items = 1;", model.name).unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "message BulkCreate{}Response {{", model.name).unwrap();
        writeln!(output, "    repeated {} items = 1;", model.name).unwrap();
        writeln!(output, "    int32 created_count = 2;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Upsert request
        writeln!(output, "message Upsert{}Request {{", model.name).unwrap();
        writeln!(output, "    string key_field = 1;").unwrap();
        writeln!(output, "    string key_value = 2;").unwrap();
        let mut field_num = 3;
        for field in &model.fields {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            let proto_type = self.field_to_proto_type(field);
            writeln!(output, "    {} {} = {};", proto_type, field.name, field_num).unwrap();
            field_num += 1;
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Trash list request
        writeln!(output, "message List{}TrashRequest {{", model.name).unwrap();
        writeln!(output, "    int32 page = 1;").unwrap();
        writeln!(output, "    int32 per_page = 2;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Restore request
        writeln!(output, "message Restore{}Request {{", model.name).unwrap();
        writeln!(output, "    string id = 1 [(buf.validate.field).string.uuid = true];").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Empty trash
        writeln!(output, "message Empty{}TrashRequest {{}}", model.name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "message Empty{}TrashResponse {{", model.name).unwrap();
        writeln!(output, "    int64 deleted_count = 1;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Streaming messages
        writeln!(output, "// ===========================================").unwrap();
        writeln!(output, "// Streaming Messages").unwrap();
        writeln!(output, "// ===========================================").unwrap();
        writeln!(output).unwrap();

        // Stream list request
        writeln!(output, "// Request for streaming list of {}", pluralize(&model.name)).unwrap();
        writeln!(output, "message Stream{}Request {{", model.name).unwrap();
        writeln!(output, "    // Filter criteria").unwrap();
        writeln!(output, "    map<string, string> filters = 1;").unwrap();
        writeln!(output, "    // Sort field").unwrap();
        writeln!(output, "    string sort_by = 2;").unwrap();
        writeln!(output, "    // Sort order (asc/desc)").unwrap();
        writeln!(output, "    string sort_order = 3;").unwrap();
        writeln!(output, "    // Maximum items to stream (0 = unlimited)").unwrap();
        writeln!(output, "    int32 limit = 4;").unwrap();
        writeln!(output, "    // Cursor for resume support").unwrap();
        writeln!(output, "    optional string cursor = 5;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Sync request/response for bidirectional streaming
        writeln!(output, "// Sync request for bidirectional streaming").unwrap();
        writeln!(output, "message Sync{}Request {{", model.name).unwrap();
        writeln!(output, "    oneof operation {{").unwrap();
        writeln!(output, "        Create{}Request create = 1;", model.name).unwrap();
        writeln!(output, "        Update{}Request update = 2;", model.name).unwrap();
        writeln!(output, "        Delete{}Request delete = 3;", model.name).unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    // Client-provided correlation ID").unwrap();
        writeln!(output, "    string correlation_id = 10;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// Sync response for bidirectional streaming").unwrap();
        writeln!(output, "message Sync{}Response {{", model.name).unwrap();
        writeln!(output, "    // Operation result").unwrap();
        writeln!(output, "    oneof result {{").unwrap();
        writeln!(output, "        {} success = 1;", model.name).unwrap();
        writeln!(output, "        SyncError error = 2;").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    // Original correlation ID").unwrap();
        writeln!(output, "    string correlation_id = 10;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// Error details for sync operations").unwrap();
        writeln!(output, "message SyncError {{").unwrap();
        writeln!(output, "    string code = 1;").unwrap();
        writeln!(output, "    string message = 2;").unwrap();
        writeln!(output, "    map<string, string> details = 3;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Watch request/event
        writeln!(output, "// Request to watch for {} changes", model.name).unwrap();
        writeln!(output, "message Watch{}Request {{", model.name).unwrap();
        writeln!(output, "    // Filter by specific IDs (empty = all)").unwrap();
        writeln!(output, "    repeated string ids = 1;").unwrap();
        writeln!(output, "    // Filter by event types").unwrap();
        writeln!(output, "    repeated string event_types = 2;").unwrap();
        writeln!(output, "    // Start from specific event sequence (for resume)").unwrap();
        writeln!(output, "    optional int64 from_sequence = 3;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// Event emitted by watch stream").unwrap();
        writeln!(output, "message {}Event {{", model.name).unwrap();
        writeln!(output, "    // Event sequence number").unwrap();
        writeln!(output, "    int64 sequence = 1;").unwrap();
        writeln!(output, "    // Event type (created, updated, deleted)").unwrap();
        writeln!(output, "    string event_type = 2;").unwrap();
        writeln!(output, "    // Entity ID").unwrap();
        writeln!(output, "    string entity_id = 3;").unwrap();
        writeln!(output, "    // Current entity state (for created/updated)").unwrap();
        writeln!(output, "    optional {} entity = 4;", model.name).unwrap();
        writeln!(output, "    // Timestamp of the event").unwrap();
        writeln!(output, "    google.protobuf.Timestamp timestamp = 5;").unwrap();
        writeln!(output, "    // User who triggered the event").unwrap();
        writeln!(output, "    optional string user_id = 6;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        Ok(())
    }

    /// Generate Rust gRPC service implementation — Phase 1: type alias over GenericGrpcService.
    ///
    /// The 11 CRUD + streaming RPC dispatch methods are provided by `GenericGrpcService`.
    /// Entity-specific proto↔domain conversion impls are still emitted here.
    fn generate_grpc_impl(&self, model: &Model, hook: Option<&Hook>) -> Result<String, GenerateError> {
        let mut output = String::new();
        let model_snake = to_snake_case(&model.name);
        let name = &model.name;

        writeln!(output, "//! gRPC service type alias for {} entity", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! All 11 CRUD RPCs + streaming are provided by `GenericGrpcService`.").unwrap();
        writeln!(output, "//! Entity-specific proto↔domain conversions are emitted below.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use backbone_core::GenericGrpcService;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use crate::presentation::dto::{{Create{n}Dto, Update{n}Dto}};",
            n = name).unwrap();
        writeln!(output, "use crate::application::service::{n}Service;", n = name).unwrap();
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output).unwrap();

        // Type alias — all RPC logic lives in GenericGrpcService.
        writeln!(output, "/// gRPC service for {} entities.", name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Wraps `{}Service` and exposes all 11 standard CRUD RPCs via Tonic.", name).unwrap();
        writeln!(output, "pub type {n}GrpcService = GenericGrpcService<{n}, Create{n}Dto, Update{n}Dto, {n}Service>;",
            n = name).unwrap();
        writeln!(output).unwrap();

        // Proto conversion impls are inherently entity-specific — keep them here.
        writeln!(output, "// ─── Proto ↔ Domain conversions ──────────────────────────────────────────────").unwrap();
        writeln!(output, "//").unwrap();
        writeln!(output, "// These `From` impls are entity-specific (field-by-field mapping).").unwrap();
        writeln!(output, "// They cannot be generic over the entity type, so they remain here.").unwrap();
        writeln!(output).unwrap();
        self.write_conversion_impls(&mut output, model)?;

        // CUSTOM zone for state machine RPCs, custom streaming, etc.
        writeln!(output, "// <<< CUSTOM").unwrap();
        if let Some(h) = hook {
            if let Some(sm) = &h.state_machine {
                writeln!(output, "// State machine transitions detected — add transition RPCs here.").unwrap();
                writeln!(output, "// State machine: {:?}", sm.states.len()).unwrap();
            }
        }
        writeln!(output, "// END CUSTOM").unwrap();

        Ok(output)
    }

    fn write_conversion_impls(&self, output: &mut String, model: &Model) -> Result<(), GenerateError> {
        // Entity to Proto
        writeln!(output, "impl From<{}> for Proto{} {{", model.name, model.name).unwrap();
        writeln!(output, "    fn from(entity: {}) -> Self {{", model.name).unwrap();
        writeln!(output, "        Self {{").unwrap();
        for field in &model.fields {
            if field.name == "created_at" || field.name == "updated_at" {
                writeln!(output, "            {0}: Some(prost_types::Timestamp {{", field.name).unwrap();
                writeln!(output, "                seconds: entity.{}.timestamp(),", field.name).unwrap();
                writeln!(output, "                nanos: entity.{}.timestamp_subsec_nanos() as i32,", field.name).unwrap();
                writeln!(output, "            }}),").unwrap();
            } else if field.name == "deleted_at" {
                writeln!(output, "            {0}: entity.{0}.map(|dt| prost_types::Timestamp {{", field.name).unwrap();
                writeln!(output, "                seconds: dt.timestamp(),").unwrap();
                writeln!(output, "                nanos: dt.timestamp_subsec_nanos() as i32,").unwrap();
                writeln!(output, "            }}),").unwrap();
            } else {
                writeln!(output, "            {0}: entity.{0},", field.name).unwrap();
            }
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        Ok(())
    }

    // Helper methods
    fn field_to_proto_type(&self, field: &crate::ast::Field) -> String {
        use crate::ast::{PrimitiveType, TypeRef};

        match &field.type_ref {
            TypeRef::Primitive(p) => match p {
                PrimitiveType::String | PrimitiveType::Markdown | PrimitiveType::Html => "string".to_string(),
                PrimitiveType::Int | PrimitiveType::Int32 => "int32".to_string(),
                PrimitiveType::Int64 => "int64".to_string(),
                PrimitiveType::Float | PrimitiveType::Float32 => "float".to_string(),
                PrimitiveType::Float64 => "double".to_string(),
                PrimitiveType::Bool => "bool".to_string(),
                PrimitiveType::Uuid => "string".to_string(),
                PrimitiveType::DateTime | PrimitiveType::Timestamp => "google.protobuf.Timestamp".to_string(),
                PrimitiveType::Date => "string".to_string(),
                PrimitiveType::Time | PrimitiveType::Duration => "string".to_string(),
                PrimitiveType::Decimal | PrimitiveType::Money | PrimitiveType::Percentage => "string".to_string(),
                PrimitiveType::Json => "string".to_string(),
                PrimitiveType::Bytes | PrimitiveType::Binary | PrimitiveType::Base64 => "bytes".to_string(),
                PrimitiveType::Email | PrimitiveType::Url | PrimitiveType::Phone | PrimitiveType::Slug => "string".to_string(),
                PrimitiveType::Ip | PrimitiveType::IpV4 | PrimitiveType::IpV6 | PrimitiveType::Mac => "string".to_string(),
            },
            TypeRef::Custom(name) => name.clone(),
            TypeRef::Array(inner) => format!("repeated {}", self.type_ref_to_proto(inner)),
            TypeRef::Optional(inner) => format!("optional {}", self.type_ref_to_proto(inner)),
            TypeRef::Map { key, value } => {
                format!("map<{}, {}>", self.type_ref_to_proto(key), self.type_ref_to_proto(value))
            }
            TypeRef::ModuleRef { module, name } => format!("{}.{}", module, name),
        }
    }

    fn field_to_optional_proto_type(&self, field: &crate::ast::Field) -> String {
        use crate::ast::TypeRef;

        match &field.type_ref {
            TypeRef::Optional(_) => self.field_to_proto_type(field),
            _ => format!("optional {}", self.field_to_proto_type(field)),
        }
    }

    fn type_ref_to_proto(&self, type_ref: &crate::ast::TypeRef) -> String {
        use crate::ast::{PrimitiveType, TypeRef};

        match type_ref {
            TypeRef::Primitive(p) => match p {
                PrimitiveType::String | PrimitiveType::Markdown | PrimitiveType::Html => "string".to_string(),
                PrimitiveType::Int | PrimitiveType::Int32 => "int32".to_string(),
                PrimitiveType::Int64 => "int64".to_string(),
                PrimitiveType::Float | PrimitiveType::Float32 => "float".to_string(),
                PrimitiveType::Float64 => "double".to_string(),
                PrimitiveType::Bool => "bool".to_string(),
                PrimitiveType::Uuid => "string".to_string(),
                PrimitiveType::DateTime | PrimitiveType::Timestamp => "google.protobuf.Timestamp".to_string(),
                PrimitiveType::Date => "string".to_string(),
                PrimitiveType::Time | PrimitiveType::Duration => "string".to_string(),
                PrimitiveType::Decimal | PrimitiveType::Money | PrimitiveType::Percentage => "string".to_string(),
                PrimitiveType::Json => "string".to_string(),
                PrimitiveType::Bytes | PrimitiveType::Binary | PrimitiveType::Base64 => "bytes".to_string(),
                PrimitiveType::Email | PrimitiveType::Url | PrimitiveType::Phone | PrimitiveType::Slug => "string".to_string(),
                PrimitiveType::Ip | PrimitiveType::IpV4 | PrimitiveType::IpV6 | PrimitiveType::Mac => "string".to_string(),
            },
            TypeRef::Custom(name) => name.clone(),
            TypeRef::Array(inner) => self.type_ref_to_proto(inner),
            TypeRef::Optional(inner) => self.type_ref_to_proto(inner),
            TypeRef::Map { key, value } => {
                format!("map<{}, {}>", self.type_ref_to_proto(key), self.type_ref_to_proto(value))
            }
            TypeRef::ModuleRef { module, name } => format!("{}.{}", module, name),
        }
    }

    fn get_proto_validations(&self, field: &crate::ast::Field) -> String {
        let mut validations = Vec::new();

        for attr in &field.attributes {
            match attr.name.as_str() {
                "required" => validations.push("(buf.validate.field).required = true".to_string()),
                "email" => validations.push("(buf.validate.field).string.email = true".to_string()),
                "uuid" => validations.push("(buf.validate.field).string.uuid = true".to_string()),
                "url" => validations.push("(buf.validate.field).string.uri = true".to_string()),
                "min" => {
                    if let Some(val) = attr.first_arg().and_then(|v| v.as_int()) {
                        validations.push(format!("(buf.validate.field).string.min_len = {}", val));
                    }
                }
                "max" => {
                    if let Some(val) = attr.first_arg().and_then(|v| v.as_int()) {
                        validations.push(format!("(buf.validate.field).string.max_len = {}", val));
                    }
                }
                _ => {}
            }
        }

        validations.join(", ")
    }
}

impl Default for GrpcGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for GrpcGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        for model in &schema.schema.models {
            // Find matching hook for this model
            let hook = schema
                .schema
                .hooks
                .iter()
                .find(|h| h.model_ref == model.name || h.name == model.name);

            // Generate proto service definition
            let proto_content = self.generate_proto_service(model)?;
            let proto_path = PathBuf::from(format!(
                "proto/{}_service.proto",
                to_snake_case(&model.name)
            ));
            output.add_file(proto_path, proto_content);

            // Generate Rust gRPC implementation
            let impl_content = self.generate_grpc_impl(model, hook)?;
            let impl_path = PathBuf::from(format!(
                "src/presentation/grpc/{}_grpc.rs",
                to_snake_case(&model.name)
            ));
            output.add_file(impl_path, impl_content);
        }

        // Generate mod.rs for grpc
        let mut mod_content = String::new();
        writeln!(mod_content, "//! gRPC service implementations").unwrap();
        writeln!(mod_content, "//!").unwrap();
        writeln!(mod_content, "//! Auto-generated by backbone-cli. Do not edit manually.").unwrap();
        writeln!(mod_content).unwrap();

        for model in &schema.schema.models {
            let model_snake = to_snake_case(&model.name);
            writeln!(mod_content, "pub mod {}_grpc;", model_snake).unwrap();
        }
        writeln!(mod_content).unwrap();

        for model in &schema.schema.models {
            let model_snake = to_snake_case(&model.name);
            writeln!(mod_content, "pub use {}_grpc::{}GrpcService;", model_snake, model.name).unwrap();
        }

        output.add_file(PathBuf::from("src/presentation/grpc/mod.rs"), mod_content);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "grpc"
    }
}

// Helper functions
use crate::utils::to_snake_case;

fn pluralize(name: &str) -> String {
    if name.ends_with('s') || name.ends_with('x') || name.ends_with("ch") || name.ends_with("sh") {
        format!("{}es", name)
    } else if name.ends_with('y') && !name.ends_with("ay") && !name.ends_with("ey") && !name.ends_with("oy") && !name.ends_with("uy") {
        format!("{}ies", &name[..name.len() - 1])
    } else {
        format!("{}s", name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Field, Model, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");

        schema.models.push(Model {
            name: "User".to_string(),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    ..Default::default()
                },
                Field {
                    name: "email".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
                Field {
                    name: "name".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
                Field {
                    name: "created_at".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::DateTime),
                    ..Default::default()
                },
                Field {
                    name: "updated_at".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::DateTime),
                    ..Default::default()
                },
                Field {
                    name: "deleted_at".to_string(),
                    type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        ResolvedSchema { schema }
    }

    #[test]
    fn test_grpc_generator_creates_proto_file() {
        let schema = create_test_schema();
        let generator = GrpcGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("proto/user_service.proto")));
    }

    #[test]
    fn test_grpc_generator_creates_impl_file() {
        let schema = create_test_schema();
        let generator = GrpcGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/presentation/grpc/user_grpc.rs")));
    }

    #[test]
    fn test_proto_contains_all_rpc_methods() {
        let schema = create_test_schema();
        let generator = GrpcGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let proto = output.files.get(&PathBuf::from("proto/user_service.proto")).unwrap();

        // Check all 11 RPC methods
        assert!(proto.contains("rpc List(ListUserRequest)"));
        assert!(proto.contains("rpc Create(CreateUserRequest)"));
        assert!(proto.contains("rpc Get(GetUserRequest)"));
        assert!(proto.contains("rpc Update(UpdateUserRequest)"));
        assert!(proto.contains("rpc Patch(PatchUserRequest)"));
        assert!(proto.contains("rpc Delete(DeleteUserRequest)"));
        assert!(proto.contains("rpc BulkCreate(BulkCreateUserRequest)"));
        assert!(proto.contains("rpc Upsert(UpsertUserRequest)"));
        assert!(proto.contains("rpc ListTrash(ListUserTrashRequest)"));
        assert!(proto.contains("rpc Restore(RestoreUserRequest)"));
        assert!(proto.contains("rpc EmptyTrash(EmptyUserTrashRequest)"));
    }

    #[test]
    fn test_impl_emits_type_alias() {
        let schema = create_test_schema();
        let generator = GrpcGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let impl_file = output.files.get(&PathBuf::from("src/presentation/grpc/user_grpc.rs")).unwrap();

        // Phase 1: impl file is now a type alias, not a full struct.
        assert!(impl_file.contains("pub type UserGrpcService = GenericGrpcService<"));
        assert!(impl_file.contains("GenericGrpcService"));
        assert!(impl_file.contains("CreateUserDto"));
        assert!(impl_file.contains("UpdateUserDto"));
        assert!(impl_file.contains("UserService"));
        // Proto conversion impls are still entity-specific and must be present.
        assert!(impl_file.contains("impl From<User> for ProtoUser"));
    }
}
