//! REST Handler generator
//!
//! Generates Axum handlers that integrate with backbone-core's BackboneCrudHandler.
//! Routes are generated with relative paths (e.g., `/users`) to be nested under a module prefix.
//! When mounted at `/api/v1/{module}`, implements all 14 standard Backbone CRUD endpoints:
//! 1. GET /{collection} - List (paginated, filtered, sorted)
//! 2. POST /{collection} - Create
//! 3. GET /{collection}/:id - Get by ID
//! 4. PUT /{collection}/:id - Full update
//! 5. PATCH /{collection}/:id - Partial update
//! 6. DELETE /{collection}/:id - Soft delete
//! 7. POST /{collection}/bulk - Bulk create
//! 8. POST /{collection}/upsert - Upsert
//! 9. GET /{collection}/trash - List deleted (paginated, filtered)
//! 10. POST /{collection}/:id/restore - Restore
//! 11. DELETE /{collection}/empty - Empty trash
//! 12. GET /{collection}/:id/deleted - Get deleted by ID
//! 13. DELETE /{collection}/trash/:id - Permanent delete from trash
//! 14. GET /{collection}/count - Count active/deleted entities

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::{Model, Hook};
use crate::resolver::ResolvedSchema;
use crate::utils::to_pascal_case;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates REST handlers using Axum and backbone-core patterns
pub struct HandlerGenerator {
    /// Group generated files by model/domain
    group_by_domain: bool,
}

impl HandlerGenerator {
    pub fn new() -> Self {
        Self {
            group_by_domain: false,  // Keep flat - only one file per entity
        }
    }

    /// Set whether to group files by domain
    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Generate handler file for a model
    fn generate_handler(&self, model: &Model, hook: Option<&Hook>) -> Result<String, GenerateError> {
        let mut output = String::new();

        // File header and imports
        self.write_imports(&mut output, model, hook)?;

        // Generate error types (the CrudService adapter struct is no longer needed —
        // the blanket impl on GenericCrudService covers it)
        self.write_error_types(&mut output, model, hook)?;

        // Generate route configuration using BackboneCrudHandler
        self.write_route_config(&mut output, model)?;

        // Generate custom action handlers if hook has state machine
        if let Some(h) = hook {
            if let Some(sm) = &h.state_machine {
                self.write_transition_handlers(&mut output, model, sm)?;
            }
        }

        Ok(output)
    }

    fn write_imports(&self, output: &mut String, model: &Model, hook: Option<&Hook>) -> Result<(), GenerateError> {
        writeln!(output, "//! {} REST handlers", model.name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Auto-generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Uses Axum and backbone-core's BackboneCrudHandler for all 12 CRUD endpoints.").unwrap();
        writeln!(output).unwrap();
        // Check what types are actually used
        let has_date_field = model.fields.iter().any(|f| self.field_uses_type(&f.type_ref, crate::ast::PrimitiveType::Date));
        let has_time_field = model.fields.iter().any(|f| self.field_uses_type(&f.type_ref, crate::ast::PrimitiveType::Time));
        let has_datetime_field = model.fields.iter().any(|f| {
            self.field_uses_type(&f.type_ref, crate::ast::PrimitiveType::DateTime) ||
            self.field_uses_type(&f.type_ref, crate::ast::PrimitiveType::Timestamp)
        });
        let has_decimal_field = model.fields.iter().any(|f| self.field_uses_type(&f.type_ref, crate::ast::PrimitiveType::Decimal));

        // Core framework imports
        writeln!(output, "use std::collections::HashMap;").unwrap();
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use axum::Router;").unwrap();
        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output, "use uuid::Uuid;").unwrap();

        // Build chrono imports - only include what's actually needed
        {
            let mut chrono_imports = Vec::new();
            if has_datetime_field {
                chrono_imports.push("DateTime");
                chrono_imports.push("Utc");
            }
            if has_date_field {
                chrono_imports.push("NaiveDate");
            }
            if has_time_field {
                chrono_imports.push("NaiveTime");
            }
            if !chrono_imports.is_empty() {
                writeln!(output, "use chrono::{{{}}};", chrono_imports.join(", ")).unwrap();
            }
        }

        // Import Decimal if needed
        if has_decimal_field {
            writeln!(output, "use rust_decimal::Decimal;").unwrap();
        }
        writeln!(output).unwrap();

        // Backbone framework imports - only import what's used
        writeln!(output, "// Backbone framework imports").unwrap();
        // ApiResponse only needed for state machine transition handlers
        let has_transitions = hook.map(|h| h.state_machine.is_some()).unwrap_or(false);
        if has_transitions {
            writeln!(output, "use backbone_core::http::{{ApiResponse, BackboneCrudHandler}};").unwrap();
        } else {
            writeln!(output, "use backbone_core::http::BackboneCrudHandler;").unwrap();
        }
        writeln!(output).unwrap();

        // Optional auth import
        writeln!(output, "// Auth integration (optional)").unwrap();
        writeln!(output, "#[cfg(feature = \"auth\")]").unwrap();
        writeln!(output, "use backbone_auth::{{AuthContext, AuthMiddleware}};").unwrap();
        writeln!(output).unwrap();


        // Domain imports - import all entity types (includes enums)
        writeln!(output, "// Domain imports").unwrap();
        writeln!(output, "use crate::domain::entity::*;").unwrap();
        // Use re-exported service type (not private module path)
        writeln!(output, "use crate::application::service::{{{}Service, ServiceError}};", model.name).unwrap();
        writeln!(output).unwrap();

        // DTO imports — generated by the dto generator into src/presentation/dto/
        writeln!(output, "// DTO imports").unwrap();
        writeln!(output,
            "use crate::presentation::dto::{{Create{n}Dto, Update{n}Dto, Patch{n}Dto, {n}ResponseDto}};",
            n = model.name).unwrap();
        writeln!(output).unwrap();

        // Only import state machine if the hook has one defined
        if let Some(h) = hook {
            if h.state_machine.is_some() {
                // Use re-exported state machine types (not private module path)
                writeln!(output, "use crate::domain::state_machine::{{{}State, {}StateMachine, {}Transition}};",
                    model.name, model.name, model.name).unwrap();
            }
        }

        writeln!(output).unwrap();
        Ok(())
    }

    /// Emit only the error type for this entity's handler.
    ///
    /// The CrudService adapter struct is no longer generated here — the blanket
    /// `impl CrudService<E, C, U> for GenericCrudService<E, C, U, R>` in
    /// backbone-core covers every entity automatically.  Generated code now passes
    /// `Arc<UserService>` (which *is* a `GenericCrudService` alias) directly to
    /// `BackboneCrudHandler::routes`.
    fn write_error_types(&self, output: &mut String, model: &Model, hook: Option<&Hook>) -> Result<(), GenerateError> {

        // CrudService implementation
        // Collect domain-specific error codes from hook rules (deduplicated by code)
        // Skip codes that would collide with base error variants
        let reserved_variants = ["NotFound", "Validation", "Database", "Internal"];
        let domain_rules: Vec<(&str, &str)> = {
            let mut seen = std::collections::HashSet::new();
            hook.map(|h| {
                h.rules.iter()
                    .filter_map(|r| r.code.as_ref().map(|code| (code.as_str(), r.message.as_str())))
                    .filter(|(code, _)| seen.insert(*code))
                    .filter(|(code, _)| {
                        let variant = to_pascal_case(&code.to_lowercase());
                        !reserved_variants.contains(&variant.as_str())
                    })
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default()
        };

        writeln!(output, "/// Application error type").unwrap();
        writeln!(output, "#[derive(Debug, thiserror::Error)]").unwrap();
        writeln!(output, "pub enum {}Error {{", model.name).unwrap();
        writeln!(output, "    #[error(\"Not found: {{0}}\")]").unwrap();
        writeln!(output, "    NotFound(String),").unwrap();
        writeln!(output, "    #[error(\"Validation error: {{0}}\")]").unwrap();
        writeln!(output, "    Validation(String),").unwrap();
        writeln!(output, "    #[error(\"Database error: {{0}}\")]").unwrap();
        writeln!(output, "    Database(String),").unwrap();
        writeln!(output, "    #[error(\"Internal error: {{0}}\")]").unwrap();
        writeln!(output, "    Internal(String),").unwrap();

        // Domain-specific error variants from hook rules
        if !domain_rules.is_empty() {
            writeln!(output, "    // Domain-specific errors from hook rules").unwrap();
            for (code, message) in &domain_rules {
                // Lowercase before PascalCase to handle SCREAMING_SNAKE_CASE codes
                let variant_name = to_pascal_case(&code.to_lowercase());
                // Escape braces in the message for thiserror format
                let escaped_message = message.replace('{', "{{").replace('}', "}}");
                writeln!(output, "    #[error(\"{}: {{0}}\")]", escaped_message).unwrap();
                writeln!(output, "    {}(String),", variant_name).unwrap();
            }
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // From<ServiceError> impl for handler error
        writeln!(output, "impl From<ServiceError> for {}Error {{", model.name).unwrap();
        writeln!(output, "    fn from(err: ServiceError) -> Self {{").unwrap();
        writeln!(output, "        match err {{").unwrap();
        writeln!(output, "            ServiceError::NotFound => Self::NotFound(err.to_string()),").unwrap();
        writeln!(output, "            ServiceError::Validation(ref msg) => Self::Validation(msg.clone()),").unwrap();
        writeln!(output, "            ServiceError::AlreadyExists(ref msg) => Self::Validation(msg.clone()),").unwrap();
        writeln!(output, "            ServiceError::Repository(ref e) => Self::Database(e.to_string()),").unwrap();
        writeln!(output, "            ServiceError::Internal(ref msg) => Self::Internal(msg.clone()),").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        let model_upper = model.name.to_uppercase();

        // IntoResponse — enables using ? operator in custom Axum handlers
        writeln!(output, "impl axum::response::IntoResponse for {}Error {{", model.name).unwrap();
        writeln!(output, "    fn into_response(self) -> axum::response::Response {{").unwrap();
        writeln!(output, "        use axum::http::StatusCode;").unwrap();
        writeln!(output, "        use axum::Json;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let (status, code) = match &self {{").unwrap();
        writeln!(output, "            Self::NotFound(_) => (StatusCode::NOT_FOUND, \"{}_NOT_FOUND\"),", model_upper).unwrap();
        writeln!(output, "            Self::Validation(_) => (StatusCode::BAD_REQUEST, \"{}_VALIDATION_ERROR\"),", model_upper).unwrap();
        writeln!(output, "            Self::Database(_) => (StatusCode::INTERNAL_SERVER_ERROR, \"{}_DATABASE_ERROR\"),", model_upper).unwrap();
        writeln!(output, "            Self::Internal(_) => (StatusCode::INTERNAL_SERVER_ERROR, \"{}_INTERNAL_ERROR\"),", model_upper).unwrap();

        // Domain-specific error variants → 422 Unprocessable Entity
        for (code, _message) in &domain_rules {
            let variant_name = to_pascal_case(&code.to_lowercase());
            let error_code = format!("{}_{}", model_upper, code.to_uppercase());
            writeln!(output, "            Self::{}(_) => (StatusCode::UNPROCESSABLE_ENTITY, \"{}\"),", variant_name, error_code).unwrap();
        }

        writeln!(output, "        }};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let body = serde_json::json!({{").unwrap();
        writeln!(output, "            \"success\": false,").unwrap();
        writeln!(output, "            \"error\": code,").unwrap();
        writeln!(output, "            \"message\": self.to_string(),").unwrap();
        writeln!(output, "        }});").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        (status, Json(body)).into_response()").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Generate domain error code constants
        if !domain_rules.is_empty() {
            let model_snake = to_snake_case(&model.name);
            writeln!(output, "/// Domain-specific error codes for {}", model.name).unwrap();
            writeln!(output, "pub mod {}_errors {{", model_snake).unwrap();
            for (code, _message) in &domain_rules {
                let const_name = code.to_uppercase();
                let full_code = format!("{}_{}", model_upper, const_name);
                writeln!(output, "    pub const {}: &str = \"{}\";", const_name, full_code).unwrap();
            }
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();
        }

        Ok(())
    }

    fn write_route_config(&self, output: &mut String, model: &Model) -> Result<(), GenerateError> {
        let model_snake = to_snake_case(&model.name);
        let model_plural = pluralize(&model_snake);

        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Route Configuration").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Create Axum router with all 16 Backbone endpoints for {}.", model.name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// # Routes").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// | Method | Path | Description |").unwrap();
        writeln!(output, "/// |--------|------|-------------|").unwrap();
        writeln!(output, "/// | GET | /{} | List with pagination |", model_plural).unwrap();
        writeln!(output, "/// | POST | /{} | Create new |", model_plural).unwrap();
        writeln!(output, "/// | GET | /{}/:id | Get by ID |", model_plural).unwrap();
        writeln!(output, "/// | PUT | /{}/:id | Full update |", model_plural).unwrap();
        writeln!(output, "/// | PATCH | /{}/:id | Partial update |", model_plural).unwrap();
        writeln!(output, "/// | DELETE | /{}/:id | Soft delete |", model_plural).unwrap();
        writeln!(output, "/// | POST | /{}/bulk | Bulk create |", model_plural).unwrap();
        writeln!(output, "/// | POST | /{}/upsert | Upsert |", model_plural).unwrap();
        writeln!(output, "/// | GET | /{}/trash | List deleted |", model_plural).unwrap();
        writeln!(output, "/// | POST | /{}/:id/restore | Restore |", model_plural).unwrap();
        writeln!(output, "/// | DELETE | /{}/empty | Empty trash |", model_plural).unwrap();
        writeln!(output, "/// | GET | /{}/:id/deleted | Get deleted by ID |", model_plural).unwrap();
        writeln!(output, "/// | DELETE | /{}/trash/:id | Permanent delete from trash |", model_plural).unwrap();
        writeln!(output, "/// | GET | /{}/count | Count active entities |", model_plural).unwrap();
        writeln!(output, "/// | GET | /{}/trash/count | Count deleted entities |", model_plural).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// # Example").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ```text").unwrap();
        writeln!(output, "/// let service = Arc::new({}Service::with_repository(repository));", model.name).unwrap();
        writeln!(output, "/// let router = create_{}_routes(service);", model_snake).unwrap();
        writeln!(output, "/// ```").unwrap();
        writeln!(output, "pub fn create_{}_routes(service: Arc<{}Service>) -> Router {{", model_snake, model.name).unwrap();
        writeln!(output, "    BackboneCrudHandler::<{}Service, {}, Create{}Dto, Update{}Dto, {}ResponseDto>::routes(",
            model.name, model.name, model.name, model.name, model.name).unwrap();
        writeln!(output, "        service,").unwrap();
        writeln!(output, "        \"/{}\",", model_plural).unwrap();
        writeln!(output, "    )").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Read-only routes (public-safe)
        writeln!(output, "/// Create Axum router with only the read (GET) endpoints for {}.", model.name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Safe for public, unauthenticated exposure (e.g., reference data).").unwrap();
        writeln!(output, "/// Mutations must be served separately via `create_{}_write_routes`,", model_snake).unwrap();
        writeln!(output, "/// typically wrapped in an auth middleware layer.").unwrap();
        writeln!(output, "pub fn create_{}_read_routes(service: Arc<{}Service>) -> Router {{", model_snake, model.name).unwrap();
        writeln!(output, "    BackboneCrudHandler::<{}Service, {}, Create{}Dto, Update{}Dto, {}ResponseDto>::read_routes(",
            model.name, model.name, model.name, model.name, model.name).unwrap();
        writeln!(output, "        service,").unwrap();
        writeln!(output, "        \"/{}\",", model_plural).unwrap();
        writeln!(output, "    )").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Write-only routes (intended for use behind auth)
        writeln!(output, "/// Create Axum router with only the write (mutation) endpoints for {}.", model.name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// These routes must NOT be publicly exposed. Wrap them with an auth").unwrap();
        writeln!(output, "/// middleware before nesting into the application router.").unwrap();
        writeln!(output, "pub fn create_{}_write_routes(service: Arc<{}Service>) -> Router {{", model_snake, model.name).unwrap();
        writeln!(output, "    BackboneCrudHandler::<{}Service, {}, Create{}Dto, Update{}Dto, {}ResponseDto>::write_routes(",
            model.name, model.name, model.name, model.name, model.name).unwrap();
        writeln!(output, "        service,").unwrap();
        writeln!(output, "        \"/{}\",", model_plural).unwrap();
        writeln!(output, "    )").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Protected routes with auth
        writeln!(output, "/// Create authenticated routes with auth middleware.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Requires the `auth` feature flag. The `AuthMiddleware` implementation").unwrap();
        writeln!(output, "/// is responsible for extracting and validating tokens, then providing").unwrap();
        writeln!(output, "/// an `AuthContext` via request extensions.").unwrap();
        writeln!(output, "#[cfg(feature = \"auth\")]").unwrap();
        writeln!(output, "pub fn create_protected_{}_routes<A: AuthMiddleware + 'static>(", model_snake).unwrap();
        writeln!(output, "    service: Arc<{}Service>,", model.name).unwrap();
        writeln!(output, "    auth: Arc<A>,").unwrap();
        writeln!(output, ") -> Router {{").unwrap();
        writeln!(output, "    use axum::middleware;").unwrap();
        writeln!(output, "    use axum::response::IntoResponse;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    let auth_layer = auth.clone();").unwrap();
        writeln!(output, "    create_{}_routes(service)", model_snake).unwrap();
        writeln!(output, "        .layer(middleware::from_fn(move |mut req: axum::extract::Request, next: axum::middleware::Next| {{").unwrap();
        writeln!(output, "            let auth = auth_layer.clone();").unwrap();
        writeln!(output, "            async move {{").unwrap();
        writeln!(output, "                match auth.authenticate(&req).await {{").unwrap();
        writeln!(output, "                    Ok(ctx) => {{").unwrap();
        writeln!(output, "                        req.extensions_mut().insert(ctx);").unwrap();
        writeln!(output, "                        next.run(req).await").unwrap();
        writeln!(output, "                    }}").unwrap();
        writeln!(output, "                    Err(_) => {{").unwrap();
        writeln!(output, "                        (axum::http::StatusCode::UNAUTHORIZED,").unwrap();
        writeln!(output, "                         axum::Json(serde_json::json!({{").unwrap();
        writeln!(output, "                             \"success\": false,").unwrap();
        writeln!(output, "                             \"error\": \"unauthorized\",").unwrap();
        writeln!(output, "                             \"message\": \"Authentication required\"").unwrap();
        writeln!(output, "                         }}))").unwrap();
        writeln!(output, "                        ).into_response()").unwrap();
        writeln!(output, "                    }}").unwrap();
        writeln!(output, "                }}").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }}))").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Note: Trash routes are already included in the main routes() function
        // which provides all 16 CRUD endpoints including trash operations.
        // No separate trash_routes function is needed.

        Ok(())
    }

    fn write_transition_handlers(&self, output: &mut String, model: &Model, sm: &crate::ast::StateMachine) -> Result<(), GenerateError> {
        let model_snake = to_snake_case(&model.name);
        let model_plural = pluralize(&model_snake);

        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// State Transition Handlers").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        for transition in &sm.transitions {
            let transition_snake = to_snake_case(&transition.name);

            writeln!(output, "/// Execute {} transition on a {}.", transition.name, model.name).unwrap();
            writeln!(output, "///").unwrap();
            writeln!(output, "/// POST /{}/:id/transitions/{}", model_plural, transition_snake).unwrap();
            writeln!(output, "pub async fn {}_transition(", transition_snake).unwrap();
            writeln!(output, "    axum::extract::State(service): axum::extract::State<Arc<{}Service>>,", model.name).unwrap();
            writeln!(output, "    axum::extract::Path(id): axum::extract::Path<String>,").unwrap();
            writeln!(output, "    #[cfg(feature = \"auth\")] auth: axum::Extension<AuthContext>,").unwrap();
            writeln!(output, ") -> impl axum::response::IntoResponse {{").unwrap();
            writeln!(output, "    use axum::{{http::StatusCode, Json}};").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    // Get current entity").unwrap();
            writeln!(output, "    let entity = match service.get_by_id(&id).await {{").unwrap();
            writeln!(output, "        Ok(Some(e)) => e,").unwrap();
            writeln!(output, "        Ok(None) => return (StatusCode::NOT_FOUND, Json(ApiResponse::<{}ResponseDto>::not_found(\"{}\", &id))),", model.name, model.name).unwrap();
            writeln!(output, "        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<{}ResponseDto>::error(e.to_string()))),", model.name).unwrap();
            writeln!(output, "    }};").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    // Check permission (if auth enabled)").unwrap();
            writeln!(output, "    #[cfg(feature = \"auth\")]").unwrap();
            writeln!(output, "    {{").unwrap();
            // Permission-based check: use transition's allowed_roles() method
            writeln!(output, "        let allowed_roles = {}Transition::{}.allowed_roles();", model.name, to_pascal_case(&transition.name)).unwrap();
            writeln!(output, "        let has_specific_perm = auth.has_permission(\"{}:transition:{}\");", model_snake, transition_snake).unwrap();
            writeln!(output, "        let has_update_perm = auth.has_permission(\"{}:update\");", model_snake).unwrap();
            if !transition.allowed_roles.is_empty() {
                writeln!(output, "        let has_role = auth.roles.iter().any(|r| allowed_roles.contains(&r.as_str()));").unwrap();
                writeln!(output, "        if !has_specific_perm && !has_update_perm && !has_role {{").unwrap();
            } else {
                writeln!(output, "        if !has_specific_perm && !has_update_perm {{").unwrap();
            }
            writeln!(output, "            return (StatusCode::FORBIDDEN, Json(ApiResponse::<{}ResponseDto>::error(\"Insufficient permissions for {} transition\")));", model.name, transition.name).unwrap();
            writeln!(output, "        }}").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output).unwrap();

            let status_field = self.find_status_field(model, &sm.field);
            writeln!(output, "    // Create state machine from entity's actual status and validate transition").unwrap();
            writeln!(output, "    let current_state: {}State = entity.{}.to_string().parse()", model.name, status_field).unwrap();
            writeln!(output, "        .unwrap_or({}State::default());", model.name).unwrap();
            writeln!(output, "    let sm = {}StateMachine::from_state(current_state);", model.name).unwrap();
            writeln!(output, "    if !sm.can_transition({}Transition::{}) {{", model.name, to_pascal_case(&transition.name)).unwrap();
            writeln!(output, "        return (StatusCode::BAD_REQUEST, Json(ApiResponse::<{}ResponseDto>::error(\"Transition not allowed from current state\")));", model.name).unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    // Apply transition via partial update").unwrap();
            writeln!(output, "    let mut fields: HashMap<String, serde_json::Value> = HashMap::new();").unwrap();
            writeln!(output, "    fields.insert(\"{}\".to_string(), serde_json::Value::String(\"{}\".to_string()));", status_field, to_pascal_case(&transition.to)).unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    match service.partial_update(&id, fields).await {{").unwrap();
            writeln!(output, "        Ok(Some(updated)) => {{").unwrap();
            writeln!(output, "            let response: {}ResponseDto = updated.into();", model.name).unwrap();
            writeln!(output, "            (StatusCode::OK, Json(ApiResponse::ok(response)))").unwrap();
            writeln!(output, "        }}").unwrap();
            writeln!(output, "        Ok(None) => (StatusCode::NOT_FOUND, Json(ApiResponse::<{}ResponseDto>::not_found(\"{}\", &id))),", model.name, model.name).unwrap();
            writeln!(output, "        Err(e) => (StatusCode::INTERNAL_SERVER_ERROR, Json(ApiResponse::<{}ResponseDto>::error(e.to_string()))),", model.name).unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();
        }

        // Transition routes helper
        writeln!(output, "/// Create routes for state transitions.").unwrap();
        writeln!(output, "pub fn create_{}_transition_routes(service: Arc<{}Service>) -> Router {{", model_snake, model.name).unwrap();
        writeln!(output, "    use axum::routing::post;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    Router::new()").unwrap();

        for transition in &sm.transitions {
            let transition_snake = to_snake_case(&transition.name);
            writeln!(output, "        .route(\"/{}/:id/transitions/{}\", post({}_transition))", model_plural, transition_snake, transition_snake).unwrap();
        }

        writeln!(output, "        .with_state(service)").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        Ok(())
    }

    // Helper methods for type conversion
    fn type_ref_to_rust(&self, type_ref: &crate::ast::TypeRef) -> String {
        use crate::ast::TypeRef;

        match type_ref {
            TypeRef::Primitive(p) => p.rust_type().to_string(),
            TypeRef::Custom(name) => to_pascal_case(name),
            TypeRef::Array(inner) => format!("Vec<{}>", self.type_ref_to_rust(inner)),
            TypeRef::Optional(inner) => format!("Option<{}>", self.type_ref_to_rust(inner)),
            TypeRef::Map { key, value } => {
                format!("std::collections::HashMap<{}, {}>", self.type_ref_to_rust(key), self.type_ref_to_rust(value))
            }
            TypeRef::ModuleRef { module, name } => format!("{}::{}", module, name),
        }
    }

    /// Find the model field that holds the state machine state enum.
    ///
    /// The hook YAML `states.field` may point to a non-enum field (e.g. `verified_at`,
    /// `is_active`) that cannot be parsed as a state value.  This method locates the
    /// actual status/state enum field in the model so that the generated transition
    /// handler reads the current state correctly.
    ///
    /// Resolution order:
    /// 1. If `sm_field` itself is a `Custom` (user-defined enum) type in the model, use it.
    /// 2. Look for a field named `status` or `state` with a `Custom` type.
    /// 3. Fall back to the first `Custom`-typed field found.
    /// 4. Last resort: return `sm_field` unchanged (preserves old behaviour).
    fn find_status_field<'a>(&self, model: &'a Model, sm_field: &'a str) -> &'a str {
        use crate::ast::TypeRef;

        // Helper: strip Optional wrapper and check for Custom type.
        let is_custom = |type_ref: &TypeRef| -> bool {
            match type_ref {
                TypeRef::Custom(_) => true,
                TypeRef::Optional(inner) => matches!(inner.as_ref(), TypeRef::Custom(_)),
                _ => false,
            }
        };

        // 1. If the hook's sm_field itself has a Custom type, it is already correct.
        if let Some(f) = model.fields.iter().find(|f| f.name == sm_field) {
            if is_custom(&f.type_ref) {
                return sm_field;
            }
        }

        // 2. Prefer a field named `status` or `state` with a Custom type.
        for name in &["status", "state", "workflow_state"] {
            if let Some(f) = model.fields.iter().find(|f| f.name == *name) {
                if is_custom(&f.type_ref) {
                    return &f.name;
                }
            }
        }

        // 3. Fall back to the first Custom-typed field in the model.
        if let Some(f) = model.fields.iter().find(|f| is_custom(&f.type_ref)) {
            return &f.name;
        }

        // 4. Last resort – return the original sm_field.
        sm_field
    }

    /// Check if a specific field is optional (wrapped in Option<>)
    fn is_field_optional(&self, model: &Model, field_name: &str) -> bool {
        use crate::ast::TypeRef;
        model.fields.iter()
            .find(|f| f.name == field_name)
            .map(|f| matches!(f.type_ref, TypeRef::Optional(_)))
            .unwrap_or(false)
    }

    /// Check if a field uses a specific primitive type (recursively handles Optional/Array)
    fn field_uses_type(&self, type_ref: &crate::ast::TypeRef, target: crate::ast::PrimitiveType) -> bool {
        use crate::ast::TypeRef;
        match type_ref {
            TypeRef::Primitive(p) => *p == target,
            TypeRef::Optional(inner) => self.field_uses_type(inner, target),
            TypeRef::Array(inner) => self.field_uses_type(inner, target),
            TypeRef::Map { key, value } => {
                self.field_uses_type(key, target) || self.field_uses_type(value, target)
            }
            _ => false,
        }
    }

}

impl Default for HandlerGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for HandlerGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Collect model names for parent mod.rs
        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        for model in &schema.schema.models {
            // Find matching hook for this model
            let hook = schema
                .schema
                .hooks
                .iter()
                .find(|h| h.model_ref == model.name || h.name == model.name);

            let content = self.generate_handler(model, hook)?;

            if self.group_by_domain {
                // Grouped structure: src/presentation/http/{model}/{model}_handler.rs
                let model_snake = to_snake_case(&model.name);
                let path = build_generated_path(
                    "src/presentation/http",
                    &model.name,
                    &format!("{}_handler.rs", model_snake),
                    true,
                );
                output.add_file(path, content);

                // Create subdirectory mod.rs: src/presentation/http/{model}/mod.rs
                let sub_mod_path = PathBuf::from(format!("src/presentation/http/{}/mod.rs", model_snake));
                let sub_mod_content = build_subdirectory_mod(&model.name, &format!("{}_handler", model_snake));
                output.add_file(sub_mod_path, sub_mod_content);
            } else {
                // Flat structure (original)
                let path = PathBuf::from(format!(
                    "src/presentation/http/{}_handler.rs",
                    to_snake_case(&model.name)
                ));
                output.add_file(path, content);
            }
        }

        // Generate mod.rs for handlers
        let mut mod_content = String::new();
        writeln!(mod_content, "//! HTTP handlers").unwrap();
        writeln!(mod_content, "//!").unwrap();
        writeln!(mod_content, "//! Auto-generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(mod_content, "//!").unwrap();
        writeln!(mod_content, "//! These handlers use Axum and backbone-core's BackboneCrudHandler").unwrap();
        writeln!(mod_content, "//! to provide all 12 standard Backbone CRUD endpoints.").unwrap();
        writeln!(mod_content).unwrap();

        if self.group_by_domain {
            // For grouped structure, parent mod.rs declares subdirectories
            writeln!(mod_content, "// Model subdirectories").unwrap();
            for model in &model_names {
                let model_snake = to_snake_case(model);
                writeln!(mod_content, "pub mod {};", model_snake).unwrap();
            }
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "// Re-exports from subdirectories").unwrap();
            for model in &model_names {
                let model_snake = to_snake_case(model);
                writeln!(mod_content, "pub use {}::{{", model_snake).unwrap();
                writeln!(mod_content, "    Create{}Dto,", model).unwrap();
                writeln!(mod_content, "    Update{}Dto,", model).unwrap();
                writeln!(mod_content, "    Patch{}Dto,", model).unwrap();
                writeln!(mod_content, "    {}ResponseDto,", model).unwrap();
                writeln!(mod_content, "    create_{}_routes,", model_snake).unwrap();
                writeln!(mod_content, "    create_{}_read_routes,", model_snake).unwrap();
                writeln!(mod_content, "    create_{}_write_routes,", model_snake).unwrap();
                writeln!(mod_content, "}};").unwrap();
            }
        } else {
            // Flat structure
            for model in &schema.schema.models {
                let model_snake = to_snake_case(&model.name);
                writeln!(mod_content, "pub mod {}_handler;", model_snake).unwrap();
            }
            writeln!(mod_content).unwrap();
            // Custom module declarations (preserved across regeneration)
            writeln!(mod_content, "// <<< CUSTOM").unwrap();
            writeln!(mod_content, "// END CUSTOM").unwrap();
            writeln!(mod_content).unwrap();

            // Re-exports (only route factory functions — services are accessed via module directly)
            writeln!(mod_content, "// Re-exports").unwrap();
            for model in &schema.schema.models {
                let model_snake = to_snake_case(&model.name);
                writeln!(
                    mod_content,
                    "pub use {}_handler::{{create_{}_routes, create_{}_read_routes, create_{}_write_routes}};",
                    model_snake, model_snake, model_snake, model_snake
                ).unwrap();
            }
            // Custom re-exports (preserved across regeneration)
            writeln!(mod_content, "// <<< CUSTOM").unwrap();
            writeln!(mod_content, "// END CUSTOM").unwrap();
        }

        output.add_file(PathBuf::from("src/presentation/http/mod.rs"), mod_content);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "handler"
    }
}

// Helper functions
use crate::utils::to_snake_case;


fn pluralize(name: &str) -> String {
    if name.ends_with('s') || name.ends_with('x') || name.ends_with("ch") || name.ends_with("sh") {
        format!("{}es", name)
    } else if name.ends_with('y') && !name.ends_with("ay") && !name.ends_with("ey") && !name.ends_with("oy") && !name.ends_with("uy") {
        format!("{}ies", &name[..name.len() - 1])
    } else {
        format!("{}s", name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Field, Model, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");

        schema.models.push(Model {
            name: "User".to_string(),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    ..Default::default()
                },
                Field {
                    name: "email".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
                Field {
                    name: "name".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
                Field {
                    name: "created_at".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::DateTime),
                    ..Default::default()
                },
                Field {
                    name: "updated_at".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::DateTime),
                    ..Default::default()
                },
                Field {
                    name: "deleted_at".to_string(),
                    type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        ResolvedSchema { schema }
    }

    #[test]
    fn test_handler_generator_creates_handler_file() {
        let schema = create_test_schema();
        let generator = HandlerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/presentation/http/user_handler.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/presentation/http/mod.rs")));
    }

    #[test]
    fn test_handler_uses_axum() {
        let schema = create_test_schema();
        let generator = HandlerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let handler = output.files.get(&PathBuf::from("src/presentation/http/user_handler.rs")).unwrap();

        // Should use Axum, not Actix
        assert!(handler.contains("use axum::Router;"));
        assert!(!handler.contains("actix_web"));
    }

    #[test]
    fn test_handler_uses_backbone_core() {
        let schema = create_test_schema();
        let generator = HandlerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let handler = output.files.get(&PathBuf::from("src/presentation/http/user_handler.rs")).unwrap();

        // Should use backbone-core patterns
        assert!(handler.contains("CrudService"));
        assert!(handler.contains("BackboneCrudHandler"));
        // ApiResponse is only imported for models with state machine transitions
        assert!(handler.contains("backbone_core::http"));
    }

    #[test]
    fn test_handler_implements_crud_service() {
        let schema = create_test_schema();
        let generator = HandlerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let handler = output.files.get(&PathBuf::from("src/presentation/http/user_handler.rs")).unwrap();

        // Should implement CrudService trait
        assert!(handler.contains("impl CrudService<User, CreateUserDto, UpdateUserDto> for UserCrudService"));
    }

    #[test]
    fn test_handler_imports_dtos_from_presentation_layer() {
        let schema = create_test_schema();
        let generator = HandlerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let handler = output.files.get(&PathBuf::from("src/presentation/http/user_handler.rs")).unwrap();

        // DTOs are imported from the dto generator, not defined inline (Phase 3)
        assert!(handler.contains("use crate::presentation::dto::{CreateUserDto, UpdateUserDto, PatchUserDto, UserResponseDto};"),
            "Handler should import DTOs from presentation layer");
        assert!(!handler.contains("pub struct CreateUserDto"),
            "Handler should not define DTOs inline");
        assert!(!handler.contains("pub struct UpdateUserDto"),
            "Handler should not define DTOs inline");
    }

    #[test]
    fn test_handler_generates_route_function() {
        let schema = create_test_schema();
        let generator = HandlerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let handler = output.files.get(&PathBuf::from("src/presentation/http/user_handler.rs")).unwrap();

        assert!(handler.contains("pub fn create_user_routes"));
        assert!(handler.contains("pub fn create_user_read_routes"));
        assert!(handler.contains("pub fn create_user_write_routes"));
        assert!(handler.contains("BackboneCrudHandler::<UserService, User, CreateUserDto, UpdateUserDto, UserResponseDto>::read_routes"));
        assert!(handler.contains("BackboneCrudHandler::<UserService, User, CreateUserDto, UpdateUserDto, UserResponseDto>::write_routes"));
    }

    #[test]
    fn test_handler_supports_events() {
        let schema = create_test_schema();
        let generator = HandlerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let handler = output.files.get(&PathBuf::from("src/presentation/http/user_handler.rs")).unwrap();

        // Should have event support (feature-gated)
        assert!(handler.contains("#[cfg(feature = \"events\")]"));
        assert!(handler.contains("pub enum UserEvent"));
        assert!(handler.contains("DomainEvent for UserEvent"));
    }

    #[test]
    fn test_pluralize() {
        assert_eq!(pluralize("user"), "users");
        assert_eq!(pluralize("category"), "categories");
        assert_eq!(pluralize("bus"), "buses");
        assert_eq!(pluralize("box"), "boxes");
        assert_eq!(pluralize("day"), "days");
    }
}
