//! Handlers Module Generator
//!
//! Generates the handlers module structure including:
//! - handlers/mod.rs with AppState (delegates to app_state generator)
//! - Placeholder for custom auth handlers
//!
//! ## Generated Files
//!
//! - `src/handlers/mod.rs` - Main handlers module (via AppStateGenerator)
//! - `src/handlers/custom.rs` - Custom handler stubs

use super::{GenerateError, GeneratedOutput, Generator};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates handlers module structure
pub struct HandlersModuleGenerator;

impl HandlersModuleGenerator {
    pub fn new() -> Self {
        Self
    }
}

impl Default for HandlersModuleGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for HandlersModuleGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Generate custom handlers stub
        let custom_handlers = self.generate_custom_handlers(schema)?;
        output.add_file(PathBuf::from("src/handlers/custom.rs"), custom_handlers);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "handlers_module"
    }
}

impl HandlersModuleGenerator {
    fn generate_custom_handlers(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        // Header
        writeln!(output, "//! {} Custom Handlers", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Safe to edit.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Add custom HTTP handlers here that need access to AppState.").unwrap();
        writeln!(output, "//! These handlers can be integrated with the routes module.").unwrap();
        writeln!(output).unwrap();

        // Imports
        writeln!(output, "#![allow(unused_imports)]").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use axum::{{").unwrap();
        writeln!(output, "    extract::{{State, Path, Query, Json}},").unwrap();
        writeln!(output, "    response::IntoResponse,").unwrap();
        writeln!(output, "    http::StatusCode,").unwrap();
        writeln!(output, "}};").unwrap();
        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use super::AppState;").unwrap();
        writeln!(output).unwrap();

        // Example custom handler
        writeln!(output, "// ============================================================").unwrap();
        writeln!(output, "// CUSTOM HANDLERS").unwrap();
        writeln!(output, "// ============================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM HANDLERS START >>>").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "/// Example custom handler demonstrating AppState usage.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// # Example").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ```ignore").unwrap();
        writeln!(output, "/// // In routes/mod.rs:").unwrap();
        writeln!(output, "/// Router::new().route(\"/health\", get(health_check))").unwrap();
        writeln!(output, "/// ```").unwrap();
        writeln!(output, "#[allow(dead_code)]").unwrap();
        writeln!(output, "pub async fn health_check(").unwrap();
        writeln!(output, "    State(_state): State<AppState>,").unwrap();
        writeln!(output, ") -> impl IntoResponse {{").unwrap();
        writeln!(output, "    // Access services via _state if needed").unwrap();
        writeln!(output, "    // e.g., _state.user_service.health_check().await").unwrap();
        writeln!(output, "    (StatusCode::OK, \"OK\")").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// Add more custom handlers below...").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM HANDLERS END >>>").unwrap();

        Ok(output)
    }
}

/// Convert string to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("user"), "User");
        assert_eq!(to_pascal_case("corpus"), "Corpus");
    }
}
