//! Integration generator
//!
//! Phase 1: Emits a concrete adapter **struct** implementing the `ModuleAdapter` trait
//! from `backbone_core` (instead of redefining the trait and utility types per module).
//!
//! ## Before (was hundreds of generated lines per module):
//! ```rust,ignore
//! // Trait redefined in every module:
//! pub trait ModuleAdapter: Send + Sync { type External; type Internal; ... }
//! pub enum IntegrationError { ServiceUnavailable(...), ... }
//! pub struct IntegrationRegistry { ... }
//! ```
//!
//! ## After:
//! ```rust,ignore
//! use backbone_core::{ModuleAdapter, IntegrationError};
//!
//! pub struct BucketToBersihirAdapter;
//! impl ModuleAdapter<BucketStoredFile, BersihirAttachment> for BucketToBersihirAdapter {
//!     // <<< CUSTOM — map fields here
//!     // END CUSTOM >>>
//! }
//! ```

use super::{GenerateError, GeneratedOutput, Generator};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates integration/ACL scaffolds from schema
pub struct IntegrationGenerator;

impl IntegrationGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate integration/mod.rs — imports from backbone-core; adapter stubs via CUSTOM.
    fn generate_mod(&self, schema: &ResolvedSchema) -> String {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        writeln!(output, "//! {} Integration Layer (Anti-Corruption Layer)", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! All external module dependencies must flow through adapters here.").unwrap();
        writeln!(output, "//! The `ModuleAdapter` trait and `IntegrationError` type come from backbone-core.").unwrap();
        writeln!(output).unwrap();

        // Re-export from backbone-core — no redefinition.
        writeln!(output, "pub use backbone_core::{{ModuleAdapter, ProjectionAdapter, IntegrationError}};").unwrap();
        writeln!(output, "pub use backbone_messaging::SubscriberRegistry;").unwrap();
        writeln!(output).unwrap();

        // Adapter module declarations (filled in via CUSTOM).
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// Declare adapter modules for each external dependency. Example:").unwrap();
        writeln!(output, "// pub mod bucket_adapter;").unwrap();
        writeln!(output, "// pub use bucket_adapter::BucketToBersihirAdapter;").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();

        output
    }

}

impl Default for IntegrationGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for IntegrationGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // mod.rs — main integration layer entry point.
        output.add_file(
            PathBuf::from("src/infrastructure/integration/mod.rs"),
            self.generate_mod(schema),
        );

        // Adapter stubs are generated for cross-module dependencies.
        // ModuleSchema does not carry an explicit `dependencies` field in the current
        // AST (dependencies are resolved at the application wiring level). Adapter
        // scaffolds can be added manually or via a future schema extension.
        // No per-dependency adapters generated here.

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "integration"
    }
}

fn to_pascal_case(name: &str) -> String {
    let mut result = String::new();
    let mut cap = true;
    for c in name.chars() {
        if c == '_' || c == '-' {
            cap = true;
        } else if cap {
            result.push(c.to_ascii_uppercase());
            cap = false;
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::ModuleSchema;

    fn create_test_schema() -> ResolvedSchema {
        let schema = ModuleSchema::new("bersihir");
        ResolvedSchema { schema }
    }

    #[test]
    fn test_integration_creates_mod_file() {
        let schema = create_test_schema();
        let gen = IntegrationGenerator::new();
        let out = gen.generate(&schema).unwrap();

        assert!(out.files.contains_key(&PathBuf::from(
            "src/infrastructure/integration/mod.rs"
        )));
    }

    #[test]
    fn test_mod_imports_from_backbone_core() {
        let schema = create_test_schema();
        let gen = IntegrationGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/infrastructure/integration/mod.rs"))
            .unwrap();

        assert!(content.contains("backbone_core"));
        assert!(content.contains("ModuleAdapter"));
        assert!(content.contains("IntegrationError"));
        // Must NOT redefine the trait
        assert!(!content.contains("pub trait ModuleAdapter"));
        assert!(!content.contains("pub enum IntegrationError"));
    }
}
