//! Module registration generator
//!
//! Generates module-level code that ties together all generated components:
//! - Module lib.rs with Builder pattern registration
//! - Module configuration structs
//! - Route registration for HTTP handlers (Axum with BackboneCrudHandler)
//! - gRPC service registration
//!
//! ## Generated Files
//!
//! - `lib.rs` - Module entry point with Builder pattern
//! - `routes.rs` - Route registration for Axum using BackboneCrudHandler
//! - `grpc.rs` - gRPC service registration

use super::{GenerateError, GeneratedOutput, Generator};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates module registration code from schema
pub struct ModuleGenerator;

impl ModuleGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate lib.rs - module entry point with Builder pattern
    fn generate_lib_rs(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);
        // Collect model names to detect service name collisions
        let model_names: std::collections::HashSet<&str> = schema.schema.models.iter().map(|m| m.name.as_str()).collect();

        // Header
        writeln!(output, "//! {} Module", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Enhanced with runtime implementations.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This module provides:").unwrap();
        writeln!(output, "//! - Domain entities and repositories").unwrap();
        writeln!(output, "//! - Application services").unwrap();
        writeln!(output, "//! - HTTP and gRPC handlers").unwrap();
        writeln!(output, "//! - Route configuration").unwrap();
        writeln!(output, "//! - State machine enforcement").unwrap();
        writeln!(output, "//! - Validation rules runtime").unwrap();
        writeln!(output, "//! - RBAC middleware").unwrap();
        writeln!(output, "//! - Trigger execution system").unwrap();
        writeln!(output, "//! - Computed fields").unwrap();
        writeln!(output, "//! - Workflow orchestrator").unwrap();
        writeln!(output).unwrap();

        // Module declarations
        writeln!(output, "// Generated modules").unwrap();
        writeln!(output, "pub mod domain;").unwrap();
        writeln!(output, "pub mod infrastructure;").unwrap();
        writeln!(output, "pub mod application;").unwrap();
        writeln!(output, "pub mod presentation;").unwrap();
        if !schema.schema.models.is_empty() {
            writeln!(output, "pub mod seeders;").unwrap();
        }
        writeln!(output).unwrap();

        // Re-exports - Domain entities
        writeln!(output, "// Re-exports for convenience - Domain entities").unwrap();
        writeln!(output, "pub use domain::entity::*;").unwrap();
        writeln!(output).unwrap();

        // Re-exports - State Machine (types are generated by state_machine generator)
        // Each entity with state machine gets: {Entity}State, {Entity}Transition, {Entity}StateMachine
        // StateMachineError is exported from the first state machine
        let hooks_with_state = schema.schema.hooks.iter()
            .filter(|h| h.state_machine.is_some())
            .collect::<Vec<_>>();
        if !hooks_with_state.is_empty() {
            writeln!(output, "// Re-exports - State Machine").unwrap();
            writeln!(output, "pub use domain::state_machine::*;").unwrap();
            writeln!(output).unwrap();
        }

        // Re-exports - Computed Fields (types are generated by computed generator)
        // Exports: HasComputedFields, ComputedFieldValues
        let hooks_with_computed = schema.schema.hooks.iter()
            .filter(|h| !h.computed_fields.is_empty())
            .collect::<Vec<_>>();
        if !hooks_with_computed.is_empty() {
            writeln!(output, "// Re-exports - Computed Fields").unwrap();
            writeln!(output, "pub use domain::computed::{{HasComputedFields, ComputedFieldValues}};").unwrap();
            writeln!(output).unwrap();
        }

        // Re-exports - Permissions (types are generated by permission generator)
        // Exports: Action, FieldRestriction, PermissionChecker, PermissionError, PermissionResult
        let hooks_with_perms = schema.schema.hooks.iter()
            .filter(|h| !h.permissions.is_empty())
            .collect::<Vec<_>>();
        if !hooks_with_perms.is_empty() {
            writeln!(output, "// Re-exports - Permissions").unwrap();
            writeln!(output, "pub use domain::permission::{{Action, FieldRestriction, PermissionChecker, PermissionError, PermissionResult}};").unwrap();
            writeln!(output).unwrap();
        }

        // Re-exports - Infrastructure
        writeln!(output, "// Re-exports - Infrastructure").unwrap();
        writeln!(output, "pub use infrastructure::persistence::*;").unwrap();
        writeln!(output).unwrap();

        // Re-exports - Application services (explicit to avoid name collisions with entities)
        writeln!(output, "// Re-exports - Application services").unwrap();
        for model in &schema.schema.models {
            let service_name = format!("{}Service", model.name);
            if model_names.contains(service_name.as_str()) {
                // Re-export with alias to avoid collision with entity name
                writeln!(output, "pub use application::service::{0} as {1}AppService;", service_name, model.name).unwrap();
            } else {
                writeln!(output, "pub use application::service::{};", service_name).unwrap();
            }
        }
        writeln!(output).unwrap();

        // Re-exports - Middleware (Auth & RBAC)
        // Only export if authorization config is present in the schema
        if schema.schema.authorization.is_some() {
            writeln!(output, "// Re-exports - Middleware (Auth & RBAC)").unwrap();
            writeln!(output, "pub use application::middleware::{{").unwrap();
            writeln!(output, "    AuthContext, AuthMiddleware, AuthExtractor, AuthError, OptionalAuth, CurrentUser,").unwrap();
            writeln!(output, "    RbacMiddleware, PermissionGuard, RequirePermission, rbac_layer,").unwrap();
            writeln!(output, "}};").unwrap();
            writeln!(output).unwrap();
        }

        // Re-exports - Validation (types are generated by validation generator)
        // Exports: ValidationError, ValidationResult, Validate, and each {Entity}Validator
        let hooks_with_validation = schema.schema.hooks.iter()
            .filter(|h| !h.rules.is_empty())
            .collect::<Vec<_>>();
        if !hooks_with_validation.is_empty() {
            writeln!(output, "// Re-exports - Validation").unwrap();
            writeln!(output, "pub use application::validation::{{ValidationError, ValidationResult, Validate}};").unwrap();
            writeln!(output).unwrap();
        }

        // Re-exports - Triggers (types are generated by triggers generator)
        // Each entity with triggers gets a module with trigger handlers
        let hooks_with_triggers = schema.schema.hooks.iter()
            .filter(|h| !h.triggers.is_empty())
            .collect::<Vec<_>>();
        if !hooks_with_triggers.is_empty() {
            writeln!(output, "// Re-exports - Triggers").unwrap();
            writeln!(output, "pub use application::triggers::*;").unwrap();
            writeln!(output).unwrap();
        }

        // Re-exports - Workflows (types are generated by workflow generator)
        // Each workflow gets: {Flow}Status, {Flow}Step, {Flow}Instance, {Flow}StepHandler, {Flow}Executor
        if !schema.schema.workflows.is_empty() {
            writeln!(output, "// Re-exports - Workflows").unwrap();
            writeln!(output, "pub use application::workflows::*;").unwrap();
            writeln!(output).unwrap();
        }

        // Imports for builder
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output, "use axum::Router;").unwrap();
        writeln!(output, "use sqlx::PgPool;").unwrap();
        writeln!(output).unwrap();

        // Module struct
        writeln!(output, "/// {} module configuration", pascal_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Use the builder pattern to configure and register this module:").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ```text").unwrap();
        writeln!(output, "/// let {} = {}Module::builder()", to_snake_case(module_name), pascal_name).unwrap();
        writeln!(output, "///     .with_database(pool.clone())").unwrap();
        writeln!(output, "///     .build()?;").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// let router = {}.routes();", to_snake_case(module_name)).unwrap();
        writeln!(output, "/// ```").unwrap();
        writeln!(output, "pub struct {}Module {{", pascal_name).unwrap();

        // Fields for each service
        for model in &schema.schema.models {
            let service_name = format!("{}Service", model.name);
            let service_type = if model_names.contains(service_name.as_str()) {
                format!("{}AppService", model.name)
            } else {
                service_name
            };
            writeln!(output, "    pub {}_service: Arc<{}>,",
                to_snake_case(&model.name), service_type).unwrap();
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Module implementation
        writeln!(output, "impl {}Module {{", pascal_name).unwrap();
        writeln!(output, "    /// Create a new module builder").unwrap();
        writeln!(output, "    pub fn builder() -> {}ModuleBuilder {{", pascal_name).unwrap();
        writeln!(output, "        {}ModuleBuilder::new()", pascal_name).unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // Configure routes method - returns Axum Router using BackboneCrudHandler
        writeln!(output, "    /// Configure HTTP routes for this module using Axum").unwrap();
        writeln!(output, "    ///").unwrap();
        writeln!(output, "    /// Returns an Axum Router with all 12 Backbone CRUD endpoints per entity.").unwrap();
        writeln!(output, "    pub fn routes(&self) -> Router {{").unwrap();
        writeln!(output, "        use presentation::http::{{").unwrap();
        for model in &schema.schema.models {
            writeln!(output, "            create_{}_routes,", to_snake_case(&model.name)).unwrap();
        }
        writeln!(output, "        }};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Router::new()").unwrap();
        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "            .merge(create_{}_routes(self.{}_service.clone()))",
                snake_name, snake_name).unwrap();
        }
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Builder struct
        writeln!(output, "/// Builder for {}Module", pascal_name).unwrap();
        writeln!(output, "pub struct {}ModuleBuilder {{", pascal_name).unwrap();
        writeln!(output, "    db_pool: Option<PgPool>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Builder implementation
        writeln!(output, "impl {}ModuleBuilder {{", pascal_name).unwrap();
        writeln!(output, "    /// Create a new builder").unwrap();
        writeln!(output, "    pub fn new() -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            db_pool: None,").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Set the database connection pool").unwrap();
        writeln!(output, "    pub fn with_database(mut self, pool: PgPool) -> Self {{").unwrap();
        writeln!(output, "        self.db_pool = Some(pool);").unwrap();
        writeln!(output, "        self").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Build the module with configured dependencies").unwrap();
        writeln!(output, "    pub fn build(self) -> anyhow::Result<{}Module> {{", pascal_name).unwrap();
        writeln!(output, "        let db_pool = self.db_pool").unwrap();
        writeln!(output, "            .ok_or_else(|| anyhow::anyhow!(\"Database pool not configured\"))?;").unwrap();
        writeln!(output).unwrap();

        // Build each repository and service
        for model in &schema.schema.models {
            let name = &model.name;
            let snake_name = to_snake_case(name);
            let service_name = format!("{}Service", name);
            let service_type = if model_names.contains(service_name.as_str()) {
                format!("{}AppService", name)
            } else {
                service_name
            };
            writeln!(output, "        // {} service", name).unwrap();
            writeln!(output, "        let {}_repository = Arc::new({}Repository::new(db_pool.clone()));",
                snake_name, name).unwrap();
            writeln!(output, "        let {}_service = Arc::new({}::with_repository({}_repository.clone()));",
                snake_name, service_type, snake_name).unwrap();
            writeln!(output).unwrap();
        }

        // Placeholder for custom let statements (e.g., additional services)
        writeln!(output, "        // <<< CUSTOM").unwrap();
        writeln!(output, "        // END CUSTOM").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok({}Module {{", pascal_name).unwrap();
        for model in &schema.schema.models {
            writeln!(output, "            {}_service,", to_snake_case(&model.name)).unwrap();
        }
        // Placeholder for custom struct fields
        writeln!(output, "            // <<< CUSTOM").unwrap();
        writeln!(output, "            // END CUSTOM").unwrap();
        writeln!(output, "        }})").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Default impl for builder
        writeln!(output, "impl Default for {}ModuleBuilder {{", pascal_name).unwrap();
        writeln!(output, "    fn default() -> Self {{").unwrap();
        writeln!(output, "        Self::new()").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();

        Ok(output)
    }

    /// Generate routes.rs - HTTP route configuration using Axum and BackboneCrudHandler
    fn generate_routes(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();

        // Header
        writeln!(output, "//! HTTP route configuration").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This module provides consolidated Axum route configuration using backbone-core's").unwrap();
        writeln!(output, "//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use axum::Router;").unwrap();
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output).unwrap();

        // Import handler route functions and service types
        writeln!(output, "use super::{{").unwrap();
        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "    {}_handler::create_{}_routes,",
                snake_name, snake_name).unwrap();
        }
        writeln!(output, "}};").unwrap();
        writeln!(output).unwrap();
        // Import service types
        writeln!(output, "use crate::application::service::{{").unwrap();
        for model in &schema.schema.models {
            writeln!(output, "    {}Service,", model.name).unwrap();
        }
        writeln!(output, "}};").unwrap();
        writeln!(output).unwrap();

        // Services collection struct
        writeln!(output, "/// Services collection for all CRUD endpoints").unwrap();
        writeln!(output, "pub struct HttpServices {{").unwrap();
        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "    pub {}: Arc<{}Service>,", snake_name, model.name).unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Configure routes function
        writeln!(output, "/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Each entity gets 12 standard Backbone CRUD endpoints:").unwrap();
        writeln!(output, "/// 1. GET /api/v1/{{collection}} - List with pagination").unwrap();
        writeln!(output, "/// 2. POST /api/v1/{{collection}} - Create").unwrap();
        writeln!(output, "/// 3. GET /api/v1/{{collection}}/:id - Get by ID").unwrap();
        writeln!(output, "/// 4. PUT /api/v1/{{collection}}/:id - Full update").unwrap();
        writeln!(output, "/// 5. PATCH /api/v1/{{collection}}/:id - Partial update").unwrap();
        writeln!(output, "/// 6. DELETE /api/v1/{{collection}}/:id - Soft delete").unwrap();
        writeln!(output, "/// 7. POST /api/v1/{{collection}}/bulk - Bulk create").unwrap();
        writeln!(output, "/// 8. POST /api/v1/{{collection}}/upsert - Upsert").unwrap();
        writeln!(output, "/// 9. GET /api/v1/{{collection}}/trash - List deleted").unwrap();
        writeln!(output, "/// 10. POST /api/v1/{{collection}}/:id/restore - Restore").unwrap();
        writeln!(output, "/// 11. DELETE /api/v1/{{collection}}/empty - Empty trash").unwrap();
        writeln!(output, "/// 12. GET /api/v1/{{collection}}/:id/deleted - Get deleted by ID").unwrap();
        writeln!(output, "pub fn configure_routes(services: HttpServices) -> Router {{").unwrap();
        writeln!(output, "    Router::new()").unwrap();

        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "        // {} routes (12 Backbone endpoints)", model.name).unwrap();
            writeln!(output, "        .merge(create_{}_routes(services.{}))", snake_name, snake_name).unwrap();
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Individual route functions module
        writeln!(output, "/// Create an individual entity's routes (for modular configuration)").unwrap();
        writeln!(output, "pub mod individual {{").unwrap();
        writeln!(output, "    use super::*;").unwrap();
        writeln!(output).unwrap();
        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "    pub fn {}_routes(service: Arc<{}Service>) -> Router {{",
                snake_name, model.name).unwrap();
            writeln!(output, "        create_{}_routes(service)", snake_name).unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output).unwrap();
        }
        writeln!(output, "}}").unwrap();

        Ok(output)
    }

    /// Generate gRPC service registration
    fn generate_grpc(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        // Header
        writeln!(output, "//! gRPC service registration").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use tonic::transport::Server;").unwrap();
        writeln!(output).unwrap();

        // Import gRPC services
        for model in &schema.schema.models {
            writeln!(output, "use super::grpc::{}_grpc_service::{}GrpcService;",
                to_snake_case(&model.name), model.name).unwrap();
        }
        writeln!(output).unwrap();

        // GrpcServer struct
        writeln!(output, "/// gRPC server for {} module", pascal_name).unwrap();
        writeln!(output, "pub struct {}GrpcServer {{", pascal_name).unwrap();
        for model in &schema.schema.models {
            writeln!(output, "    {}_service: {}GrpcService,",
                to_snake_case(&model.name), model.name).unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Implementation
        writeln!(output, "impl {}GrpcServer {{", pascal_name).unwrap();
        writeln!(output, "    /// Create a new gRPC server from module").unwrap();
        writeln!(output, "    pub fn new(module: &super::{}Module) -> Self {{", pascal_name).unwrap();
        writeln!(output, "        Self {{").unwrap();
        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "            {}_service: {}GrpcService::new(module.{}_service.clone()),",
                snake_name, model.name, snake_name).unwrap();
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Start the gRPC server").unwrap();
        writeln!(output, "    pub async fn serve(self, addr: std::net::SocketAddr) -> Result<(), tonic::transport::Error> {{").unwrap();
        writeln!(output, "        Server::builder()").unwrap();
        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "            .add_service(self.{}_service.into_service())", snake_name).unwrap();
        }
        writeln!(output, "            .serve(addr)").unwrap();
        writeln!(output, "            .await").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();

        Ok(output)
    }

    /// Generate GraphQL schema composition (server.rs)
    fn generate_graphql(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        // Header
        writeln!(output, "//! GraphQL schema composition for {} module", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Provides both standalone `build_schema()` and composable `inject_services()`").unwrap();
        writeln!(output, "//! methods. Use `inject_services()` to compose module GraphQL services into").unwrap();
        writeln!(output, "//! a shared app-level schema.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output, "use async_graphql::*;").unwrap();
        writeln!(output).unwrap();

        // Import query/mutation types
        for model in &schema.schema.models {
            writeln!(output, "use super::{{{}Query, {}Mutation}};", model.name, model.name).unwrap();
        }
        writeln!(output).unwrap();

        // Import service types
        for model in &schema.schema.models {
            writeln!(output, "use crate::application::service::{}Service;", model.name).unwrap();
        }
        writeln!(output).unwrap();

        // Merged Query root
        writeln!(output, "/// Merged Query root for {} module", pascal_name).unwrap();
        writeln!(output, "#[derive(MergedObject, Default)]").unwrap();
        write!(output, "pub struct {}Query(", pascal_name).unwrap();
        for (i, model) in schema.schema.models.iter().enumerate() {
            if i > 0 { write!(output, ", ").unwrap(); }
            if i > 0 && i % 5 == 0 { writeln!(output).unwrap(); write!(output, "    ").unwrap(); }
            write!(output, "{}Query", model.name).unwrap();
        }
        writeln!(output, ");").unwrap();
        writeln!(output).unwrap();

        // Merged Mutation root
        writeln!(output, "/// Merged Mutation root for {} module", pascal_name).unwrap();
        writeln!(output, "#[derive(MergedObject, Default)]").unwrap();
        write!(output, "pub struct {}Mutation(", pascal_name).unwrap();
        for (i, model) in schema.schema.models.iter().enumerate() {
            if i > 0 { write!(output, ", ").unwrap(); }
            if i > 0 && i % 5 == 0 { writeln!(output).unwrap(); write!(output, "    ").unwrap(); }
            write!(output, "{}Mutation", model.name).unwrap();
        }
        writeln!(output, ");").unwrap();
        writeln!(output).unwrap();

        // inject_services function
        writeln!(output, "/// Inject all {} services into a schema builder", pascal_name).unwrap();
        writeln!(output, "pub fn inject_services<Q: ObjectType + 'static, M: ObjectType + 'static, S: SubscriptionType + 'static>(").unwrap();
        writeln!(output, "    builder: SchemaBuilder<Q, M, S>,").unwrap();
        writeln!(output, "    module: &crate::{}Module,", pascal_name).unwrap();
        writeln!(output, ") -> SchemaBuilder<Q, M, S> {{").unwrap();
        writeln!(output, "    builder").unwrap();
        for model in &schema.schema.models {
            let model_snake = to_snake_case(&model.name);
            writeln!(output, "        .data(module.{}_service.clone())", model_snake).unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // build_schema function
        writeln!(output, "/// Build the GraphQL schema for {} module (standalone)", pascal_name).unwrap();
        writeln!(output, "pub fn build_schema(module: &crate::{}Module) -> Schema<{}Query, {}Mutation, EmptySubscription> {{",
            pascal_name, pascal_name, pascal_name).unwrap();
        writeln!(output, "    let builder = Schema::build({}Query::default(), {}Mutation::default(), EmptySubscription);",
            pascal_name, pascal_name).unwrap();
        writeln!(output, "    inject_services(builder, module).finish()").unwrap();
        writeln!(output, "}}").unwrap();

        Ok(output)
    }

    /// Generate domain/mod.rs
    fn generate_domain_mod(&self, schema: &ResolvedSchema) -> String {
        let mut output = String::new();

        writeln!(output, "//! Domain layer").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Enhanced with runtime implementations.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub mod entity;").unwrap();

        // Add repository traits module (always generated for all models)
        if !schema.schema.models.is_empty() {
            writeln!(output, "pub mod repositories;").unwrap();
        }

        // Add domain services module if any models exist
        if !schema.schema.models.is_empty() {
            writeln!(output, "pub mod services;").unwrap();
        }

        // Add specifications module if any models exist
        if !schema.schema.models.is_empty() {
            writeln!(output, "pub mod specifications;").unwrap();
        }

        // Add value_objects module if any models exist
        if !schema.schema.models.is_empty() {
            writeln!(output, "pub mod value_objects;").unwrap();
        }

        // Add state_machine module if any hook has a state machine
        if schema.schema.hooks.iter().any(|h| h.state_machine.is_some()) {
            writeln!(output, "pub mod state_machine;").unwrap();
        }

        // Add events module if any models exist (events are generated for all models)
        if !schema.schema.models.is_empty() {
            writeln!(output, "pub mod event;").unwrap();
        }

        // Always add permission module for RBAC support
        writeln!(output, "pub mod permission;").unwrap();

        // Add computed fields module if any hook has computed fields
        if schema.schema.hooks.iter().any(|h| !h.computed_fields.is_empty()) {
            writeln!(output, "pub mod computed;").unwrap();
        }

        writeln!(output).unwrap();

        // Re-export commonly used types
        writeln!(output, "// Re-export commonly used types").unwrap();
        if !schema.schema.models.is_empty() {
            writeln!(output, "pub use repositories::*;").unwrap();
            writeln!(output, "pub use services::*;").unwrap();
            writeln!(output, "pub use specifications::*;").unwrap();
            writeln!(output, "pub use value_objects::*;").unwrap();
        }
        if schema.schema.hooks.iter().any(|h| h.state_machine.is_some()) {
            writeln!(output, "pub use state_machine::*;").unwrap();
        }
        if schema.schema.hooks.iter().any(|h| !h.computed_fields.is_empty()) {
            writeln!(output, "pub use computed::*;").unwrap();
        }
        writeln!(output, "pub use entity::*;").unwrap();

        output
    }

    /// Generate infrastructure/mod.rs
    fn generate_infrastructure_mod(&self, _schema: &ResolvedSchema) -> String {
        let mut output = String::new();

        writeln!(output, "//! Infrastructure layer").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub mod persistence;").unwrap();

        output
    }

    /// Generate application/mod.rs
    fn generate_application_mod(&self, schema: &ResolvedSchema) -> String {
        let mut output = String::new();

        writeln!(output, "//! Application layer").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Enhanced with runtime implementations.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This layer contains:").unwrap();
        writeln!(output, "//! - Commands (CQRS write operations)").unwrap();
        writeln!(output, "//! - Queries (CQRS read operations)").unwrap();
        writeln!(output, "//! - Services (business logic)").unwrap();
        writeln!(output, "//! - Middleware (Auth & RBAC)").unwrap();
        writeln!(output, "//! - Triggers (lifecycle hooks)").unwrap();
        writeln!(output, "//! - Validation (input validation)").unwrap();
        writeln!(output, "//! - Workflows (saga/orchestration patterns)").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "pub mod service;").unwrap();

        // Always add middleware module for Auth & RBAC
        writeln!(output, "pub mod middleware;").unwrap();

        // Add triggers module if any hook has triggers
        if schema.schema.hooks.iter().any(|h| !h.triggers.is_empty()) {
            writeln!(output, "pub mod triggers;").unwrap();
        }

        // Add validator module if there are models (validators are generated for each model)
        if !schema.schema.models.is_empty() {
            writeln!(output, "pub mod validator;").unwrap();
        }

        // Add workflows module if there are workflows defined
        if !schema.schema.workflows.is_empty() {
            writeln!(output, "pub mod workflows;").unwrap();
        }

        writeln!(output).unwrap();
        writeln!(output, "// Re-exports").unwrap();
        writeln!(output, "pub use service::*;").unwrap();

        output
    }

    /// Generate presentation/mod.rs
    fn generate_presentation_mod(&self, _schema: &ResolvedSchema) -> String {
        let mut output = String::new();

        writeln!(output, "//! Presentation layer").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub mod dto;").unwrap();
        writeln!(output, "pub mod http;").unwrap();
        writeln!(output).unwrap();
        // gRPC module is feature-gated since it requires proto compilation
        writeln!(output, "#[cfg(feature = \"grpc\")]").unwrap();
        writeln!(output, "pub mod grpc;").unwrap();
        writeln!(output).unwrap();
        // GraphQL module is feature-gated
        writeln!(output, "#[cfg(feature = \"graphql\")]").unwrap();
        writeln!(output, "pub mod graphql;").unwrap();

        output
    }
}

impl Default for ModuleGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for ModuleGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Generate lib.rs (module entry point)
        let lib_content = self.generate_lib_rs(schema)?;
        output.add_file(PathBuf::from("src/lib.rs"), lib_content);

        // Generate routes.rs
        let routes_content = self.generate_routes(schema)?;
        output.add_file(PathBuf::from("src/presentation/http/routes.rs"), routes_content);

        // Generate gRPC registration
        let grpc_content = self.generate_grpc(schema)?;
        output.add_file(PathBuf::from("src/presentation/grpc/server.rs"), grpc_content);

        // Generate GraphQL schema composition (server.rs only — entity files from GraphqlGenerator)
        let graphql_content = self.generate_graphql(schema)?;
        output.add_file(PathBuf::from("src/presentation/graphql/server.rs"), graphql_content);

        // Generate layer mod.rs files
        output.add_file(
            PathBuf::from("src/domain/mod.rs"),
            self.generate_domain_mod(schema),
        );
        output.add_file(
            PathBuf::from("src/infrastructure/mod.rs"),
            self.generate_infrastructure_mod(schema),
        );
        output.add_file(
            PathBuf::from("src/application/mod.rs"),
            self.generate_application_mod(schema),
        );
        output.add_file(
            PathBuf::from("src/presentation/mod.rs"),
            self.generate_presentation_mod(schema),
        );

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "module"
    }
}

use crate::utils::to_snake_case;


fn to_pascal_case(name: &str) -> String {
    name.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, Model, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("User");
        model.collection = Some("users".to_string());
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::String))),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "email".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Email),
                attributes: vec![Attribute::new("unique")],
                ..Default::default()
            },
            Field {
                name: "deleted_at".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("orders");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_module_generator_creates_lib_rs() {
        let schema = create_test_schema();
        let generator = ModuleGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/lib.rs")));

        let lib_content = output.files.get(&PathBuf::from("src/lib.rs")).unwrap();
        assert!(lib_content.contains("pub struct OrdersModule"));
        assert!(lib_content.contains("pub struct OrdersModuleBuilder"));
        assert!(lib_content.contains("user_service: Arc<UserService>"));
    }

    #[test]
    fn test_module_generator_creates_routes() {
        let schema = create_test_schema();
        let generator = ModuleGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/presentation/http/routes.rs")));

        let routes_content = output.files.get(&PathBuf::from("src/presentation/http/routes.rs")).unwrap();
        // Check for Axum Router usage
        assert!(routes_content.contains("use axum::Router;"));
        // Check for route and service imports
        assert!(routes_content.contains("create_user_routes"));
        assert!(routes_content.contains("UserService"));
        // Check for HttpServices struct
        assert!(routes_content.contains("pub struct HttpServices"));
        // Check for configure_routes function
        assert!(routes_content.contains("pub fn configure_routes"));
        // Check for BackboneCrudHandler documentation
        assert!(routes_content.contains("BackboneCrudHandler"));
    }

    #[test]
    fn test_module_generator_includes_soft_delete_routes() {
        let schema = create_test_schema();
        let generator = ModuleGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let routes_content = output.files.get(&PathBuf::from("src/presentation/http/routes.rs")).unwrap();
        // Routes now use BackboneCrudHandler which includes all 12 endpoints
        // The documentation mentions soft delete routes
        assert!(routes_content.contains("/trash"));
        assert!(routes_content.contains("/restore"));
        assert!(routes_content.contains("/empty"));
    }

    #[test]
    fn test_module_generator_creates_grpc_server() {
        let schema = create_test_schema();
        let generator = ModuleGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/presentation/grpc/server.rs")));

        let grpc_content = output.files.get(&PathBuf::from("src/presentation/grpc/server.rs")).unwrap();
        assert!(grpc_content.contains("pub struct OrdersGrpcServer"));
        assert!(grpc_content.contains("UserGrpcService"));
    }

    #[test]
    fn test_module_generator_creates_layer_mods() {
        let schema = create_test_schema();
        let generator = ModuleGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/domain/mod.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/mod.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/application/mod.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/presentation/mod.rs")));
    }

    #[test]
    fn test_builder_pattern_generated() {
        let schema = create_test_schema();
        let generator = ModuleGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let lib_content = output.files.get(&PathBuf::from("src/lib.rs")).unwrap();

        // Check builder methods
        assert!(lib_content.contains("pub fn builder()"));
        assert!(lib_content.contains("pub fn with_database"));
        assert!(lib_content.contains("pub fn build"));
        // Routes method is defined on the module struct, not as configure_routes
        assert!(lib_content.contains("pub fn routes(&self)"));
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("orders"), "Orders");
        assert_eq!(to_pascal_case("user_management"), "UserManagement");
        assert_eq!(to_pascal_case("api_gateway"), "ApiGateway");
    }
}
