//! OpenAPI specification generator
//!
//! Generates OpenAPI 3.0 specification (JSON/YAML) for the 11 standard Backbone CRUD endpoints.

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::{Model, PrimitiveType, TypeRef};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates OpenAPI 3.0 specification
pub struct OpenApiGenerator {
    /// API title
    title: String,
    /// API version
    version: String,
    /// Server URL
    server_url: String,
    /// Split output into multiple files (one per entity)
    split: bool,
}

impl OpenApiGenerator {
    pub fn new() -> Self {
        Self {
            title: "Backbone API".to_string(),
            version: "1.0.0".to_string(),
            server_url: "http://localhost:3000".to_string(),
            split: false,
        }
    }

    pub fn with_title(mut self, title: impl Into<String>) -> Self {
        self.title = title.into();
        self
    }

    pub fn with_version(mut self, version: impl Into<String>) -> Self {
        self.version = version.into();
        self
    }

    pub fn with_server_url(mut self, url: impl Into<String>) -> Self {
        self.server_url = url.into();
        self
    }

    pub fn with_split(mut self, split: bool) -> Self {
        self.split = split;
        self
    }

    fn generate_spec(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();

        // OpenAPI header
        writeln!(output, "openapi: '3.0.3'").unwrap();
        writeln!(output, "info:").unwrap();
        writeln!(output, "  title: {}", self.title).unwrap();
        writeln!(output, "  version: '{}'", self.version).unwrap();
        writeln!(output, "  description: |").unwrap();
        writeln!(output, "    Auto-generated by backbone-cli.").unwrap();
        writeln!(output, "    This API provides 11 standard CRUD endpoints for each model.").unwrap();
        writeln!(output).unwrap();

        // Servers
        writeln!(output, "servers:").unwrap();
        writeln!(output, "  - url: {}", self.server_url).unwrap();
        writeln!(output, "    description: Development server").unwrap();
        writeln!(output).unwrap();

        // Tags
        writeln!(output, "tags:").unwrap();
        for model in &schema.schema.models {
            writeln!(output, "  - name: {}", pluralize(&model.name)).unwrap();
            writeln!(output, "    description: {} management endpoints", model.name).unwrap();
        }
        writeln!(output).unwrap();

        // Paths
        writeln!(output, "paths:").unwrap();
        for model in &schema.schema.models {
            self.write_model_paths(&mut output, model)?;
        }

        // Components
        writeln!(output, "components:").unwrap();
        writeln!(output, "  schemas:").unwrap();

        // Common schemas
        self.write_common_schemas(&mut output)?;

        // Model schemas
        for model in &schema.schema.models {
            self.write_model_schemas(&mut output, model)?;
        }

        // Security schemes
        writeln!(output, "  securitySchemes:").unwrap();
        writeln!(output, "    bearerAuth:").unwrap();
        writeln!(output, "      type: http").unwrap();
        writeln!(output, "      scheme: bearer").unwrap();
        writeln!(output, "      bearerFormat: JWT").unwrap();
        writeln!(output).unwrap();

        // Global security
        writeln!(output, "security:").unwrap();
        writeln!(output, "  - bearerAuth: []").unwrap();

        Ok(output)
    }

    fn write_model_paths(&self, output: &mut String, model: &Model) -> Result<(), GenerateError> {
        let model_snake = to_snake_case(&model.name);
        let model_plural = pluralize(&model_snake);
        let base_path = format!("/api/v1/{}", model_plural);
        let tag = pluralize(&model.name);

        // Collection endpoints
        writeln!(output, "  {}:", base_path).unwrap();

        // GET - List
        writeln!(output, "    get:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: List {}", pluralize(&model.name)).unwrap();
        writeln!(output, "      description: Get a paginated list of {} with optional filtering and sorting", pluralize(&model.name)).unwrap();
        writeln!(output, "      operationId: list{}", pluralize(&model.name)).unwrap();
        writeln!(output, "      parameters:").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/PageParam'").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/PerPageParam'").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/SortByParam'").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/SortOrderParam'").unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Successful response").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}List'", model.name).unwrap();
        writeln!(output, "        '401':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/Unauthorized'").unwrap();
        writeln!(output).unwrap();

        // POST - Create
        writeln!(output, "    post:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Create {}", model.name).unwrap();
        writeln!(output, "      description: Create a new {}", model.name).unwrap();
        writeln!(output, "      operationId: create{}", model.name).unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              $ref: '#/components/schemas/Create{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '201':").unwrap();
        writeln!(output, "          description: Created").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '400':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/BadRequest'").unwrap();
        writeln!(output, "        '401':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/Unauthorized'").unwrap();
        writeln!(output).unwrap();

        // Single item endpoint
        writeln!(output, "  {}/{{id}}:", base_path).unwrap();
        writeln!(output, "    parameters:").unwrap();
        writeln!(output, "      - $ref: '#/components/parameters/IdParam'").unwrap();
        writeln!(output).unwrap();

        // GET - Get by ID
        writeln!(output, "    get:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Get {} by ID", model.name).unwrap();
        writeln!(output, "      operationId: get{}", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Successful response").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // PUT - Full update
        writeln!(output, "    put:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Update {} (full)", model.name).unwrap();
        writeln!(output, "      operationId: update{}", model.name).unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              $ref: '#/components/schemas/Update{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Updated").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // PATCH - Partial update
        writeln!(output, "    patch:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Update {} (partial)", model.name).unwrap();
        writeln!(output, "      operationId: patch{}", model.name).unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              $ref: '#/components/schemas/Patch{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Updated").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // DELETE - Soft delete
        writeln!(output, "    delete:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Delete {} (soft)", model.name).unwrap();
        writeln!(output, "      operationId: delete{}", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '204':").unwrap();
        writeln!(output, "          description: Deleted").unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // Bulk create
        writeln!(output, "  {}/bulk:", base_path).unwrap();
        writeln!(output, "    post:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Bulk create {}", pluralize(&model.name)).unwrap();
        writeln!(output, "      operationId: bulkCreate{}", pluralize(&model.name)).unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              type: array").unwrap();
        writeln!(output, "              items:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/Create{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '201':").unwrap();
        writeln!(output, "          description: Created").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                type: array").unwrap();
        writeln!(output, "                items:").unwrap();
        writeln!(output, "                  $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output).unwrap();

        // Upsert
        writeln!(output, "  {}/upsert:", base_path).unwrap();
        writeln!(output, "    post:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Upsert {}", model.name).unwrap();
        writeln!(output, "      operationId: upsert{}", model.name).unwrap();
        writeln!(output, "      parameters:").unwrap();
        writeln!(output, "        - name: key_field").unwrap();
        writeln!(output, "          in: query").unwrap();
        writeln!(output, "          schema:").unwrap();
        writeln!(output, "            type: string").unwrap();
        writeln!(output, "        - name: key_value").unwrap();
        writeln!(output, "          in: query").unwrap();
        writeln!(output, "          required: true").unwrap();
        writeln!(output, "          schema:").unwrap();
        writeln!(output, "            type: string").unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              $ref: '#/components/schemas/Update{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Upserted").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output).unwrap();

        // Trash list
        writeln!(output, "  {}/trash:", base_path).unwrap();
        writeln!(output, "    get:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: List deleted {}", pluralize(&model.name)).unwrap();
        writeln!(output, "      operationId: listDeleted{}", pluralize(&model.name)).unwrap();
        writeln!(output, "      parameters:").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/PageParam'").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/PerPageParam'").unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Successful response").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}List'", model.name).unwrap();
        writeln!(output).unwrap();

        // Restore
        writeln!(output, "  {}/{{id}}/restore:", base_path).unwrap();
        writeln!(output, "    parameters:").unwrap();
        writeln!(output, "      - $ref: '#/components/parameters/IdParam'").unwrap();
        writeln!(output, "    post:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Restore deleted {}", model.name).unwrap();
        writeln!(output, "      operationId: restore{}", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Restored").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // Empty trash
        writeln!(output, "  {}/empty:", base_path).unwrap();
        writeln!(output, "    delete:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Empty trash for {}", pluralize(&model.name)).unwrap();
        writeln!(output, "      operationId: emptyTrash{}", pluralize(&model.name)).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Trash emptied").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                type: object").unwrap();
        writeln!(output, "                properties:").unwrap();
        writeln!(output, "                  deleted_count:").unwrap();
        writeln!(output, "                    type: integer").unwrap();
        writeln!(output).unwrap();

        Ok(())
    }

    fn write_common_schemas(&self, output: &mut String) -> Result<(), GenerateError> {
        // Pagination response
        writeln!(output, "    PaginationMeta:").unwrap();
        writeln!(output, "      type: object").unwrap();
        writeln!(output, "      properties:").unwrap();
        writeln!(output, "        total:").unwrap();
        writeln!(output, "          type: integer").unwrap();
        writeln!(output, "          example: 100").unwrap();
        writeln!(output, "        page:").unwrap();
        writeln!(output, "          type: integer").unwrap();
        writeln!(output, "          example: 1").unwrap();
        writeln!(output, "        per_page:").unwrap();
        writeln!(output, "          type: integer").unwrap();
        writeln!(output, "          example: 20").unwrap();
        writeln!(output, "        total_pages:").unwrap();
        writeln!(output, "          type: integer").unwrap();
        writeln!(output, "          example: 5").unwrap();
        writeln!(output).unwrap();

        // Error schema
        writeln!(output, "    Error:").unwrap();
        writeln!(output, "      type: object").unwrap();
        writeln!(output, "      required:").unwrap();
        writeln!(output, "        - code").unwrap();
        writeln!(output, "        - message").unwrap();
        writeln!(output, "      properties:").unwrap();
        writeln!(output, "        code:").unwrap();
        writeln!(output, "          type: string").unwrap();
        writeln!(output, "          example: VALIDATION_ERROR").unwrap();
        writeln!(output, "        message:").unwrap();
        writeln!(output, "          type: string").unwrap();
        writeln!(output, "          example: Invalid input data").unwrap();
        writeln!(output, "        details:").unwrap();
        writeln!(output, "          type: object").unwrap();
        writeln!(output, "          additionalProperties: true").unwrap();
        writeln!(output).unwrap();

        // Parameters
        writeln!(output, "  parameters:").unwrap();
        writeln!(output, "    IdParam:").unwrap();
        writeln!(output, "      name: id").unwrap();
        writeln!(output, "      in: path").unwrap();
        writeln!(output, "      required: true").unwrap();
        writeln!(output, "      schema:").unwrap();
        writeln!(output, "        type: string").unwrap();
        writeln!(output, "        format: uuid").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    PageParam:").unwrap();
        writeln!(output, "      name: page").unwrap();
        writeln!(output, "      in: query").unwrap();
        writeln!(output, "      schema:").unwrap();
        writeln!(output, "        type: integer").unwrap();
        writeln!(output, "        minimum: 1").unwrap();
        writeln!(output, "        default: 1").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    PerPageParam:").unwrap();
        writeln!(output, "      name: per_page").unwrap();
        writeln!(output, "      in: query").unwrap();
        writeln!(output, "      schema:").unwrap();
        writeln!(output, "        type: integer").unwrap();
        writeln!(output, "        minimum: 1").unwrap();
        writeln!(output, "        maximum: 100").unwrap();
        writeln!(output, "        default: 20").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    SortByParam:").unwrap();
        writeln!(output, "      name: sort_by").unwrap();
        writeln!(output, "      in: query").unwrap();
        writeln!(output, "      schema:").unwrap();
        writeln!(output, "        type: string").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    SortOrderParam:").unwrap();
        writeln!(output, "      name: sort_order").unwrap();
        writeln!(output, "      in: query").unwrap();
        writeln!(output, "      schema:").unwrap();
        writeln!(output, "        type: string").unwrap();
        writeln!(output, "        enum: [asc, desc]").unwrap();
        writeln!(output, "        default: asc").unwrap();
        writeln!(output).unwrap();

        // Common responses
        writeln!(output, "  responses:").unwrap();
        writeln!(output, "    BadRequest:").unwrap();
        writeln!(output, "      description: Bad request").unwrap();
        writeln!(output, "      content:").unwrap();
        writeln!(output, "        application/json:").unwrap();
        writeln!(output, "          schema:").unwrap();
        writeln!(output, "            $ref: '#/components/schemas/Error'").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    Unauthorized:").unwrap();
        writeln!(output, "      description: Unauthorized").unwrap();
        writeln!(output, "      content:").unwrap();
        writeln!(output, "        application/json:").unwrap();
        writeln!(output, "          schema:").unwrap();
        writeln!(output, "            $ref: '#/components/schemas/Error'").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    NotFound:").unwrap();
        writeln!(output, "      description: Resource not found").unwrap();
        writeln!(output, "      content:").unwrap();
        writeln!(output, "        application/json:").unwrap();
        writeln!(output, "          schema:").unwrap();
        writeln!(output, "            $ref: '#/components/schemas/Error'").unwrap();
        writeln!(output).unwrap();

        Ok(())
    }

    fn write_model_schemas(&self, output: &mut String, model: &Model) -> Result<(), GenerateError> {
        // Main entity schema
        writeln!(output, "    {}:", model.name).unwrap();
        writeln!(output, "      type: object").unwrap();
        writeln!(output, "      required:").unwrap();
        for field in &model.fields {
            if !field.type_ref.is_optional() && field.name != "deleted_at" {
                writeln!(output, "        - {}", field.name).unwrap();
            }
        }
        writeln!(output, "      properties:").unwrap();
        for field in &model.fields {
            self.write_field_schema(output, field, 8)?;
        }
        writeln!(output).unwrap();

        // Create request schema
        writeln!(output, "    Create{}Request:", model.name).unwrap();
        writeln!(output, "      type: object").unwrap();
        writeln!(output, "      required:").unwrap();
        for field in &model.fields {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            if !field.type_ref.is_optional() {
                writeln!(output, "        - {}", field.name).unwrap();
            }
        }
        writeln!(output, "      properties:").unwrap();
        for field in &model.fields {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            self.write_field_schema(output, field, 8)?;
        }
        writeln!(output).unwrap();

        // Update request schema (same as create but might include id)
        writeln!(output, "    Update{}Request:", model.name).unwrap();
        writeln!(output, "      type: object").unwrap();
        writeln!(output, "      required:").unwrap();
        for field in &model.fields {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            if !field.type_ref.is_optional() {
                writeln!(output, "        - {}", field.name).unwrap();
            }
        }
        writeln!(output, "      properties:").unwrap();
        for field in &model.fields {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            self.write_field_schema(output, field, 8)?;
        }
        writeln!(output).unwrap();

        // Patch request schema (all optional)
        writeln!(output, "    Patch{}Request:", model.name).unwrap();
        writeln!(output, "      type: object").unwrap();
        writeln!(output, "      properties:").unwrap();
        for field in &model.fields {
            if field.name == "id" || field.name == "created_at" || field.name == "updated_at" || field.name == "deleted_at" {
                continue;
            }
            self.write_field_schema(output, field, 8)?;
        }
        writeln!(output).unwrap();

        // List response schema
        writeln!(output, "    {}List:", model.name).unwrap();
        writeln!(output, "      type: object").unwrap();
        writeln!(output, "      properties:").unwrap();
        writeln!(output, "        items:").unwrap();
        writeln!(output, "          type: array").unwrap();
        writeln!(output, "          items:").unwrap();
        writeln!(output, "            $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        meta:").unwrap();
        writeln!(output, "          $ref: '#/components/schemas/PaginationMeta'").unwrap();
        writeln!(output).unwrap();

        Ok(())
    }

    fn write_field_schema(&self, output: &mut String, field: &crate::ast::Field, indent: usize) -> Result<(), GenerateError> {
        let spaces = " ".repeat(indent);
        writeln!(output, "{}{}:", spaces, field.name).unwrap();

        let (schema_type, format) = self.type_to_openapi(&field.type_ref);

        if field.type_ref.is_optional() {
            writeln!(output, "{}  nullable: true", spaces).unwrap();
        }

        writeln!(output, "{}  type: {}", spaces, schema_type).unwrap();

        if let Some(fmt) = format {
            writeln!(output, "{}  format: {}", spaces, fmt).unwrap();
        }

        // Add validation from attributes
        for attr in &field.attributes {
            match attr.name.as_str() {
                "min" => {
                    if let Some(val) = attr.first_arg().and_then(|v| v.as_int()) {
                        if schema_type == "integer" || schema_type == "number" {
                            writeln!(output, "{}  minimum: {}", spaces, val).unwrap();
                        } else {
                            writeln!(output, "{}  minLength: {}", spaces, val).unwrap();
                        }
                    }
                }
                "max" => {
                    if let Some(val) = attr.first_arg().and_then(|v| v.as_int()) {
                        if schema_type == "integer" || schema_type == "number" {
                            writeln!(output, "{}  maximum: {}", spaces, val).unwrap();
                        } else {
                            writeln!(output, "{}  maxLength: {}", spaces, val).unwrap();
                        }
                    }
                }
                _ => {}
            }
        }

        Ok(())
    }

    fn type_to_openapi(&self, type_ref: &TypeRef) -> (String, Option<String>) {
        match type_ref {
            TypeRef::Primitive(p) => match p {
                PrimitiveType::String | PrimitiveType::Markdown | PrimitiveType::Html => ("string".to_string(), None),
                PrimitiveType::Int | PrimitiveType::Int32 => ("integer".to_string(), Some("int32".to_string())),
                PrimitiveType::Int64 => ("integer".to_string(), Some("int64".to_string())),
                PrimitiveType::Float | PrimitiveType::Float32 => ("number".to_string(), Some("float".to_string())),
                PrimitiveType::Float64 => ("number".to_string(), Some("double".to_string())),
                PrimitiveType::Bool => ("boolean".to_string(), None),
                PrimitiveType::Uuid => ("string".to_string(), Some("uuid".to_string())),
                PrimitiveType::DateTime | PrimitiveType::Timestamp => ("string".to_string(), Some("date-time".to_string())),
                PrimitiveType::Date => ("string".to_string(), Some("date".to_string())),
                PrimitiveType::Time => ("string".to_string(), Some("time".to_string())),
                PrimitiveType::Duration => ("string".to_string(), Some("duration".to_string())),
                PrimitiveType::Decimal | PrimitiveType::Money | PrimitiveType::Percentage => ("string".to_string(), None),
                PrimitiveType::Json => ("object".to_string(), None),
                PrimitiveType::Bytes | PrimitiveType::Binary | PrimitiveType::Base64 => ("string".to_string(), Some("byte".to_string())),
                PrimitiveType::Email => ("string".to_string(), Some("email".to_string())),
                PrimitiveType::Url => ("string".to_string(), Some("uri".to_string())),
                PrimitiveType::Phone => ("string".to_string(), None),
                PrimitiveType::Slug => ("string".to_string(), None),
                PrimitiveType::Ip | PrimitiveType::IpV4 | PrimitiveType::IpV6 => ("string".to_string(), None),
                PrimitiveType::Mac => ("string".to_string(), None),
            },
            TypeRef::Custom(_) => ("string".to_string(), None), // Enums treated as strings
            TypeRef::Array(_) => ("array".to_string(), None),
            TypeRef::Optional(inner) => self.type_to_openapi(inner),
            TypeRef::Map { .. } => ("object".to_string(), None),
            TypeRef::ModuleRef { .. } => ("string".to_string(), None),
        }
    }

    /// Generate split OpenAPI specs: index.openapi.yaml + one file per entity
    fn generate_split_spec(&self, schema: &ResolvedSchema, output: &mut GeneratedOutput) -> Result<(), GenerateError> {
        // Generate index file with shared components and references to entity files
        let index_spec = self.generate_index_spec(schema)?;
        output.add_file(PathBuf::from("schema/openapi/index.openapi.yaml"), index_spec);

        // Generate one file per model
        for model in &schema.schema.models {
            let model_snake = to_snake_case(&model.name);
            let model_spec = self.generate_model_spec(model, schema)?;
            output.add_file(
                PathBuf::from(format!("schema/openapi/{}.openapi.yaml", model_snake)),
                model_spec,
            );
        }

        Ok(())
    }

    /// Generate the index/root OpenAPI file with shared components
    fn generate_index_spec(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();

        // OpenAPI header
        writeln!(output, "openapi: '3.0.3'").unwrap();
        writeln!(output, "info:").unwrap();
        writeln!(output, "  title: {}", self.title).unwrap();
        writeln!(output, "  version: '{}'", self.version).unwrap();
        writeln!(output, "  description: |").unwrap();
        writeln!(output, "    Auto-generated by backbone-cli.").unwrap();
        writeln!(output, "    This is the index file that references individual entity OpenAPI files.").unwrap();
        writeln!(output).unwrap();

        // Servers
        writeln!(output, "servers:").unwrap();
        writeln!(output, "  - url: {}", self.server_url).unwrap();
        writeln!(output, "    description: Development server").unwrap();
        writeln!(output).unwrap();

        // Tags - list all models
        writeln!(output, "tags:").unwrap();
        for model in &schema.schema.models {
            writeln!(output, "  - name: {}", pluralize(&model.name)).unwrap();
            writeln!(output, "    description: {} management endpoints", model.name).unwrap();
        }
        writeln!(output).unwrap();

        // Paths - references to entity files
        writeln!(output, "paths:").unwrap();
        for model in &schema.schema.models {
            let model_snake = to_snake_case(&model.name);
            let model_plural = pluralize(&model_snake);
            let base_path = format!("/api/v1/{}", model_plural);

            // Reference to entity file for collection endpoints
            writeln!(output, "  {}:", base_path).unwrap();
            writeln!(output, "    $ref: './{}.openapi.yaml#/paths/~1api~1v1~1{}'", model_snake, model_plural).unwrap();

            // Reference for single item endpoints
            writeln!(output, "  {}/{{id}}:", base_path).unwrap();
            writeln!(output, "    $ref: './{}.openapi.yaml#/paths/~1api~1v1~1{}~1{{id}}'", model_snake, model_plural).unwrap();

            // Reference for bulk endpoints
            writeln!(output, "  {}/bulk:", base_path).unwrap();
            writeln!(output, "    $ref: './{}.openapi.yaml#/paths/~1api~1v1~1{}~1bulk'", model_snake, model_plural).unwrap();

            // Reference for upsert endpoints
            writeln!(output, "  {}/upsert:", base_path).unwrap();
            writeln!(output, "    $ref: './{}.openapi.yaml#/paths/~1api~1v1~1{}~1upsert'", model_snake, model_plural).unwrap();

            // Reference for trash endpoints
            writeln!(output, "  {}/trash:", base_path).unwrap();
            writeln!(output, "    $ref: './{}.openapi.yaml#/paths/~1api~1v1~1{}~1trash'", model_snake, model_plural).unwrap();

            // Reference for restore endpoints
            writeln!(output, "  {}/{{id}}/restore:", base_path).unwrap();
            writeln!(output, "    $ref: './{}.openapi.yaml#/paths/~1api~1v1~1{}~1{{id}}~1restore'", model_snake, model_plural).unwrap();

            // Reference for empty trash endpoints
            writeln!(output, "  {}/empty:", base_path).unwrap();
            writeln!(output, "    $ref: './{}.openapi.yaml#/paths/~1api~1v1~1{}~1empty'", model_snake, model_plural).unwrap();
        }
        writeln!(output).unwrap();

        // Components - shared schemas
        writeln!(output, "components:").unwrap();
        writeln!(output, "  schemas:").unwrap();

        // Common schemas
        self.write_common_schemas(&mut output)?;

        // Security schemes
        writeln!(output, "  securitySchemes:").unwrap();
        writeln!(output, "    bearerAuth:").unwrap();
        writeln!(output, "      type: http").unwrap();
        writeln!(output, "      scheme: bearer").unwrap();
        writeln!(output, "      bearerFormat: JWT").unwrap();
        writeln!(output).unwrap();

        // Global security
        writeln!(output, "security:").unwrap();
        writeln!(output, "  - bearerAuth: []").unwrap();

        Ok(output)
    }

    /// Generate OpenAPI spec for a single model
    fn generate_model_spec(&self, model: &Model, _schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let model_snake = to_snake_case(&model.name);
        let model_plural = pluralize(&model_snake);
        let base_path = format!("/api/v1/{}", model_plural);
        let tag = pluralize(&model.name);

        // OpenAPI header
        writeln!(output, "openapi: '3.0.3'").unwrap();
        writeln!(output, "info:").unwrap();
        writeln!(output, "  title: {} API", model.name).unwrap();
        writeln!(output, "  version: '{}'", self.version).unwrap();
        writeln!(output, "  description: |").unwrap();
        writeln!(output, "    Auto-generated by backbone-cli.").unwrap();
        writeln!(output, "    {} entity CRUD endpoints.", model.name).unwrap();
        writeln!(output).unwrap();

        // Servers
        writeln!(output, "servers:").unwrap();
        writeln!(output, "  - url: {}", self.server_url).unwrap();
        writeln!(output, "    description: Development server").unwrap();
        writeln!(output).unwrap();

        // Tags
        writeln!(output, "tags:").unwrap();
        writeln!(output, "  - name: {}", tag).unwrap();
        writeln!(output, "    description: {} management endpoints", model.name).unwrap();
        writeln!(output).unwrap();

        // Paths
        writeln!(output, "paths:").unwrap();

        // Collection endpoints
        writeln!(output, "  {}:", base_path).unwrap();

        // GET - List
        writeln!(output, "    get:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: List {}", pluralize(&model.name)).unwrap();
        writeln!(output, "      description: Get a paginated list of {} with optional filtering and sorting", pluralize(&model.name)).unwrap();
        writeln!(output, "      operationId: list{}", pluralize(&model.name)).unwrap();
        writeln!(output, "      parameters:").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/PageParam'").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/PerPageParam'").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/SortByParam'").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/SortOrderParam'").unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Successful response").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}List'", model.name).unwrap();
        writeln!(output, "        '401':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/Unauthorized'").unwrap();
        writeln!(output).unwrap();

        // POST - Create
        writeln!(output, "    post:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Create {}", model.name).unwrap();
        writeln!(output, "      description: Create a new {}", model.name).unwrap();
        writeln!(output, "      operationId: create{}", model.name).unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              $ref: '#/components/schemas/Create{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '201':").unwrap();
        writeln!(output, "          description: Created").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '400':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/BadRequest'").unwrap();
        writeln!(output, "        '401':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/Unauthorized'").unwrap();
        writeln!(output).unwrap();

        // Single item endpoint
        writeln!(output, "  {}/{{id}}:", base_path).unwrap();
        writeln!(output, "    parameters:").unwrap();
        writeln!(output, "      - $ref: '#/components/parameters/IdParam'").unwrap();
        writeln!(output).unwrap();

        // GET - Get by ID
        writeln!(output, "    get:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Get {} by ID", model.name).unwrap();
        writeln!(output, "      operationId: get{}", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Successful response").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // PUT - Full update
        writeln!(output, "    put:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Update {} (full)", model.name).unwrap();
        writeln!(output, "      operationId: update{}", model.name).unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              $ref: '#/components/schemas/Update{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Updated").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // PATCH - Partial update
        writeln!(output, "    patch:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Update {} (partial)", model.name).unwrap();
        writeln!(output, "      operationId: patch{}", model.name).unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              $ref: '#/components/schemas/Patch{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Updated").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // DELETE - Soft delete
        writeln!(output, "    delete:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Delete {} (soft)", model.name).unwrap();
        writeln!(output, "      operationId: delete{}", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '204':").unwrap();
        writeln!(output, "          description: Deleted").unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // Bulk create
        writeln!(output, "  {}/bulk:", base_path).unwrap();
        writeln!(output, "    post:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Bulk create {}", pluralize(&model.name)).unwrap();
        writeln!(output, "      operationId: bulkCreate{}", pluralize(&model.name)).unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              type: array").unwrap();
        writeln!(output, "              items:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/Create{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '201':").unwrap();
        writeln!(output, "          description: Created").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                type: array").unwrap();
        writeln!(output, "                items:").unwrap();
        writeln!(output, "                  $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output).unwrap();

        // Upsert
        writeln!(output, "  {}/upsert:", base_path).unwrap();
        writeln!(output, "    post:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Upsert {}", model.name).unwrap();
        writeln!(output, "      operationId: upsert{}", model.name).unwrap();
        writeln!(output, "      parameters:").unwrap();
        writeln!(output, "        - name: key_field").unwrap();
        writeln!(output, "          in: query").unwrap();
        writeln!(output, "          schema:").unwrap();
        writeln!(output, "            type: string").unwrap();
        writeln!(output, "        - name: key_value").unwrap();
        writeln!(output, "          in: query").unwrap();
        writeln!(output, "          required: true").unwrap();
        writeln!(output, "          schema:").unwrap();
        writeln!(output, "            type: string").unwrap();
        writeln!(output, "      requestBody:").unwrap();
        writeln!(output, "        required: true").unwrap();
        writeln!(output, "        content:").unwrap();
        writeln!(output, "          application/json:").unwrap();
        writeln!(output, "            schema:").unwrap();
        writeln!(output, "              $ref: '#/components/schemas/Update{}Request'", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Upserted").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output).unwrap();

        // Trash list
        writeln!(output, "  {}/trash:", base_path).unwrap();
        writeln!(output, "    get:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: List deleted {}", pluralize(&model.name)).unwrap();
        writeln!(output, "      operationId: listDeleted{}", pluralize(&model.name)).unwrap();
        writeln!(output, "      parameters:").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/PageParam'").unwrap();
        writeln!(output, "        - $ref: '#/components/parameters/PerPageParam'").unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Successful response").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}List'", model.name).unwrap();
        writeln!(output).unwrap();

        // Restore
        writeln!(output, "  {}/{{id}}/restore:", base_path).unwrap();
        writeln!(output, "    parameters:").unwrap();
        writeln!(output, "      - $ref: '#/components/parameters/IdParam'").unwrap();
        writeln!(output, "    post:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Restore deleted {}", model.name).unwrap();
        writeln!(output, "      operationId: restore{}", model.name).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Restored").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                $ref: '#/components/schemas/{}'", model.name).unwrap();
        writeln!(output, "        '404':").unwrap();
        writeln!(output, "          $ref: '#/components/responses/NotFound'").unwrap();
        writeln!(output).unwrap();

        // Empty trash
        writeln!(output, "  {}/empty:", base_path).unwrap();
        writeln!(output, "    delete:").unwrap();
        writeln!(output, "      tags:").unwrap();
        writeln!(output, "        - {}", tag).unwrap();
        writeln!(output, "      summary: Empty trash for {}", pluralize(&model.name)).unwrap();
        writeln!(output, "      operationId: emptyTrash{}", pluralize(&model.name)).unwrap();
        writeln!(output, "      responses:").unwrap();
        writeln!(output, "        '200':").unwrap();
        writeln!(output, "          description: Trash emptied").unwrap();
        writeln!(output, "          content:").unwrap();
        writeln!(output, "            application/json:").unwrap();
        writeln!(output, "              schema:").unwrap();
        writeln!(output, "                type: object").unwrap();
        writeln!(output, "                properties:").unwrap();
        writeln!(output, "                  deleted_count:").unwrap();
        writeln!(output, "                    type: integer").unwrap();
        writeln!(output).unwrap();

        // Components
        writeln!(output, "components:").unwrap();
        writeln!(output, "  schemas:").unwrap();

        // Model-specific schemas
        self.write_model_schemas(&mut output, model)?;

        // Common schemas (shared)
        self.write_common_schemas(&mut output)?;

        // Security schemes
        writeln!(output, "  securitySchemes:").unwrap();
        writeln!(output, "    bearerAuth:").unwrap();
        writeln!(output, "      type: http").unwrap();
        writeln!(output, "      scheme: bearer").unwrap();
        writeln!(output, "      bearerFormat: JWT").unwrap();
        writeln!(output).unwrap();

        // Global security
        writeln!(output, "security:").unwrap();
        writeln!(output, "  - bearerAuth: []").unwrap();

        Ok(output)
    }
}

impl Default for OpenApiGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for OpenApiGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        if self.split {
            // Generate split files: index.openapi.yaml + one file per model
            self.generate_split_spec(schema, &mut output)?;
        } else {
            // Generate single combined spec to schema/openapi/ directory
            let spec = self.generate_spec(schema)?;
            output.add_file(PathBuf::from("schema/openapi/openapi.yaml"), spec);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "openapi"
    }
}

// Helper functions
use crate::utils::to_snake_case;


fn pluralize(name: &str) -> String {
    if name.ends_with('s') || name.ends_with('x') || name.ends_with("ch") || name.ends_with("sh") {
        format!("{}es", name)
    } else if name.ends_with('y') && !name.ends_with("ay") && !name.ends_with("ey") && !name.ends_with("oy") && !name.ends_with("uy") {
        format!("{}ies", &name[..name.len() - 1])
    } else {
        format!("{}s", name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Field, Model, ModuleSchema};

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");

        schema.models.push(Model {
            name: "User".to_string(),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    ..Default::default()
                },
                Field {
                    name: "email".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Email),
                    ..Default::default()
                },
                Field {
                    name: "name".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
                Field {
                    name: "age".to_string(),
                    type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::Int))),
                    ..Default::default()
                },
                Field {
                    name: "created_at".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::DateTime),
                    ..Default::default()
                },
                Field {
                    name: "updated_at".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::DateTime),
                    ..Default::default()
                },
                Field {
                    name: "deleted_at".to_string(),
                    type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        ResolvedSchema { schema }
    }

    #[test]
    fn test_openapi_generator_creates_spec() {
        let schema = create_test_schema();
        let generator = OpenApiGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("schema/openapi/openapi.yaml")));
    }

    #[test]
    fn test_openapi_contains_all_paths() {
        let schema = create_test_schema();
        let generator = OpenApiGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let spec = output.files.get(&PathBuf::from("schema/openapi/openapi.yaml")).unwrap();

        // Check all 11 endpoints are present
        assert!(spec.contains("/api/v1/users:"));
        assert!(spec.contains("/api/v1/users/{id}:"));
        assert!(spec.contains("/api/v1/users/bulk:"));
        assert!(spec.contains("/api/v1/users/upsert:"));
        assert!(spec.contains("/api/v1/users/trash:"));
        assert!(spec.contains("/api/v1/users/{id}/restore:"));
        assert!(spec.contains("/api/v1/users/empty:"));
    }

    #[test]
    fn test_openapi_contains_schemas() {
        let schema = create_test_schema();
        let generator = OpenApiGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let spec = output.files.get(&PathBuf::from("schema/openapi/openapi.yaml")).unwrap();

        assert!(spec.contains("User:"));
        assert!(spec.contains("CreateUserRequest:"));
        assert!(spec.contains("UpdateUserRequest:"));
        assert!(spec.contains("PatchUserRequest:"));
        assert!(spec.contains("UserList:"));
    }

    #[test]
    fn test_openapi_version() {
        let schema = create_test_schema();
        let generator = OpenApiGenerator::new()
            .with_title("My API")
            .with_version("2.0.0");
        let output = generator.generate(&schema).unwrap();

        let spec = output.files.get(&PathBuf::from("schema/openapi/openapi.yaml")).unwrap();

        assert!(spec.contains("title: My API"));
        assert!(spec.contains("version: '2.0.0'"));
    }
}
