//! Projection generator
//!
//! Generates CQRS projections (read models) from schema.
//! Projections are optimized read-side views updated from domain events.
//!
//! ## CQRS Projections
//!
//! Projections:
//! - Optimized for specific read use cases
//! - Updated asynchronously from domain events
//! - Can be rebuilt from event history
//! - Denormalized for query performance
//!
//! ## Generated Output
//!
//! For each model, generates:
//! - `{model}_projection.rs` - Read model with event handlers
//! - `{model}_projector.rs` - Event handler that updates the projection

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path};
use crate::ast::{Model, PrimitiveType, TypeRef};
use crate::resolver::ResolvedSchema;
use crate::utils::{escape_rust_keyword, to_snake_case};
use std::fmt::Write;
use std::path::PathBuf;

/// Generates CQRS projections from schema
pub struct ProjectionGenerator {
    /// Group generated files by model/domain
    group_by_domain: bool,
}

impl ProjectionGenerator {
    pub fn new() -> Self {
        Self {
            group_by_domain: false,  // Keep flat - only one file per entity
        }
    }

    /// Set whether to group files by domain
    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Get primary key field name
    fn get_pk_field(&self, model: &Model) -> String {
        model.fields.iter()
            .find(|f| f.is_primary_key())
            .map(|f| f.name.clone())
            .unwrap_or_else(|| "id".to_string())
    }

    /// Get primary key type
    fn get_pk_type(&self, model: &Model) -> String {
        model.fields.iter()
            .find(|f| f.is_primary_key())
            .map(|f| self.type_to_rust(&f.type_ref))
            .unwrap_or_else(|| "Uuid".to_string())
    }

    /// Convert TypeRef to Rust type
    fn type_to_rust(&self, type_ref: &TypeRef) -> String {
        match type_ref {
            TypeRef::Primitive(p) => p.rust_type().to_string(),
            TypeRef::Custom(name) => name.clone(),
            TypeRef::Array(inner) => format!("Vec<{}>", self.type_to_rust(inner)),
            TypeRef::Optional(inner) => format!("Option<{}>", self.type_to_rust(inner)),
            TypeRef::Map { key, value } => {
                format!("std::collections::HashMap<{}, {}>",
                    self.type_to_rust(key),
                    self.type_to_rust(value))
            }
            TypeRef::ModuleRef { module, name } => format!("{}::{}", module, name),
        }
    }

    /// Check if a type reference needs a specific primitive type
    fn field_needs_type(&self, type_ref: &TypeRef, target: PrimitiveType) -> bool {
        match type_ref {
            TypeRef::Primitive(p) => *p == target,
            TypeRef::Optional(inner) => self.field_needs_type(inner, target),
            TypeRef::Array(inner) => self.field_needs_type(inner, target),
            TypeRef::Map { key, value } => {
                self.field_needs_type(key, target) || self.field_needs_type(value, target)
            }
            _ => false,
        }
    }

    /// Generate projection read model
    fn generate_projection(&self, model: &Model) -> String {
        let mut output = String::new();
        let name = &model.name;
        let pk_type = self.get_pk_type(model);
        let inner_pk_type = pk_type.trim_start_matches("Option<").trim_end_matches('>');

        writeln!(output, "//! {} Projection (Read Model)", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This is a CQRS projection - an optimized read model for queries.").unwrap();
        writeln!(output, "//! It is updated asynchronously from domain events.").unwrap();
        writeln!(output).unwrap();

        // Check which imports are needed based on field types
        let has_date_field = model.fields.iter().any(|f| {
            self.field_needs_type(&f.type_ref, PrimitiveType::Date)
        });
        let has_time_field = model.fields.iter().any(|f| {
            self.field_needs_type(&f.type_ref, PrimitiveType::Time)
        });
        let has_decimal_field = model.fields.iter().any(|f| {
            self.field_needs_type(&f.type_ref, PrimitiveType::Decimal)
                || self.field_needs_type(&f.type_ref, PrimitiveType::Money)
                || self.field_needs_type(&f.type_ref, PrimitiveType::Percentage)
        });

        // Imports - build chrono imports dynamically
        let mut chrono_imports = vec!["DateTime", "Utc"];
        if has_date_field {
            chrono_imports.push("NaiveDate");
        }
        if has_time_field {
            chrono_imports.push("NaiveTime");
        }
        writeln!(output, "use chrono::{{{}}};", chrono_imports.join(", ")).unwrap();
        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output, "use sqlx::FromRow;").unwrap();
        writeln!(output, "use uuid::Uuid;").unwrap();
        if has_decimal_field {
            writeln!(output, "use rust_decimal::Decimal;").unwrap();
        }
        writeln!(output).unwrap();

        // Projection struct
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// PROJECTION (READ MODEL)").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// {} read model optimized for queries", name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// This projection is denormalized for fast reads.").unwrap();
        writeln!(output, "/// It is updated when domain events are published.").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]").unwrap();
        writeln!(output, "pub struct {}Projection {{", name).unwrap();

        // Include all entity fields
        for field in &model.fields {
            let rust_type = self.type_to_rust(&field.type_ref);
            let field_name = escape_rust_keyword(&field.name);
            writeln!(output, "    pub {}: {},", field_name, rust_type).unwrap();
        }

        // Add projection metadata
        writeln!(output).unwrap();
        writeln!(output, "    // Projection metadata").unwrap();
        writeln!(output, "    /// Version of the projection (for optimistic locking)").unwrap();
        writeln!(output, "    pub projection_version: i64,").unwrap();
        writeln!(output, "    /// Last event sequence number applied").unwrap();
        writeln!(output, "    pub last_event_sequence: i64,").unwrap();
        writeln!(output, "    /// When this projection was last updated").unwrap();
        writeln!(output, "    pub projection_updated_at: DateTime<Utc>,").unwrap();

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Projection implementation
        writeln!(output, "impl {}Projection {{", name).unwrap();
        writeln!(output, "    /// Create a new projection from entity data").unwrap();
        writeln!(output, "    pub fn new(").unwrap();

        let mut first = true;
        for field in &model.fields {
            if !first {
                writeln!(output, ",").unwrap();
            }
            first = false;
            let rust_type = self.type_to_rust(&field.type_ref);
            let field_name = escape_rust_keyword(&field.name);
            write!(output, "        {}: {}", field_name, rust_type).unwrap();
        }

        writeln!(output).unwrap();
        writeln!(output, "    ) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();

        for field in &model.fields {
            let field_name = escape_rust_keyword(&field.name);
            writeln!(output, "            {},", field_name).unwrap();
        }

        writeln!(output, "            projection_version: 1,").unwrap();
        writeln!(output, "            last_event_sequence: 0,").unwrap();
        writeln!(output, "            projection_updated_at: Utc::now(),").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Get the projection ID").unwrap();
        writeln!(output, "    pub fn id(&self) -> &{} {{", inner_pk_type).unwrap();
        let pk_field = escape_rust_keyword(&self.get_pk_field(model));
        if pk_type.starts_with("Option<") {
            writeln!(output, "        self.{}.as_ref().expect(\"Projection must have ID\")", pk_field).unwrap();
        } else {
            writeln!(output, "        &self.{}", pk_field).unwrap();
        }
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Update projection version after applying event").unwrap();
        writeln!(output, "    pub fn apply_event(&mut self, event_sequence: i64) {{").unwrap();
        writeln!(output, "        self.projection_version += 1;").unwrap();
        writeln!(output, "        self.last_event_sequence = event_sequence;").unwrap();
        writeln!(output, "        self.projection_updated_at = Utc::now();").unwrap();
        writeln!(output, "    }}").unwrap();

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Summary projection (for list views)
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// SUMMARY PROJECTION (LIST VIEW)").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Summary view of {} for list displays", name).unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]").unwrap();
        writeln!(output, "pub struct {}Summary {{", name).unwrap();

        // Include only key fields for summary
        for field in &model.fields {
            if field.is_primary_key() ||
               field.name.ends_with("_name") ||
               field.name == "name" ||
               field.name == "title" ||
               field.name == "email" ||
               field.name == "status" ||
               field.name == "created_at" {
                let rust_type = self.type_to_rust(&field.type_ref);
                let field_name = escape_rust_keyword(&field.name);
                writeln!(output, "    pub {}: {},", field_name, rust_type).unwrap();
            }
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Custom projections section
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// CUSTOM PROJECTIONS").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM PROJECTIONS START >>>").unwrap();
        writeln!(output, "// Add custom read models here for specific query use cases").unwrap();
        writeln!(output, "// Example:").unwrap();
        writeln!(output, "//").unwrap();
        writeln!(output, "// #[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "// pub struct {}Dashboard {{", name).unwrap();
        writeln!(output, "//     pub id: Uuid,").unwrap();
        writeln!(output, "//     pub key_metric: i64,").unwrap();
        writeln!(output, "// }}").unwrap();
        writeln!(output, "// <<< CUSTOM PROJECTIONS END >>>").unwrap();

        output
    }

    /// Generate projector (event handler)
    fn generate_projector(&self, model: &Model) -> String {
        let mut output = String::new();
        let name = &model.name;

        writeln!(output, "//! {} Projector (Event Handler)", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This projector listens to domain events and updates the projection.").unwrap();
        writeln!(output).unwrap();

        // Imports
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use anyhow::Result;").unwrap();
        writeln!(output, "use async_trait::async_trait;").unwrap();
        writeln!(output, "use chrono::Utc;").unwrap();
        writeln!(output, "use backbone_core::projection::Projector;").unwrap();
        writeln!(output).unwrap();
        // Use crate path when grouped, super path when flat
        if self.group_by_domain {
            writeln!(output, "use crate::application::projections::{}::{}Projection;", to_snake_case(name), name).unwrap();
        } else {
            writeln!(output, "use super::{}Projection;", name).unwrap();
        }
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output, "use crate::domain::events::{{").unwrap();
        writeln!(output, "    {}CreatedEvent, {}UpdatedEvent, {}DeletedEvent,", name, name, name).unwrap();
        writeln!(output, "}};").unwrap();
        writeln!(output).unwrap();

        // Event handler trait
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// EVENT HANDLER TRAIT").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Trait for handling {} domain events", name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// All handler methods receive the event sequence number for tracking").unwrap();
        writeln!(output, "/// which events have been processed by the projector.").unwrap();
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "pub trait {}EventHandler: Send + Sync {{", name).unwrap();
        writeln!(output, "    /// Handle entity created event").unwrap();
        writeln!(output, "    async fn on_created(&self, event: {}CreatedEvent, sequence: i64) -> Result<()>;", name).unwrap();
        writeln!(output, "    /// Handle entity updated event").unwrap();
        writeln!(output, "    async fn on_updated(&self, event: {}UpdatedEvent, sequence: i64) -> Result<()>;", name).unwrap();
        writeln!(output, "    /// Handle entity deleted event").unwrap();
        writeln!(output, "    async fn on_deleted(&self, event: {}DeletedEvent, sequence: i64) -> Result<()>;", name).unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Projection repository trait
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// PROJECTION REPOSITORY").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Repository for {} projections", name).unwrap();
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "pub trait {}ProjectionRepository: Send + Sync {{", name).unwrap();
        writeln!(output, "    async fn save(&self, projection: &{}Projection) -> Result<()>;", name).unwrap();
        writeln!(output, "    async fn find_by_id(&self, id: uuid::Uuid) -> Result<Option<{}Projection>>;", name).unwrap();
        writeln!(output, "    async fn delete(&self, id: uuid::Uuid) -> Result<()>;").unwrap();
        writeln!(output, "    async fn rebuild_all(&self) -> Result<u64>;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Projector struct
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// PROJECTOR").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Projector that updates {} projection from events", name).unwrap();
        writeln!(output, "pub struct {}Projector<R: {}ProjectionRepository> {{", name, name).unwrap();
        writeln!(output, "    repository: Arc<R>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl<R: {}ProjectionRepository> {}Projector<R> {{", name, name).unwrap();
        writeln!(output, "    /// Create a new projector").unwrap();
        writeln!(output, "    pub fn new(repository: Arc<R>) -> Self {{").unwrap();
        writeln!(output, "        Self {{ repository }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Rebuild all projections from event history").unwrap();
        writeln!(output, "    pub async fn rebuild(&self) -> Result<u64> {{").unwrap();
        writeln!(output, "        self.repository.rebuild_all().await").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Process a stored event from the event store").unwrap();
        writeln!(output, "    ///").unwrap();
        writeln!(output, "    /// This method dispatches the event to the appropriate handler based on event type.").unwrap();
        writeln!(output, "    /// Returns Ok(true) if the event was processed, Ok(false) if it was skipped.").unwrap();
        writeln!(output, "    pub async fn process_stored_event(&self, event: &crate::infrastructure::event_store::StoredEvent) -> Result<bool>").unwrap();
        writeln!(output, "    where").unwrap();
        writeln!(output, "        Self: {}EventHandler,", name).unwrap();
        writeln!(output, "    {{").unwrap();
        writeln!(output, "        let sequence = event.sequence;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        match event.event_type.as_str() {{").unwrap();
        writeln!(output, "            \"{}CreatedEvent\" => {{", name).unwrap();
        writeln!(output, "                let created: {}CreatedEvent = serde_json::from_value(event.payload.clone())?;", name).unwrap();
        writeln!(output, "                self.on_created(created, sequence).await?;").unwrap();
        writeln!(output, "                Ok(true)").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "            \"{}UpdatedEvent\" => {{", name).unwrap();
        writeln!(output, "                let updated: {}UpdatedEvent = serde_json::from_value(event.payload.clone())?;", name).unwrap();
        writeln!(output, "                self.on_updated(updated, sequence).await?;").unwrap();
        writeln!(output, "                Ok(true)").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "            \"{}DeletedEvent\" => {{", name).unwrap();
        writeln!(output, "                let deleted: {}DeletedEvent = serde_json::from_value(event.payload.clone())?;", name).unwrap();
        writeln!(output, "                self.on_deleted(deleted, sequence).await?;").unwrap();
        writeln!(output, "                Ok(true)").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "            _ => Ok(false), // Event type not handled by this projector").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // EventHandler implementation
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "impl<R: {}ProjectionRepository> {}EventHandler for {}Projector<R> {{", name, name, name).unwrap();
        writeln!(output).unwrap();

        // on_created
        writeln!(output, "    async fn on_created(&self, event: {}CreatedEvent, sequence: i64) -> Result<()> {{", name).unwrap();
        writeln!(output, "        let mut projection = {}Projection::new(", name).unwrap();

        let mut first = true;
        for field in &model.fields {
            if !first {
                writeln!(output, ",").unwrap();
            }
            first = false;
            let field_name = escape_rust_keyword(&field.name);
            write!(output, "            event.{}", field_name).unwrap();
        }

        writeln!(output).unwrap();
        writeln!(output, "        );").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Track the event sequence for this projection").unwrap();
        writeln!(output, "        projection.apply_event(sequence);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        self.repository.save(&projection).await").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // on_updated
        writeln!(output, "    async fn on_updated(&self, event: {}UpdatedEvent, sequence: i64) -> Result<()> {{", name).unwrap();
        writeln!(output, "        if let Some(mut projection) = self.repository.find_by_id(event.id).await? {{").unwrap();
        writeln!(output, "            // Apply updates from event").unwrap();

        for field in &model.fields {
            if field.is_primary_key() || field.name == "created_at" {
                continue;
            }
            let field_name = escape_rust_keyword(&field.name);
            writeln!(output, "            projection.{} = event.{};", field_name, field_name).unwrap();
        }

        writeln!(output, "            // Track the event sequence for this projection").unwrap();
        writeln!(output, "            projection.apply_event(sequence);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "            self.repository.save(&projection).await?;").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(())").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        // on_deleted
        writeln!(output, "    async fn on_deleted(&self, event: {}DeletedEvent, _sequence: i64) -> Result<()> {{", name).unwrap();
        writeln!(output, "        self.repository.delete(event.id).await").unwrap();
        writeln!(output, "    }}").unwrap();

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Phase 1 Category C: implement backbone_core::projection::Projector.
        // The event type here is the aggregate event produced by this module's
        // event generator (e.g. OrderEvent / CrudEvent<Order>).
        // Use a marker enum variant dispatch via process_stored_event for now;
        // full integration happens when the module wires up the event bus.
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// BACKBONE PROJECTOR TRAIT").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "/// Implements [`backbone_core::projection::Projector`] for [`{}Projector`].", name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// The `Evt` parameter is `serde_json::Value` here so the projector can be").unwrap();
        writeln!(output, "/// driven generically from the event store.  Swap for a concrete event type").unwrap();
        writeln!(output, "/// (e.g. `{}Event`) in the CUSTOM section when the event bus is wired up.", name).unwrap();
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "impl<R: {n}ProjectionRepository> Projector<{n}, serde_json::Value> for {n}Projector<R> {{", n = name).unwrap();
        writeln!(output, "    async fn project(&self, event: serde_json::Value, sequence: i64) -> anyhow::Result<()> {{").unwrap();
        writeln!(output, "        let stored = crate::infrastructure::event_store::StoredEvent {{").unwrap();
        writeln!(output, "            event_type: event[\"event_type\"].as_str().unwrap_or(\"\").to_string(),").unwrap();
        writeln!(output, "            payload: event,").unwrap();
        writeln!(output, "            sequence,").unwrap();
        writeln!(output, "            ..Default::default()").unwrap();
        writeln!(output, "        }};").unwrap();
        writeln!(output, "        let _ = self.process_stored_event(&stored).await?;").unwrap();
        writeln!(output, "        Ok(())").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    async fn rebuild(&self) -> anyhow::Result<u64> {{").unwrap();
        writeln!(output, "        Ok(self.repository.rebuild_all().await?)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Custom handlers section
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output, "// CUSTOM EVENT HANDLERS").unwrap();
        writeln!(output, "// ============================================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM HANDLERS START >>>").unwrap();
        writeln!(output, "// Add custom event handlers here").unwrap();
        writeln!(output, "// <<< CUSTOM HANDLERS END >>>").unwrap();

        output
    }

    /// Generate module file
    fn generate_mod(&self, models: &[&Model], group_by_domain: bool) -> String {
        let mut output = String::new();

        writeln!(output, "//! CQRS Projections (Read Models)").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Projections are optimized read-side views of domain entities.").unwrap();
        writeln!(output, "//! They are updated asynchronously from domain events.").unwrap();
        writeln!(output).unwrap();

        for model in models {
            let snake_name = to_snake_case(&model.name);
            if group_by_domain {
                writeln!(output, "mod {};", snake_name).unwrap();
            } else {
                writeln!(output, "mod {}_projection;", snake_name).unwrap();
                writeln!(output, "mod {}_projector;", snake_name).unwrap();
            }
        }

        writeln!(output).unwrap();
        writeln!(output, "// Re-exports").unwrap();
        for model in models {
            let snake_name = to_snake_case(&model.name);
            let name = &model.name;
            if group_by_domain {
                writeln!(output, "pub use {}::{{{}Projection, {}Summary, {}EventHandler, {}ProjectionRepository, {}Projector}};",
                    snake_name, name, name, name, name, name).unwrap();
            } else {
                writeln!(output, "pub use {}_projection::{{{}Projection, {}Summary}};",
                    snake_name, name, name).unwrap();
                writeln!(output, "pub use {}_projector::{{{}EventHandler, {}ProjectionRepository, {}Projector}};",
                    snake_name, name, name, name).unwrap();
            }
        }

        output
    }
}

impl Default for ProjectionGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for ProjectionGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        if schema.schema.models.is_empty() {
            return Ok(output);
        }

        let models: Vec<&Model> = schema.schema.models.iter().collect();

        for model in &models {
            let snake_name = to_snake_case(&model.name);

            // Generate projection
            let proj_file_name = format!("{}_projection.rs", snake_name);
            let proj_path = build_generated_path("src/infrastructure/projections", &model.name, &proj_file_name, self.group_by_domain);
            output.add_file(proj_path, self.generate_projection(model));

            // Generate projector
            let projr_file_name = format!("{}_projector.rs", snake_name);
            let projr_path = build_generated_path("src/infrastructure/projections", &model.name, &projr_file_name, self.group_by_domain);
            output.add_file(projr_path, self.generate_projector(model));

            // Generate subdirectory mod.rs if grouping by domain
            if self.group_by_domain {
                let mod_path = PathBuf::from(format!("src/infrastructure/projections/{}/mod.rs", snake_name));
                let sub_mod_content = format!(
                    "//! {} module\n//!\n//! Auto-generated by metaphor-schema. Do not edit manually.\n\npub mod {}_projection;\npub mod {}_projector;\n\npub use {}_projection::*;\npub use {}_projector::*;\n",
                    model.name, snake_name, snake_name, snake_name, snake_name
                );
                output.add_file(mod_path, sub_mod_content);
            }
        }

        // Generate mod.rs
        output.add_file(
            PathBuf::from("src/infrastructure/projections/mod.rs"),
            self.generate_mod(&models, self.group_by_domain),
        );

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "projection"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType};

    fn create_test_model() -> Model {
        let mut model = Model::new("User");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::Uuid))),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "email".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Email),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "name".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "status".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "created_at".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_projection_generator_creates_files() {
        let schema = create_test_schema();
        let generator = ProjectionGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/projections/user_projection.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/projections/user_projector.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/projections/mod.rs")));
    }

    #[test]
    fn test_projection_has_metadata() {
        let schema = create_test_schema();
        let generator = ProjectionGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/infrastructure/projections/user_projection.rs")).unwrap();

        assert!(content.contains("projection_version"));
        assert!(content.contains("last_event_sequence"));
        assert!(content.contains("projection_updated_at"));
    }

    #[test]
    fn test_projector_has_event_handlers() {
        let schema = create_test_schema();
        let generator = ProjectionGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/infrastructure/projections/user_projector.rs")).unwrap();

        assert!(content.contains("on_created"));
        assert!(content.contains("on_updated"));
        assert!(content.contains("on_deleted"));
        assert!(content.contains("UserEventHandler"));
    }

    #[test]
    fn test_projection_has_summary() {
        let schema = create_test_schema();
        let generator = ProjectionGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/infrastructure/projections/user_projection.rs")).unwrap();

        assert!(content.contains("UserSummary"));
    }
}
