//! Repository generator
//!
//! Generates PostgreSQL repository implementations for models using backbone-orm.
//! Aligns with backbone-orm's `DatabaseOperations<T>` trait and `Entity` trait.
//!
//! ## Generated Output
//!
//! For each model, generates:
//! 1. `Entity` trait implementation in domain layer
//! 2. Extended repository with additional query methods
//! 3. Common filter types for query building

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::{EnumDef, Field, Model, PrimitiveType, TypeRef};
use crate::resolver::ResolvedSchema;
use std::collections::HashSet;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates repository implementations from schema
pub struct RepositoryGenerator {
    /// Group generated files by model/domain
    group_by_domain: bool,
}

impl RepositoryGenerator {
    pub fn new() -> Self {
        Self {
            group_by_domain: false,  // Keep flat - only one file per entity
        }
    }

    /// Set whether to group files by domain
    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Get the set of all enum type names defined in the schema
    fn get_enum_type_names(&self, schema_enums: &[EnumDef]) -> HashSet<String> {
        schema_enums.iter().map(|e| e.name.clone()).collect()
    }

    /// Get the PostgreSQL enum type name for a field (snake_case of the enum name)
    /// Returns None if the field is not an enum type
    fn get_enum_column_type(&self, field: &Field, enum_names: &HashSet<String>) -> Option<String> {
        match &field.type_ref {
            TypeRef::Custom(type_name) => {
                if enum_names.contains(type_name) {
                    // Convert PascalCase enum name to snake_case PostgreSQL type
                    Some(to_snake_case(type_name))
                } else {
                    None
                }
            }
            TypeRef::Optional(inner) => {
                if let TypeRef::Custom(type_name) = inner.as_ref() {
                    if enum_names.contains(type_name) {
                        Some(to_snake_case(type_name))
                    } else {
                        None
                    }
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    /// Get the PostgreSQL type cast for a field based on its primitive type.
    /// Returns the cast suffix (e.g., "date", "timestamptz", "numeric") or None.
    fn get_primitive_pg_cast(&self, field: &Field) -> Option<&'static str> {
        let primitive = match &field.type_ref {
            TypeRef::Primitive(p) => Some(p),
            TypeRef::Optional(inner) => match inner.as_ref() {
                TypeRef::Primitive(p) => Some(p),
                _ => None,
            },
            _ => None,
        };
        primitive.and_then(|p| match p {
            PrimitiveType::Date => Some("date"),
            PrimitiveType::DateTime | PrimitiveType::Timestamp => Some("timestamptz"),
            PrimitiveType::Time => Some("time"),
            PrimitiveType::Duration => Some("interval"),
            PrimitiveType::Decimal | PrimitiveType::Money | PrimitiveType::Percentage => Some("numeric"),
            _ => None,
        })
    }

    /// Generate repository using newtype + Deref over `GenericCrudRepository`.
    ///
    /// Emits only entity-specific methods (unique-field finders, filtered listings,
    /// partial_update).  All standard CRUD methods come free via the `Deref` impl
    /// onto `backbone_orm::GenericCrudRepository<T, D>`.
    fn generate_repository(&self, model: &Model, schema: &crate::ast::ModuleSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let name = &model.name;
        let snake_name = to_snake_case(name);
        let table_name = model.collection_name();
        let has_soft_delete = model.has_soft_delete();
        let delete_mode = if has_soft_delete { "SoftDelete" } else { "HardDelete" };

        // ── Header ────────────────────────────────────────────────────────────
        writeln!(output, "//! Repository for {name} entities").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Thin newtype over `backbone_orm::GenericCrudRepository<{name}, backbone_orm::{delete_mode}>`.").unwrap();
        writeln!(output, "//! All standard CRUD methods are available via `Deref`.").unwrap();
        writeln!(output).unwrap();

        // ── Imports ───────────────────────────────────────────────────────────
        writeln!(output, "use anyhow::Result;").unwrap();
        writeln!(output, "use sqlx::PgPool;").unwrap();

        // Add Uuid import if any unique non-PK field uses Uuid type
        let needs_uuid = model.fields.iter().any(|f| {
            if !f.is_unique() || f.is_primary_key() { return false; }
            match &f.type_ref {
                TypeRef::Primitive(PrimitiveType::Uuid) => true,
                TypeRef::Optional(inner) => matches!(inner.as_ref(), TypeRef::Primitive(PrimitiveType::Uuid)),
                _ => false,
            }
        });
        if needs_uuid {
            writeln!(output, "use uuid::Uuid;").unwrap();
        }

        writeln!(output).unwrap();

        // Collect enum types needed for find_by_* parameters
        let enum_names = self.get_enum_type_names(&schema.enums);
        let mut enum_import_set: std::collections::HashSet<String> = std::collections::HashSet::new();
        model.fields.iter()
            .filter(|f| f.is_unique() && !f.is_primary_key())
            .for_each(|f| {
                match &f.type_ref {
                    TypeRef::Custom(type_name) if enum_names.contains(type_name) => {
                        enum_import_set.insert(type_name.clone());
                    }
                    TypeRef::Optional(inner) => {
                        if let TypeRef::Custom(type_name) = inner.as_ref() {
                            if enum_names.contains(type_name) {
                                enum_import_set.insert(type_name.clone());
                            }
                        }
                    }
                    _ => {}
                }
            });
        let mut enum_imports: Vec<String> = enum_import_set.into_iter().collect();
        enum_imports.sort();

        if enum_imports.is_empty() {
            writeln!(output, "use crate::domain::entity::{name};").unwrap();
        } else {
            let imports: Vec<String> = std::iter::once(name.clone()).chain(enum_imports).collect();
            writeln!(output, "use crate::domain::entity::{{{}}};", imports.join(", ")).unwrap();
        }
        writeln!(output).unwrap();

        // ── Table name constant ───────────────────────────────────────────────
        writeln!(output, "/// Table name for {name} entities").unwrap();
        writeln!(output, "pub const TABLE_NAME: &str = \"{table_name}\";").unwrap();
        writeln!(output).unwrap();

        // ── Newtype struct ────────────────────────────────────────────────────
        writeln!(output, "/// Repository for {name} entities.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// All standard CRUD, soft-delete, pagination, and bulk methods are").unwrap();
        writeln!(output, "/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.").unwrap();
        writeln!(output, "pub struct {name}Repository(").unwrap();
        writeln!(output, "    backbone_orm::GenericCrudRepository<{name}, backbone_orm::{delete_mode}>,").unwrap();
        writeln!(output, ");").unwrap();
        writeln!(output).unwrap();

        // ── Deref impl ────────────────────────────────────────────────────────
        writeln!(output, "impl std::ops::Deref for {name}Repository {{").unwrap();
        writeln!(output, "    type Target = backbone_orm::GenericCrudRepository<{name}, backbone_orm::{delete_mode}>;").unwrap();
        writeln!(output, "    fn deref(&self) -> &Self::Target {{ &self.0 }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // ── Constructor ───────────────────────────────────────────────────────
        writeln!(output, "impl {name}Repository {{").unwrap();
        writeln!(output, "    /// Create a new repository instance.").unwrap();
        writeln!(output, "    pub fn new(pool: PgPool) -> Self {{").unwrap();
        writeln!(output, "        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // ── Entity-specific methods (unique-field finders only) ──────────────
        // list_paginated_filtered, list_deleted_filtered: provided by GenericCrudRepository
        // partial_update: provided by GenericCrudService
        let unique_fields: Vec<&Field> = model.fields.iter()
            .filter(|f| f.is_unique() && !f.is_primary_key())
            .collect();

        if !unique_fields.is_empty() {
            writeln!(output, "impl {name}Repository {{").unwrap();

            // find_by_<unique_field> — 2-line wrapper over GenericCrudRepository helpers
            for field in &unique_fields {
                let fname = &field.name;
                let sd_note = if has_soft_delete { " (excludes soft-deleted)" } else { "" };
                writeln!(output, "    /// Find {snake_name} by {fname}{sd_note}").unwrap();

                let is_uuid_type = matches!(
                    &field.type_ref,
                    TypeRef::Primitive(PrimitiveType::Uuid)
                ) || matches!(
                    &field.type_ref,
                    TypeRef::Optional(inner) if matches!(inner.as_ref(), TypeRef::Primitive(PrimitiveType::Uuid))
                );
                let is_text_type = matches!(
                    &field.type_ref,
                    TypeRef::Primitive(PrimitiveType::String)
                    | TypeRef::Primitive(PrimitiveType::Email)
                    | TypeRef::Primitive(PrimitiveType::Slug)
                    | TypeRef::Primitive(PrimitiveType::Url)
                );

                if is_uuid_type {
                    writeln!(output, "    pub async fn find_by_{fname}(&self, {fname}: uuid::Uuid) -> Result<Option<{name}>> {{").unwrap();
                    writeln!(output, "        self.find_by_uuid_field(\"{fname}\", {fname}).await").unwrap();
                    writeln!(output, "    }}").unwrap();
                } else if is_text_type {
                    writeln!(output, "    pub async fn find_by_{fname}(&self, {fname}: &str) -> Result<Option<{name}>> {{").unwrap();
                    writeln!(output, "        self.find_by_text_field(\"{fname}\", {fname}).await").unwrap();
                    writeln!(output, "    }}").unwrap();
                } else {
                    // Enum or other custom type: keep explicit sqlx query
                    let param_type = self.type_to_param_type(&field.type_ref);
                    let sd_cond = if has_soft_delete { " AND metadata->>'deleted_at' IS NULL" } else { "" };
                    writeln!(output, "    pub async fn find_by_{fname}(&self, {fname}: {param_type}) -> Result<Option<{name}>> {{").unwrap();
                    writeln!(output, "        let query = format!(\"SELECT * FROM {{}} WHERE {fname} = $1{sd_cond}\", self.table_name());").unwrap();
                    writeln!(output, "        let result = sqlx::query_as::<_, {name}>(&query)").unwrap();
                    writeln!(output, "            .bind({fname})").unwrap();
                    writeln!(output, "            .fetch_optional(self.pool())").unwrap();
                    writeln!(output, "            .await?;").unwrap();
                    writeln!(output, "        Ok(result)").unwrap();
                    writeln!(output, "    }}").unwrap();
                }
                writeln!(output).unwrap();
            }

            // exists_by_<unique_field>
            for field in &unique_fields {
                let fname = &field.name;
                let sd_note = if has_soft_delete { " (excludes soft-deleted)" } else { "" };
                writeln!(output, "    /// Check if {snake_name} exists by {fname}{sd_note}").unwrap();

                let is_uuid_type = matches!(
                    &field.type_ref,
                    TypeRef::Primitive(PrimitiveType::Uuid)
                ) || matches!(
                    &field.type_ref,
                    TypeRef::Optional(inner) if matches!(inner.as_ref(), TypeRef::Primitive(PrimitiveType::Uuid))
                );
                let is_text_type = matches!(
                    &field.type_ref,
                    TypeRef::Primitive(PrimitiveType::String)
                    | TypeRef::Primitive(PrimitiveType::Email)
                    | TypeRef::Primitive(PrimitiveType::Slug)
                    | TypeRef::Primitive(PrimitiveType::Url)
                );

                if is_uuid_type {
                    writeln!(output, "    pub async fn exists_by_{fname}(&self, {fname}: uuid::Uuid) -> Result<bool> {{").unwrap();
                    writeln!(output, "        self.exists_by_uuid_field(\"{fname}\", {fname}).await").unwrap();
                    writeln!(output, "    }}").unwrap();
                } else if is_text_type {
                    writeln!(output, "    pub async fn exists_by_{fname}(&self, {fname}: &str) -> Result<bool> {{").unwrap();
                    writeln!(output, "        self.exists_by_text_field(\"{fname}\", {fname}).await").unwrap();
                    writeln!(output, "    }}").unwrap();
                } else {
                    // Enum or other custom type: keep explicit sqlx query
                    let param_type = self.type_to_param_type(&field.type_ref);
                    let sd_cond = if has_soft_delete { " AND metadata->>'deleted_at' IS NULL" } else { "" };
                    writeln!(output, "    pub async fn exists_by_{fname}(&self, {fname}: {param_type}) -> Result<bool> {{").unwrap();
                    writeln!(output, "        let query = format!(\"SELECT 1 FROM {{}} WHERE {fname} = $1{sd_cond} LIMIT 1\", self.table_name());").unwrap();
                    writeln!(output, "        let result = sqlx::query_scalar::<_, i32>(&query)").unwrap();
                    writeln!(output, "            .bind({fname})").unwrap();
                    writeln!(output, "            .fetch_optional(self.pool())").unwrap();
                    writeln!(output, "            .await?;").unwrap();
                    writeln!(output, "        Ok(result.is_some())").unwrap();
                    writeln!(output, "    }}").unwrap();
                }
                writeln!(output).unwrap();
            }

            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();
        }

        // ── CrudRepository<T> trait impl via macro ────────────────────────────
        let variant = if has_soft_delete { "soft_delete" } else { "no_soft_delete" };
        writeln!(output, "backbone_core::impl_crud_repository!({name}Repository, {name}, {variant});").unwrap();

        Ok(output)
    }

    /// Generate partial_update method for dynamic field updates
    fn generate_partial_update_method(&self, output: &mut String, model: &Model, enum_names: &HashSet<String>, has_soft_delete: bool) -> Result<(), GenerateError> {
        let name = &model.name;
        let snake_name = to_snake_case(name);

        // Get updatable fields (exclude primary key, created_at, and auto fields)
        let updatable_fields: Vec<&Field> = model.fields.iter()
            .filter(|f| {
                !f.is_primary_key()
                && f.name != "id"
                && f.name != "created_at"
                && !f.has_attribute("auto")
            })
            .collect();

        writeln!(output).unwrap();
        writeln!(output, "    /// Partial update {} with specific fields", snake_name).unwrap();
        writeln!(output, "    ///").unwrap();
        writeln!(output, "    /// Updates only the fields present in the HashMap.").unwrap();
        writeln!(output, "    /// Field names must match database column names.").unwrap();
        writeln!(output, "    pub async fn partial_update(").unwrap();
        writeln!(output, "        &self,").unwrap();
        writeln!(output, "        id: &str,").unwrap();
        writeln!(output, "        fields: std::collections::HashMap<String, serde_json::Value>,").unwrap();
        writeln!(output, "    ) -> Result<Option<{}>> {{", name).unwrap();
        writeln!(output, "        if fields.is_empty() {{").unwrap();
        writeln!(output, "            return self.find_by_id(id).await;").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output).unwrap();

        // Build list of allowed fields
        writeln!(output, "        // Allowed fields for partial update").unwrap();
        writeln!(output, "        let allowed_fields: std::collections::HashSet<&str> = [").unwrap();
        for field in &updatable_fields {
            writeln!(output, "            \"{}\",", field.name).unwrap();
        }
        writeln!(output, "        ].into_iter().collect();").unwrap();
        writeln!(output).unwrap();

        // Build a unified cast map: field_name -> PostgreSQL type cast
        // Collects enum, UUID, date/time, and numeric fields that need explicit casting
        let mut cast_fields: Vec<(&str, String)> = Vec::new();

        // Enum fields
        for field in &updatable_fields {
            if let Some(pg_type) = self.get_enum_column_type(field, enum_names) {
                cast_fields.push((&field.name, pg_type));
            }
        }

        // UUID fields (name ending in _id, excluding "id" itself)
        for field in &updatable_fields {
            let is_uuid_type = match &field.type_ref {
                TypeRef::Primitive(PrimitiveType::Uuid) => true,
                TypeRef::Optional(inner) => {
                    matches!(inner.as_ref(), TypeRef::Primitive(PrimitiveType::Uuid))
                }
                _ => false,
            };
            if field.name != "id" && field.name.ends_with("_id") && is_uuid_type {
                cast_fields.push((&field.name, "uuid".to_string()));
            }
        }

        // Date/time and numeric fields
        for field in &updatable_fields {
            if let Some(pg_cast) = self.get_primitive_pg_cast(field) {
                cast_fields.push((&field.name, pg_cast.to_string()));
            }
        }

        let has_cast_fields = !cast_fields.is_empty();
        if has_cast_fields {
            writeln!(output, "        // Fields that need PostgreSQL type casting (enum, uuid, date, numeric)").unwrap();
            writeln!(output, "        let cast_fields: std::collections::HashMap<&str, &str> = [").unwrap();
            for (field_name, pg_type) in &cast_fields {
                writeln!(output, "            (\"{}\", \"{}\"),", field_name, pg_type).unwrap();
            }
            writeln!(output, "        ].into_iter().collect();").unwrap();
            writeln!(output).unwrap();
        }

        writeln!(output, "        // Build SET clause dynamically").unwrap();
        writeln!(output, "        let mut set_parts: Vec<String> = Vec::new();").unwrap();
        writeln!(output, "        let mut param_values: Vec<serde_json::Value> = Vec::new();").unwrap();
        writeln!(output, "        let mut param_idx = 1usize;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        for (field_name, value) in &fields {{").unwrap();
        writeln!(output, "            if allowed_fields.contains(field_name.as_str()) {{").unwrap();

        // Generate casting logic
        if has_cast_fields {
            writeln!(output, "                // Apply PostgreSQL type cast if field requires it").unwrap();
            writeln!(output, "                if let Some(pg_type) = cast_fields.get(field_name.as_str()) {{").unwrap();
            writeln!(output, "                    set_parts.push(format!(\"{{}} = ${{}}::{{}}\", field_name, param_idx, pg_type));").unwrap();
            writeln!(output, "                }} else {{").unwrap();
            writeln!(output, "                    set_parts.push(format!(\"{{}} = ${{}}\", field_name, param_idx));").unwrap();
            writeln!(output, "                }}").unwrap();
        } else {
            writeln!(output, "                set_parts.push(format!(\"{{}} = ${{}}\", field_name, param_idx));").unwrap();
        }

        writeln!(output, "                param_values.push(value.clone());").unwrap();
        writeln!(output, "                param_idx += 1;").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        if set_parts.is_empty() {{").unwrap();
        writeln!(output, "            return self.find_by_id(id).await;").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Build and execute query").unwrap();
        if has_soft_delete {
            writeln!(output, "        let query = format!(").unwrap();
            writeln!(output, "            \"UPDATE {{}} SET {{}} WHERE id = ${{}}::uuid AND metadata->>'deleted_at' IS NULL RETURNING *\",").unwrap();
            writeln!(output, "            self.table_name(),").unwrap();
            writeln!(output, "            set_parts.join(\", \"),").unwrap();
            writeln!(output, "            param_idx").unwrap();
            writeln!(output, "        );").unwrap();
        } else {
            writeln!(output, "        let query = format!(").unwrap();
            writeln!(output, "            \"UPDATE {{}} SET {{}} WHERE id = ${{}} RETURNING *\",").unwrap();
            writeln!(output, "            self.table_name(),").unwrap();
            writeln!(output, "            set_parts.join(\", \"),").unwrap();
            writeln!(output, "            param_idx").unwrap();
            writeln!(output, "        );").unwrap();
        }
        writeln!(output).unwrap();
        writeln!(output, "        // Build sqlx query with dynamic bindings").unwrap();
        writeln!(output, "        let mut sqlx_query = sqlx::query_as::<_, {}>(&query);", name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Bind each value based on its JSON type").unwrap();
        writeln!(output, "        for value in param_values {{").unwrap();
        writeln!(output, "            sqlx_query = match value {{").unwrap();
        writeln!(output, "                serde_json::Value::String(s) => sqlx_query.bind(s),").unwrap();
        writeln!(output, "                serde_json::Value::Number(n) => {{").unwrap();
        writeln!(output, "                    if let Some(i) = n.as_i64() {{").unwrap();
        writeln!(output, "                        sqlx_query.bind(i)").unwrap();
        writeln!(output, "                    }} else if let Some(f) = n.as_f64() {{").unwrap();
        writeln!(output, "                        sqlx_query.bind(f)").unwrap();
        writeln!(output, "                    }} else {{").unwrap();
        writeln!(output, "                        sqlx_query.bind(n.to_string())").unwrap();
        writeln!(output, "                    }}").unwrap();
        writeln!(output, "                }}").unwrap();
        writeln!(output, "                serde_json::Value::Bool(b) => sqlx_query.bind(b),").unwrap();
        writeln!(output, "                serde_json::Value::Null => sqlx_query.bind(Option::<String>::None),").unwrap();
        writeln!(output, "                serde_json::Value::Array(_) | serde_json::Value::Object(_) => sqlx_query.bind(value),").unwrap();
        writeln!(output, "            }};").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        // Bind the ID parameter (parse string to UUID for PostgreSQL)").unwrap();
        writeln!(output, "        let id_uuid = uuid::Uuid::parse_str(id)").unwrap();
        writeln!(output, "            .map_err(|e| anyhow::anyhow!(\"Invalid UUID format: {{}}\", e))?;").unwrap();
        writeln!(output, "        sqlx_query = sqlx_query.bind(id_uuid);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        let result = sqlx_query").unwrap();
        writeln!(output, "            .fetch_optional(self.pool())").unwrap();
        writeln!(output, "            .await?;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "        Ok(result)").unwrap();
        writeln!(output, "    }}").unwrap();

        Ok(())
    }

    fn type_to_rust(&self, type_ref: &TypeRef) -> String {
        match type_ref {
            TypeRef::Primitive(p) => p.rust_type().to_string(),
            TypeRef::Custom(name) => name.clone(),
            TypeRef::Array(inner) => format!("Vec<{}>", self.type_to_rust(inner)),
            TypeRef::Optional(inner) => format!("Option<{}>", self.type_to_rust(inner)),
            TypeRef::Map { key, value } => {
                format!(
                    "std::collections::HashMap<{}, {}>",
                    self.type_to_rust(key),
                    self.type_to_rust(value)
                )
            }
            TypeRef::ModuleRef { module, name } => format!("{}::{}", module, name),
        }
    }

    fn type_to_param_type(&self, type_ref: &TypeRef) -> String {
        match type_ref {
            TypeRef::Primitive(PrimitiveType::String)
            | TypeRef::Primitive(PrimitiveType::Email)
            | TypeRef::Primitive(PrimitiveType::Url)
            | TypeRef::Primitive(PrimitiveType::Slug) => "&str".to_string(),
            _ => self.type_to_rust(type_ref),
        }
    }
}

impl Default for RepositoryGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for RepositoryGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Collect model names for parent mod.rs
        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        for model in &schema.schema.models {
            let model_snake = to_snake_case(&model.name);

            // Note: Entity trait implementations are no longer generated here.
            // Entity structs are generated by the Rust generator in domain/entity/.
            // Repositories use direct SQL with sqlx instead of backbone-orm Entity trait.

            // Generate repository (pass schema for enum type detection)
            let repo_content = self.generate_repository(model, &schema.schema)?;

            if self.group_by_domain {
                // Grouped structure: src/infrastructure/persistence/{model}/{model}_repository.rs
                let repo_path = build_generated_path(
                    "src/infrastructure/persistence",
                    &model.name,
                    &format!("{}_repository.rs", model_snake),
                    true,
                );
                output.add_file(repo_path, repo_content);

                // Create subdirectory mod.rs: src/infrastructure/persistence/{model}/mod.rs
                let sub_mod_path = PathBuf::from(format!("src/infrastructure/persistence/{}/mod.rs", model_snake));
                let sub_mod_content = build_subdirectory_mod(&model.name, &format!("{}_repository", model_snake));
                output.add_file(sub_mod_path, sub_mod_content);
            } else {
                // Flat structure (original)
                let repo_path = PathBuf::from(format!(
                    "src/infrastructure/persistence/{}_repository.rs",
                    model_snake
                ));
                output.add_file(repo_path, repo_content);
            }
        }

        // Generate mod.rs files
        if !schema.schema.models.is_empty() {
            // Note: Entity mod.rs is NOT generated here.
            // It's generated by the Rust generator which creates the entity structs.

            // Repository mod.rs
            let mut repo_mod = String::new();
            writeln!(repo_mod, "//! Repository implementations").unwrap();
            writeln!(repo_mod, "//!").unwrap();
            writeln!(repo_mod, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
            writeln!(repo_mod, "//!").unwrap();
            writeln!(repo_mod, "//! Uses backbone-orm's `DatabaseOperations<T>` trait.").unwrap();
            writeln!(repo_mod).unwrap();

            if self.group_by_domain {
                // For grouped structure, parent mod.rs declares subdirectories
                writeln!(repo_mod, "// Model subdirectories").unwrap();
                for model in &model_names {
                    let model_snake = to_snake_case(model);
                    writeln!(repo_mod, "pub mod {};", model_snake).unwrap();
                }
                writeln!(repo_mod).unwrap();
                writeln!(repo_mod, "// Re-exports from subdirectories").unwrap();
                for model in &model_names {
                    let model_snake = to_snake_case(model);
                    writeln!(repo_mod, "pub use {}::{}Repository;", model_snake, model).unwrap();
                }
            } else {
                // Flat structure
                for model in &schema.schema.models {
                    writeln!(repo_mod, "mod {}_repository;", to_snake_case(&model.name)).unwrap();
                }
                writeln!(repo_mod).unwrap();
                // Custom module declarations — unique anchor prevents misplacement on regeneration
                writeln!(repo_mod, "// Custom persistence modules").unwrap();
                writeln!(repo_mod, "// <<< CUSTOM").unwrap();
                writeln!(repo_mod, "// END CUSTOM").unwrap();
                writeln!(repo_mod).unwrap();

                // Re-exports
                writeln!(repo_mod, "// Re-exports").unwrap();
                for model in &schema.schema.models {
                    writeln!(repo_mod, "pub use {}_repository::{}Repository;",
                        to_snake_case(&model.name), model.name).unwrap();
                }
            }
            writeln!(repo_mod).unwrap();

            // Re-export backbone-orm types for convenience
            // Note: Entity trait not re-exported to avoid conflict with domain::entity::Entity
            writeln!(repo_mod, "// Re-export backbone-orm types").unwrap();
            writeln!(repo_mod, "pub use backbone_orm::repository::{{").unwrap();
            writeln!(repo_mod, "    DatabaseOperations, PostgresRepository,").unwrap();
            writeln!(repo_mod, "    PaginationParams, PaginationInfo, PaginatedResult,").unwrap();
            writeln!(repo_mod, "    FilterParams, FilterCondition, SortParams, SortDirection,").unwrap();
            writeln!(repo_mod, "}};").unwrap();
            writeln!(repo_mod).unwrap();
            // Custom re-exports section — unique anchor prevents misplacement on regeneration
            writeln!(repo_mod, "// Re-export custom persistence types").unwrap();
            writeln!(repo_mod, "// <<< CUSTOM").unwrap();
            writeln!(repo_mod, "// END CUSTOM").unwrap();

            output.add_file(PathBuf::from("src/infrastructure/persistence/mod.rs"), repo_mod);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "repository"
    }
}

use crate::utils::to_snake_case;


#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, ModuleSchema, PrimitiveType};

    fn create_test_model() -> Model {
        let mut model = Model::new("User");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::String))),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "email".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Email),
                attributes: vec![Attribute::new("unique")],
                ..Default::default()
            },
            Field {
                name: "name".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "created_at".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::DateTime),
                attributes: vec![Attribute::new("auto")],
                ..Default::default()
            },
            Field {
                name: "updated_at".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::DateTime),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "deleted_at".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_repository_generator_creates_files() {
        let schema = create_test_schema();
        let generator = RepositoryGenerator::new();
        let output = generator.generate(&schema).unwrap();

        // Note: Entity trait files are no longer generated by the repository generator
        // Entity structs are generated by the Rust generator
        assert!(!output.files.contains_key(&PathBuf::from("src/domain/entity/user_entity.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/persistence/user_repository.rs")));
        // Entity mod.rs is generated by Rust generator, not repository generator
        assert!(!output.files.contains_key(&PathBuf::from("src/domain/entity/mod.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/infrastructure/persistence/mod.rs")));
    }

    #[test]
    fn test_repository_uses_table_name_constant() {
        let schema = create_test_schema();
        let generator = RepositoryGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let repo_content = output.files.get(&PathBuf::from("src/infrastructure/persistence/user_repository.rs")).unwrap();

        // Should define TABLE_NAME constant
        assert!(repo_content.contains("pub const TABLE_NAME: &str = \"users\";"));
        // Should use TABLE_NAME in constructor
        assert!(repo_content.contains("PostgresRepository::new(pool, TABLE_NAME)"));
    }

    #[test]
    fn test_repository_uses_database_operations() {
        let schema = create_test_schema();
        let generator = RepositoryGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let repo_content = output.files.get(&PathBuf::from("src/infrastructure/persistence/user_repository.rs")).unwrap();

        // Should import backbone-orm types
        assert!(repo_content.contains("use backbone_orm::repository::"));
        assert!(repo_content.contains("DatabaseOperations"));
        assert!(repo_content.contains("PostgresRepository"));

        // Should wrap PostgresRepository
        assert!(repo_content.contains("inner: PostgresRepository<User>"));
    }

    #[test]
    fn test_repository_uses_str_ids() {
        let schema = create_test_schema();
        let generator = RepositoryGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let repo_content = output.files.get(&PathBuf::from("src/infrastructure/persistence/user_repository.rs")).unwrap();

        // Should use &str for IDs, not Uuid
        assert!(repo_content.contains("id: &str"));
        assert!(!repo_content.contains("id: Uuid"));
    }

    #[test]
    fn test_repository_has_soft_delete_methods() {
        let schema = create_test_schema();
        let generator = RepositoryGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let repo_content = output.files.get(&PathBuf::from("src/infrastructure/persistence/user_repository.rs")).unwrap();

        // Should have soft delete methods
        assert!(repo_content.contains("pub async fn soft_delete"));
        assert!(repo_content.contains("pub async fn restore"));
        assert!(repo_content.contains("pub async fn list_deleted"));
        assert!(repo_content.contains("pub async fn empty_trash"));
    }

    #[test]
    fn test_repository_has_pagination() {
        let schema = create_test_schema();
        let generator = RepositoryGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let repo_content = output.files.get(&PathBuf::from("src/infrastructure/persistence/user_repository.rs")).unwrap();

        // Should use backbone-orm pagination types
        assert!(repo_content.contains("PaginationParams"));
        assert!(repo_content.contains("PaginatedResult"));
        assert!(repo_content.contains("pub async fn list_paginated"));
    }

    #[test]
    fn test_find_by_unique_field() {
        let schema = create_test_schema();
        let generator = RepositoryGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let repo_content = output.files.get(&PathBuf::from("src/infrastructure/persistence/user_repository.rs")).unwrap();

        // Should have find_by_email for unique field
        assert!(repo_content.contains("pub async fn find_by_email"));
    }

    #[test]
    fn test_mod_re_exports_backbone_orm() {
        let schema = create_test_schema();
        let generator = RepositoryGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let mod_content = output.files.get(&PathBuf::from("src/infrastructure/persistence/mod.rs")).unwrap();

        // Should re-export backbone-orm types
        assert!(mod_content.contains("pub use backbone_orm::repository::"));
    }
}
