//! Repository Trait generator
//!
//! Generates DDD repository trait interfaces in the domain layer.
//! These traits define the contract for persistence without implementation details.
//!
//! ## DDD Repository Pattern
//!
//! Repositories:
//! - One repository per Aggregate Root
//! - Abstract persistence mechanism
//! - Provide collection-like interface for aggregates
//! - Defined in domain layer, implemented in infrastructure
//!
//! ## Generated Output
//!
//! For each model, generates:
//! - `{model}_repository.rs` - Repository trait definition in domain layer

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::{Model, PrimitiveType, TypeRef};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates repository traits from schema
pub struct RepositoryTraitGenerator {
    /// Group generated files by model/domain
    group_by_domain: bool,
}

impl RepositoryTraitGenerator {
    pub fn new() -> Self {
        Self {
            group_by_domain: false,  // Keep flat - only one file per entity
        }
    }

    /// Set whether to group files by domain
    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Generate repository trait for a model
    fn generate_repository_trait(&self, model: &Model) -> Result<String, GenerateError> {
        let mut output = String::new();
        let name = &model.name;
        let snake_name = to_snake_case(name);

        // Header
        writeln!(output, "//! Repository trait for {} aggregate", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This trait defines the repository contract for the {} aggregate.", name).unwrap();
        writeln!(output, "//! Implementation is in the infrastructure layer.").unwrap();
        writeln!(output).unwrap();

        // Imports
        writeln!(output, "use async_trait::async_trait;").unwrap();
        writeln!(output, "use anyhow::Result;").unwrap();

        // Add Uuid import only if filterable fields use Uuid type
        let needs_uuid = model.fields.iter().any(|f| {
            if f.is_primary_key() || self.is_audit_field(&f.name) { return false; }
            self.field_uses_uuid(&f.type_ref) && self.is_filterable_field(&f.type_ref)
        });
        if needs_uuid {
            writeln!(output, "use uuid::Uuid;").unwrap();
        }
        writeln!(output).unwrap();

        // Collect enum types used in filterable fields (deduplicated)
        let mut enum_types_set: std::collections::HashSet<String> = std::collections::HashSet::new();
        model.fields.iter()
            .filter(|f| !f.is_primary_key() && !self.is_audit_field(&f.name) && self.is_filterable_field(&f.type_ref))
            .for_each(|f| {
                if let Some(type_name) = self.get_custom_type(&f.type_ref) {
                    enum_types_set.insert(type_name);
                }
            });
        // Convert to sorted Vec for deterministic output
        let mut enum_types: Vec<String> = enum_types_set.into_iter().collect();
        enum_types.sort();

        if !enum_types.is_empty() {
            writeln!(output, "use crate::domain::entity::{{{}, {}}};", name, enum_types.join(", ")).unwrap();
        } else {
            writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        }
        writeln!(output).unwrap();

        // Pagination types (could be from backbone-orm or defined locally)
        writeln!(output, "/// Pagination parameters for list queries").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Default)]").unwrap();
        writeln!(output, "pub struct {}PaginationParams {{", name).unwrap();
        writeln!(output, "    pub page: u32,").unwrap();
        writeln!(output, "    pub per_page: u32,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl {}PaginationParams {{", name).unwrap();
        writeln!(output, "    pub fn new(page: u32, per_page: u32) -> Self {{").unwrap();
        writeln!(output, "        Self {{ page, per_page }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    pub fn offset(&self) -> u64 {{").unwrap();
        writeln!(output, "        ((self.page.saturating_sub(1)) * self.per_page) as u64").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    pub fn limit(&self) -> u64 {{").unwrap();
        writeln!(output, "        self.per_page as u64").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Paginated result
        writeln!(output, "/// Paginated result for list queries").unwrap();
        writeln!(output, "#[derive(Debug, Clone)]").unwrap();
        writeln!(output, "pub struct {}PaginatedResult {{", name).unwrap();
        writeln!(output, "    pub data: Vec<{}>,", name).unwrap();
        writeln!(output, "    pub total: u64,").unwrap();
        writeln!(output, "    pub page: u32,").unwrap();
        writeln!(output, "    pub per_page: u32,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Filter struct
        writeln!(output, "/// Filter parameters for list queries").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Default)]").unwrap();
        writeln!(output, "pub struct {}Filter {{", name).unwrap();

        for field in &model.fields {
            if field.is_primary_key() || self.is_audit_field(&field.name) {
                continue;
            }
            if self.is_filterable_field(&field.type_ref) {
                let rust_type = self.type_to_rust(&field.type_ref);
                let filter_type = if rust_type.starts_with("Option<") {
                    rust_type.clone()
                } else {
                    format!("Option<{}>", rust_type)
                };
                writeln!(output, "    pub {}: {},", field.name, filter_type).unwrap();
            }
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl {}Filter {{", name).unwrap();
        writeln!(output, "    /// Check if any filter is set").unwrap();
        writeln!(output, "    pub fn has_filters(&self) -> bool {{").unwrap();

        // Generate conditions for each filterable field
        let filterable_fields: Vec<_> = model.fields.iter()
            .filter(|f| !f.is_primary_key() && !self.is_audit_field(&f.name) && self.is_filterable_field(&f.type_ref))
            .collect();

        if filterable_fields.is_empty() {
            writeln!(output, "        false").unwrap();
        } else {
            let conditions: Vec<String> = filterable_fields.iter()
                .map(|f| format!("self.{}.is_some()", f.name))
                .collect();
            writeln!(output, "        {}", conditions.join(" || ")).unwrap();
        }

        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Repository trait
        writeln!(output, "/// Repository trait for {} aggregate", name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// This trait defines the persistence contract for {} entities.", name).unwrap();
        writeln!(output, "/// Implementations should be in the infrastructure layer.").unwrap();
        writeln!(output, "#[async_trait]").unwrap();
        writeln!(output, "pub trait {}Repository: Send + Sync {{", name).unwrap();
        writeln!(output).unwrap();

        // Core CRUD methods
        writeln!(output, "    // =========================================================================").unwrap();
        writeln!(output, "    // Core CRUD Operations").unwrap();
        writeln!(output, "    // =========================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Save a new {} entity", snake_name).unwrap();
        writeln!(output, "    async fn save(&self, entity: &{}) -> Result<{}>;", name, name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Find {} by ID", snake_name).unwrap();
        writeln!(output, "    async fn find_by_id(&self, id: &str) -> Result<Option<{}>>;", name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Find all {} entities", snake_name).unwrap();
        writeln!(output, "    async fn find_all(&self) -> Result<Vec<{}>>;", name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Update {} by ID", snake_name).unwrap();
        writeln!(output, "    async fn update(&self, id: &str, entity: &{}) -> Result<Option<{}>>;", name, name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Delete {} by ID", snake_name).unwrap();
        writeln!(output, "    async fn delete(&self, id: &str) -> Result<bool>;").unwrap();
        writeln!(output).unwrap();

        // Pagination
        writeln!(output, "    // =========================================================================").unwrap();
        writeln!(output, "    // Pagination").unwrap();
        writeln!(output, "    // =========================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// List {} with pagination", snake_name).unwrap();
        writeln!(output, "    async fn list(&self, params: {}PaginationParams) -> Result<{}PaginatedResult>;", name, name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// List {} with pagination and filters", snake_name).unwrap();
        writeln!(output, "    async fn list_with_filters(&self, params: {}PaginationParams, filters: {}Filter) -> Result<{}PaginatedResult>;", name, name, name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Count all {} entities", snake_name).unwrap();
        writeln!(output, "    async fn count(&self) -> Result<u64>;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Count {} entities matching filters", snake_name).unwrap();
        writeln!(output, "    async fn count_with_filters(&self, filters: {}Filter) -> Result<u64>;", name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Check if {} exists by ID", snake_name).unwrap();
        writeln!(output, "    async fn exists(&self, id: &str) -> Result<bool>;").unwrap();
        writeln!(output).unwrap();

        // Soft delete methods if applicable
        if model.has_soft_delete() {
            writeln!(output, "    // =========================================================================").unwrap();
            writeln!(output, "    // Soft Delete Operations").unwrap();
            writeln!(output, "    // =========================================================================").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    /// Soft delete {} by ID", snake_name).unwrap();
            writeln!(output, "    async fn soft_delete(&self, id: &str) -> Result<bool>;").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    /// Restore soft-deleted {} by ID", snake_name).unwrap();
            writeln!(output, "    async fn restore(&self, id: &str) -> Result<Option<{}>>;", name).unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    /// List soft-deleted {} entities", snake_name).unwrap();
            writeln!(output, "    async fn list_deleted(&self, params: {}PaginationParams) -> Result<{}PaginatedResult>;", name, name).unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    /// Empty trash (permanently delete all soft-deleted entities)").unwrap();
            writeln!(output, "    async fn empty_trash(&self) -> Result<u64>;").unwrap();
            writeln!(output).unwrap();
        }

        // Query by unique fields
        let unique_fields: Vec<_> = model.fields.iter()
            .filter(|f| f.is_unique() && !f.is_primary_key())
            .collect();

        if !unique_fields.is_empty() {
            writeln!(output, "    // =========================================================================").unwrap();
            writeln!(output, "    // Query by Unique Fields").unwrap();
            writeln!(output, "    // =========================================================================").unwrap();
            writeln!(output).unwrap();

            for field in unique_fields.iter() {
                let param_type = self.type_to_param_type(&field.type_ref);
                writeln!(output, "    /// Find {} by {}", snake_name, field.name).unwrap();
                writeln!(output, "    async fn find_by_{}(&self, {}: {}) -> Result<Option<{}>>;",
                    field.name, field.name, param_type, name).unwrap();
                writeln!(output).unwrap();
            }

            writeln!(output, "    // =========================================================================").unwrap();
            writeln!(output, "    // Existence Checks by Unique Fields").unwrap();
            writeln!(output, "    // =========================================================================").unwrap();
            writeln!(output).unwrap();

            for field in unique_fields.iter() {
                let param_type = self.type_to_param_type(&field.type_ref);
                writeln!(output, "    /// Check if {} exists by {}", snake_name, field.name).unwrap();
                writeln!(output, "    async fn exists_by_{}(&self, {}: {}) -> Result<bool>;",
                    field.name, field.name, param_type).unwrap();
                writeln!(output).unwrap();
            }
        }

        // Bulk operations
        writeln!(output, "    // =========================================================================").unwrap();
        writeln!(output, "    // Bulk Operations").unwrap();
        writeln!(output, "    // =========================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Bulk save {} entities", snake_name).unwrap();
        writeln!(output, "    async fn bulk_save(&self, entities: &[{}]) -> Result<Vec<{}>>;", name, name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Bulk delete by IDs").unwrap();
        writeln!(output, "    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;").unwrap();

        writeln!(output, "}}").unwrap();

        Ok(output)
    }

    fn type_to_param_type(&self, type_ref: &TypeRef) -> String {
        match type_ref {
            TypeRef::Primitive(PrimitiveType::String)
            | TypeRef::Primitive(PrimitiveType::Email)
            | TypeRef::Primitive(PrimitiveType::Url)
            | TypeRef::Primitive(PrimitiveType::Slug) => "&str".to_string(),
            TypeRef::Primitive(p) => p.rust_type().to_string(),
            TypeRef::Custom(name) => format!("&{}", name),
            TypeRef::Optional(inner) => format!("Option<{}>", self.type_to_param_type(inner)),
            _ => "String".to_string(),
        }
    }

    fn is_audit_field(&self, name: &str) -> bool {
        matches!(name, "created_at" | "updated_at" | "deleted_at" | "created_by" | "updated_by" | "deleted_by")
    }

    fn field_uses_uuid(&self, type_ref: &TypeRef) -> bool {
        match type_ref {
            TypeRef::Primitive(PrimitiveType::Uuid) => true,
            TypeRef::Optional(inner) => self.field_uses_uuid(inner),
            _ => false,
        }
    }

    fn is_filterable_field(&self, type_ref: &TypeRef) -> bool {
        match type_ref {
            TypeRef::Primitive(p) => matches!(p,
                PrimitiveType::String |
                PrimitiveType::Email |
                PrimitiveType::Uuid |
                PrimitiveType::Bool |
                PrimitiveType::Int32 |
                PrimitiveType::Int64
            ),
            TypeRef::Optional(inner) => self.is_filterable_field(inner),
            TypeRef::Custom(_) => true, // Enums are filterable
            _ => false,
        }
    }

    fn type_to_rust(&self, type_ref: &TypeRef) -> String {
        match type_ref {
            TypeRef::Primitive(p) => p.rust_type().to_string(),
            TypeRef::Optional(inner) => format!("Option<{}>", self.type_to_rust(inner)),
            TypeRef::Array(inner) => format!("Vec<{}>", self.type_to_rust(inner)),
            TypeRef::Custom(name) => name.clone(),
            TypeRef::ModuleRef { name, .. } => name.clone(),
            TypeRef::Map { key, value } => format!("std::collections::HashMap<{}, {}>", self.type_to_rust(key), self.type_to_rust(value)),
        }
    }

    fn get_custom_type(&self, type_ref: &TypeRef) -> Option<String> {
        match type_ref {
            TypeRef::Custom(name) => Some(name.clone()),
            TypeRef::Optional(inner) => self.get_custom_type(inner),
            _ => None,
        }
    }
}

impl Default for RepositoryTraitGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for RepositoryTraitGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        if schema.schema.models.is_empty() {
            return Ok(output);
        }

        // Collect model names for parent mod.rs
        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        let mut mod_content = String::new();
        writeln!(mod_content, "//! Repository traits").unwrap();
        writeln!(mod_content, "//!").unwrap();
        writeln!(mod_content, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(mod_content, "//!").unwrap();
        writeln!(mod_content, "//! DDD Repository traits - define persistence contracts for aggregates.").unwrap();
        writeln!(mod_content, "//! Implementations should be in the infrastructure layer.").unwrap();
        writeln!(mod_content).unwrap();

        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);

            // Generate repository trait
            let trait_content = self.generate_repository_trait(model)?;

            if self.group_by_domain {
                // Grouped structure: src/domain/repositories/{model}/{model}_repository.rs
                let trait_path = build_generated_path(
                    "src/domain/repositories",
                    &model.name,
                    &format!("{}_repository.rs", snake_name),
                    true,
                );
                output.add_file(trait_path, trait_content);

                // Create subdirectory mod.rs: src/domain/repositories/{model}/mod.rs
                let sub_mod_path = PathBuf::from(format!("src/domain/repositories/{}/mod.rs", snake_name));
                let sub_mod_content = build_subdirectory_mod(&model.name, &format!("{}_repository", snake_name));
                output.add_file(sub_mod_path, sub_mod_content);
            } else {
                // Flat structure (original)
                let trait_path = PathBuf::from(format!(
                    "src/domain/repositories/{}_repository.rs",
                    snake_name
                ));
                output.add_file(trait_path, trait_content);
            }
        }

        writeln!(mod_content).unwrap();

        if self.group_by_domain {
            // For grouped structure, parent mod.rs declares subdirectories
            writeln!(mod_content, "// Model subdirectories").unwrap();
            for model in &model_names {
                let snake_name = to_snake_case(model);
                writeln!(mod_content, "pub mod {};", snake_name).unwrap();
            }
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "// Re-exports from subdirectories").unwrap();
            for model in &model_names {
                let snake_name = to_snake_case(model);
                writeln!(mod_content, "pub use {}::{{", snake_name).unwrap();
                writeln!(mod_content, "    {}Repository,", model).unwrap();
                writeln!(mod_content, "    {}PaginationParams,", model).unwrap();
                writeln!(mod_content, "    {}PaginatedResult,", model).unwrap();
                writeln!(mod_content, "    {}Filter,", model).unwrap();
                writeln!(mod_content, "}};").unwrap();
            }
        } else {
            // Flat structure
            for model in &schema.schema.models {
                let snake_name = to_snake_case(&model.name);
                writeln!(mod_content, "pub mod {}_repository;", snake_name).unwrap();
            }
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "// Re-exports").unwrap();
            for model in &schema.schema.models {
                let snake_name = to_snake_case(&model.name);
                writeln!(mod_content, "pub use {}_repository::{{", snake_name).unwrap();
                writeln!(mod_content, "    {}Repository,", model.name).unwrap();
                writeln!(mod_content, "    {}PaginationParams,", model.name).unwrap();
                writeln!(mod_content, "    {}PaginatedResult,", model.name).unwrap();
                writeln!(mod_content, "    {}Filter,", model.name).unwrap();
                writeln!(mod_content, "}};").unwrap();
            }
        }

        output.add_file(PathBuf::from("src/domain/repositories/mod.rs"), mod_content);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "repository_trait"
    }
}

use crate::utils::to_snake_case;


#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType};

    fn create_test_model() -> Model {
        let mut model = Model::new("User");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::String))),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "email".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Email),
                attributes: vec![Attribute::new("unique")],
                ..Default::default()
            },
            Field {
                name: "deleted_at".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_repository_trait_generator_creates_files() {
        let schema = create_test_schema();
        let generator = RepositoryTraitGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/domain/repositories/user_repository.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/domain/repositories/mod.rs")));
    }

    #[test]
    fn test_repository_trait_has_crud_methods() {
        let schema = create_test_schema();
        let generator = RepositoryTraitGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/domain/repositories/user_repository.rs")).unwrap();

        assert!(content.contains("async fn save"));
        assert!(content.contains("async fn find_by_id"));
        assert!(content.contains("async fn find_all"));
        assert!(content.contains("async fn update"));
        assert!(content.contains("async fn delete"));
    }

    #[test]
    fn test_repository_trait_has_soft_delete() {
        let schema = create_test_schema();
        let generator = RepositoryTraitGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/domain/repositories/user_repository.rs")).unwrap();

        // Should have soft delete methods for model with deleted_at
        assert!(content.contains("async fn soft_delete"));
        assert!(content.contains("async fn restore"));
        assert!(content.contains("async fn empty_trash"));
    }

    #[test]
    fn test_repository_trait_has_unique_field_queries() {
        let schema = create_test_schema();
        let generator = RepositoryTraitGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/domain/repositories/user_repository.rs")).unwrap();

        // Should have find_by_email for unique field
        assert!(content.contains("async fn find_by_email"));
    }

    #[test]
    fn test_repository_trait_uses_async_trait() {
        let schema = create_test_schema();
        let generator = RepositoryTraitGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("src/domain/repositories/user_repository.rs")).unwrap();

        assert!(content.contains("use async_trait::async_trait;"));
        assert!(content.contains("#[async_trait]"));
    }
}
