//! Routes Composer Generator
//!
//! Generates route composition for HTTP handlers with dual pattern support:
//! - Stateless routes (Router<()>) - simpler, current pattern
//! - Stateful routes (Router<AppState>) - enables custom handlers
//!
//! ## Generated Files
//!
//! - `src/routes/mod.rs` - Route composition with both patterns

use super::{GenerateError, GeneratedOutput, Generator};
use crate::resolver::ResolvedSchema;
use crate::utils::to_snake_case;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates route composition code
pub struct RoutesComposerGenerator;

impl RoutesComposerGenerator {
    pub fn new() -> Self {
        Self
    }
}

impl Default for RoutesComposerGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for RoutesComposerGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        let routes_mod = self.generate_routes_mod(schema)?;
        output.add_file(PathBuf::from("src/routes/mod.rs"), routes_mod);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "routes_composer"
    }
}

impl RoutesComposerGenerator {
    fn generate_routes_mod(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let module_name = &schema.schema.name;
        let pascal_name = to_pascal_case(module_name);

        // Header
        writeln!(output, "//! {} Module Routes", pascal_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This module provides route composition with dual pattern support:").unwrap();
        writeln!(output, "//! - Stateless routes: `create_stateless_routes()` -> `Router<()>`").unwrap();
        writeln!(output, "//! - Stateful routes: `create_stateful_routes()` -> `Router<AppState>`").unwrap();
        writeln!(output).unwrap();

        // Imports
        writeln!(output, "use axum::Router;").unwrap();
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output).unwrap();

        // Import handler route functions. Models that disabled the
        // Handler generator emit no `create_{name}_routes` function, so
        // skip them here to avoid generating an import that won't resolve.
        writeln!(output, "// Import handlers").unwrap();
        writeln!(output, "use crate::presentation::http::{{").unwrap();
        let routed_models: Vec<&crate::ast::Model> = schema
            .schema
            .models
            .iter()
            .filter(|m| !super::model_skips_target(m, super::GenerationTarget::Handler))
            .collect();
        let imports: Vec<String> = routed_models
            .iter()
            .flat_map(|m| {
                let s = to_snake_case(&m.name);
                // Both the full-CRUD composer and the read-only composer (the latter feeds the guarded mount).
                vec![format!("create_{}_routes", s), format!("create_{}_read_routes", s)]
            })
            .collect();
        for (i, import) in imports.iter().enumerate() {
            let comma = if i < imports.len() - 1 { "," } else { "" };
            writeln!(output, "    {}{}", import, comma).unwrap();
        }
        writeln!(output, "}};").unwrap();
        writeln!(output).unwrap();

        // Import AppState for stateful routes
        writeln!(output, "// Import AppState for stateful routes").unwrap();
        writeln!(output, "use crate::handlers::AppState;").unwrap();
        writeln!(output).unwrap();

        // ============================================================
        // Pattern 1: Stateless Routes
        // ============================================================
        writeln!(output, "// ============================================================").unwrap();
        writeln!(output, "// PATTERN 1: STATELESS ROUTES").unwrap();
        writeln!(output, "// ============================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Create stateless routes for the {} module.", pascal_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// These routes don't require shared state and are simpler to use.").unwrap();
        writeln!(output, "/// Use this when you only need standard CRUD operations.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// # Example").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ```ignore").unwrap();
        writeln!(output, "/// let module = {}Module::builder().with_database(pool).build()?;", pascal_name).unwrap();
        writeln!(output, "/// let routes = create_stateless_routes(&module);").unwrap();
        writeln!(output, "/// let app = Router::new().merge(routes);").unwrap();
        writeln!(output, "/// ```").unwrap();
        writeln!(output, "pub fn create_stateless_routes(module: &crate::{}Module) -> Router<()> {{", pascal_name).unwrap();
        writeln!(output, "    Router::new()").unwrap();

        for model in &routed_models {
            let snake_name = to_snake_case(&model.name);
            // Add CRUD routes (includes all 16 endpoints including trash operations)
            writeln!(output, "        .merge(create_{}_routes(module.{}_service.clone()))", snake_name, snake_name).unwrap();
        }

        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // ============================================================
        // Read-only-by-default composer (the guarded base)
        // ============================================================
        // The generic `create_stateless_routes` exposes full mutable CRUD on every entity, backed by generic
        // services with NO domain validation — so a caller can bypass the hand-authored write service's
        // invariants (the recurring gap the 2026-07-11 hardening audit found hand-patched module after
        // module). This composer mounts every entity READ-ONLY: the safe default. A module with domain
        // invariants mounts THIS instead of `create_stateless_routes`, and merges its own validated-write
        // endpoints onto it — `create_readonly_{name}_routes(m).merge(my_validated_writes)`. (A distinct name
        // from any hand-authored `create_guarded_{name}_routes`, so both can coexist / layer.)
        writeln!(output, "/// Read-only routes for the {} module — every entity mounted READ-ONLY (the guarded base).", pascal_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// The generic `create_stateless_routes` exposes full mutable CRUD with no domain").unwrap();
        writeln!(output, "/// validation; this exposes only reads, so generic mutation can't bypass a write").unwrap();
        writeln!(output, "/// service's invariants. Extend it: `create_readonly_{}_routes(m).merge(my_validated_writes)`.", module_name).unwrap();
        writeln!(output, "pub fn create_readonly_{}_routes(module: &crate::{}Module) -> Router<()> {{", module_name, pascal_name).unwrap();
        writeln!(output, "    Router::new()").unwrap();
        for model in &routed_models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "        .merge(create_{}_read_routes(module.{}_service.clone()))", snake_name, snake_name).unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Convenience function
        writeln!(output, "/// Get all routes (stateless) for the {} module.", pascal_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// This is a convenience function that wraps routes with API versioning.").unwrap();
        writeln!(output, "pub fn get_routes(module: &crate::{}Module) -> Router<()> {{", pascal_name).unwrap();
        writeln!(output, "    Router::new()").unwrap();
        writeln!(output, "        .nest(\"/api/v1\", create_stateless_routes(module))").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // ============================================================
        // Pattern 2: Stateful Routes
        // ============================================================
        writeln!(output, "// ============================================================").unwrap();
        writeln!(output, "// PATTERN 2: STATEFUL ROUTES (WITH APPSTATE)").unwrap();
        writeln!(output, "// ============================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Create stateful routes for the {} module.", pascal_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// These routes require AppState and support custom handlers").unwrap();
        writeln!(output, "/// that need access to services via dependency injection.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// # Example").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ```ignore").unwrap();
        writeln!(output, "/// let module = {}Module::builder().with_database(pool).build()?;", pascal_name).unwrap();
        writeln!(output, "/// let state = AppState::from_module(&module);").unwrap();
        writeln!(output, "/// let routes = create_stateful_routes();").unwrap();
        writeln!(output, "/// let app = Router::new().merge(routes).with_state(state);").unwrap();
        writeln!(output, "/// ```").unwrap();
        writeln!(output, "pub fn create_stateful_routes() -> Router<AppState> {{").unwrap();
        writeln!(output, "    Router::new()").unwrap();
        writeln!(output, "        // Add custom handlers here that need AppState").unwrap();
        writeln!(output, "        // .route(\"/custom\", get(custom_handler))").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Combined routes
        writeln!(output, "/// Create combined routes (stateless CRUD + stateful custom handlers).").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// This merges both stateless CRUD routes and stateful custom routes.").unwrap();
        writeln!(output, "pub fn create_combined_routes(module: &crate::{}Module) -> Router<AppState> {{", pascal_name).unwrap();
        writeln!(output, "    // First create stateless routes").unwrap();
        writeln!(output, "    let crud_routes: Router<()> = create_stateless_routes(module);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    // Convert to stateful by adding state requirement").unwrap();
        writeln!(output, "    // Note: The CRUD routes don't actually use the state,").unwrap();
        writeln!(output, "    // but this allows them to be merged with stateful routes.").unwrap();
        writeln!(output, "    let crud_routes_stateful: Router<AppState> = crud_routes.with_state(()).into();").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    // Merge with stateful routes").unwrap();
        writeln!(output, "    Router::new()").unwrap();
        writeln!(output, "        .merge(crud_routes_stateful)").unwrap();
        writeln!(output, "        .merge(create_stateful_routes())").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Get routes with state
        writeln!(output, "/// Get all routes (stateful) for the {} module.", pascal_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// This is a convenience function that wraps routes with API versioning.").unwrap();
        writeln!(output, "pub fn get_routes_with_state(module: &crate::{}Module) -> Router<AppState> {{", pascal_name).unwrap();
        writeln!(output, "    Router::new()").unwrap();
        writeln!(output, "        .nest(\"/api/v1\", create_combined_routes(module))").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // ============================================================
        // Custom handler section marker
        // ============================================================
        writeln!(output, "// ============================================================").unwrap();
        writeln!(output, "// CUSTOM HANDLERS").unwrap();
        writeln!(output, "// ============================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM HANDLERS START >>>").unwrap();
        writeln!(output, "// Add custom route handlers here").unwrap();
        writeln!(output, "// Example:").unwrap();
        writeln!(output, "//").unwrap();
        writeln!(output, "// use axum::extract::State;").unwrap();
        writeln!(output, "// use axum::response::IntoResponse;").unwrap();
        writeln!(output, "//").unwrap();
        writeln!(output, "// pub async fn custom_handler(").unwrap();
        writeln!(output, "//     State(state): State<AppState>,").unwrap();
        writeln!(output, "// ) -> impl IntoResponse {{").unwrap();
        writeln!(output, "//     // Use state.user_service, etc.").unwrap();
        writeln!(output, "//     \"Custom response\"").unwrap();
        writeln!(output, "// }}").unwrap();
        writeln!(output, "// <<< CUSTOM HANDLERS END >>>").unwrap();

        Ok(output)
    }
}

/// Convert string to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-', ' '])
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("user"), "User");
        assert_eq!(to_pascal_case("user_profile"), "UserProfile");
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("User"), "user");
        assert_eq!(to_snake_case("UserProfile"), "user_profile");
        assert_eq!(to_snake_case("CorporateSLA"), "corporate_sla");
        assert_eq!(to_snake_case("HTTPRequest"), "http_request");
    }
}
