//! Service generator
//!
//! Phase 1: Generates a **type alias** over `GenericCrudService` instead of a
//! full CRUD implementation per entity.
//!
//! ## Before (was 250+ generated lines per entity):
//! ```rust,ignore
//! pub struct OrderService { repository: Arc<OrderRepository>, ... }
//! impl OrderService { pub async fn list(...) { ... } ... }  // 12 methods
//! ```
//!
//! ## After (3 generated lines per entity):
//! ```rust,ignore
//! pub type OrderService = GenericCrudService<
//!     Order, CreateOrderDto, UpdateOrderDto, OrderRepository
//! >;
//! ```
//!
//! Custom behaviour is added via a decorator in `*_service_custom.rs` (never regenerated).

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates application service type aliases from schema
pub struct ServiceGenerator {
    /// Group generated files by model/domain
    group_by_domain: bool,
}

impl ServiceGenerator {
    pub fn new() -> Self {
        Self {
            group_by_domain: false,
        }
    }

    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Generate a type alias file for a single entity's service.
    fn generate_service_alias(&self, model: &Model) -> String {
        let mut output = String::new();
        let name = &model.name;
        let snake_name = to_snake_case(name);

        writeln!(output, "//! Application service for {} entities", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.").unwrap();
        writeln!(output, "//! For custom behaviour, create `{}_service_custom.rs` (preserved on regen).", snake_name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use backbone_core::GenericCrudService;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use crate::presentation::dto::{{Create{}Dto, Update{}Dto}};",
            name, name).unwrap();
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output, "use crate::infrastructure::persistence::{}Repository;", name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Application service for {} entities.", name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// All 12 standard CRUD operations (list, create, get, update, patch,").unwrap();
        writeln!(output, "/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,").unwrap();
        writeln!(output, "/// list_deleted) are provided by `GenericCrudService`.").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Custom extensions go in `{}_service_custom.rs`:", snake_name).unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// ```rust,ignore").unwrap();
        writeln!(output, "/// pub struct {}ServiceCustom {{", name).unwrap();
        writeln!(output, "///     inner: Arc<{}Service>,", name).unwrap();
        writeln!(output, "///     // add domain-specific dependencies here").unwrap();
        writeln!(output, "/// }}").unwrap();
        writeln!(output, "/// ```").unwrap();
        writeln!(output, "pub type {}Service = GenericCrudService<",  name).unwrap();
        writeln!(output, "    {},", name).unwrap();
        writeln!(output, "    Create{}Dto,", name).unwrap();
        writeln!(output, "    Update{}Dto,", name).unwrap();
        writeln!(output, "    {}Repository,", name).unwrap();
        writeln!(output, ">;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();

        output
    }

    /// Generate the error.rs module — now a simple re-export from backbone-core.
    fn generate_error_module(&self) -> String {
        let mut output = String::new();
        writeln!(output, "//! Service error types").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Re-exported from backbone-core so that existing `super::error::ServiceError`").unwrap();
        writeln!(output, "//! import paths continue to work without change.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub use backbone_core::{{ServiceError, ServiceResult}};").unwrap();
        output
    }
}

impl Default for ServiceGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for ServiceGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        for model in &schema.schema.models {
            let model_snake = to_snake_case(&model.name);
            let service_content = self.generate_service_alias(model);

            if self.group_by_domain {
                let service_path = build_generated_path(
                    "src/application/service",
                    &model.name,
                    &format!("{}_service.rs", model_snake),
                    true,
                );
                output.add_file(service_path, service_content);

                let sub_mod_path = PathBuf::from(format!(
                    "src/application/service/{}/mod.rs", model_snake
                ));
                let sub_mod_content = build_subdirectory_mod(
                    &model.name,
                    &format!("{}_service", model_snake),
                );
                output.add_file(sub_mod_path, sub_mod_content);
            } else {
                let service_path = PathBuf::from(format!(
                    "src/application/service/{}_service.rs",
                    model_snake
                ));
                output.add_file(service_path, service_content);
            }
        }

        // error.rs — re-export from backbone-core
        output.add_file(
            PathBuf::from("src/application/service/error.rs"),
            self.generate_error_module(),
        );

        // mod.rs
        if !schema.schema.models.is_empty() {
            let mut mod_content = String::new();
            writeln!(mod_content, "//! Application services").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Each entity service is a type alias over `GenericCrudService`.").unwrap();
            writeln!(mod_content).unwrap();

            writeln!(mod_content, "pub mod error;").unwrap();
            writeln!(mod_content, "pub use error::{{ServiceError, ServiceResult}};").unwrap();
            writeln!(mod_content).unwrap();

            if self.group_by_domain {
                for model in &model_names {
                    let model_snake = to_snake_case(model);
                    writeln!(mod_content, "pub mod {};", model_snake).unwrap();
                }
                writeln!(mod_content).unwrap();
                for model in &model_names {
                    let model_snake = to_snake_case(model);
                    writeln!(mod_content, "pub use {}::{}Service;", model_snake, model).unwrap();
                }
            } else {
                for model in &schema.schema.models {
                    writeln!(mod_content, "mod {}_service;", to_snake_case(&model.name)).unwrap();
                }
                writeln!(mod_content).unwrap();
                writeln!(mod_content, "// <<< CUSTOM").unwrap();
                writeln!(mod_content, "// END CUSTOM").unwrap();
                writeln!(mod_content).unwrap();
                for model in &schema.schema.models {
                    writeln!(mod_content, "pub use {}_service::{}Service;",
                        to_snake_case(&model.name), model.name).unwrap();
                }
                writeln!(mod_content, "// <<< CUSTOM").unwrap();
                writeln!(mod_content, "// END CUSTOM").unwrap();
            }

            output.add_file(PathBuf::from("src/application/service/mod.rs"), mod_content);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "service"
    }
}

use crate::utils::to_snake_case;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "name".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_service_generator_creates_files() {
        let schema = create_test_schema();
        let generator = ServiceGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/application/service/order_service.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/application/service/mod.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/application/service/error.rs")));
    }

    #[test]
    fn test_service_emits_type_alias() {
        let schema = create_test_schema();
        let generator = ServiceGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files
            .get(&PathBuf::from("src/application/service/order_service.rs"))
            .unwrap();

        assert!(content.contains("pub type OrderService = GenericCrudService<"));
        assert!(content.contains("GenericCrudService"));
        assert!(content.contains("CreateOrderDto"));
        assert!(content.contains("UpdateOrderDto"));
        assert!(content.contains("OrderRepository"));
    }

    #[test]
    fn test_error_module_re_exports_backbone_core() {
        let schema = create_test_schema();
        let generator = ServiceGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let error_content = output.files
            .get(&PathBuf::from("src/application/service/error.rs"))
            .unwrap();

        assert!(error_content.contains("backbone_core"));
        assert!(error_content.contains("ServiceError"));
        assert!(error_content.contains("ServiceResult"));
    }

    #[test]
    fn test_service_has_custom_marker() {
        let schema = create_test_schema();
        let generator = ServiceGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files
            .get(&PathBuf::from("src/application/service/order_service.rs"))
            .unwrap();

        assert!(content.contains("<<< CUSTOM"));
        assert!(content.contains("END CUSTOM"));
    }
}
