//! Specification generator
//!
//! Phase 1: Stops generating the `Specification` trait, `AndSpec`, `OrSpec`, and `NotSpec`
//! combinators per entity (those come from `backbone_core::Specification`).
//! Only emits entity-specific **predicate structs** that implement the trait.
//!
//! ## Before (was 400 generated lines per entity):
//! ```rust,ignore
//! pub trait OrderSpecification: Send + Sync { fn is_satisfied_by(&self, e: &Order) -> bool; }
//! pub struct AndOrderSpec<L, R> { ... }  // combinator
//! pub struct OrOrderSpec<L, R>  { ... }  // combinator
//! pub struct NotOrderSpec<S>    { ... }  // combinator
//! // ... combinator impls (~300 lines)
//! ```
//!
//! ## After (entity-specific predicates only):
//! ```rust,ignore
//! use backbone_core::Specification;
//! use crate::domain::entity::Order;
//!
//! // Only entity-specific predicates:
//! pub struct ActiveOrderSpec;
//! impl Specification<Order> for ActiveOrderSpec {
//!     fn is_satisfied_by(&self, e: &Order) -> bool { /* <<< CUSTOM */ }
//! }
//! ```

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path, build_subdirectory_mod};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use crate::utils::to_snake_case;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates specification predicate structs from schema
pub struct SpecificationGenerator {
    group_by_domain: bool,
}

impl SpecificationGenerator {
    pub fn new() -> Self {
        Self { group_by_domain: false }
    }

    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Generate specification file for a single entity.
    ///
    /// Emits only entity-specific predicate structs — combinators come from backbone-core.
    fn generate_specification(&self, model: &Model) -> Result<String, GenerateError> {
        let mut output = String::new();
        let name = &model.name;

        writeln!(output, "//! Specifications for {} aggregate", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Entity-specific predicate structs implementing `backbone_core::Specification`.").unwrap();
        writeln!(output, "//! Combinators (AND/OR/NOT) are available via the trait methods — no duplication.").unwrap();
        writeln!(output).unwrap();

        // Import the generic trait — combinators come for free.
        writeln!(output, "use backbone_core::Specification;").unwrap();
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output).unwrap();

        // Re-export combinators from backbone-core for ergonomic use.
        // These are the specification-pattern combinators (not policy combinators).
        writeln!(output, "pub use backbone_core::{{AndSpecification, OrSpecification, NotSpecification}};").unwrap();
        writeln!(output).unwrap();

        // Scaffold predicate — one example; custom predicates go in the CUSTOM zone.
        writeln!(output, "// ─── Entity-specific predicates ──────────────────────────────────────────────").unwrap();
        writeln!(output, "//").unwrap();
        writeln!(output, "// Add entity-specific predicate structs below.").unwrap();
        writeln!(output, "// Each predicate implements `Specification<{}>` and can be combined", name).unwrap();
        writeln!(output, "// using `.and()`, `.or()`, `.not()` from the trait.").unwrap();
        writeln!(output, "//").unwrap();
        writeln!(output, "// Example:").unwrap();
        writeln!(output, "//   let spec = ActiveSpec.and(VerifiedSpec);").unwrap();
        writeln!(output, "//   if spec.is_satisfied_by(&entity) {{ ... }}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// Add predicate structs here. Example:").unwrap();
        writeln!(output, "//").unwrap();
        writeln!(output, "// pub struct Active{}Spec;", name).unwrap();
        writeln!(output, "// impl Specification<{}> for Active{}Spec {{", name, name).unwrap();
        writeln!(output, "//     fn is_satisfied_by(&self, e: &{}) -> bool {{", name).unwrap();
        writeln!(output, "//         // e.is_active").unwrap();
        writeln!(output, "//         todo!()").unwrap();
        writeln!(output, "//     }}").unwrap();
        writeln!(output, "// }}").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();

        Ok(output)
    }
}

impl Default for SpecificationGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for SpecificationGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();
        let model_names: Vec<String> = schema.schema.models.iter()
            .map(|m| m.name.clone())
            .collect();

        for model in &schema.schema.models {
            let snake_name = to_snake_case(&model.name);
            let content = self.generate_specification(model)?;

            if self.group_by_domain {
                let path = build_generated_path(
                    "src/domain/specifications",
                    &model.name,
                    &format!("{}_specification.rs", snake_name),
                    true,
                );
                output.add_file(path, content);

                let sub_mod_path = PathBuf::from(format!(
                    "src/domain/specifications/{}/mod.rs", snake_name
                ));
                let sub_mod = build_subdirectory_mod(
                    &model.name,
                    &format!("{}_specification", snake_name),
                );
                output.add_file(sub_mod_path, sub_mod);
            } else {
                let path = PathBuf::from(format!(
                    "src/domain/specifications/{}_specification.rs",
                    snake_name
                ));
                output.add_file(path, content);
            }
        }

        // mod.rs
        if !model_names.is_empty() {
            let mut mod_content = String::new();
            writeln!(mod_content, "//! Domain specifications").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.").unwrap();
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "pub use backbone_core::{{Specification, AndSpecification, OrSpecification, NotSpecification}};").unwrap();
            writeln!(mod_content).unwrap();
            for name in &model_names {
                writeln!(mod_content, "pub mod {}_specification;", to_snake_case(name)).unwrap();
            }
            writeln!(mod_content).unwrap();
            writeln!(mod_content, "// <<< CUSTOM").unwrap();
            writeln!(mod_content, "// END CUSTOM").unwrap();
            output.add_file(PathBuf::from("src/domain/specifications/mod.rs"), mod_content);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "specification"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![Field {
            name: "id".to_string(),
            type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
            attributes: vec![Attribute::new("id")],
            ..Default::default()
        }];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_specification_creates_files() {
        let schema = create_test_schema();
        let gen = SpecificationGenerator::new();
        let out = gen.generate(&schema).unwrap();

        assert!(out.files.contains_key(&PathBuf::from(
            "src/domain/specifications/order_specification.rs"
        )));
        assert!(out.files.contains_key(&PathBuf::from(
            "src/domain/specifications/mod.rs"
        )));
    }

    #[test]
    fn test_no_combinator_structs_generated() {
        let schema = create_test_schema();
        let gen = SpecificationGenerator::new();
        let out = gen.generate(&schema).unwrap();

        let content = out.files
            .get(&PathBuf::from("src/domain/specifications/order_specification.rs"))
            .unwrap();

        // Combinators must NOT be emitted per-entity — they live in backbone-core.
        assert!(!content.contains("pub struct AndOrderSpec"));
        assert!(!content.contains("pub struct OrOrderSpec"));
        assert!(!content.contains("pub struct NotOrderSpec"));
        // The generic trait import must be present.
        assert!(content.contains("backbone_core::Specification"));
    }
}
