//! SQL migration generator
//!
//! Generates PostgreSQL migration files from schema.
//! Supports both single-file and split-by-model output.

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::{EnumDef, Field, ForeignKeyAction, Index, IndexType, Model, PrimitiveType, RelationType, TypeRef};
use crate::resolver::ResolvedSchema;
use crate::utils::{pluralize, to_snake_case};
use std::fmt::Write;
use std::path::PathBuf;

// ============================================================================
// Constants
// ============================================================================

/// Default JSONB value for audit metadata fields.
/// Contains all audit tracking fields initialized to null.
const AUDIT_METADATA_DEFAULT_JSON: &str =
    r#"'{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb"#;

/// Generates SQL migrations from schema
pub struct SqlGenerator {
    version: Option<String>,
    split: bool,
}

impl SqlGenerator {
    pub fn new() -> Self {
        Self {
            version: None,
            split: true, // Default to split by model for readability
        }
    }

    pub fn with_version(mut self, version: impl Into<String>) -> Self {
        self.version = Some(version.into());
        self
    }

    pub fn with_split(mut self, split: bool) -> Self {
        self.split = split;
        self
    }

    fn generate_table(&self, model: &Model) -> Result<String, GenerateError> {
        let mut output = String::new();
        let table_name = model.collection_name();

        // Header comment
        writeln!(output, "-- Migration: Create {} table", table_name).unwrap();
        writeln!(output, "-- Generated by metaphor-schema").unwrap();
        writeln!(output).unwrap();

        // Create table
        writeln!(output, "CREATE TABLE IF NOT EXISTS {} (", table_name).unwrap();

        let mut columns = Vec::new();
        let mut primary_key = None;

        for field in &model.fields {
            let column_def = self.generate_column(field)?;
            if field.is_primary_key() {
                primary_key = Some(field.name.clone());
            }
            columns.push(column_def);
        }

        // Add primary key constraint if needed
        if let Some(pk) = &primary_key {
            columns.push(format!("    PRIMARY KEY ({})", pk));
        }

        writeln!(output, "{}", columns.join(",\n")).unwrap();
        writeln!(output, ");").unwrap();

        // Create indexes
        for index in &model.indexes {
            writeln!(output).unwrap();
            let index_sql = self.generate_index(&table_name, index, model)?;
            writeln!(output, "{}", index_sql).unwrap();
        }

        // Create implicit indexes for unique fields, but skip if an explicit
        // unique index already covers the same single field (avoids duplicates)
        let explicit_unique_fields: std::collections::HashSet<&str> = model.indexes.iter()
            .filter(|idx| matches!(idx.index_type, IndexType::Unique) && idx.fields.len() == 1)
            .map(|idx| idx.fields[0].as_str())
            .collect();

        for field in &model.fields {
            if field.is_unique() && !field.is_primary_key()
                && !explicit_unique_fields.contains(field.name.as_str())
            {
                writeln!(output).unwrap();
                writeln!(
                    output,
                    "CREATE UNIQUE INDEX IF NOT EXISTS idx_{}_{} ON {} ({});",
                    table_name, field.name, table_name, field.name
                )
                .unwrap();
            }
        }

        // Create GIN index and expression indexes for audit metadata JSONB fields
        // Also create triggers for automatic timestamp management
        for field in &model.fields {
            if field.has_attribute("audit_metadata") {
                writeln!(output).unwrap();
                writeln!(output, "-- GIN index for audit metadata JSONB queries").unwrap();
                writeln!(
                    output,
                    "CREATE INDEX IF NOT EXISTS idx_{}_{}_gin ON {} USING GIN ({});",
                    table_name, field.name, table_name, field.name
                )
                .unwrap();
                // Expression indexes for the audit timestamps. Stored as ISO-8601
                // strings inside the JSONB, so lex ordering on the text projection
                // matches chronological order — range queries like
                // `(metadata->>'created_at') >= '2026-01-01'` use the index without
                // needing an IMMUTABLE timestamptz cast wrapper.
                writeln!(
                    output,
                    "CREATE INDEX IF NOT EXISTS idx_{}_{}_deleted_at ON {} (({}->>'deleted_at'));",
                    table_name, field.name, table_name, field.name
                )
                .unwrap();
                writeln!(
                    output,
                    "CREATE INDEX IF NOT EXISTS idx_{}_{}_created_at ON {} (({}->>'created_at'));",
                    table_name, field.name, table_name, field.name
                )
                .unwrap();
                writeln!(
                    output,
                    "CREATE INDEX IF NOT EXISTS idx_{}_{}_updated_at ON {} (({}->>'updated_at'));",
                    table_name, field.name, table_name, field.name
                )
                .unwrap();

                // Generate triggers for automatic timestamp management
                writeln!(output).unwrap();
                self.generate_audit_triggers(&mut output, &table_name, field)?;
            }
        }

        Ok(output)
    }

    fn generate_column(&self, field: &Field) -> Result<String, GenerateError> {
        let sql_type = self.type_to_sql(&field.type_ref);
        let mut constraints: Vec<String> = Vec::new();

        // Special handling for @audit_metadata: JSONB column with audit fields default
        // This handles its own NOT NULL and DEFAULT, so check first to avoid duplicates
        if field.has_attribute("audit_metadata") {
            constraints.push("NOT NULL".to_string());
            constraints.push(format!("DEFAULT {}", AUDIT_METADATA_DEFAULT_JSON));
        } else {
            // NOT NULL constraint (only for non-audit-metadata fields)
            if field.is_required() && !field.type_ref.is_optional() {
                constraints.push("NOT NULL".to_string());
            }

            // DEFAULT value
            if let Some(default) = field.default_value() {
                let default_sql = self.default_to_sql(default, &field.type_ref);
                constraints.push(format!("DEFAULT {}", default_sql));
            } else if field.has_attribute("id") && matches!(field.type_ref, TypeRef::Primitive(PrimitiveType::Uuid)) {
                constraints.push("DEFAULT gen_random_uuid()".to_string());
            }
        }

        // JSONB type validation CHECK constraint (when field has jsonb_schema attribute)
        // Skip for audit_metadata fields since the default value ensures correct structure
        if field.has_attribute("jsonb_type") && !field.has_attribute("audit_metadata") {
            if let Some(schema_attr) = field.find_attribute("jsonb_schema") {
                if let Some(schema_json) = schema_attr.get_string_arg() {
                    // Generate CHECK constraint for JSONB field validation
                    // This validates required fields and basic structure
                    if let Some(check) = self.generate_jsonb_check(&field.name, schema_json) {
                        constraints.push(check);
                    }
                }
            }
        }

        let constraint_str = if constraints.is_empty() {
            String::new()
        } else {
            format!(" {}", constraints.join(" "))
        };

        Ok(format!("    {} {}{}", field.name, sql_type, constraint_str))
    }

    /// Generate JSONB CHECK constraint for type validation
    fn generate_jsonb_check(&self, field_name: &str, schema_json: &str) -> Option<String> {
        // Parse the schema JSON
        let schema: serde_json::Value = match serde_json::from_str(schema_json) {
            Ok(v) => v,
            Err(_) => return None,
        };

        let obj = schema.as_object()?;
        let mut checks = Vec::new();

        // Generate checks for required fields
        for (name, field_schema) in obj {
            let optional = field_schema.get("optional").and_then(|v| v.as_bool()).unwrap_or(false);

            if !optional {
                // Required field must be present
                checks.push(format!("{} ? '{}'", field_name, name));
            }
        }

        if checks.is_empty() {
            return None;
        }

        Some(format!("CHECK ({})", checks.join(" AND ")))
    }

    /// Generate audit metadata triggers for automatic timestamp management
    /// Creates triggers that automatically set created_at and updated_at in the metadata JSONB field
    fn generate_audit_triggers(&self, output: &mut String, table_name: &str, field: &Field) -> Result<(), GenerateError> {
        let field_name = &field.name;
        let trigger_func_name = format!("{}_audit_timestamp", table_name);
        let insert_trigger_name = format!("{}_insert_audit", table_name);
        let update_trigger_name = format!("{}_update_audit", table_name);

        writeln!(output, "-- Triggers for automatic {} timestamp management", field_name).unwrap();
        writeln!(output, "-- Automatically sets created_at on INSERT and updated_at on UPDATE").unwrap();
        writeln!(output).unwrap();

        // Create trigger function for INSERT (sets created_at)
        writeln!(output, "-- Function to set {}->'created_at' on INSERT", field_name).unwrap();
        writeln!(output, "CREATE OR REPLACE FUNCTION {}() RETURNS trigger AS $$", trigger_func_name).unwrap();
        writeln!(output, "BEGIN").unwrap();
        writeln!(output, "    IF TG_OP = 'INSERT' THEN").unwrap();
        writeln!(output, "        NEW.{} = jsonb_set(NEW.{}::jsonb, '{{created_at}}', to_jsonb(NOW()));", field_name, field_name).unwrap();
        writeln!(output, "        NEW.{} = jsonb_set(NEW.{}::jsonb, '{{updated_at}}', to_jsonb(NOW()));", field_name, field_name).unwrap();
        writeln!(output, "    ELSIF TG_OP = 'UPDATE' THEN").unwrap();
        writeln!(output, "        NEW.{} = jsonb_set(NEW.{}::jsonb, '{{updated_at}}', to_jsonb(NOW()));", field_name, field_name).unwrap();
        writeln!(output, "    END IF;").unwrap();
        writeln!(output, "    RETURN NEW;").unwrap();
        writeln!(output, "END;").unwrap();
        writeln!(output, "$$ LANGUAGE plpgsql;").unwrap();
        writeln!(output).unwrap();

        // Create INSERT trigger
        writeln!(output, "-- Trigger to set timestamps on INSERT",).unwrap();
        writeln!(output, "DROP TRIGGER IF EXISTS {} ON {};", insert_trigger_name, table_name).unwrap();
        writeln!(output, "CREATE TRIGGER {} BEFORE INSERT ON {}", insert_trigger_name, table_name).unwrap();
        writeln!(output, "    FOR EACH ROW EXECUTE FUNCTION {}();", trigger_func_name).unwrap();
        writeln!(output).unwrap();

        // Create UPDATE trigger
        writeln!(output, "-- Trigger to set updated_at on UPDATE",).unwrap();
        writeln!(output, "DROP TRIGGER IF EXISTS {} ON {};", update_trigger_name, table_name).unwrap();
        writeln!(output, "CREATE TRIGGER {} BEFORE UPDATE ON {}", update_trigger_name, table_name).unwrap();
        writeln!(output, "    FOR EACH ROW EXECUTE FUNCTION {}();", trigger_func_name).unwrap();

        Ok(())
    }

    fn generate_index(&self, table_name: &str, index: &Index, model: &Model) -> Result<String, GenerateError> {
        let index_name = index.name.clone().unwrap_or_else(|| {
            format!("idx_{}_{}", table_name, index.fields.join("_"))
        });

        let index_type = match index.index_type {
            IndexType::Unique => "UNIQUE INDEX",
            IndexType::Index => "INDEX",
            IndexType::Fulltext => "INDEX", // PostgreSQL uses GIN for fulltext
            IndexType::Gin => "INDEX",
        };

        let using_clause = match index.index_type {
            IndexType::Fulltext | IndexType::Gin => " USING GIN",
            _ => "",
        };

        // Resolve index fields: check each field exists as a real column,
        // or rewrite as JSONB expression if it's a sub-key of a JSONB field
        let resolved_fields: Vec<String> = index.fields.iter().map(|field_name| {
            self.resolve_index_field(field_name, model)
        }).collect();

        // Extract optional WHERE clause for partial indexes.
        // Audit-metadata sub-keys (e.g. `deleted_at`) referenced bare in the
        // clause must be rewritten to their JSONB expression form, since they
        // aren't real columns when the model stores audit data in an
        // `@audit_metadata` JSONB field.
        let where_clause = index.attributes.iter()
            .find(|a| a.name == "where")
            .and_then(|a| a.get_string_arg())
            .map(|w| format!(" WHERE {}", self.resolve_where_clause(w, model)))
            .unwrap_or_default();

        Ok(format!(
            "CREATE {} IF NOT EXISTS {}{} ON {} ({}){};",
            index_type,
            index_name,
            using_clause,
            table_name,
            resolved_fields.join(", "),
            where_clause
        ))
    }

    /// Resolve an index field name to its SQL column reference.
    ///
    /// If the field exists as a real column, return it as-is.
    /// If the field is a known sub-key of a JSONB field (e.g., `created_at` inside
    /// `metadata` with `@audit_metadata`), return a JSONB expression like
    /// `((metadata->>'created_at'))`.
    fn resolve_index_field(&self, field_name: &str, model: &Model) -> String {
        // If the field is already a JSONB expression (e.g., "(data->>'field')"), pass through as-is
        if field_name.contains("->>") {
            return format!("({})", field_name);
        }

        // Check if field exists as a real column
        if model.fields.iter().any(|f| f.name == field_name) {
            return field_name.to_string();
        }

        // Known sub-keys of audit_metadata JSONB fields
        const AUDIT_METADATA_KEYS: &[&str] = &[
            "created_at", "updated_at", "deleted_at",
            "created_by", "updated_by", "deleted_by",
        ];

        // Check if the field is a sub-key of an audit_metadata JSONB field
        if AUDIT_METADATA_KEYS.contains(&field_name) {
            if let Some(jsonb_field) = model.fields.iter().find(|f| f.has_attribute("audit_metadata")) {
                return format!("(({}->>'{}'))", jsonb_field.name, field_name);
            }
        }

        // Check if the field is a sub-key of any JSONB field by inspecting defaults
        for f in &model.fields {
            let is_json = matches!(f.type_ref, TypeRef::Primitive(PrimitiveType::Json))
                || matches!(&f.type_ref, TypeRef::Optional(inner) if matches!(inner.as_ref(), TypeRef::Primitive(PrimitiveType::Json)));
            if is_json {
                if let Some(default_val) = f.default_value() {
                    // Extract the raw string from AttributeValue::String,
                    // matching the validator's extraction logic
                    let default_str = match default_val {
                        crate::ast::AttributeValue::String(s) => s.clone(),
                        other => format!("{:?}", other),
                    };
                    if default_str.contains(field_name) {
                        return format!("(({}->>'{}'))", f.name, field_name);
                    }
                }
            }
        }

        // Field not found — emit as-is (will fail at migration time, alerting the developer)
        eprintln!(
            "WARNING: Index field '{}' not found as a column in model '{}'. \
             This will cause a migration error.",
            field_name, model.name
        );
        field_name.to_string()
    }

    /// Rewrite audit-metadata sub-keys appearing as bare identifiers in a
    /// partial-index `WHERE` clause to their JSONB expression form.
    ///
    /// For models carrying an `@audit_metadata` JSONB field (e.g. `metadata`),
    /// `deleted_at` (and the other audit keys) are stored *inside* that JSONB
    /// rather than as real columns. A clause authored as
    /// `WHERE deleted_at IS NULL` would therefore fail with
    /// `column "deleted_at" does not exist`.
    ///
    /// This rewrites bare audit-key identifiers (whole-word, outside string
    /// literals, not already qualified with `table.`) to
    /// `(metadata->>'deleted_at')`. Real columns shadow the JSONB key, so a
    /// model that declares `deleted_at` as a real column is left untouched.
    fn resolve_where_clause(&self, where_clause: &str, model: &Model) -> String {
        const AUDIT_METADATA_KEYS: &[&str] = &[
            "created_at", "updated_at", "deleted_at",
            "created_by", "updated_by", "deleted_by",
        ];

        let Some(jsonb_field) = model.fields.iter().find(|f| f.has_attribute("audit_metadata")) else {
            return where_clause.to_string();
        };

        let keys_to_rewrite: Vec<&str> = AUDIT_METADATA_KEYS.iter()
            .copied()
            .filter(|key| !model.fields.iter().any(|f| f.name == *key))
            .collect();

        if keys_to_rewrite.is_empty() {
            return where_clause.to_string();
        }

        let mut out = String::with_capacity(where_clause.len());
        let bytes = where_clause.as_bytes();
        let mut i = 0;
        let mut in_string = false;

        while i < bytes.len() {
            let b = bytes[i];

            if in_string {
                out.push(b as char);
                if b == b'\'' {
                    in_string = false;
                }
                i += 1;
                continue;
            }

            if b == b'\'' {
                in_string = true;
                out.push(b as char);
                i += 1;
                continue;
            }

            if b.is_ascii_alphabetic() || b == b'_' {
                let start = i;
                while i < bytes.len() && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
                    i += 1;
                }
                let ident = &where_clause[start..i];
                let prev_is_dot = start > 0 && bytes[start - 1] == b'.';
                if !prev_is_dot && keys_to_rewrite.contains(&ident) {
                    write!(out, "({}->>'{}')", jsonb_field.name, ident).unwrap();
                } else {
                    out.push_str(ident);
                }
                continue;
            }

            out.push(b as char);
            i += 1;
        }

        out
    }

    fn generate_enum(&self, enum_def: &EnumDef) -> Result<String, GenerateError> {
        let mut output = String::new();
        let type_name = to_snake_case(&enum_def.name);

        // Create enum type
        writeln!(output, "-- Create {} enum type", type_name).unwrap();
        writeln!(output, "DO $$").unwrap();
        writeln!(output, "BEGIN").unwrap();
        writeln!(output, "    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{}') THEN", type_name).unwrap();
        write!(output, "        CREATE TYPE {} AS ENUM (", type_name).unwrap();

        let variants: Vec<String> = enum_def
            .variants
            .iter()
            .map(|v| format!("'{}'", to_snake_case(&v.name)))
            .collect();

        writeln!(output, "{});", variants.join(", ")).unwrap();
        writeln!(output, "    END IF;").unwrap();
        writeln!(output, "END").unwrap();
        writeln!(output, "$$;").unwrap();

        Ok(output)
    }

    fn generate_foreign_keys(&self, model: &Model, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();
        let table_name = model.collection_name();

        for relation in &model.relations {
            // Skip many-to-many relations here - they need join tables
            if relation.relation_type == RelationType::ManyToMany {
                continue;
            }

            // Skip one-to-many relations - the FK column lives on the CHILD table,
            // not on this (parent) table. The child's @one relation handles the FK.
            if relation.relation_type == RelationType::Many {
                continue;
            }

            // Check if this relation should have a database foreign key
            if !relation.has_database_fk() {
                continue;
            }

            // Determine foreign key column name
            let fk_column = if let Some(explicit_fk) = relation.foreign_key() {
                explicit_fk
            } else {
                // Auto-generate FK column name based on relation name
                // For "user" relation -> "user_id"
                format!("{}_id", to_snake_case(&relation.name))
            };

            // Verify the FK column actually exists in this model's fields
            let column_exists = model.fields.iter().any(|f| f.name == fk_column);
            if !column_exists {
                // FK column doesn't exist on this table - skip this constraint
                continue;
            }

            let target_name = get_relation_target_table(&relation.target, &schema.schema);
            let references = relation.references();

            // Build constraint name
            let constraint_name = format!("fk_{}_{}", table_name, fk_column);

            // Build ON DELETE clause
            let on_delete = match relation.on_delete() {
                ForeignKeyAction::Cascade => "ON DELETE CASCADE",
                ForeignKeyAction::SetNull => "ON DELETE SET NULL",
                ForeignKeyAction::SetDefault => "ON DELETE SET DEFAULT",
                ForeignKeyAction::Restrict => "ON DELETE RESTRICT",
                ForeignKeyAction::NoAction => "", // default
            };

            // Build ON UPDATE clause
            let on_update = match relation.on_update() {
                ForeignKeyAction::Cascade => "ON UPDATE CASCADE",
                ForeignKeyAction::SetNull => "ON UPDATE SET NULL",
                ForeignKeyAction::SetDefault => "ON UPDATE SET DEFAULT",
                ForeignKeyAction::Restrict => "ON UPDATE RESTRICT",
                ForeignKeyAction::NoAction => "", // default
            };

            // Combine actions
            let actions = [on_delete, on_update]
                .iter()
                .filter(|s| !s.is_empty())
                .map(|s| s.to_string())
                .collect::<Vec<_>>()
                .join(" ");

            let actions_sql = if actions.is_empty() {
                String::new()
            } else {
                format!(" {}", actions)
            };

            writeln!(
                output,
                "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({}){};",
                table_name, constraint_name, fk_column, target_name, references, actions_sql
            ).unwrap();
        }

        Ok(output)
    }

    /// Generate join tables for many-to-many relationships
    fn generate_join_tables(&self, schema: &ResolvedSchema) -> Result<String, GenerateError> {
        let mut output = String::new();

        // Collect all many-to-many relations
        let mut m2m_relations: Vec<(String, &crate::ast::Relation)> = Vec::new();

        for model in &schema.schema.models {
            for relation in &model.relations {
                if relation.relation_type == RelationType::ManyToMany {
                    // Track relation with its source model
                    m2m_relations.push((model.name.clone(), relation));
                }
            }
        }

        // Generate join tables (avoiding duplicates)
        let mut processed_tables = std::collections::HashSet::new();

        for (source_model, relation) in m2m_relations {
            let table_name = if let Some(custom_name) = relation.join_table() {
                custom_name
            } else {
                // Auto-generate: combine both model names alphabetically
                let target_name = get_relation_target_table(&relation.target, &schema.schema);
                let source_name = to_snake_case(&source_model);
                let mut names = [source_name.clone(), target_name.clone()];
                names.sort();
                format!("{}_{}", names[0], names[1])
            };

            // Skip if we already processed this join table
            if !processed_tables.insert(table_name.clone()) {
                continue;
            }

            writeln!(output, "-- Join table for {} <-> {}", source_model, get_relation_target_table(&relation.target, &schema.schema)).unwrap();
            writeln!(output, "CREATE TABLE IF NOT EXISTS {} (", table_name).unwrap();

            // Determine foreign key column names
            let source_fk = relation.join_foreign_key()
                .unwrap_or_else(|| format!("{}_id", to_snake_case(&source_model)));

            let target_name = get_relation_target_table(&relation.target, &schema.schema);
            let target_fk = format!("{}_id", target_name.trim_end_matches('s'));

            // Composite primary key
            writeln!(output, "    {} UUID NOT NULL,", source_fk).unwrap();
            writeln!(output, "    {} UUID NOT NULL,", target_fk).unwrap();
            writeln!(output, "    PRIMARY KEY ({}, {}),", source_fk, target_fk).unwrap();

            writeln!(output, ");").unwrap();
            writeln!(output).unwrap();

            // Foreign key to source table
            let fk1_name = format!("fk_{}_{}_fk", table_name, source_fk);
            let source_table = format!("{}s", to_snake_case(&source_model)); // pluralize
            writeln!(
                output,
                "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} (id) ON DELETE CASCADE;",
                table_name, fk1_name, source_fk, source_table
            ).unwrap();
            writeln!(output).unwrap();

            // Foreign key to target table
            let fk2_name = format!("fk_{}_{}_fk", table_name, target_fk);
            writeln!(
                output,
                "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} (id) ON DELETE CASCADE;",
                table_name, fk2_name, target_fk, target_name
            ).unwrap();
            writeln!(output).unwrap();

            // Indexes for join table
            writeln!(
                output,
                "CREATE INDEX IF NOT EXISTS idx_{}_{} ON {} ({});",
                table_name, source_fk, table_name, source_fk
            ).unwrap();
            writeln!(
                output,
                "CREATE INDEX IF NOT EXISTS idx_{}_{} ON {} ({});",
                table_name, target_fk, table_name, target_fk
            ).unwrap();
            writeln!(output).unwrap();
        }

        Ok(output)
    }

    fn type_to_sql(&self, type_ref: &TypeRef) -> String {
        match type_ref {
            TypeRef::Primitive(p) => p.postgres_type().to_string(),
            TypeRef::Custom(name) => to_snake_case(name), // Assume it's an enum
            TypeRef::Array(inner) => format!("{}[]", self.type_to_sql(inner)),
            TypeRef::Optional(inner) => self.type_to_sql(inner),
            TypeRef::Map { .. } => "JSONB".to_string(),
            TypeRef::ModuleRef { .. } => "TEXT".to_string(), // Cross-module refs stored as IDs
        }
    }

    fn default_to_sql(&self, value: &crate::ast::AttributeValue, type_ref: &TypeRef) -> String {
        // Check if this is a JSON/JSONB field type
        let is_json_field = matches!(type_ref, TypeRef::Primitive(PrimitiveType::Json))
            || matches!(type_ref, TypeRef::Optional(inner) if matches!(inner.as_ref(), TypeRef::Primitive(PrimitiveType::Json)));

        match value {
            crate::ast::AttributeValue::String(s) => {
                // For JSON fields, try to validate and cast string as JSONB
                if is_json_field {
                    // Check if string looks like JSON (starts with { or [)
                    let trimmed = s.trim();
                    if trimmed.starts_with('{') || trimmed.starts_with('[') {
                        format!("'{}'::jsonb", s.replace("'", "''"))
                    } else {
                        format!("'{}'", s)
                    }
                } else {
                    format!("'{}'", s)
                }
            }
            crate::ast::AttributeValue::Int(n) => n.to_string(),
            crate::ast::AttributeValue::Float(n) => n.to_string(),
            crate::ast::AttributeValue::Bool(b) => b.to_string().to_uppercase(),
            crate::ast::AttributeValue::Ident(s) => {
                // Handle special defaults
                match s.as_str() {
                    "uuid" => "gen_random_uuid()".to_string(),
                    "now" => "NOW()".to_string(),
                    "true" => "TRUE".to_string(),
                    "false" => "FALSE".to_string(),
                    _ => format!("'{}'", s), // Treat as enum value
                }
            }
            crate::ast::AttributeValue::Array(arr) => {
                // Serialize array to JSON
                if let Ok(json) = serde_json::to_string(arr) {
                    format!("'{}'::jsonb", json.replace("'", "''"))
                } else {
                    "'[]'::jsonb".to_string()
                }
            }
            crate::ast::AttributeValue::Object(obj) => {
                // Serialize object to JSONB
                if let Ok(json) = serde_json::to_string(obj) {
                    format!("'{}'::jsonb", json.replace("'", "''"))
                } else {
                    "'{}'::jsonb".to_string()
                }
            }
        }
    }
}

impl Default for SqlGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for SqlGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        if self.split {
            // Split mode: generate separate files for each model
            self.generate_split(&mut output, schema)?;
        } else {
            // Single file mode: generate one migration file
            self.generate_single(&mut output, schema)?;
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "sql"
    }
}

impl SqlGenerator {
    /// Generate split migration files (one per model)
    fn generate_split(&self, output: &mut GeneratedOutput, schema: &ResolvedSchema) -> Result<(), GenerateError> {
        let module_name = to_snake_case(&schema.schema.name);

        // 001: Create enum types
        if !schema.schema.enums.is_empty() {
            let mut enums_sql = String::new();
            writeln!(enums_sql, "-- Enum types for {} module", module_name).unwrap();
            writeln!(enums_sql, "-- Generated by metaphor-schema").unwrap();
            writeln!(enums_sql).unwrap();

            for enum_def in &schema.schema.enums {
                let enum_sql = self.generate_enum(enum_def)?;
                writeln!(enums_sql, "{}", enum_sql).unwrap();
            }

            let path = PathBuf::from("migrations/001_create_enums.up.sql");
            output.add_file(path, enums_sql);
        }

        // Generate one file per model (002, 003, ...)
        for (i, model) in schema.schema.models.iter().enumerate() {
            let model_snake = to_snake_case(&model.name);
            let seq = format!("{:03}", i + 2); // Start from 002

            let mut model_sql = String::new();

            // Add table creation
            let table_sql = self.generate_table(model)?;
            writeln!(model_sql, "{}", table_sql).unwrap();

            let path = PathBuf::from(format!(
                "migrations/{}_create_{}_table.up.sql",
                seq, model_snake
            ));
            output.add_file(path, model_sql);
        }

        // Generate foreign keys file (after all tables)
        let mut has_fk = false;
        let mut fk_sql = String::new();
        writeln!(fk_sql, "-- Foreign key constraints for {} module", module_name).unwrap();
        writeln!(fk_sql, "-- Generated by metaphor-schema").unwrap();
        writeln!(fk_sql).unwrap();

        for model in &schema.schema.models {
            let fk_content = self.generate_foreign_keys(model, schema)?;
            if !fk_content.is_empty() {
                has_fk = true;
                writeln!(fk_sql, "{}", fk_content).unwrap();
            }
        }

        if has_fk {
            let seq = format!("{:03}", schema.schema.models.len() + 2);
            let path = PathBuf::from(format!(
                "migrations/{}_add_foreign_keys.up.sql",
                seq
            ));
            output.add_file(path, fk_sql);
        }

        // Generate join tables for many-to-many relationships
        let join_tables_sql = self.generate_join_tables(schema)?;
        if !join_tables_sql.is_empty() {
            let seq = format!("{:03}", schema.schema.models.len() + if has_fk { 3 } else { 2 });
            let path = PathBuf::from(format!(
                "migrations/{}_create_join_tables.up.sql",
                seq
            ));
            let mut full_sql = String::new();
            writeln!(full_sql, "-- Join tables for {} module", module_name).unwrap();
            writeln!(full_sql, "-- Generated by metaphor-schema").unwrap();
            writeln!(full_sql).unwrap();
            writeln!(full_sql, "{}", join_tables_sql).unwrap();
            output.add_file(path, full_sql);
        }

        // Generate down migrations
        self.generate_down_migrations(output, schema)?;

        Ok(())
    }

    /// Generate single migration file (legacy mode)
    fn generate_single(&self, output: &mut GeneratedOutput, schema: &ResolvedSchema) -> Result<(), GenerateError> {
        let version = self.version.clone().unwrap_or_else(|| {
            // Use fixed version to avoid duplicate files
            "001".to_string()
        });

        let mut migration = String::new();

        // Generate enums first
        for enum_def in &schema.schema.enums {
            let enum_sql = self.generate_enum(enum_def)?;
            writeln!(migration, "{}", enum_sql).unwrap();
            writeln!(migration).unwrap();
        }

        // Generate tables
        for model in &schema.schema.models {
            let table_sql = self.generate_table(model)?;
            writeln!(migration, "{}", table_sql).unwrap();
            writeln!(migration).unwrap();
        }

        // Generate foreign key constraints (after all tables exist)
        for model in &schema.schema.models {
            let fk_sql = self.generate_foreign_keys(model, schema)?;
            if !fk_sql.is_empty() {
                writeln!(migration, "{}", fk_sql).unwrap();
            }
        }

        // Generate join tables for many-to-many relationships
        let join_tables_sql = self.generate_join_tables(schema)?;
        if !join_tables_sql.is_empty() {
            writeln!(migration, "{}", join_tables_sql).unwrap();
        }

        let path = PathBuf::from(format!(
            "migrations/{}_create_tables.up.sql",
            version
        ));

        output.add_file(path, migration);

        Ok(())
    }

    /// Generate down migrations (for rollback)
    fn generate_down_migrations(&self, output: &mut GeneratedOutput, schema: &ResolvedSchema) -> Result<(), GenerateError> {
        let module_name = to_snake_case(&schema.schema.name);
        let mut down_sql = String::new();

        writeln!(down_sql, "-- Down migration for {} module", module_name).unwrap();
        writeln!(down_sql, "-- Generated by metaphor-schema").unwrap();
        writeln!(down_sql).unwrap();

        // Collect and drop join tables first (they have FKs to main tables)
        let mut join_tables = std::collections::HashSet::new();
        for model in &schema.schema.models {
            for relation in &model.relations {
                if relation.relation_type == RelationType::ManyToMany {
                    let table_name = if let Some(custom_name) = relation.join_table() {
                        custom_name
                    } else {
                        let target_name = get_relation_target_table(&relation.target, &schema.schema);
                        let source_name = to_snake_case(&model.name);
                        let mut names = [source_name.clone(), target_name.clone()];
                        names.sort();
                        format!("{}_{}", names[0], names[1])
                    };
                    join_tables.insert(table_name);
                }
            }
        }

        // Drop join tables
        for table_name in join_tables {
            writeln!(down_sql, "DROP TABLE IF EXISTS {} CASCADE;", table_name).unwrap();
        }

        writeln!(down_sql).unwrap();

        // Drop tables in reverse order
        for model in schema.schema.models.iter().rev() {
            let table_name = model.collection_name();
            writeln!(down_sql, "DROP TABLE IF EXISTS {} CASCADE;", table_name).unwrap();
        }

        writeln!(down_sql).unwrap();

        // Drop enums
        for enum_def in &schema.schema.enums {
            let type_name = to_snake_case(&enum_def.name);
            writeln!(down_sql, "DROP TYPE IF EXISTS {} CASCADE;", type_name).unwrap();
        }

        let path = PathBuf::from("migrations/down.sql");
        output.add_file(path, down_sql);

        Ok(())
    }
}

fn get_relation_target_table(type_ref: &TypeRef, schema: &crate::ast::ModuleSchema) -> String {
    match type_ref {
        TypeRef::Custom(name) => {
            // Look for the model in the schema to get its actual collection name
            schema.models.iter()
                .find(|m| &m.name == name)
                .map(|m| m.collection_name())
                .unwrap_or_else(|| to_snake_case(name) + "s")
        }
        TypeRef::Array(inner) => get_relation_target_table(inner, schema),
        TypeRef::Optional(inner) => get_relation_target_table(inner, schema),
        TypeRef::ModuleRef { module, name } => {
            // For cross-module references, we can't look up the actual model
            // since it's in a different module. Use the module-qualified table name.
            // We need to properly pluralize the name.
            format!("{}.{}", module, pluralize(&to_snake_case(name)))
        }
        _ => "unknown".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, AttributeValue, ModuleSchema, PrimitiveType};

    fn create_test_model() -> Model {
        let mut model = Model::new("User");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "email".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Email),
                attributes: vec![Attribute::new("unique")],
                ..Default::default()
            },
            Field {
                name: "name".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_sql_generator_split_creates_files() {
        let schema = create_test_schema();
        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&schema).unwrap();

        // Should create per-model migration files directly in migrations/
        assert!(output.files.contains_key(&PathBuf::from("migrations/002_create_user_table.up.sql")));
        assert!(output.files.contains_key(&PathBuf::from("migrations/down.sql")));
    }

    #[test]
    fn test_sql_generator_single_creates_file() {
        let schema = create_test_schema();
        let generator = SqlGenerator::new().with_split(false);
        let output = generator.generate(&schema).unwrap();

        // Should create single migration file directly in migrations/
        assert!(output.files.contains_key(&PathBuf::from("migrations/001_create_tables.up.sql")));
    }

    #[test]
    fn test_sql_generator_creates_table() {
        let schema = create_test_schema();
        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("migrations/002_create_user_table.up.sql")).unwrap();

        assert!(content.contains("CREATE TABLE IF NOT EXISTS users"));
        assert!(content.contains("id UUID"));
        assert!(content.contains("email TEXT"));
        assert!(content.contains("PRIMARY KEY (id)"));
    }

    #[test]
    fn test_sql_generator_creates_unique_index() {
        let schema = create_test_schema();
        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("migrations/002_create_user_table.up.sql")).unwrap();

        assert!(content.contains("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email"));
    }

    /// Audit-metadata models should get text-typed expression indexes on
    /// `created_at`, `updated_at`, and `deleted_at` so range queries against
    /// the JSONB-stored timestamps don't fall back to full table scans.
    /// (ISO-8601 string ordering matches chronological order, so lex compares
    /// behave correctly without needing an IMMUTABLE timestamptz cast.)
    #[test]
    fn test_audit_metadata_emits_timestamp_expression_indexes() {
        let mut model = Model::new("Account");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "metadata".to_string(),
                type_ref: TypeRef::Custom("Metadata".to_string()),
                attributes: vec![Attribute::new("audit_metadata")],
                ..Default::default()
            },
        ];

        let mut schema = ModuleSchema::new("test");
        schema.models.push(model);
        let resolved = ResolvedSchema { schema };

        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&resolved).unwrap();
        let content = output.files
            .get(&PathBuf::from("migrations/002_create_account_table.up.sql"))
            .unwrap();

        assert!(
            content.contains("idx_accounts_metadata_created_at ON accounts ((metadata->>'created_at'))"),
            "expected created_at expression index, got:\n{}", content
        );
        assert!(
            content.contains("idx_accounts_metadata_updated_at ON accounts ((metadata->>'updated_at'))"),
            "expected updated_at expression index, got:\n{}", content
        );
        assert!(
            content.contains("idx_accounts_metadata_deleted_at ON accounts ((metadata->>'deleted_at'))"),
            "expected deleted_at expression index (regression check), got:\n{}", content
        );
    }

    /// Models with `@audit_metadata` store `deleted_at` inside a JSONB column,
    /// so partial indexes authored as `WHERE deleted_at IS NULL` must be
    /// rewritten to `WHERE (metadata->>'deleted_at') IS NULL` — otherwise the
    /// migration fails with `column "deleted_at" does not exist`.
    #[test]
    fn test_partial_index_where_rewrites_audit_metadata_keys() {
        let mut model = Model::new("Account");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "account_number".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![Attribute::new("required")],
                ..Default::default()
            },
            Field {
                name: "metadata".to_string(),
                type_ref: TypeRef::Custom("Metadata".to_string()),
                attributes: vec![Attribute::new("audit_metadata")],
                ..Default::default()
            },
        ];
        model.indexes.push(Index {
            fields: vec!["account_number".to_string()],
            index_type: IndexType::Unique,
            attributes: vec![
                Attribute::new("where")
                    .with_arg(AttributeValue::String("deleted_at IS NULL".to_string())),
            ],
            ..Default::default()
        });

        let mut schema = ModuleSchema::new("test");
        schema.models.push(model);
        let resolved = ResolvedSchema { schema };

        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&resolved).unwrap();
        let content = output.files
            .get(&PathBuf::from("migrations/002_create_account_table.up.sql"))
            .unwrap();

        assert!(
            content.contains("WHERE (metadata->>'deleted_at') IS NULL"),
            "expected JSONB-rewritten WHERE clause, got:\n{}",
            content
        );
        assert!(
            !content.contains("WHERE deleted_at IS NULL"),
            "raw `deleted_at` should not appear as a top-level column in WHERE, got:\n{}",
            content
        );
    }

    /// String literals inside the WHERE clause must be passed through
    /// unchanged — only bare identifiers are rewritten.
    #[test]
    fn test_partial_index_where_preserves_string_literals() {
        let mut model = Model::new("Job");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "label".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![Attribute::new("required")],
                ..Default::default()
            },
            Field {
                name: "metadata".to_string(),
                type_ref: TypeRef::Custom("Metadata".to_string()),
                attributes: vec![Attribute::new("audit_metadata")],
                ..Default::default()
            },
        ];
        model.indexes.push(Index {
            fields: vec!["label".to_string()],
            index_type: IndexType::Index,
            attributes: vec![
                Attribute::new("where")
                    .with_arg(AttributeValue::String(
                        "deleted_at IS NULL AND label != 'deleted_at'".to_string(),
                    )),
            ],
            ..Default::default()
        });

        let mut schema = ModuleSchema::new("test");
        schema.models.push(model);
        let resolved = ResolvedSchema { schema };

        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&resolved).unwrap();
        let content = output.files
            .get(&PathBuf::from("migrations/002_create_job_table.up.sql"))
            .unwrap();

        // Bare identifier rewritten:
        assert!(content.contains("(metadata->>'deleted_at') IS NULL"), "got:\n{}", content);
        // String literal preserved verbatim:
        assert!(content.contains("label != 'deleted_at'"), "got:\n{}", content);
    }

    /// If the model declares `deleted_at` as a real column, that column
    /// shadows the audit-metadata sub-key and the WHERE clause should be
    /// left alone.
    #[test]
    fn test_partial_index_where_skips_rewrite_when_real_column_shadows_audit_key() {
        let mut model = Model::new("Legacy");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "name".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![Attribute::new("required")],
                ..Default::default()
            },
            Field {
                name: "deleted_at".to_string(),
                type_ref: TypeRef::Optional(Box::new(TypeRef::Primitive(PrimitiveType::DateTime))),
                attributes: vec![],
                ..Default::default()
            },
            Field {
                name: "metadata".to_string(),
                type_ref: TypeRef::Custom("Metadata".to_string()),
                attributes: vec![Attribute::new("audit_metadata")],
                ..Default::default()
            },
        ];
        model.indexes.push(Index {
            fields: vec!["name".to_string()],
            index_type: IndexType::Unique,
            attributes: vec![
                Attribute::new("where")
                    .with_arg(AttributeValue::String("deleted_at IS NULL".to_string())),
            ],
            ..Default::default()
        });

        let mut schema = ModuleSchema::new("test");
        schema.models.push(model);
        let resolved = ResolvedSchema { schema };

        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&resolved).unwrap();
        let content = output.files
            .get(&PathBuf::from("migrations/002_create_legacy_table.up.sql"))
            .unwrap();

        assert!(
            content.contains("WHERE deleted_at IS NULL"),
            "real column should not be rewritten, got:\n{}",
            content
        );
        assert!(
            !content.contains("(metadata->>'deleted_at') IS NULL"),
            "should not produce JSONB rewrite when real column shadows the audit key, got:\n{}",
            content
        );
    }

    #[test]
    fn test_sql_generator_creates_down_migration() {
        let schema = create_test_schema();
        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&schema).unwrap();

        let content = output.files.get(&PathBuf::from("migrations/down.sql")).unwrap();

        assert!(content.contains("DROP TABLE IF EXISTS users CASCADE"));
    }

    #[test]
    fn test_sql_generator_creates_foreign_key_with_cascade() {
        let mut post_model = Model::new("Post");
        post_model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "title".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![],
                ..Default::default()
            },
        ];

        // Add relation with cascade
        post_model.relations.push(crate::ast::Relation {
            name: "author".to_string(),
            target: TypeRef::Custom("User".to_string()),
            relation_type: RelationType::One,
            attributes: vec![
                Attribute::new("on_delete").with_arg(AttributeValue::Ident("cascade".to_string())),
                Attribute::new("on_update").with_arg(AttributeValue::Ident("cascade".to_string())),
            ],
            ..Default::default()
        });

        let mut schema = ModuleSchema::new("test");
        schema.models.push(post_model);
        schema.models.push(create_test_model());

        let resolved = ResolvedSchema { schema };

        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&resolved).unwrap();

        // Check that foreign key file is created
        let fk_content = output.files.get(&PathBuf::from("migrations/004_add_foreign_keys.up.sql")).unwrap();
        assert!(fk_content.contains("ALTER TABLE posts ADD CONSTRAINT fk_posts_author_id"));
        assert!(fk_content.contains("FOREIGN KEY (author_id) REFERENCES users"));
        assert!(fk_content.contains("ON DELETE CASCADE"));
        assert!(fk_content.contains("ON UPDATE CASCADE"));
    }

    #[test]
    fn test_sql_generator_creates_join_table_for_many_to_many() {
        let mut user_model = create_test_model();
        let mut role_model = Model::new("Role");
        role_model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "name".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![Attribute::new("unique")],
                ..Default::default()
            },
        ];

        // Add many-to-many relation
        user_model.relations.push(crate::ast::Relation {
            name: "roles".to_string(),
            target: TypeRef::Array(Box::new(TypeRef::Custom("Role".to_string()))),
            relation_type: RelationType::ManyToMany,
            attributes: vec![Attribute::new("many_to_many")],
            ..Default::default()
        });

        let mut schema = ModuleSchema::new("test");
        schema.models.push(user_model);
        schema.models.push(role_model);

        let resolved = ResolvedSchema { schema };

        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&resolved).unwrap();

        // Verify a join tables file was created
        let join_key = output.files.keys().find(|k| k.to_string_lossy().contains("create_join_tables")).unwrap();
        let join_content = output.files.get(join_key).unwrap();

        // Check for key elements of join table
        assert!(join_content.contains("CREATE TABLE IF NOT EXISTS"));
        assert!(join_content.contains("role_id UUID NOT NULL"));
        assert!(join_content.contains("user_id UUID NOT NULL"));
        assert!(join_content.contains("PRIMARY KEY"));
        assert!(join_content.contains("FOREIGN KEY"));
        assert!(join_content.contains("REFERENCES users"));
        assert!(join_content.contains("REFERENCES roles"));
        assert!(join_content.contains("ON DELETE CASCADE"));
    }

    #[test]
    fn test_sql_generator_custom_join_table_name() {
        let mut user_model = create_test_model();
        let mut role_model = Model::new("Role");
        role_model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
            Field {
                name: "name".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::String),
                attributes: vec![Attribute::new("unique")],
                ..Default::default()
            },
        ];

        // Add many-to-many relation with custom join table name
        user_model.relations.push(crate::ast::Relation {
            name: "roles".to_string(),
            target: TypeRef::Array(Box::new(TypeRef::Custom("Role".to_string()))),
            relation_type: RelationType::ManyToMany,
            attributes: vec![
                Attribute::new("many_to_many"),
                Attribute::new("join_table").with_arg(AttributeValue::String("user_roles".to_string())),
            ],
            ..Default::default()
        });

        let mut schema = ModuleSchema::new("test");
        schema.models.push(user_model);
        schema.models.push(role_model);

        let resolved = ResolvedSchema { schema };

        let generator = SqlGenerator::new().with_split(true);
        let output = generator.generate(&resolved).unwrap();

        // Find the join tables file
        let join_key = output.files.keys().find(|k| k.to_string_lossy().contains("create_join_tables")).unwrap();
        let join_content = output.files.get(join_key).unwrap();
        assert!(join_content.contains("CREATE TABLE IF NOT EXISTS user_roles"));
    }
}
