//! Trigger handler generator
//!
//! Generates trigger/event handlers from hook definitions.
//! This includes:
//! - Lifecycle triggers (before/after create, update, delete)
//! - State machine triggers (on transition, on enter/exit state)
//! - Action handlers (send_email, notify, webhook, etc.)

use super::{GenerateError, GeneratedOutput, Generator};
use crate::ast::hook::{ActionKind, Hook, TriggerEvent};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use crate::utils::escape_rust_keyword;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates trigger handlers from hook definitions
pub struct TriggerGenerator;

impl TriggerGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate trigger handlers for a model/hook pair
    fn generate_triggers(&self, model: &Model, hook: &Hook) -> Result<String, GenerateError> {
        let mut output = String::new();

        // File header and imports
        self.write_imports(&mut output, model, hook)?;

        // Type aliases pointing to backbone-core generics (composition pattern)
        self.write_type_aliases(&mut output, model)?;

        // Generate lifecycle triggers
        self.write_lifecycle_triggers(&mut output, model, hook)?;

        // Generate state machine triggers if present
        if let Some(sm) = &hook.state_machine {
            self.write_state_triggers(&mut output, model, sm)?;
        }

        // Registry builder function
        self.write_trigger_registry_fn(&mut output, model, hook)?;

        Ok(output)
    }

    fn write_imports(&self, output: &mut String, model: &Model, _hook: &Hook) -> Result<(), GenerateError> {
        writeln!(output, "//! {} trigger handlers", model.name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Auto-generated by backbone-cli. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use std::sync::Arc;").unwrap();
        writeln!(output, "use async_trait::async_trait;").unwrap();
        writeln!(output, "use backbone_core::trigger::{{").unwrap();
        writeln!(output, "    ActionExecutor, TriggerContext, TriggerContextMut, TriggerEvent, TriggerHandler, TriggerRegistry,").unwrap();
        writeln!(output, "}};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use crate::domain::entity::{};", model.name).unwrap();
        writeln!(output).unwrap();

        Ok(())
    }

    /// Emit type aliases that point to backbone-core generic types (composition pattern).
    ///
    /// Replaces the old per-entity TriggerEvent enum, TriggerContext struct,
    /// ActionExecutor struct, and TriggerRegistry struct.
    fn write_type_aliases(&self, output: &mut String, model: &Model) -> Result<(), GenerateError> {
        let n = &model.name;
        writeln!(output, "pub type {n}TriggerEvent      = TriggerEvent;").unwrap();
        writeln!(output, "pub type {n}TriggerContext    = TriggerContext<{n}>;").unwrap();
        writeln!(output, "pub type {n}TriggerContextMut = TriggerContextMut<{n}>;").unwrap();
        writeln!(output, "pub type {n}ActionExecutor    = ActionExecutor;").unwrap();
        writeln!(output, "pub type {n}TriggerRegistry   = TriggerRegistry<{n}>;").unwrap();
        writeln!(output, "pub type {n}TriggerHandlerObj =").unwrap();
        writeln!(output, "    dyn TriggerHandler<TriggerContext<{n}>, TriggerEvent>;").unwrap();
        writeln!(output).unwrap();
        Ok(())
    }

    fn write_lifecycle_triggers(&self, output: &mut String, model: &Model, hook: &Hook) -> Result<(), GenerateError> {
        // Group triggers by event type
        let lifecycle_triggers: Vec<_> = hook.triggers.iter()
            .filter(|t| matches!(t.event,
                TriggerEvent::BeforeCreate | TriggerEvent::AfterCreate |
                TriggerEvent::BeforeUpdate | TriggerEvent::AfterUpdate |
                TriggerEvent::BeforeDelete | TriggerEvent::AfterDelete
            ))
            .collect();

        if lifecycle_triggers.is_empty() {
            return Ok(());
        }

        writeln!(output, "// Lifecycle trigger handlers").unwrap();
        writeln!(output).unwrap();

        for (i, trigger) in lifecycle_triggers.iter().enumerate() {
            let event_name = match &trigger.event {
                TriggerEvent::BeforeCreate => "BeforeCreate",
                TriggerEvent::AfterCreate => "AfterCreate",
                TriggerEvent::BeforeUpdate => "BeforeUpdate",
                TriggerEvent::AfterUpdate => "AfterUpdate",
                TriggerEvent::BeforeDelete => "BeforeDelete",
                TriggerEvent::AfterDelete => "AfterDelete",
                _ => continue,
            };

            let handler_name = format!("{}{}Handler{}", model.name, event_name, i + 1);

            writeln!(output, "/// {} handler", event_name).unwrap();
            writeln!(output, "pub struct {} {{", handler_name).unwrap();
            writeln!(output, "    /// Event publisher for emitting domain events").unwrap();
            writeln!(output, "    pub event_publisher: Option<Arc<crate::domain::event::{}EventPublisher>>,", model.name).unwrap();
            writeln!(output, "    /// Action executor for side effects").unwrap();
            writeln!(output, "    pub action_executor: Option<Arc<{}ActionExecutor>>,", model.name).unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "impl {} {{", handler_name).unwrap();
            writeln!(output, "    pub fn new() -> Self {{").unwrap();
            writeln!(output, "        Self {{").unwrap();
            writeln!(output, "            event_publisher: None,").unwrap();
            writeln!(output, "            action_executor: None,").unwrap();
            writeln!(output, "        }}").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output).unwrap();
            writeln!(output, "    pub fn with_event_publisher(mut self, publisher: Arc<crate::domain::event::{}EventPublisher>) -> Self {{", model.name).unwrap();
            writeln!(output, "        self.event_publisher = Some(publisher);").unwrap();
            writeln!(output, "        self").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output).unwrap();
            writeln!(output, "    pub fn with_action_executor(mut self, executor: Arc<{}ActionExecutor>) -> Self {{", model.name).unwrap();
            writeln!(output, "        self.action_executor = Some(executor);").unwrap();
            writeln!(output, "        self").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "#[async_trait]").unwrap();
            writeln!(output, "impl TriggerHandler<{n}TriggerContext, {n}TriggerEvent> for {h} {{",
                n = model.name, h = handler_name).unwrap();
            writeln!(output, "    fn events(&self) -> Vec<{n}TriggerEvent> {{", n = model.name).unwrap();
            writeln!(output, "        vec![TriggerEvent::{}]", event_name).unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output).unwrap();

            writeln!(output, "    async fn handle(&self, ctx: &{}TriggerContext) -> anyhow::Result<()> {{", model.name).unwrap();
            writeln!(output, "        let _ = &ctx; // Mark as used to avoid unused warning").unwrap();

            // Generate action calls
            for action in &trigger.actions {
                self.write_action_call(output, &action.action_type, 8, model)?;
            }

            writeln!(output, "        Ok(())").unwrap();
            writeln!(output, "    }}").unwrap();
            writeln!(output, "}}").unwrap();
            writeln!(output).unwrap();
        }

        Ok(())
    }

    fn write_state_triggers(&self, output: &mut String, model: &Model, sm: &crate::ast::StateMachine) -> Result<(), GenerateError> {
        writeln!(output, "// State machine trigger handlers").unwrap();
        writeln!(output).unwrap();

        // Generate handlers for on_enter/on_exit actions in states
        for state in &sm.states {
            // On enter handlers
            if !state.on_enter.is_empty() {
                let handler_name = format!("{}OnEnter{}Handler", model.name, to_pascal_case(&state.name));

                // Check if actions need executor or publisher
                let needs_executor = state.on_enter.iter().any(|a| self.action_needs_executor(&a.action_type));
                let needs_publisher = state.on_enter.iter().any(|a| self.action_needs_publisher(&a.action_type));

                writeln!(output, "/// Handler for entering {} state", state.name).unwrap();
                if needs_executor || needs_publisher {
                    writeln!(output, "pub struct {} {{", handler_name).unwrap();
                    if needs_publisher {
                        writeln!(output, "    pub event_publisher: Option<Arc<crate::domain::event::{}EventPublisher>>,", model.name).unwrap();
                    }
                    if needs_executor {
                        writeln!(output, "    pub action_executor: Option<Arc<{}ActionExecutor>>,", model.name).unwrap();
                    }
                    writeln!(output, "}}").unwrap();
                } else {
                    writeln!(output, "pub struct {} {{}}", handler_name).unwrap();
                }
                writeln!(output).unwrap();

                writeln!(output, "impl {} {{", handler_name).unwrap();
                if needs_executor || needs_publisher {
                    writeln!(output, "    pub fn new() -> Self {{").unwrap();
                    writeln!(output, "        Self {{").unwrap();
                    if needs_publisher {
                        writeln!(output, "            event_publisher: None,").unwrap();
                    }
                    if needs_executor {
                        writeln!(output, "            action_executor: None,").unwrap();
                    }
                    writeln!(output, "        }}").unwrap();
                    writeln!(output, "    }}").unwrap();
                } else {
                    writeln!(output, "    pub fn new() -> Self {{ Self {{}} }}").unwrap();
                }
                writeln!(output, "}}").unwrap();
                writeln!(output).unwrap();

                writeln!(output, "#[async_trait]").unwrap();
                writeln!(output, "impl TriggerHandler<{n}TriggerContext, {n}TriggerEvent> for {h} {{",
                    n = model.name, h = handler_name).unwrap();
                writeln!(output, "    fn events(&self) -> Vec<{n}TriggerEvent> {{", n = model.name).unwrap();
                writeln!(output, "        vec![TriggerEvent::OnEnterState(\"{}\".to_string())]", state.name).unwrap();
                writeln!(output, "    }}").unwrap();
                writeln!(output).unwrap();

                writeln!(output, "    async fn handle(&self, ctx: &{}TriggerContext) -> anyhow::Result<()> {{", model.name).unwrap();
                writeln!(output, "        let _ = &ctx; // Mark as used to avoid unused warning").unwrap();
                for action in &state.on_enter {
                    self.write_action_call(output, &action.action_type, 8, model)?;
                }
                writeln!(output, "        Ok(())").unwrap();
                writeln!(output, "    }}").unwrap();
                writeln!(output, "}}").unwrap();
                writeln!(output).unwrap();
            }

            // On exit handlers
            if !state.on_exit.is_empty() {
                let handler_name = format!("{}OnExit{}Handler", model.name, to_pascal_case(&state.name));

                // Check if actions need executor or publisher
                let needs_executor = state.on_exit.iter().any(|a| self.action_needs_executor(&a.action_type));
                let needs_publisher = state.on_exit.iter().any(|a| self.action_needs_publisher(&a.action_type));

                writeln!(output, "/// Handler for exiting {} state", state.name).unwrap();
                if needs_executor || needs_publisher {
                    writeln!(output, "pub struct {} {{", handler_name).unwrap();
                    if needs_publisher {
                        writeln!(output, "    pub event_publisher: Option<Arc<crate::domain::event::{}EventPublisher>>,", model.name).unwrap();
                    }
                    if needs_executor {
                        writeln!(output, "    pub action_executor: Option<Arc<{}ActionExecutor>>,", model.name).unwrap();
                    }
                    writeln!(output, "}}").unwrap();
                } else {
                    writeln!(output, "pub struct {} {{}}", handler_name).unwrap();
                }
                writeln!(output).unwrap();

                writeln!(output, "impl {} {{", handler_name).unwrap();
                if needs_executor || needs_publisher {
                    writeln!(output, "    pub fn new() -> Self {{").unwrap();
                    writeln!(output, "        Self {{").unwrap();
                    if needs_publisher {
                        writeln!(output, "            event_publisher: None,").unwrap();
                    }
                    if needs_executor {
                        writeln!(output, "            action_executor: None,").unwrap();
                    }
                    writeln!(output, "        }}").unwrap();
                    writeln!(output, "    }}").unwrap();
                } else {
                    writeln!(output, "    pub fn new() -> Self {{ Self {{}} }}").unwrap();
                }
                writeln!(output, "}}").unwrap();
                writeln!(output).unwrap();

                writeln!(output, "#[async_trait]").unwrap();
                writeln!(output, "impl TriggerHandler<{n}TriggerContext, {n}TriggerEvent> for {h} {{",
                    n = model.name, h = handler_name).unwrap();
                writeln!(output, "    fn events(&self) -> Vec<{n}TriggerEvent> {{", n = model.name).unwrap();
                writeln!(output, "        vec![TriggerEvent::OnExitState(\"{}\".to_string())]", state.name).unwrap();
                writeln!(output, "    }}").unwrap();
                writeln!(output).unwrap();

                writeln!(output, "    async fn handle(&self, ctx: &{}TriggerContext) -> anyhow::Result<()> {{", model.name).unwrap();
                writeln!(output, "        let _ = &ctx; // Mark as used to avoid unused warning").unwrap();
                for action in &state.on_exit {
                    self.write_action_call(output, &action.action_type, 8, model)?;
                }
                writeln!(output, "        Ok(())").unwrap();
                writeln!(output, "    }}").unwrap();
                writeln!(output, "}}").unwrap();
                writeln!(output).unwrap();
            }
        }

        Ok(())
    }

    /// Check if an action type requires action_executor
    fn action_needs_executor(&self, action_kind: &ActionKind) -> bool {
        matches!(action_kind,
            ActionKind::SendEmail |
            ActionKind::Notify |
            ActionKind::Webhook
        )
    }

    /// Check if an action type requires event_publisher
    fn action_needs_publisher(&self, action_kind: &ActionKind) -> bool {
        match action_kind {
            ActionKind::Emit => true,
            ActionKind::Custom(s) => s.to_lowercase().starts_with("emit:"),
            _ => false,
        }
    }

    fn write_action_call(&self, output: &mut String, action_kind: &ActionKind, indent: usize, model: &Model) -> Result<(), GenerateError> {
        let spaces = " ".repeat(indent);
        // Get the primary key field name (defaults to "id" if not found)
        let pk_field_raw = model.primary_key().map(|f| f.name.as_str()).unwrap_or("id");
        let pk_field = escape_rust_keyword(pk_field_raw);

        match action_kind {
            ActionKind::SendEmail => {
                writeln!(output, "{}// Send email notification", spaces).unwrap();
                writeln!(output, "{}if let Some(executor) = &self.action_executor {{", spaces).unwrap();
                writeln!(output, "{}    executor.send_email(ctx, \"default\").await?;", spaces).unwrap();
                writeln!(output, "{}}}", spaces).unwrap();
            }
            ActionKind::Notify => {
                writeln!(output, "{}// Send notification", spaces).unwrap();
                writeln!(output, "{}if let Some(executor) = &self.action_executor {{", spaces).unwrap();
                writeln!(output, "{}    executor.notify(ctx, \"default\").await?;", spaces).unwrap();
                writeln!(output, "{}}}", spaces).unwrap();
            }
            ActionKind::Webhook => {
                writeln!(output, "{}// Call webhook", spaces).unwrap();
                writeln!(output, "{}if let Some(executor) = &self.action_executor {{", spaces).unwrap();
                writeln!(output, "{}    executor.webhook(ctx, \"\").await?;", spaces).unwrap();
                writeln!(output, "{}}}", spaces).unwrap();
            }
            ActionKind::Execute => {
                writeln!(output, "{}// Execute custom function", spaces).unwrap();
                writeln!(output, "{}// <<< CUSTOM EXECUTE START >>>", spaces).unwrap();
                writeln!(output, "{}// Add custom execution logic here", spaces).unwrap();
                writeln!(output, "{}// <<< CUSTOM EXECUTE END >>>", spaces).unwrap();
            }
            ActionKind::Log => {
                writeln!(output, "{}tracing::info!(\"Trigger executed for entity: {{:?}}\", ctx.entity.{});", spaces, pk_field).unwrap();
            }
            ActionKind::Emit => {
                writeln!(output, "{}// Emit domain event", spaces).unwrap();
                writeln!(output, "{}if let Some(publisher) = &self.event_publisher {{", spaces).unwrap();
                writeln!(output, "{}    publisher.publish_created(ctx.entity.clone(), ctx.user_id.clone()).await?;", spaces).unwrap();
                writeln!(output, "{}}}", spaces).unwrap();
            }
            ActionKind::Custom(name) => {
                // Parse custom action patterns
                self.write_custom_action(output, name, &spaces, model)?;
            }
        }

        Ok(())
    }

    fn write_custom_action(&self, output: &mut String, action_str: &str, spaces: &str, model: &Model) -> Result<(), GenerateError> {
        let _pk_field = model.primary_key().map(|f| f.name.as_str()).unwrap_or("id");

        // Parse action pattern: "action_type: params"
        if let Some((action_type, params)) = action_str.split_once(':') {
            let action_type = action_type.trim().to_lowercase();
            let params = params.trim();

            match action_type.as_str() {
                "set" => {
                    // Parse "field = value" or "field = expression"
                    if let Some((field, value)) = params.split_once('=') {
                        let field = field.trim();
                        let value = value.trim();
                        self.write_set_action(output, field, value, spaces, model)?;
                    } else {
                        writeln!(output, "{}// Invalid set action format: {}", spaces, params).unwrap();
                    }
                }
                "emit" => {
                    // Emit a domain event
                    let event_name = params.to_lowercase();
                    self.write_emit_action(output, &event_name, spaces, model)?;
                }
                "call" => {
                    // Call a service method: "service.method" or just "method"
                    self.write_call_action(output, params, spaces, model)?;
                }
                "assert" => {
                    // Assertion/validation
                    self.write_assert_action(output, params, spaces, model)?;
                }
                "validate" => {
                    // Validation rule
                    writeln!(output, "{}// Validate: {}", spaces, params).unwrap();
                    writeln!(output, "{}// <<< CUSTOM VALIDATE START >>>", spaces).unwrap();
                    writeln!(output, "{}// Add validation logic for: {}", spaces, params).unwrap();
                    writeln!(output, "{}// <<< CUSTOM VALIDATE END >>>", spaces).unwrap();
                }
                _ => {
                    writeln!(output, "{}// Unknown action type '{}': {}", spaces, action_type, params).unwrap();
                }
            }
        } else {
            // Not a structured action, treat as generic custom action
            writeln!(output, "{}// Custom action: {}", spaces, action_str).unwrap();
            writeln!(output, "{}// <<< CUSTOM ACTION START >>>", spaces).unwrap();
            writeln!(output, "{}// Implement custom action: {}", spaces, action_str).unwrap();
            writeln!(output, "{}// <<< CUSTOM ACTION END >>>", spaces).unwrap();
        }

        Ok(())
    }

    fn write_set_action(&self, output: &mut String, field: &str, value: &str, spaces: &str, model: &Model) -> Result<(), GenerateError> {
        // Handle special value expressions
        let value_lower = value.to_lowercase();
        let escaped_field = escape_rust_keyword(field);

        // Check if field exists in model and get its type info
        let field_info = model.fields.iter().find(|f| f.name == field);
        let is_optional = field_info.map(|f| f.type_ref.is_optional()).unwrap_or(true);

        match value_lower.as_str() {
            "upper" => {
                // Set field to uppercase
                writeln!(output, "{}// Set {} to uppercase", spaces, field).unwrap();
                writeln!(output, "{}// <<< CUSTOM SET: {} = upper >>>", spaces, field).unwrap();
                if is_optional {
                    writeln!(output, "{}// if let Some(val) = &ctx.entity.{} {{", spaces, escaped_field).unwrap();
                    writeln!(output, "{}//     ctx.entity.{} = Some(val.to_uppercase());", spaces, escaped_field).unwrap();
                    writeln!(output, "{}// }}", spaces).unwrap();
                } else {
                    writeln!(output, "{}// ctx.entity.{} = ctx.entity.{}.to_uppercase();", spaces, escaped_field, escaped_field).unwrap();
                }
            }
            "lower" => {
                // Set field to lowercase
                writeln!(output, "{}// Set {} to lowercase", spaces, field).unwrap();
                writeln!(output, "{}// <<< CUSTOM SET: {} = lower >>>", spaces, field).unwrap();
                if is_optional {
                    writeln!(output, "{}// if let Some(val) = &ctx.entity.{} {{", spaces, escaped_field).unwrap();
                    writeln!(output, "{}//     ctx.entity.{} = Some(val.to_lowercase());", spaces, escaped_field).unwrap();
                    writeln!(output, "{}// }}", spaces).unwrap();
                } else {
                    writeln!(output, "{}// ctx.entity.{} = ctx.entity.{}.to_lowercase();", spaces, escaped_field, escaped_field).unwrap();
                }
            }
            "now" => {
                // Set field to current timestamp
                writeln!(output, "{}// Set {} to current timestamp", spaces, field).unwrap();
                writeln!(output, "{}// <<< CUSTOM SET: {} = now >>>", spaces, field).unwrap();
                writeln!(output, "{}// ctx.entity.{} = {}chrono::Utc::now();", spaces, escaped_field, if is_optional { "Some(" } else { "" }).unwrap();
                if is_optional {
                    writeln!(output, "{}// Note: Add closing parenthesis if using Some()", spaces).unwrap();
                }
            }
            "true" | "false" => {
                writeln!(output, "{}// Set {} = {}", spaces, field, value_lower).unwrap();
                writeln!(output, "{}// <<< CUSTOM SET: {} = {} >>>", spaces, field, value_lower).unwrap();
                if is_optional {
                    writeln!(output, "{}// ctx.entity.{} = Some({});", spaces, escaped_field, value_lower).unwrap();
                } else {
                    writeln!(output, "{}// ctx.entity.{} = {};", spaces, escaped_field, value_lower).unwrap();
                }
            }
            _ => {
                // Check for conditional: "value if condition"
                if let Some((val, condition)) = value.split_once(" if ") {
                    let val = val.trim();
                    let condition = condition.trim();
                    writeln!(output, "{}// Set {} = {} if {}", spaces, field, val, condition).unwrap();
                    writeln!(output, "{}// <<< CUSTOM CONDITIONAL SET START >>>", spaces).unwrap();
                    writeln!(output, "{}// Implement: {} = {} when {}", spaces, field, val, condition).unwrap();
                    writeln!(output, "{}// <<< CUSTOM CONDITIONAL SET END >>>", spaces).unwrap();
                } else {
                    // Direct value assignment
                    self.write_field_assignment(output, field, value, spaces)?;
                }
            }
        }

        Ok(())
    }

    fn write_field_assignment(&self, output: &mut String, field: &str, value: &str, spaces: &str) -> Result<(), GenerateError> {
        let value_lower = value.to_lowercase();
        let escaped_field = escape_rust_keyword(field);

        // All assignments are commented out to prevent type errors
        // User should uncomment and adjust based on actual field types
        writeln!(output, "{}// <<< CUSTOM SET: {} = {} >>>", spaces, field, value).unwrap();

        // Check for string literals (quoted)
        if (value.starts_with('\'') && value.ends_with('\''))
            || (value.starts_with('"') && value.ends_with('"')) {
            let str_val = &value[1..value.len()-1];
            writeln!(output, "{}// ctx.entity.{} = \"{}\".to_string(); // or Some(...) if optional", spaces, escaped_field, str_val).unwrap();
        } else if value_lower == "true" || value_lower == "false" {
            writeln!(output, "{}// ctx.entity.{} = {}; // or Some({}) if optional", spaces, escaped_field, value_lower, value_lower).unwrap();
        } else if value.parse::<i64>().is_ok() {
            writeln!(output, "{}// ctx.entity.{} = {}; // or Some({}) if optional", spaces, escaped_field, value, value).unwrap();
        } else if value.contains('(') || value.starts_with("calculate_") || value.starts_with("get_") || value.starts_with("build_") {
            // Function call or computed value
            writeln!(output, "{}// ctx.entity.{} = {}(&ctx.entity); // implement this function", spaces, escaped_field, value).unwrap();
        } else {
            // Assume it's an enum or other value
            writeln!(output, "{}// ctx.entity.{} = {}; // adjust type as needed", spaces, escaped_field, value).unwrap();
        }

        Ok(())
    }

    fn write_emit_action(&self, output: &mut String, event_name: &str, spaces: &str, _model: &Model) -> Result<(), GenerateError> {
        // Map event names to event types
        let event_type = if event_name.contains("created") {
            "Created"
        } else if event_name.contains("updated") {
            "Updated"
        } else if event_name.contains("deleted") {
            "Deleted"
        } else if event_name.contains("restored") {
            "Restored"
        } else if event_name.contains("verified") {
            "Verified"
        } else {
            "Custom"
        };

        writeln!(output, "{}// Emit {} event", spaces, event_name).unwrap();

        // For custom events where publisher is not actually used, use _publisher to avoid warning
        let publisher_var = if event_type == "Custom" { "_publisher" } else { "publisher" };
        writeln!(output, "{}if let Some({}) = &self.event_publisher {{", spaces, publisher_var).unwrap();

        match event_type {
            "Created" => {
                writeln!(output, "{}    publisher.publish_created(ctx.entity.clone(), ctx.user_id.clone()).await?;", spaces).unwrap();
            }
            "Updated" => {
                writeln!(output, "{}    publisher.publish_updated(ctx.entity.clone(), ctx.user_id.clone()).await?;", spaces).unwrap();
            }
            "Deleted" => {
                writeln!(output, "{}    publisher.publish_deleted(ctx.entity.id().to_string(), ctx.user_id.clone()).await?;", spaces).unwrap();
            }
            "Restored" => {
                writeln!(output, "{}    publisher.publish_restored(ctx.entity.clone(), ctx.user_id.clone()).await?;", spaces).unwrap();
            }
            _ => {
                writeln!(output, "{}    // Custom event: {}", spaces, event_name).unwrap();
                writeln!(output, "{}    // <<< CUSTOM EMIT: {} >>>", spaces, event_name).unwrap();
            }
        }

        writeln!(output, "{}}}", spaces).unwrap();

        Ok(())
    }

    fn write_call_action(&self, output: &mut String, call_target: &str, spaces: &str, _model: &Model) -> Result<(), GenerateError> {
        // Parse "service.method" or just "method"
        if let Some((service, method)) = call_target.split_once('.') {
            let service = service.trim().to_lowercase();
            let method = method.trim();

            writeln!(output, "{}// Call {}.{}", spaces, service, method).unwrap();
            writeln!(output, "{}// <<< CUSTOM SERVICE CALL START >>>", spaces).unwrap();
            writeln!(output, "{}// self.{}_service.{}(&ctx.entity).await?;", spaces, service, method).unwrap();
            writeln!(output, "{}// <<< CUSTOM SERVICE CALL END >>>", spaces).unwrap();
        } else {
            writeln!(output, "{}// Call method: {}", spaces, call_target).unwrap();
            writeln!(output, "{}// <<< CUSTOM METHOD CALL START >>>", spaces).unwrap();
            writeln!(output, "{}// Implement call to: {}", spaces, call_target).unwrap();
            writeln!(output, "{}// <<< CUSTOM METHOD CALL END >>>", spaces).unwrap();
        }

        Ok(())
    }

    fn write_assert_action(&self, output: &mut String, assertion: &str, spaces: &str, _model: &Model) -> Result<(), GenerateError> {
        let assertion_lower = assertion.to_lowercase();

        if assertion_lower == "count" || assertion_lower.contains("no_children") {
            // Check that there are no child records
            writeln!(output, "{}// Assert: {} (ensure no child records)", spaces, assertion).unwrap();
            writeln!(output, "{}// <<< CUSTOM ASSERTION START >>>", spaces).unwrap();
            writeln!(output, "{}// Check for child records before proceeding", spaces).unwrap();
            writeln!(output, "{}// if child_count > 0 {{ return Err(anyhow::anyhow!(\"Cannot delete: has children\")); }}", spaces).unwrap();
            writeln!(output, "{}// <<< CUSTOM ASSERTION END >>>", spaces).unwrap();
        } else {
            writeln!(output, "{}// Assert: {}", spaces, assertion).unwrap();
            writeln!(output, "{}// <<< CUSTOM ASSERTION: {} >>>", spaces, assertion).unwrap();
        }

        Ok(())
    }

    /// Emit a free `{snake}_trigger_registry()` function using `TriggerRegistry::build`.
    ///
    /// Replaces the old per-entity TriggerRegistry struct and ActionExecutor struct.
    fn write_trigger_registry_fn(&self, output: &mut String, model: &Model, hook: &Hook) -> Result<(), GenerateError> {
        let snake = to_snake_case(&model.name);
        writeln!(output, "/// Create a default registry pre-populated with all handlers for {}.", model.name).unwrap();
        writeln!(output, "pub fn {snake}_trigger_registry() -> {n}TriggerRegistry {{",
            snake = snake, n = model.name).unwrap();
        writeln!(output, "    TriggerRegistry::build(|r| {{").unwrap();

        // Register lifecycle trigger handlers
        let lifecycle_triggers: Vec<_> = hook.triggers.iter()
            .filter(|t| matches!(t.event,
                TriggerEvent::BeforeCreate | TriggerEvent::AfterCreate |
                TriggerEvent::BeforeUpdate | TriggerEvent::AfterUpdate |
                TriggerEvent::BeforeDelete | TriggerEvent::AfterDelete
            ))
            .collect();

        for (i, trigger) in lifecycle_triggers.iter().enumerate() {
            let event_name = match &trigger.event {
                TriggerEvent::BeforeCreate => "BeforeCreate",
                TriggerEvent::AfterCreate => "AfterCreate",
                TriggerEvent::BeforeUpdate => "BeforeUpdate",
                TriggerEvent::AfterUpdate => "AfterUpdate",
                TriggerEvent::BeforeDelete => "BeforeDelete",
                TriggerEvent::AfterDelete => "AfterDelete",
                _ => continue,
            };
            let handler_name = format!("{}{}Handler{}", model.name, event_name, i + 1);
            writeln!(output, "        r.register(Arc::new({}::new()));", handler_name).unwrap();
        }

        // Register state machine handlers
        if let Some(sm) = &hook.state_machine {
            for state in &sm.states {
                if !state.on_enter.is_empty() {
                    let handler_name = format!("{}OnEnter{}Handler", model.name, to_pascal_case(&state.name));
                    writeln!(output, "        r.register(Arc::new({}::new()));", handler_name).unwrap();
                }
                if !state.on_exit.is_empty() {
                    let handler_name = format!("{}OnExit{}Handler", model.name, to_pascal_case(&state.name));
                    writeln!(output, "        r.register(Arc::new({}::new()));", handler_name).unwrap();
                }
            }
        }

        writeln!(output, "    }})").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        Ok(())
    }
}

impl Default for TriggerGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for TriggerGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Only generate triggers for models that have hooks
        for hook in &schema.schema.hooks {
            // Find the model for this hook
            let model = schema.schema.models.iter()
                .find(|m| m.name == hook.model_ref || m.name == hook.name);

            if let Some(model) = model {
                let content = self.generate_triggers(model, hook)?;
                let path = PathBuf::from(format!(
                    "src/application/triggers/{}_triggers.rs",
                    to_snake_case(&model.name)
                ));
                output.add_file(path, content);
            }
        }

        // Generate mod.rs if we have any triggers
        if !output.files.is_empty() {
            let mut mod_content = String::new();
            writeln!(mod_content, "//! Trigger handlers").unwrap();
            writeln!(mod_content, "//!").unwrap();
            writeln!(mod_content, "//! Auto-generated by backbone-cli. Do not edit manually.").unwrap();
            writeln!(mod_content).unwrap();

            for hook in &schema.schema.hooks {
                let model = schema.schema.models.iter()
                    .find(|m| m.name == hook.model_ref || m.name == hook.name);

                if let Some(model) = model {
                    let model_snake = to_snake_case(&model.name);
                    writeln!(mod_content, "pub mod {}_triggers;", model_snake).unwrap();
                }
            }

            output.add_file(PathBuf::from("src/application/triggers/mod.rs"), mod_content);
        }

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "trigger"
    }
}

// Helper functions
use crate::utils::to_snake_case;


fn to_pascal_case(name: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in name.chars() {
        if c == '_' || c == '-' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c.to_ascii_lowercase());
        }
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Field, ModuleSchema, PrimitiveType, TypeRef};
    use crate::ast::hook::{Action, State, StateMachine, Transition, Trigger, TriggerEvent};

    fn create_test_schema_with_hook() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");

        schema.models.push(Model {
            name: "Order".to_string(),
            fields: vec![
                Field {
                    name: "id".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                    ..Default::default()
                },
                Field {
                    name: "status".to_string(),
                    type_ref: TypeRef::Primitive(PrimitiveType::String),
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        schema.hooks.push(Hook {
            name: "Order".to_string(),
            model_ref: "Order".to_string(),
            state_machine: Some(StateMachine {
                field: "status".to_string(),
                states: vec![
                    State {
                        name: "pending".to_string(),
                        initial: true,
                        on_enter: vec![Action {
                            action_type: ActionKind::Log,
                            ..Default::default()
                        }],
                        ..Default::default()
                    },
                    State {
                        name: "confirmed".to_string(),
                        on_enter: vec![Action {
                            action_type: ActionKind::SendEmail,
                            ..Default::default()
                        }],
                        ..Default::default()
                    },
                ],
                transitions: vec![
                    Transition::new("confirm", vec!["pending".to_string()], "confirmed"),
                ],
                ..Default::default()
            }),
            triggers: vec![
                Trigger {
                    event: TriggerEvent::AfterCreate,
                    actions: vec![Action {
                        action_type: ActionKind::SendEmail,
                        ..Default::default()
                    }],
                    ..Default::default()
                },
            ],
            ..Default::default()
        });

        ResolvedSchema { schema }
    }

    #[test]
    fn test_trigger_generator_creates_files() {
        let schema = create_test_schema_with_hook();
        let generator = TriggerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/application/triggers/order_triggers.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/application/triggers/mod.rs")));
    }

    #[test]
    fn test_trigger_generates_event_enum() {
        let schema = create_test_schema_with_hook();
        let generator = TriggerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let triggers = output.files.get(&PathBuf::from("src/application/triggers/order_triggers.rs")).unwrap();

        assert!(triggers.contains("pub enum OrderTriggerEvent"));
        assert!(triggers.contains("BeforeCreate"));
        assert!(triggers.contains("AfterCreate"));
        assert!(triggers.contains("OnTransition"));
    }

    #[test]
    fn test_trigger_generates_registry() {
        let schema = create_test_schema_with_hook();
        let generator = TriggerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let triggers = output.files.get(&PathBuf::from("src/application/triggers/order_triggers.rs")).unwrap();

        assert!(triggers.contains("pub struct OrderTriggerRegistry"));
        assert!(triggers.contains("fn register(&mut self"));
        assert!(triggers.contains("fn execute(&self"));
    }

    #[test]
    fn test_trigger_generates_state_handlers() {
        let schema = create_test_schema_with_hook();
        let generator = TriggerGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let triggers = output.files.get(&PathBuf::from("src/application/triggers/order_triggers.rs")).unwrap();

        assert!(triggers.contains("OrderOnEnterPendingHandler"));
        assert!(triggers.contains("OrderOnEnterConfirmedHandler"));
    }
}
