//! Use Case generator
//!
//! Phase 1: Generates **type aliases** over the generic use cases in backbone-core
//! instead of 5 × 150-line per-entity structs.
//!
//! ## Before (was 750 generated lines per entity):
//! ```rust,ignore
//! pub struct CreateOrderUseCase { ... }
//! impl UseCase for CreateOrderUseCase { async fn execute(...) { ... } }
//! // ... × 5 operations
//! ```
//!
//! ## After (5 generated lines per entity):
//! ```rust,ignore
//! pub type CreateOrderUseCase = CreateUseCase<Order, CreateOrderDto, OrderService>;
//! pub type UpdateOrderUseCase = UpdateUseCase<Order, UpdateOrderDto, OrderService>;
//! pub type GetOrderUseCase    = GetUseCase<Order, OrderService>;
//! pub type DeleteOrderUseCase = DeleteUseCase<Order, OrderService>;
//! pub type ListOrderUseCase   = ListUseCase<Order, OrderService>;
//! ```

use super::{GenerateError, GeneratedOutput, Generator, build_generated_path};
use crate::ast::Model;
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates use case type aliases from schema
pub struct UseCaseGenerator {
    /// Group generated files by model/domain
    group_by_domain: bool,
}

impl UseCaseGenerator {
    pub fn new() -> Self {
        Self {
            group_by_domain: false,
        }
    }

    pub fn with_group_by_domain(mut self, group: bool) -> Self {
        self.group_by_domain = group;
        self
    }

    /// Generate all 5 use case type aliases for a single entity in one file.
    fn generate_usecase_aliases_v2(&self, model: &Model) -> String {
        let mut output = String::new();
        let name = &model.name;
        let snake_name = to_snake_case(name);

        writeln!(output, "//! Use case type aliases for {} aggregate", name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Each alias delegates to the matching generic use case in backbone-core.").unwrap();
        writeln!(output, "//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use backbone_core::{{").unwrap();
        writeln!(output, "    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,").unwrap();
        writeln!(output, "}};").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "use crate::presentation::dto::{{Create{}Dto, Update{}Dto}};",
            name, name).unwrap();
        writeln!(output, "use crate::application::service::{}Service;", name).unwrap();
        writeln!(output, "use crate::domain::entity::{};", name).unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// ─── Use case type aliases ───────────────────────────────────────────────────").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub type Create{}UseCase = CreateUseCase<{}, Create{}Dto, {}Service>;",
            name, name, name, name).unwrap();
        writeln!(output, "pub type Update{}UseCase = UpdateUseCase<{}, Update{}Dto, {}Service>;",
            name, name, name, name).unwrap();
        writeln!(output, "pub type Get{}UseCase    = GetUseCase<{}, {}Service>;",
            name, name, name).unwrap();
        writeln!(output, "pub type Delete{}UseCase = DeleteUseCase<{}, {}Service>;",
            name, name, name).unwrap();
        writeln!(output, "pub type List{}UseCase   = ListUseCase<{}, {}Service>;",
            name, name, name).unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();

        output
    }

    /// Generate the base.rs file with the UseCase trait (now just imports from backbone-core).
    fn generate_base(&self) -> String {
        let mut output = String::new();
        writeln!(output, "//! Use case base traits — re-exported from backbone-core.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "pub use backbone_core::{{").unwrap();
        writeln!(output, "    UseCaseError, UseCaseResult,").unwrap();
        writeln!(output, "    UseCaseHooks, DefaultHooks,").unwrap();
        writeln!(output, "    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,").unwrap();
        writeln!(output, "}};").unwrap();
        output
    }

    /// Generate mod.rs for the usecases directory.
    fn generate_mod(&self, models: &[Model]) -> String {
        let mut output = String::new();
        writeln!(output, "//! Application use cases").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Each entity contributes 5 type aliases (create, update, get, delete, list).").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "pub mod base;").unwrap();
        writeln!(output, "pub use base::{{UseCaseError, UseCaseResult, UseCaseHooks}};").unwrap();
        writeln!(output).unwrap();

        for model in models {
            let snake_name = to_snake_case(&model.name);
            writeln!(output, "pub mod {}_usecases;", snake_name).unwrap();
        }
        writeln!(output).unwrap();
        // Re-exports
        for model in models {
            let snake_name = to_snake_case(&model.name);
            let name = &model.name;
            writeln!(output, "pub use {snake}_usecases::{{",
                snake = snake_name).unwrap();
            writeln!(output, "    Create{n}UseCase, Update{n}UseCase, Get{n}UseCase,",
                n = name).unwrap();
            writeln!(output, "    Delete{n}UseCase, List{n}UseCase,",
                n = name).unwrap();
            writeln!(output, "}};").unwrap();
        }
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM").unwrap();
        writeln!(output, "// END CUSTOM").unwrap();
        output
    }
}

impl Default for UseCaseGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for UseCaseGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // base.rs — shared trait re-exports
        output.add_file(
            PathBuf::from("src/application/usecases/base.rs"),
            self.generate_base(),
        );

        let models: Vec<&Model> = schema.schema.models.iter().collect();

        for model in &models {
            let snake_name = to_snake_case(&model.name);
            let aliases_content = self.generate_usecase_aliases_v2(model);

            if self.group_by_domain {
                let path = build_generated_path(
                    "src/application/usecases",
                    &model.name,
                    &format!("{}_usecases.rs", snake_name),
                    true,
                );
                output.add_file(path, aliases_content);
            } else {
                let path = PathBuf::from(format!(
                    "src/application/usecases/{}_usecases.rs",
                    snake_name
                ));
                output.add_file(path, aliases_content);
            }
        }

        // mod.rs
        let owned_models: Vec<Model> = schema.schema.models.clone();
        output.add_file(
            PathBuf::from("src/application/usecases/mod.rs"),
            self.generate_mod(&owned_models),
        );

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "usecase"
    }
}

use crate::utils::to_snake_case;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Attribute, Field, ModuleSchema, PrimitiveType, TypeRef};

    fn create_test_model() -> Model {
        let mut model = Model::new("Order");
        model.fields = vec![
            Field {
                name: "id".to_string(),
                type_ref: TypeRef::Primitive(PrimitiveType::Uuid),
                attributes: vec![Attribute::new("id")],
                ..Default::default()
            },
        ];
        model
    }

    fn create_test_schema() -> ResolvedSchema {
        let mut schema = ModuleSchema::new("test");
        schema.models.push(create_test_model());
        ResolvedSchema { schema }
    }

    #[test]
    fn test_usecase_generator_creates_files() {
        let schema = create_test_schema();
        let generator = UseCaseGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/application/usecases/base.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/application/usecases/order_usecases.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/application/usecases/mod.rs")));
    }

    #[test]
    fn test_usecase_emits_type_aliases() {
        let schema = create_test_schema();
        let generator = UseCaseGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let content = output.files
            .get(&PathBuf::from("src/application/usecases/order_usecases.rs"))
            .unwrap();

        assert!(content.contains("pub type CreateOrderUseCase = CreateUseCase<"));
        assert!(content.contains("pub type UpdateOrderUseCase = UpdateUseCase<"));
        assert!(content.contains("pub type GetOrderUseCase"));
        assert!(content.contains("pub type DeleteOrderUseCase"));
        assert!(content.contains("pub type ListOrderUseCase"));
        assert!(content.contains("backbone_core"));
    }

    #[test]
    fn test_base_re_exports_backbone_core() {
        let schema = create_test_schema();
        let generator = UseCaseGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let base = output.files
            .get(&PathBuf::from("src/application/usecases/base.rs"))
            .unwrap();

        assert!(base.contains("backbone_core"));
        assert!(base.contains("UseCaseError"));
    }
}
