//! API Versioning Generator
//!
//! Generates API versioning infrastructure for both HTTP and gRPC:
//! - Version configuration and constants
//! - Version routing helpers
//! - Version negotiation (Accept header, URL path)
//! - Deprecation warnings
//! - Version migration utilities
//!
//! ## Versioning Strategies
//!
//! 1. **URL Path Versioning**: `/api/v1/users`, `/api/v2/users`
//! 2. **Header Versioning**: `Accept: application/vnd.api+json;version=1`
//! 3. **Query Parameter**: `?version=1`
//!
//! ## Generated Files
//!
//! - `version.rs` - Version constants and configuration
//! - `version_router.rs` - Version-aware routing
//! - `version_middleware.rs` - Version negotiation middleware
//! - `version_compat.rs` - Backward compatibility helpers

use super::{GenerateError, GeneratedOutput, Generator};
use crate::resolver::ResolvedSchema;
use std::fmt::Write;
use std::path::PathBuf;

/// Generates API versioning infrastructure
pub struct VersioningGenerator {
    /// Supported API versions
    versions: Vec<ApiVersion>,
    /// Default version
    default_version: String,
    /// Versioning strategy
    strategy: VersioningStrategy,
}

/// Represents an API version
#[derive(Debug, Clone)]
pub struct ApiVersion {
    /// Version number (e.g., 1, 2)
    pub major: u32,
    /// Minor version (optional)
    pub minor: Option<u32>,
    /// Whether this version is deprecated
    pub deprecated: bool,
    /// Deprecation message (if deprecated)
    pub deprecation_message: Option<String>,
    /// Sunset date (if deprecated)
    pub sunset_date: Option<String>,
}

impl Default for ApiVersion {
    fn default() -> Self {
        Self {
            major: 1,
            minor: None,
            deprecated: false,
            deprecation_message: None,
            sunset_date: None,
        }
    }
}

/// Versioning strategy
#[derive(Debug, Clone, Copy, Default)]
pub enum VersioningStrategy {
    /// Version in URL path: /api/v1/resource
    #[default]
    UrlPath,
    /// Version in Accept header: Accept: application/vnd.api+json;version=1
    Header,
    /// Version in query parameter: ?version=1
    QueryParam,
    /// Combination of strategies (prefer header, fallback to URL)
    Combined,
}

impl VersioningGenerator {
    pub fn new() -> Self {
        Self {
            versions: vec![
                ApiVersion {
                    major: 1,
                    minor: Some(0),
                    deprecated: false,
                    deprecation_message: None,
                    sunset_date: None,
                },
            ],
            default_version: "v1".to_string(),
            strategy: VersioningStrategy::UrlPath,
        }
    }

    /// Set supported versions
    pub fn with_versions(mut self, versions: Vec<ApiVersion>) -> Self {
        self.versions = versions;
        self
    }

    /// Set default version
    pub fn with_default(mut self, version: &str) -> Self {
        self.default_version = version.to_string();
        self
    }

    /// Set versioning strategy
    pub fn with_strategy(mut self, strategy: VersioningStrategy) -> Self {
        self.strategy = strategy;
        self
    }

    /// Generate version constants and configuration
    fn generate_version_config(&self, schema: &ResolvedSchema) -> String {
        let mut output = String::new();
        let module_name = &schema.schema.name;

        writeln!(output, "//! API Version Configuration for {}", module_name).unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Auto-generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This module defines API version constants and configuration.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use std::fmt;").unwrap();
        writeln!(output, "use std::str::FromStr;").unwrap();
        writeln!(output).unwrap();

        // Version enum
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// API Versions").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Supported API versions").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
        writeln!(output, "pub enum ApiVersion {{").unwrap();
        for version in &self.versions {
            let version_name = format!("V{}", version.major);
            if version.deprecated {
                writeln!(output, "    /// Version {} (DEPRECATED)", version.major).unwrap();
                if let Some(msg) = &version.deprecation_message {
                    writeln!(output, "    /// {}", msg).unwrap();
                }
                writeln!(output, "    #[deprecated]").unwrap();
            } else {
                writeln!(output, "    /// Version {}", version.major).unwrap();
            }
            writeln!(output, "    {},", version_name).unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Default version constant
        writeln!(output, "/// Current/default API version").unwrap();
        writeln!(output, "pub const CURRENT_VERSION: ApiVersion = ApiVersion::{};",
            self.default_version.to_uppercase()).unwrap();
        writeln!(output).unwrap();

        // Version constants
        writeln!(output, "/// All supported API versions").unwrap();
        writeln!(output, "pub const SUPPORTED_VERSIONS: &[ApiVersion] = &[").unwrap();
        for version in &self.versions {
            writeln!(output, "    ApiVersion::V{},", version.major).unwrap();
        }
        writeln!(output, "];").unwrap();
        writeln!(output).unwrap();

        // Version string constants
        writeln!(output, "/// Version string constants").unwrap();
        writeln!(output, "pub mod versions {{").unwrap();
        for version in &self.versions {
            writeln!(output, "    pub const V{}: &str = \"v{}\";", version.major, version.major).unwrap();
        }
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // ApiVersion impl
        writeln!(output, "impl ApiVersion {{").unwrap();
        writeln!(output, "    /// Get version as string (e.g., \"v1\")").unwrap();
        writeln!(output, "    pub fn as_str(&self) -> &'static str {{").unwrap();
        writeln!(output, "        match self {{").unwrap();
        for version in &self.versions {
            writeln!(output, "            Self::V{} => \"v{}\",", version.major, version.major).unwrap();
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Get major version number").unwrap();
        writeln!(output, "    pub fn major(&self) -> u32 {{").unwrap();
        writeln!(output, "        match self {{").unwrap();
        for version in &self.versions {
            writeln!(output, "            Self::V{} => {},", version.major, version.major).unwrap();
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Check if this version is deprecated").unwrap();
        writeln!(output, "    pub fn is_deprecated(&self) -> bool {{").unwrap();
        writeln!(output, "        match self {{").unwrap();
        for version in &self.versions {
            writeln!(output, "            Self::V{} => {},", version.major, version.deprecated).unwrap();
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Get deprecation message if deprecated").unwrap();
        writeln!(output, "    pub fn deprecation_message(&self) -> Option<&'static str> {{").unwrap();
        writeln!(output, "        match self {{").unwrap();
        for version in &self.versions {
            if let Some(msg) = &version.deprecation_message {
                writeln!(output, "            Self::V{} => Some(\"{}\"),", version.major, msg).unwrap();
            } else {
                writeln!(output, "            Self::V{} => None,", version.major).unwrap();
            }
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Get sunset date if deprecated").unwrap();
        writeln!(output, "    pub fn sunset_date(&self) -> Option<&'static str> {{").unwrap();
        writeln!(output, "        match self {{").unwrap();
        for version in &self.versions {
            if let Some(date) = &version.sunset_date {
                writeln!(output, "            Self::V{} => Some(\"{}\"),", version.major, date).unwrap();
            } else {
                writeln!(output, "            Self::V{} => None,", version.major).unwrap();
            }
        }
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Display impl
        writeln!(output, "impl fmt::Display for ApiVersion {{").unwrap();
        writeln!(output, "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{").unwrap();
        writeln!(output, "        write!(f, \"{{}}\", self.as_str())").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // FromStr impl
        writeln!(output, "impl FromStr for ApiVersion {{").unwrap();
        writeln!(output, "    type Err = VersionParseError;").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "    fn from_str(s: &str) -> Result<Self, Self::Err> {{").unwrap();
        writeln!(output, "        match s.to_lowercase().as_str() {{").unwrap();
        for version in &self.versions {
            writeln!(output, "            \"v{}\" | \"{}\" => Ok(Self::V{}),",
                version.major, version.major, version.major).unwrap();
        }
        writeln!(output, "            _ => Err(VersionParseError(s.to_string())),").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Parse error
        writeln!(output, "/// Error when parsing an invalid version string").unwrap();
        writeln!(output, "#[derive(Debug, Clone)]").unwrap();
        writeln!(output, "pub struct VersionParseError(pub String);").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "impl std::error::Error for VersionParseError {{}}").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "impl fmt::Display for VersionParseError {{").unwrap();
        writeln!(output, "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{").unwrap();
        writeln!(output, "        write!(f, \"Invalid API version: '{{}}'\", self.0)").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();

        output
    }

    /// Generate version routing helpers
    fn generate_version_router(&self, _schema: &ResolvedSchema) -> String {
        let mut output = String::new();

        writeln!(output, "//! Version-aware Routing").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Auto-generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Provides helpers for version-aware routing.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use axum::{{").unwrap();
        writeln!(output, "    Router,").unwrap();
        writeln!(output, "    routing::{{get, post, put, patch, delete}},").unwrap();
        writeln!(output, "}};").unwrap();
        writeln!(output, "use super::version::ApiVersion;").unwrap();
        writeln!(output).unwrap();

        // Version router builder
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Version Router Builder").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Builder for creating versioned API routes").unwrap();
        writeln!(output, "pub struct VersionedRouter<S = ()> {{").unwrap();
        writeln!(output, "    base_path: String,").unwrap();
        writeln!(output, "    routers: Vec<(ApiVersion, Router<S>)>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl<S: Clone + Send + Sync + 'static> VersionedRouter<S> {{").unwrap();
        writeln!(output, "    /// Create a new versioned router with base path").unwrap();
        writeln!(output, "    pub fn new(base_path: impl Into<String>) -> Self {{").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            base_path: base_path.into(),").unwrap();
        writeln!(output, "            routers: Vec::new(),").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Add routes for a specific version").unwrap();
        writeln!(output, "    pub fn version(mut self, version: ApiVersion, router: Router<S>) -> Self {{").unwrap();
        writeln!(output, "        self.routers.push((version, router));").unwrap();
        writeln!(output, "        self").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "    /// Build the final router with all versions").unwrap();
        writeln!(output, "    pub fn build(self) -> Router<S> {{").unwrap();
        writeln!(output, "        let mut router = Router::new();").unwrap();
        writeln!(output, "        ").unwrap();
        writeln!(output, "        for (version, version_router) in self.routers {{").unwrap();
        writeln!(output, "            let path = format!(\"{{}}/{{}}\", self.base_path, version.as_str());").unwrap();
        writeln!(output, "            router = router.nest(&path, version_router);").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "        ").unwrap();
        writeln!(output, "        router").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Helper functions
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Helper Functions").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Create a versioned path from base path and version").unwrap();
        writeln!(output, "pub fn versioned_path(base: &str, version: ApiVersion) -> String {{").unwrap();
        writeln!(output, "    format!(\"{{}}/{{}}\", base, version.as_str())").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Create a versioned path with resource").unwrap();
        writeln!(output, "pub fn versioned_resource_path(base: &str, version: ApiVersion, resource: &str) -> String {{").unwrap();
        writeln!(output, "    format!(\"{{}}/{{}}/{{}}\", base, version.as_str(), resource)").unwrap();
        writeln!(output, "}}").unwrap();

        output
    }

    /// Generate version negotiation middleware
    fn generate_version_middleware(&self, _schema: &ResolvedSchema) -> String {
        let mut output = String::new();

        writeln!(output, "//! Version Negotiation Middleware").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Auto-generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Provides middleware for API version negotiation.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use axum::{{").unwrap();
        writeln!(output, "    extract::Request,").unwrap();
        writeln!(output, "    http::{{HeaderMap, HeaderValue, StatusCode}},").unwrap();
        writeln!(output, "    middleware::Next,").unwrap();
        writeln!(output, "    response::{{IntoResponse, Response}},").unwrap();
        writeln!(output, "}};").unwrap();
        writeln!(output, "use super::version::{{ApiVersion, CURRENT_VERSION, SUPPORTED_VERSIONS}};").unwrap();
        writeln!(output).unwrap();

        // Version extension
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Request Extension").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Extension to carry resolved API version through request").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Copy)]").unwrap();
        writeln!(output, "pub struct ResolvedVersion(pub ApiVersion);").unwrap();
        writeln!(output).unwrap();

        // Version negotiation middleware
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Version Negotiation Middleware").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Middleware that negotiates API version from request").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Supports multiple strategies:").unwrap();
        writeln!(output, "/// 1. URL path: /api/v1/resource").unwrap();
        writeln!(output, "/// 2. Accept header: Accept: application/vnd.api+json;version=1").unwrap();
        writeln!(output, "/// 3. Query param: ?version=1").unwrap();
        writeln!(output, "/// 4. Custom header: X-API-Version: 1").unwrap();
        writeln!(output, "pub async fn version_negotiation_middleware(").unwrap();
        writeln!(output, "    mut request: Request,").unwrap();
        writeln!(output, "    next: Next,").unwrap();
        writeln!(output, ") -> Response {{").unwrap();
        writeln!(output, "    // Try to extract version from various sources").unwrap();
        writeln!(output, "    let version = extract_version_from_path(request.uri().path())").unwrap();
        writeln!(output, "        .or_else(|| extract_version_from_header(request.headers()))").unwrap();
        writeln!(output, "        .or_else(|| extract_version_from_query(request.uri().query()))").unwrap();
        writeln!(output, "        .unwrap_or(CURRENT_VERSION);").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Add version to request extensions").unwrap();
        writeln!(output, "    request.extensions_mut().insert(ResolvedVersion(version));").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Add deprecation warning if version is deprecated").unwrap();
        writeln!(output, "    let mut response = next.run(request).await;").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    if version.is_deprecated() {{").unwrap();
        writeln!(output, "        if let Some(msg) = version.deprecation_message() {{").unwrap();
        writeln!(output, "            response.headers_mut().insert(").unwrap();
        writeln!(output, "                \"Deprecation\",").unwrap();
        writeln!(output, "                HeaderValue::from_str(msg).unwrap_or_else(|_| HeaderValue::from_static(\"true\")),").unwrap();
        writeln!(output, "            );").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "        if let Some(date) = version.sunset_date() {{").unwrap();
        writeln!(output, "            if let Ok(val) = HeaderValue::from_str(date) {{").unwrap();
        writeln!(output, "                response.headers_mut().insert(\"Sunset\", val);").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Add API-Version header to response").unwrap();
        writeln!(output, "    response.headers_mut().insert(").unwrap();
        writeln!(output, "        \"X-API-Version\",").unwrap();
        writeln!(output, "        HeaderValue::from_str(version.as_str()).unwrap_or_else(|_| HeaderValue::from_static(\"v1\")),").unwrap();
        writeln!(output, "    );").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    response").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Helper functions
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Version Extraction Helpers").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Extract version from URL path (e.g., /api/v1/users)").unwrap();
        writeln!(output, "fn extract_version_from_path(path: &str) -> Option<ApiVersion> {{").unwrap();
        writeln!(output, "    // Look for /v1/, /v2/, etc. in path").unwrap();
        writeln!(output, "    for version in SUPPORTED_VERSIONS {{").unwrap();
        writeln!(output, "        let version_segment = format!(\"/{{}}/\", version.as_str());").unwrap();
        writeln!(output, "        if path.contains(&version_segment) {{").unwrap();
        writeln!(output, "            return Some(*version);").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "        // Also check if path ends with version").unwrap();
        writeln!(output, "        let version_end = format!(\"/{{}}\", version.as_str());").unwrap();
        writeln!(output, "        if path.ends_with(&version_end) {{").unwrap();
        writeln!(output, "            return Some(*version);").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    None").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Extract version from Accept header").unwrap();
        writeln!(output, "fn extract_version_from_header(headers: &HeaderMap) -> Option<ApiVersion> {{").unwrap();
        writeln!(output, "    // Check X-API-Version header first").unwrap();
        writeln!(output, "    if let Some(value) = headers.get(\"X-API-Version\") {{").unwrap();
        writeln!(output, "        if let Ok(s) = value.to_str() {{").unwrap();
        writeln!(output, "            if let Ok(v) = s.parse() {{").unwrap();
        writeln!(output, "                return Some(v);").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    // Check Accept header for version parameter").unwrap();
        writeln!(output, "    if let Some(accept) = headers.get(\"Accept\") {{").unwrap();
        writeln!(output, "        if let Ok(s) = accept.to_str() {{").unwrap();
        writeln!(output, "            // Look for version=X in Accept header").unwrap();
        writeln!(output, "            if let Some(version_part) = s.split(';').find(|p| p.trim().starts_with(\"version=\")) {{").unwrap();
        writeln!(output, "                let version_str = version_part.trim().trim_start_matches(\"version=\");").unwrap();
        writeln!(output, "                if let Ok(v) = version_str.parse() {{").unwrap();
        writeln!(output, "                    return Some(v);").unwrap();
        writeln!(output, "                }}").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    None").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Extract version from query parameter").unwrap();
        writeln!(output, "fn extract_version_from_query(query: Option<&str>) -> Option<ApiVersion> {{").unwrap();
        writeln!(output, "    let query = query?;").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    for param in query.split('&') {{").unwrap();
        writeln!(output, "        if let Some(value) = param.strip_prefix(\"version=\") {{").unwrap();
        writeln!(output, "            if let Ok(v) = value.parse() {{").unwrap();
        writeln!(output, "                return Some(v);").unwrap();
        writeln!(output, "            }}").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    None").unwrap();
        writeln!(output, "}}").unwrap();

        output
    }

    /// Generate version compatibility helpers
    fn generate_version_compat(&self, _schema: &ResolvedSchema) -> String {
        let mut output = String::new();

        writeln!(output, "//! Version Compatibility Helpers").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Auto-generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Provides utilities for maintaining backward compatibility.").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "use super::version::ApiVersion;").unwrap();
        writeln!(output, "use serde::{{Deserialize, Serialize}};").unwrap();
        writeln!(output).unwrap();

        // Version transform trait
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Version Transform Trait").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Trait for types that can be transformed between versions").unwrap();
        writeln!(output, "pub trait VersionTransform {{").unwrap();
        writeln!(output, "    /// The type this transforms into for a specific version").unwrap();
        writeln!(output, "    type Output;").unwrap();
        writeln!(output, "    ").unwrap();
        writeln!(output, "    /// Transform this type to the representation for the given version").unwrap();
        writeln!(output, "    fn to_version(&self, version: ApiVersion) -> Self::Output;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Versioned response wrapper
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Versioned Response Wrapper").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Wrapper for versioned API responses").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "#[serde(rename_all = \"camelCase\")]").unwrap();
        writeln!(output, "pub struct VersionedResponse<T> {{").unwrap();
        writeln!(output, "    /// The API version used for this response").unwrap();
        writeln!(output, "    pub api_version: String,").unwrap();
        writeln!(output, "    /// The actual response data").unwrap();
        writeln!(output, "    pub data: T,").unwrap();
        writeln!(output, "    /// Deprecation warning if applicable").unwrap();
        writeln!(output, "    #[serde(skip_serializing_if = \"Option::is_none\")]").unwrap();
        writeln!(output, "    pub deprecation_warning: Option<String>,").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl<T> VersionedResponse<T> {{").unwrap();
        writeln!(output, "    /// Create a new versioned response").unwrap();
        writeln!(output, "    pub fn new(version: ApiVersion, data: T) -> Self {{").unwrap();
        writeln!(output, "        let deprecation_warning = if version.is_deprecated() {{").unwrap();
        writeln!(output, "            version.deprecation_message().map(|s| s.to_string())").unwrap();
        writeln!(output, "        }} else {{").unwrap();
        writeln!(output, "            None").unwrap();
        writeln!(output, "        }};").unwrap();
        writeln!(output, "        ").unwrap();
        writeln!(output, "        Self {{").unwrap();
        writeln!(output, "            api_version: version.as_str().to_string(),").unwrap();
        writeln!(output, "            data,").unwrap();
        writeln!(output, "            deprecation_warning,").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Field migration helpers
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Field Migration Helpers").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "/// Helper for renamed fields between versions").unwrap();
        writeln!(output, "///").unwrap();
        writeln!(output, "/// Use this to handle field renames gracefully.").unwrap();
        writeln!(output, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(output, "#[serde(untagged)]").unwrap();
        writeln!(output, "pub enum RenamedField<T> {{").unwrap();
        writeln!(output, "    /// The new field name").unwrap();
        writeln!(output, "    Current(T),").unwrap();
        writeln!(output, "    /// The old field name (for backward compatibility)").unwrap();
        writeln!(output, "    Legacy(T),").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "impl<T> RenamedField<T> {{").unwrap();
        writeln!(output, "    /// Get the inner value regardless of which variant it is").unwrap();
        writeln!(output, "    pub fn into_inner(self) -> T {{").unwrap();
        writeln!(output, "        match self {{").unwrap();
        writeln!(output, "            Self::Current(v) | Self::Legacy(v) => v,").unwrap();
        writeln!(output, "        }}").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();

        // Custom section
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output, "// Custom Compatibility Logic").unwrap();
        writeln!(output, "// =============================================================================").unwrap();
        writeln!(output).unwrap();
        writeln!(output, "// <<< CUSTOM COMPAT").unwrap();
        writeln!(output, "// Add custom version compatibility transformations here.").unwrap();
        writeln!(output, "// This section will be preserved during regeneration.").unwrap();
        writeln!(output, "// >>> END CUSTOM COMPAT").unwrap();

        output
    }

    /// Generate mod.rs for versioning module
    fn generate_mod_file(&self) -> String {
        let mut output = String::new();

        writeln!(output, "//! API Versioning").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! Auto-generated by metaphor-schema. Do not edit manually.").unwrap();
        writeln!(output, "//!").unwrap();
        writeln!(output, "//! This module provides API versioning infrastructure:").unwrap();
        writeln!(output, "//! - Version constants and configuration").unwrap();
        writeln!(output, "//! - Version-aware routing").unwrap();
        writeln!(output, "//! - Version negotiation middleware").unwrap();
        writeln!(output, "//! - Backward compatibility helpers").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "pub mod version;").unwrap();
        writeln!(output, "pub mod version_router;").unwrap();
        writeln!(output, "pub mod version_middleware;").unwrap();
        writeln!(output, "pub mod version_compat;").unwrap();
        writeln!(output).unwrap();

        writeln!(output, "// Re-exports").unwrap();
        writeln!(output, "pub use version::{{ApiVersion, CURRENT_VERSION, SUPPORTED_VERSIONS, VersionParseError}};").unwrap();
        writeln!(output, "pub use version_router::{{VersionedRouter, versioned_path, versioned_resource_path}};").unwrap();
        writeln!(output, "pub use version_middleware::{{ResolvedVersion, version_negotiation_middleware}};").unwrap();
        writeln!(output, "pub use version_compat::{{VersionTransform, VersionedResponse, RenamedField}};").unwrap();

        output
    }
}

impl Default for VersioningGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for VersioningGenerator {
    fn generate(&self, schema: &ResolvedSchema) -> Result<GeneratedOutput, GenerateError> {
        let mut output = GeneratedOutput::new();

        // Generate version configuration
        let version_content = self.generate_version_config(schema);
        output.add_file(PathBuf::from("src/presentation/versioning/version.rs"), version_content);

        // Generate version router
        let router_content = self.generate_version_router(schema);
        output.add_file(PathBuf::from("src/presentation/versioning/version_router.rs"), router_content);

        // Generate version middleware
        let middleware_content = self.generate_version_middleware(schema);
        output.add_file(PathBuf::from("src/presentation/versioning/version_middleware.rs"), middleware_content);

        // Generate version compatibility helpers
        let compat_content = self.generate_version_compat(schema);
        output.add_file(PathBuf::from("src/presentation/versioning/version_compat.rs"), compat_content);

        // Generate mod.rs
        let mod_content = self.generate_mod_file();
        output.add_file(PathBuf::from("src/presentation/versioning/mod.rs"), mod_content);

        Ok(output)
    }

    fn name(&self) -> &'static str {
        "versioning"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::ModuleSchema;

    fn create_test_schema() -> ResolvedSchema {
        let schema = ModuleSchema::new("test");
        ResolvedSchema { schema }
    }

    #[test]
    fn test_versioning_generator_creates_files() {
        let schema = create_test_schema();
        let generator = VersioningGenerator::new();
        let output = generator.generate(&schema).unwrap();

        assert!(output.files.contains_key(&PathBuf::from("src/presentation/versioning/version.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/presentation/versioning/version_router.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/presentation/versioning/version_middleware.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/presentation/versioning/version_compat.rs")));
        assert!(output.files.contains_key(&PathBuf::from("src/presentation/versioning/mod.rs")));
    }

    #[test]
    fn test_version_config_has_api_version_enum() {
        let schema = create_test_schema();
        let generator = VersioningGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let version_file = output.files.get(&PathBuf::from("src/presentation/versioning/version.rs")).unwrap();

        assert!(version_file.contains("pub enum ApiVersion"));
        assert!(version_file.contains("pub const CURRENT_VERSION"));
        assert!(version_file.contains("pub const SUPPORTED_VERSIONS"));
    }

    #[test]
    fn test_version_router_has_versioned_router() {
        let schema = create_test_schema();
        let generator = VersioningGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let router_file = output.files.get(&PathBuf::from("src/presentation/versioning/version_router.rs")).unwrap();

        assert!(router_file.contains("pub struct VersionedRouter"));
        assert!(router_file.contains("pub fn versioned_path"));
        assert!(router_file.contains("pub fn versioned_resource_path"));
    }

    #[test]
    fn test_version_middleware_has_negotiation() {
        let schema = create_test_schema();
        let generator = VersioningGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let middleware_file = output.files.get(&PathBuf::from("src/presentation/versioning/version_middleware.rs")).unwrap();

        assert!(middleware_file.contains("pub struct ResolvedVersion"));
        assert!(middleware_file.contains("pub async fn version_negotiation_middleware"));
        assert!(middleware_file.contains("extract_version_from_path"));
        assert!(middleware_file.contains("extract_version_from_header"));
    }

    #[test]
    fn test_version_compat_has_transform_trait() {
        let schema = create_test_schema();
        let generator = VersioningGenerator::new();
        let output = generator.generate(&schema).unwrap();

        let compat_file = output.files.get(&PathBuf::from("src/presentation/versioning/version_compat.rs")).unwrap();

        assert!(compat_file.contains("pub trait VersionTransform"));
        assert!(compat_file.contains("pub struct VersionedResponse"));
        assert!(compat_file.contains("pub enum RenamedField"));
    }

    #[test]
    fn test_multiple_versions() {
        let schema = create_test_schema();
        let generator = VersioningGenerator::new()
            .with_versions(vec![
                ApiVersion {
                    major: 1,
                    minor: None,
                    deprecated: true,
                    deprecation_message: Some("Use v2 instead".to_string()),
                    sunset_date: Some("2025-06-01".to_string()),
                },
                ApiVersion {
                    major: 2,
                    minor: None,
                    deprecated: false,
                    deprecation_message: None,
                    sunset_date: None,
                },
            ])
            .with_default("v2");

        let output = generator.generate(&schema).unwrap();
        let version_file = output.files.get(&PathBuf::from("src/presentation/versioning/version.rs")).unwrap();

        assert!(version_file.contains("V1"));
        assert!(version_file.contains("V2"));
        assert!(version_file.contains("#[deprecated]"));
        assert!(version_file.contains("Use v2 instead"));
    }
}
