//! Phase 4: under `--force`, sweep stale generator-authored migration
//! files so a regen doesn't accumulate duplicate sequence numbers.
//!
//! Survival rules — a file is **preserved** when any of these hold:
//!
//! - It exactly matches a newly-generated migration filename (will be
//!   overwritten in the write phase).
//! - It is matched by a `user_owned` glob in `metaphor.codegen.yaml`
//!   (the manifest reserves it for the application).
//! - It lacks the `-- Generated by metaphor-schema` header (hand-written:
//!   audit triggers, backfills, ad-hoc data fixes).
//!
//! Anything else under `migrations/` matching the `NNN_*.up.sql` /
//! `NNN_*.sql` pattern is considered stale and deleted.

use colored::Colorize;
use globset::GlobSet;
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

use crate::generators::GeneratedOutput;

use super::super::migrations::is_generator_authored_migration;

pub(super) fn cleanup_stale_migrations(
    output_dir: &Path,
    generated: &GeneratedOutput,
    user_owned: &GlobSet,
) {
    let has_migration_files = generated.files.keys().any(|p| {
        p.to_string_lossy().starts_with("migrations/")
            && p.to_string_lossy().ends_with(".up.sql")
    });

    if !has_migration_files {
        return;
    }

    let migrations_dir = output_dir.join("migrations");
    if !migrations_dir.exists() {
        return;
    }

    // Collect just-generated migration filenames so we don't delete a file
    // we're about to overwrite.
    let generated_migration_names: HashSet<String> = generated
        .files
        .keys()
        .filter_map(|p| {
            let s = p.to_string_lossy();
            if s.starts_with("migrations/") && s.ends_with(".up.sql") {
                p.file_name().map(|n| n.to_string_lossy().to_string())
            } else {
                None
            }
        })
        .collect();

    let entries = match fs::read_dir(&migrations_dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    let mut removed = 0;
    let mut preserved_user = 0;
    let mut preserved_handwritten = 0;

    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();

        // Only target numbered migrations: NNN_*.up.sql or NNN_*.sql
        let is_numbered_migration = name.len() > 4
            && name[..3].chars().all(|c| c.is_ascii_digit())
            && name.ends_with(".sql")
            && !name.ends_with(".down.sql");

        if !is_numbered_migration {
            continue;
        }

        if generated_migration_names.contains(&name) {
            continue;
        }

        let rel_path = PathBuf::from("migrations").join(&name);
        if user_owned.is_match(&rel_path) {
            preserved_user += 1;
            continue;
        }

        if !is_generator_authored_migration(&entry.path()) {
            preserved_handwritten += 1;
            continue;
        }

        if let Err(e) = fs::remove_file(entry.path()) {
            eprintln!(
                "  {} Failed to remove stale migration {}: {}",
                "⚠".yellow(),
                name,
                e
            );
        } else {
            removed += 1;
        }
    }

    if removed > 0 {
        println!(
            "  {} Removed {} stale migration file(s)",
            "🧹".to_string().green(),
            removed
        );
    }
    if preserved_handwritten > 0 {
        println!(
            "  {} Preserved {} hand-written migration file(s) (no generator marker)",
            "•".cyan(),
            preserved_handwritten
        );
    }
    if preserved_user > 0 {
        println!(
            "  {} Preserved {} user-owned migration file(s)",
            "•".cyan(),
            preserved_user
        );
    }
}
