//! Stabilize migration filenames against on-disk state so a regen keeps each
//! logical migration at a stable timestamp — no renumbering and no collisions,
//! under both plain `generate` and `--force`.
//!
//! Runs after generation and before [`super::migration_cleanup`] / the write
//! phase. Because the cleanup pass preserves any on-disk migration whose
//! filename appears in the generated set, feeding it already-stabilized names
//! (existing identities reused at their existing on-disk timestamp) makes the
//! cleanup preserve them and delete only genuinely-orphaned generated files.
//!
//! Timestamp decisions are keyed on a migration's **base name** — the identity
//! shared by an up/down pair (e.g. `create_company_table`), NOT the
//! per-direction suffix. Rules applied to every generated
//! `migrations/<ts>_<name>.{up,down}.sql`:
//!
//! - If a GENERATOR-AUTHORED migration with the same base name already exists
//!   on disk (its `.up.sql` carries the `-- Generated by metaphor-schema`
//!   marker), reuse its timestamp. Both the generated `.up.sql` and `.down.sql`
//!   receive that same timestamp, so the pair stays unified and is overwritten
//!   in place at a stable identity.
//! - Otherwise the migration is genuinely new: assign a fresh timestamp
//!   strictly greater than every existing migration timestamp, shared by the
//!   up/down pair. Multiple new migrations get successive timestamps, assigned
//!   in sorted base-name order for determinism.
//! - A HAND-WRITTEN migration (no marker) sharing a base name is never reused:
//!   the generated migration gets a fresh timestamp and the hand-written file
//!   is left untouched for the cleanup pass to preserve.
//!
//! If the `migrations/` dir does not exist yet (first generation), the
//! positional timestamps produced by the generators are left untouched.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::generators::GeneratedOutput;

use super::super::migrations::{
    build_migration_index, is_unstable_timestamped_migration, migration_base_name,
    migration_direction,
};

pub(super) fn stabilize_migration_timestamps(generated: &mut GeneratedOutput, output_dir: &Path) {
    let migrations_dir = output_dir.join("migrations");
    if !migrations_dir.exists() {
        return; // First generation: positional timestamps are correct.
    }

    let index = build_migration_index(&migrations_dir);
    let Some(max_ts) = index.max_ts else {
        return; // No timestamped files on disk — nothing to stabilize against.
    };
    let mut next_new = bump_timestamp(&max_ts);

    // Group generated migration paths by base name so an up/down pair shares a
    // single timestamp decision. BTreeMap → deterministic order across runs
    // (HashMap iteration order is not), which makes fresh-timestamp assignment
    // to genuinely-new migrations reproducible.
    let mut by_name: BTreeMap<String, Vec<PathBuf>> = BTreeMap::new();
    for path in generated.files.keys() {
        if !is_unstable_timestamped_migration(path) {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let Some(base) = migration_base_name(name) else {
            continue;
        };
        by_name.entry(base.to_string()).or_default().push(path.clone());
    }

    // (old_path, new_path) remappings, applied after the iteration.
    let mut remaps: Vec<(PathBuf, PathBuf)> = Vec::new();

    for (base, paths) in &by_name {
        // Decide ONE timestamp for the whole migration (its up and down together)
        // so the pair can never split across two timestamps.
        let ts = match index.authored.get(base.as_str()) {
            // Existing generator-authored identity: reuse its on-disk timestamp.
            Some(existing) => existing.clone(),
            // Genuinely new (or collides only with a hand-written migration):
            // assign the next fresh, strictly-later timestamp.
            None => {
                let t = next_new.clone();
                next_new = bump_timestamp(&next_new);
                t
            }
        };
        for path in paths {
            let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
                continue;
            };
            let Some(dir) = migration_direction(name) else {
                continue;
            };
            let Some(parent) = path.parent() else {
                continue;
            };
            let new_path = parent.join(format!("{}_{}{}", ts, base, dir));
            if new_path != *path {
                remaps.push((path.clone(), new_path));
            }
        }
    }

    for (old, new) in remaps {
        if let Some(content) = generated.files.remove(&old) {
            generated.files.insert(new, content);
        }
    }
}

/// Add one second to a `YYYYMMDDHHMMSS` timestamp string, returning the next.
/// Falls back to the input unchanged if parsing fails (should not happen for
/// values produced by `build_migration_index`, which only emits valid
/// 14-digit prefixes).
fn bump_timestamp(ts: &str) -> String {
    use chrono::{NaiveDateTime, TimeDelta, TimeZone};
    if let Ok(ndt) = NaiveDateTime::parse_from_str(ts, "%Y%m%d%H%M%S") {
        let utc = chrono::Utc.from_utc_datetime(&ndt);
        return (utc + TimeDelta::seconds(1))
            .format("%Y%m%d%H%M%S")
            .to_string();
    }
    ts.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::GeneratedOutput;
    use std::path::Path;

    fn mig(ts: &str, base: &str, dir: &str) -> PathBuf {
        PathBuf::from(format!("migrations/{}_{}{}", ts, base, dir))
    }

    fn has(generated: &GeneratedOutput, ts: &str, base: &str, dir: &str) -> bool {
        generated
            .files
            .contains_key(Path::new(&format!("migrations/{}_{}{}", ts, base, dir)))
    }

    fn write_authored(dir: &std::path::Path, ts: &str, base: &str, dir_kind: &str) {
        std::fs::write(
            dir.join(format!("{}_{}{}", ts, base, dir_kind)),
            "-- Generated by metaphor-schema\n",
        )
        .unwrap();
    }

    #[test]
    fn bump_adds_one_second() {
        assert_eq!(bump_timestamp("20260723180001"), "20260723180002");
        // Rolls over minutes/hours/days correctly via chrono.
        assert_eq!(bump_timestamp("20260723180059"), "20260723180100");
        assert_eq!(bump_timestamp("20260723235959"), "20260724000000");
    }

    #[test]
    fn up_and_down_pair_share_one_timestamp_when_reused() {
        // On disk: company already at 20260426220001 (generator-authored).
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        let md = dir.join("migrations");
        std::fs::create_dir_all(&md).unwrap();
        write_authored(&md, "20260426220001", "create_company_table", ".up.sql");
        write_authored(&md, "20260426220001", "create_company_table", ".down.sql");

        // Generator (out of topo order) produced the pair at a different ts.
        let mut generated = GeneratedOutput::default();
        generated.files.insert(mig("20260426220009", "create_company_table", ".up.sql"), "-- new up\n".to_string());
        generated.files.insert(mig("20260426220009", "create_company_table", ".down.sql"), "-- new down\n".to_string());

        stabilize_migration_timestamps(&mut generated, dir);

        // BOTH directions reuse the existing on-disk timestamp → pair stays unified.
        assert!(has(&generated, "20260426220001", "create_company_table", ".up.sql"));
        assert!(has(&generated, "20260426220001", "create_company_table", ".down.sql"));
        assert!(!has(&generated, "20260426220009", "create_company_table", ".up.sql"));
    }

    #[test]
    fn asymmetric_pair_is_unified_not_split() {
        // Regression guard: on-disk has the .up.sql but NOT the .down.sql.
        // The regenerated down must land at the SAME timestamp as the up
        // (reused), not at max+1 — otherwise the runner sees two migrations.
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        let md = dir.join("migrations");
        std::fs::create_dir_all(&md).unwrap();
        write_authored(&md, "20260426220001", "create_company_table", ".up.sql");
        // (no .down.sql on disk)

        let mut generated = GeneratedOutput::default();
        generated.files.insert(mig("20260426220009", "create_company_table", ".up.sql"), "-- up\n".to_string());
        generated.files.insert(mig("20260426220009", "create_company_table", ".down.sql"), "-- down\n".to_string());

        stabilize_migration_timestamps(&mut generated, dir);

        assert!(has(&generated, "20260426220001", "create_company_table", ".up.sql"));
        assert!(has(&generated, "20260426220001", "create_company_table", ".down.sql"));
        assert!(!has(&generated, "20260426220007", "create_company_table", ".down.sql"));
    }

    #[test]
    fn hand_written_migration_is_not_reused() {
        // A hand-written (no marker) migration shares a base name with a new
        // generated entity. Its timestamp must NOT be reused — the generated
        // migration gets a fresh max+1, leaving the hand-written file for the
        // cleanup pass to preserve.
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        let md = dir.join("migrations");
        std::fs::create_dir_all(&md).unwrap();
        // Hand-written, no marker:
        std::fs::write(md.join("20240101120000_create_user_table.up.sql"), "-- hand\n").unwrap();
        // A generator-authored migration establishes the max timestamp:
        write_authored(&md, "20260426220006", "add_audit_triggers", ".up.sql");

        let mut generated = GeneratedOutput::default();
        generated.files.insert(mig("20260426220003", "create_user_table", ".up.sql"), "-- gen\n".to_string());
        generated.files.insert(mig("20260426220003", "create_user_table", ".down.sql"), "-- gen\n".to_string());

        stabilize_migration_timestamps(&mut generated, dir);

        // Not reused (would have been 20240101120000); gets max+1 = ...20007.
        assert!(has(&generated, "20260426220007", "create_user_table", ".up.sql"));
        assert!(has(&generated, "20260426220007", "create_user_table", ".down.sql"));
        assert!(!has(&generated, "20240101120000", "create_user_table", ".up.sql"));
    }

    #[test]
    fn new_migration_gets_max_plus_one_no_collision() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        let md = dir.join("migrations");
        std::fs::create_dir_all(&md).unwrap();
        write_authored(&md, "20260426220006", "add_audit_triggers", ".up.sql");
        write_authored(&md, "20260426220003", "create_department_table", ".up.sql");

        // Generator produced a NEW entity at a colliding positional slot (003).
        let mut generated = GeneratedOutput::default();
        generated.files.insert(mig("20260426220003", "create_industry_table", ".up.sql"), "-- new\n".to_string());
        generated.files.insert(mig("20260426220003", "create_industry_table", ".down.sql"), "-- new\n".to_string());

        stabilize_migration_timestamps(&mut generated, dir);

        // Must NOT be 003 (collision); must be max+1 = 007, pair unified.
        assert!(has(&generated, "20260426220007", "create_industry_table", ".up.sql"));
        assert!(has(&generated, "20260426220007", "create_industry_table", ".down.sql"));
        assert!(!has(&generated, "20260426220003", "create_industry_table", ".up.sql"));
    }

    #[test]
    fn multiple_new_migrations_get_distinct_successive_timestamps() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        let md = dir.join("migrations");
        std::fs::create_dir_all(&md).unwrap();
        write_authored(&md, "20260426220006", "add_audit_triggers", ".up.sql");

        let mut generated = GeneratedOutput::default();
        generated.files.insert(mig("20260426220003", "create_industry_table", ".up.sql"), "-- a\n".to_string());
        generated.files.insert(mig("20260426220003", "create_company_industry_table", ".up.sql"), "-- b\n".to_string());

        stabilize_migration_timestamps(&mut generated, dir);

        let mut tses: Vec<String> = generated
            .files
            .keys()
            .filter_map(|p| p.file_name()?.to_str())
            .filter_map(|n| n.get(..14).map(|s| s.to_string()))
            .collect();
        // Both new, both > max(006), and distinct.
        assert!(tses.iter().all(|t| t.as_str() > "20260426220006"));
        tses.sort();
        tses.dedup();
        assert_eq!(tses.len(), 2); // no duplicates
    }

    #[test]
    fn no_migrations_dir_leaves_paths_untouched() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path(); // no migrations/ subdir
        let mut generated = GeneratedOutput::default();
        generated.files.insert(mig("20260426220001", "create_company_table", ".up.sql"), "x".to_string());
        stabilize_migration_timestamps(&mut generated, dir);
        assert!(has(&generated, "20260426220001", "create_company_table", ".up.sql"));
    }

    #[test]
    fn non_migration_files_are_not_renamed() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        std::fs::create_dir_all(dir.join("migrations")).unwrap();
        write_authored(&dir.join("migrations"), "20260426220006", "add_audit_triggers", ".up.sql");
        let mut generated = GeneratedOutput::default();
        generated.files.insert(PathBuf::from("src/domain/entity/company.rs"), "pub struct Company;\n".to_string());
        stabilize_migration_timestamps(&mut generated, dir);
        assert!(generated.files.contains_key(Path::new("src/domain/entity/company.rs")));
    }
}
