//! Shared, framework-free runtime emitted once into `src/generated/shared/`.
//!
//! These generic bases (CRUD api client, repository/service ports, repository
//! impl, use-case factories, entity helpers, injectable HTTP transport) collapse
//! the per-entity boilerplate: a generated entity file just extends/calls these,
//! instead of repeating ~300 lines of identical CRUD. Pure TypeScript — the only
//! external import is `zod` (none here) — so the purity guard still holds.

/// `(relative path under output root, file content)` for every shared file.
pub fn shared_files() -> Vec<(&'static str, &'static str)> {
    vec![
        ("shared/http/index.ts", HTTP),
        ("shared/types/pagination.ts", PAGINATION),
        ("shared/types/index.ts", "// Generated by metaphor-webgen\nexport * from './pagination';\n"),
        ("shared/crud/CrudService.ts", CRUD_SERVICE),
        ("shared/crud/CrudRepository.ts", CRUD_REPOSITORY),
        ("shared/crud/BaseCrudApiClient.ts", BASE_API_CLIENT),
        ("shared/crud/BaseRepositoryImpl.ts", BASE_REPO_IMPL),
        ("shared/crud/crudUseCases.ts", CRUD_USECASES),
        ("shared/crud/crudAppService.ts", CRUD_APPSERVICE),
        ("shared/crud/index.ts", CRUD_INDEX),
        ("shared/entity/helpers.ts", ENTITY_HELPERS),
    ]
}

const HTTP: &str = r#"/**
 * Injectable HTTP transport (fetch-compatible).
 *
 * Generated API clients call `httpRequest`, which defaults to the global
 * `fetch`. An application overrides it once at startup with any fetch-compatible
 * client (e.g. `ky`, which extends fetch) to reuse its auth/refresh/error
 * pipeline:
 *
 *   import ky from 'ky';
 *   import { setHttpRequest } from '@/generated/shared/http';
 *   setHttpRequest((input, init) => ky(input as string, init));
 *
 * @module shared/http
 */

export type HttpRequestFn = (input: string, init?: RequestInit) => Promise<Response>;

let _request: HttpRequestFn = (input, init) => fetch(input, init);

/** Override the transport used by every generated API client. */
export function setHttpRequest(fn: HttpRequestFn): void {
  _request = fn;
}

/** Perform an HTTP request through the configured transport. */
export function httpRequest(input: string, init?: RequestInit): Promise<Response> {
  return _request(input, init);
}
"#;

const PAGINATION: &str = r#"/**
 * Shared pagination types.
 *
 * @module shared/types/pagination
 */

/** Generic paginated response envelope. */
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
}

/** Common list query parameters. */
export interface PaginationParams {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  search?: string;
}
"#;

const CRUD_SERVICE: &str = r#"/**
 * Generic service ports (the contract an API client implements) + an injectable
 * singleton accessor factory.
 *
 * @module shared/crud/CrudService
 */

import type { PaginatedResponse } from '../types/pagination';

export interface CrudService<T, C, U, Q = unknown, F = unknown> {
  getById(id: string): Promise<T>;
  getAll(params?: Q, filters?: F): Promise<PaginatedResponse<T>>;
  create(input: C): Promise<T>;
  update(id: string, input: U): Promise<T>;
  patch(id: string, input: Partial<U>): Promise<T>;
  delete(id: string): Promise<void>;
  exists(id: string): Promise<boolean>;
  count(filters?: F): Promise<number>;
}

export interface SoftDeleteCrudService<T, C, U, Q = unknown, F = unknown>
  extends CrudService<T, C, U, Q, F> {
  getDeleted(params?: Q, filters?: F): Promise<PaginatedResponse<T>>;
  getDeletedById(id: string): Promise<T>;
  restore(id: string): Promise<T>;
  permanentDelete(id: string): Promise<void>;
  emptyTrash(): Promise<{ deleted: number }>;
  countDeleted(): Promise<number>;
}

/** Build a typed, injectable singleton accessor for a service implementation. */
export function makeServiceAccessor<S>(name: string): { get: () => S; set: (impl: S) => void } {
  let instance: S | null = null;
  return {
    set: (impl: S) => {
      instance = impl;
    },
    get: () => {
      if (!instance) {
        throw new Error(`${name}Service not initialized. Call set${name}Service() first.`);
      }
      return instance;
    },
  };
}
"#;

const CRUD_REPOSITORY: &str = r#"/**
 * Generic repository port + result envelopes.
 *
 * @module shared/crud/CrudRepository
 */

import type { PaginatedResponse } from '../types/pagination';

export interface DeleteResult {
  success: boolean;
  id: string;
}

export interface BatchResult {
  success: boolean;
  count: number;
  ids: string[];
  errors?: Array<{ id: string; error: string }>;
}

export interface CrudRepository<T, C, U, Q = unknown, F = unknown> {
  findById(id: string): Promise<T | null>;
  findByIdOrThrow(id: string): Promise<T>;
  findAll(params?: Q, filters?: F): Promise<PaginatedResponse<T>>;
  create(input: C): Promise<T>;
  update(id: string, input: U): Promise<T>;
  delete(id: string): Promise<DeleteResult>;
  exists(id: string): Promise<boolean>;
  count(filters?: F): Promise<number>;
  createMany(inputs: C[]): Promise<BatchResult>;
  deleteMany(ids: string[]): Promise<BatchResult>;
}
"#;

const BASE_API_CLIENT: &str = r#"/**
 * Generic REST CRUD API client. Concrete clients only declare `module` +
 * `collection`; all transport goes through the injectable `httpRequest`.
 *
 * @module shared/crud/BaseCrudApiClient
 */

import { httpRequest } from '../http';
import type { PaginatedResponse } from '../types/pagination';
import type { CrudService, SoftDeleteCrudService } from './CrudService';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '/api';
const API_VERSION = 'v1';

export interface ApiResponseMeta {
  total: number;
  page: number;
  limit: number;
  total_pages: number;
}

/** Flat paginated API response: { success, data, meta }. */
export interface PaginatedApiResponse<T> {
  success: boolean;
  data: T[];
  meta: ApiResponseMeta;
  error?: string;
}

export class CrudApiError extends Error {
  constructor(
    message: string,
    public status: number,
    public code?: string,
    public details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'CrudApiError';
  }
}

function buildQuery(params?: Record<string, unknown>): string {
  if (!params) return '';
  const sp = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) sp.append(k, String(v));
  }
  const q = sp.toString();
  return q ? `?${q}` : '';
}

async function handle<R>(res: Response): Promise<R> {
  if (!res.ok) {
    const body = (await res.json().catch(() => ({}))) as {
      message?: string;
      code?: string;
      details?: Record<string, unknown>;
    };
    throw new CrudApiError(body.message || `HTTP error ${res.status}`, res.status, body.code, body.details);
  }
  return res.json() as Promise<R>;
}

function toPaginated<T>(res: PaginatedApiResponse<T>): PaginatedResponse<T> {
  if (!res.success) throw new CrudApiError(res.error || 'Failed to fetch', 500, 'FETCH_FAILED');
  const { data, meta } = res;
  return {
    data,
    total: meta.total,
    page: meta.page,
    limit: meta.limit,
    totalPages: meta.total_pages,
    hasNext: meta.page < meta.total_pages,
    hasPrev: meta.page > 1,
  };
}

export abstract class BaseCrudApiClient<T, C, U, Q = unknown, F = unknown>
  implements CrudService<T, C, U, Q, F>
{
  protected abstract readonly module: string;
  protected abstract readonly collection: string;

  protected basePath(): string {
    return `${API_BASE_URL}/${API_VERSION}/${this.module}/${this.collection}`;
  }
  protected url(path = ''): string {
    return `${this.basePath()}${path}`;
  }
  protected headers(): HeadersInit {
    return { 'Content-Type': 'application/json' };
  }

  async getById(id: string): Promise<T> {
    return handle<T>(await httpRequest(this.url(`/${id}`), { method: 'GET', headers: this.headers() }));
  }

  async getAll(params?: Q, filters?: F): Promise<PaginatedResponse<T>> {
    const qs = buildQuery({ ...(params as Record<string, unknown>), ...(filters as Record<string, unknown>) });
    return toPaginated(
      await handle<PaginatedApiResponse<T>>(
        await httpRequest(this.url(qs), { method: 'GET', headers: this.headers() }),
      ),
    );
  }

  async create(input: C): Promise<T> {
    return handle<T>(
      await httpRequest(this.url(''), { method: 'POST', headers: this.headers(), body: JSON.stringify(input) }),
    );
  }

  async update(id: string, input: U): Promise<T> {
    return handle<T>(
      await httpRequest(this.url(`/${id}`), { method: 'PUT', headers: this.headers(), body: JSON.stringify(input) }),
    );
  }

  async patch(id: string, input: Partial<U>): Promise<T> {
    return handle<T>(
      await httpRequest(this.url(`/${id}`), { method: 'PATCH', headers: this.headers(), body: JSON.stringify(input) }),
    );
  }

  async delete(id: string): Promise<void> {
    const res = await httpRequest(this.url(`/${id}`), { method: 'DELETE', headers: this.headers() });
    if (!res.ok) {
      const b = (await res.json().catch(() => ({}))) as { message?: string; code?: string };
      throw new CrudApiError(b.message || `HTTP error ${res.status}`, res.status, b.code);
    }
  }

  async exists(id: string): Promise<boolean> {
    try {
      const res = await httpRequest(this.url(`/${id}`), { method: 'HEAD', headers: this.headers() });
      return res.ok;
    } catch {
      return false;
    }
  }

  async count(filters?: F): Promise<number> {
    const res = await handle<{ count: number }>(
      await httpRequest(this.url('/count' + buildQuery(filters as Record<string, unknown>)), {
        method: 'GET',
        headers: this.headers(),
      }),
    );
    return res.count;
  }
}

export abstract class SoftDeleteCrudApiClient<T, C, U, Q = unknown, F = unknown>
  extends BaseCrudApiClient<T, C, U, Q, F>
  implements SoftDeleteCrudService<T, C, U, Q, F>
{
  async getDeleted(params?: Q, filters?: F): Promise<PaginatedResponse<T>> {
    const qs = buildQuery({ ...(params as Record<string, unknown>), ...(filters as Record<string, unknown>) });
    return toPaginated(
      await handle<PaginatedApiResponse<T>>(
        await httpRequest(this.url('/trash' + qs), { method: 'GET', headers: this.headers() }),
      ),
    );
  }

  async getDeletedById(id: string): Promise<T> {
    return handle<T>(await httpRequest(this.url(`/trash/${id}`), { method: 'GET', headers: this.headers() }));
  }

  async restore(id: string): Promise<T> {
    return handle<T>(await httpRequest(this.url(`/${id}/restore`), { method: 'POST', headers: this.headers() }));
  }

  async permanentDelete(id: string): Promise<void> {
    const res = await httpRequest(this.url(`/trash/${id}`), { method: 'DELETE', headers: this.headers() });
    if (!res.ok) {
      const b = (await res.json().catch(() => ({}))) as { message?: string; code?: string };
      throw new CrudApiError(b.message || `HTTP error ${res.status}`, res.status, b.code);
    }
  }

  async emptyTrash(): Promise<{ deleted: number }> {
    return handle<{ deleted: number }>(
      await httpRequest(this.url('/trash'), { method: 'DELETE', headers: this.headers() }),
    );
  }

  async countDeleted(): Promise<number> {
    const res = await handle<{ count: number }>(
      await httpRequest(this.url('/trash/count'), { method: 'GET', headers: this.headers() }),
    );
    return res.count;
  }
}
"#;

const BASE_REPO_IMPL: &str = r#"/**
 * Generic repository implementation that delegates to a CRUD service (the API
 * client). Concrete repos only pass the service + primary-key field.
 *
 * @module shared/crud/BaseRepositoryImpl
 */

import { CrudApiError } from './BaseCrudApiClient';
import type { BatchResult, CrudRepository, DeleteResult } from './CrudRepository';
import type { CrudService } from './CrudService';

export abstract class BaseRepositoryImpl<T, C, U, Q = unknown, F = unknown>
  implements CrudRepository<T, C, U, Q, F>
{
  protected readonly service: CrudService<T, C, U, Q, F>;
  protected readonly pk: keyof T;

  constructor(service: CrudService<T, C, U, Q, F>, pk: keyof T) {
    this.service = service;
    this.pk = pk;
  }

  async findById(id: string): Promise<T | null> {
    try {
      return await this.service.getById(id);
    } catch (e) {
      if (e instanceof CrudApiError && e.status === 404) return null;
      throw e;
    }
  }

  async findByIdOrThrow(id: string): Promise<T> {
    const result = await this.findById(id);
    if (!result) throw new CrudApiError(`Not found: ${id}`, 404, 'NOT_FOUND');
    return result;
  }

  findAll(params?: Q, filters?: F) {
    return this.service.getAll(params, filters);
  }
  create(input: C) {
    return this.service.create(input);
  }
  update(id: string, input: U) {
    return this.service.update(id, input);
  }
  exists(id: string) {
    return this.service.exists(id);
  }
  count(filters?: F) {
    return this.service.count(filters);
  }

  async delete(id: string): Promise<DeleteResult> {
    await this.service.delete(id);
    return { success: true, id };
  }

  async createMany(inputs: C[]): Promise<BatchResult> {
    const results = await Promise.all(inputs.map((i) => this.service.create(i)));
    return { success: true, count: results.length, ids: results.map((e) => String(e[this.pk])) };
  }

  async deleteMany(ids: string[]): Promise<BatchResult> {
    await Promise.all(ids.map((id) => this.service.delete(id)));
    return { success: true, count: ids.length, ids };
  }
}
"#;

const CRUD_USECASES: &str = r#"/**
 * Generic use-case factories. An entity's use cases are a single call:
 *   const x = makeCrudUseCases('ACCOUNT', getAccountService);
 *
 * @module shared/crud/crudUseCases
 */

import type { PaginatedResponse } from '../types/pagination';
import type { CrudService, SoftDeleteCrudService } from './CrudService';

export interface UseCaseContext {
  userId?: string;
  permissions?: string[];
  correlationId?: string;
}

export interface UseCaseResult<T> {
  success: boolean;
  data?: T;
  error?: { code: string; message: string };
}

const msg = (e: unknown) => (e instanceof Error ? e.message : 'Unknown error');
const ok = <T>(data: T): UseCaseResult<T> => ({ success: true, data });
const fail = (code: string, message: string): UseCaseResult<never> => ({
  success: false,
  error: { code, message },
});

export function makeCrudUseCases<T, C, U, Q, F>(
  label: string,
  getService: () => CrudService<T, C, U, Q, F>,
) {
  return {
    create: async (input: C, _ctx?: UseCaseContext): Promise<UseCaseResult<T>> => {
      try {
        return ok(await getService().create(input));
      } catch (e) {
        return fail(`CREATE_${label}_FAILED`, msg(e));
      }
    },
    update: async (id: string, input: U, _ctx?: UseCaseContext): Promise<UseCaseResult<T>> => {
      try {
        const existing = await getService()
          .getById(id)
          .catch(() => null);
        if (!existing) return fail(`${label}_NOT_FOUND`, `${label} ${id} not found`);
        return ok(await getService().update(id, input));
      } catch (e) {
        return fail(`UPDATE_${label}_FAILED`, msg(e));
      }
    },
    patch: async (id: string, input: Partial<U>, _ctx?: UseCaseContext): Promise<UseCaseResult<T>> => {
      try {
        return ok(await getService().patch(id, input));
      } catch (e) {
        return fail(`PATCH_${label}_FAILED`, msg(e));
      }
    },
    remove: async (id: string, _ctx?: UseCaseContext): Promise<UseCaseResult<void>> => {
      try {
        await getService().delete(id);
        return { success: true };
      } catch (e) {
        return fail(`DELETE_${label}_FAILED`, msg(e));
      }
    },
    getById: async (id: string, _ctx?: UseCaseContext): Promise<UseCaseResult<T>> => {
      try {
        return ok(await getService().getById(id));
      } catch (e) {
        return fail(`GET_${label}_FAILED`, msg(e));
      }
    },
    list: async (params?: Q, filters?: F, _ctx?: UseCaseContext): Promise<UseCaseResult<PaginatedResponse<T>>> => {
      try {
        return ok(await getService().getAll(params, filters));
      } catch (e) {
        return fail(`LIST_${label}_FAILED`, msg(e));
      }
    },
  };
}

export function makeSoftDeleteUseCases<T, C, U, Q, F>(
  label: string,
  getService: () => SoftDeleteCrudService<T, C, U, Q, F>,
) {
  return {
    softDelete: async (id: string): Promise<UseCaseResult<void>> => {
      try {
        await getService().delete(id);
        return { success: true };
      } catch (e) {
        return fail(`SOFT_DELETE_${label}_FAILED`, msg(e));
      }
    },
    restore: async (id: string): Promise<UseCaseResult<T>> => {
      try {
        return ok(await getService().restore(id));
      } catch (e) {
        return fail(`RESTORE_${label}_FAILED`, msg(e));
      }
    },
    permanentDelete: async (id: string): Promise<UseCaseResult<void>> => {
      try {
        await getService().permanentDelete(id);
        return { success: true };
      } catch (e) {
        return fail(`PERMANENT_DELETE_${label}_FAILED`, msg(e));
      }
    },
    listDeleted: async (params?: Q, filters?: F): Promise<UseCaseResult<PaginatedResponse<T>>> => {
      try {
        return ok(await getService().getDeleted(params, filters));
      } catch (e) {
        return fail(`LIST_DELETED_${label}_FAILED`, msg(e));
      }
    },
  };
}
"#;

const CRUD_APPSERVICE: &str = r#"/**
 * Generic application-service factory: a thin, DTO-free orchestration surface
 * over a CRUD service. Entities get one: `makeCrudAppService(getXService)`.
 *
 * @module shared/crud/crudAppService
 */

import type { PaginatedResponse } from '../types/pagination';
import type { CrudService } from './CrudService';

export function makeCrudAppService<T, C, U, Q, F>(getService: () => CrudService<T, C, U, Q, F>) {
  return {
    get: (id: string): Promise<T> => getService().getById(id),
    list: (params?: Q, filters?: F): Promise<PaginatedResponse<T>> => getService().getAll(params, filters),
    create: (input: C): Promise<T> => getService().create(input),
    update: (id: string, input: U): Promise<T> => getService().update(id, input),
    patch: (id: string, input: Partial<U>): Promise<T> => getService().patch(id, input),
    remove: (id: string): Promise<void> => getService().delete(id),
  };
}
"#;

const CRUD_INDEX: &str = r#"// Generated by metaphor-webgen
export * from './CrudService';
export * from './CrudRepository';
export * from './BaseCrudApiClient';
export * from './BaseRepositoryImpl';
export * from './crudUseCases';
export * from './crudAppService';
"#;

const ENTITY_HELPERS: &str = r#"/**
 * Generic entity helpers used by generated entity files.
 *
 * @module shared/entity/helpers
 */

/** Shallow clone with optional field overrides. */
export function cloneEntity<T>(entity: T, overrides: Partial<T> = {}): T {
  return { ...entity, ...overrides };
}

/** Compare two entities by a key (usually the primary key). */
export function equalsBy<T>(a: T, b: T, key: keyof T): boolean {
  return a[key] === b[key];
}

/** Structural guard: a non-null object with a string-typed `key`. */
export function hasStringKey(value: unknown, key: string): boolean {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof (value as Record<string, unknown>)[key] === 'string'
  );
}
"#;
