//! Webapp code generator

use std::fs;
use std::path::{Path, PathBuf};
use crate::webgen::config::{Config, Target};
use crate::webgen::error::{Error, Result};
use crate::webgen::parser::{ProtoParser, WorkflowParser, HookParser, ModelParser, to_snake_case, to_pascal_case};
use crate::webgen::templates::{
    HookTemplate, SchemaTemplate, FormTemplate, PageTemplate, TemplateReplacer
};

/// Webapp code generator
pub struct Generator {
    config: Config,
}

impl Generator {
    /// Create a new generator with the given config
    pub fn new(config: Config) -> Result<Self> {
        config.validate()?;
        Ok(Self { config })
    }

    /// Run the code generation
    pub fn generate(&self) -> Result<GenerationResult> {
        let mut result = GenerationResult::default();

        // Validate output directory exists
        if !self.config.output_dir.exists() {
            return Err(Error::WebappNotFound(self.config.output_dir.clone()));
        }

        // Check if we only need enhanced targets (no proto required)
        let only_enhanced = self.config.targets.iter().all(|t| t.is_enhanced());

        // Find proto entities (only if not doing enhanced-only generation)
        let entities = if only_enhanced {
            Vec::new() // Not needed for enhanced targets
        } else {
            let proto_dir = self.config.proto_dir();
            ProtoParser::find_entities(
                &proto_dir,
                self.config.entity_filter.as_deref(),
            )?
        };

        if !only_enhanced && entities.is_empty() {
            return Err(Error::NoEntitiesFound);
        }

        result.entities_found = entities.len();

        // Generate for each target
        for target in &self.config.targets {
            match target {
                Target::Hooks => self.generate_hooks(&entities, &mut result)?,
                Target::Schemas => self.generate_schemas(&entities, &mut result)?,
                Target::Forms => self.generate_forms(&entities, &mut result)?,
                Target::Pages => self.generate_pages(&entities, &mut result)?,
                Target::Types => {
                    // Types are generated by buf, skip
                    result.skipped += entities.len();
                }
                Target::All => {
                    // Handled by expanding targets
                }
                Target::Workflows => {
                    self.generate_workflows(&mut result)?;
                }
                Target::StateMachines => {
                    self.generate_state_machines(&mut result)?;
                }
                Target::Routing => {
                    self.generate_routing(&entities, &mut result)?;
                }
                Target::EnhancedCrud => {
                    // Enhanced CRUD uses YAML schema parsing
                    self.generate_enhanced_crud(&mut result)?;
                }
                Target::Domain => {
                    // Domain layer generation uses YAML schema parsing via EnhancedGenerator
                    self.generate_domain_layer(&mut result)?;
                }
                Target::Presentation => {
                    // Presentation layer uses YAML schema parsing via EnhancedGenerator
                    self.generate_presentation_layer(&mut result)?;
                }
                Target::Application => {
                    // Application layer uses YAML schema parsing via EnhancedGenerator
                    self.generate_application_layer(&mut result)?;
                }
                Target::Infrastructure => {
                    // Infrastructure layer uses YAML schema parsing via EnhancedGenerator
                    self.generate_infrastructure_layer(&mut result)?;
                }
            }
        }

        Ok(result)
    }

    /// Generate React Query hooks
    fn generate_hooks(&self, entities: &[crate::webgen::parser::ProtoEntity], result: &mut GenerationResult) -> Result<()> {
        let hooks_dir = self.config.output_dir
            .join("application/hooks")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&hooks_dir)
                .map_err(|e| Error::Parse(format!("Failed to create hooks dir: {}", e)))?;
        }

        let domain_import = self.config.domain_import_path();

        for entity in entities {
            let entity_pascal = to_pascal_case(&entity.name);
            let entity_snake = to_snake_case(&entity.name);
            let replacer = TemplateReplacer::new(
                entity_pascal.clone(),
                entity_snake,
                self.config.module.clone(),
                domain_import.clone(),
            );

            // Generate query hook
            let query_template = HookTemplate::query();
            let query_content = replacer.replace(query_template);
            let query_path = hooks_dir.join(format!("use{}.ts", entity_pascal));

            if self.config.dry_run {
                result.dry_run_files.push(query_path);
            } else {
                self.write_file(&query_path, &query_content, false)?;
                result.files_generated.push(query_path);
            }

            // Generate mutation hook
            let mutation_template = HookTemplate::mutation();
            let mutation_content = replacer.replace(mutation_template);
            let mutation_path = hooks_dir.join(format!("use{}Mutation.ts", entity_pascal));

            if self.config.dry_run {
                result.dry_run_files.push(mutation_path);
            } else {
                self.write_file(&mutation_path, &mutation_content, false)?;
                result.files_generated.push(mutation_path);
            }
        }

        Ok(())
    }

    /// Generate Zod schemas
    fn generate_schemas(&self, entities: &[crate::webgen::parser::ProtoEntity], result: &mut GenerationResult) -> Result<()> {
        let validators_dir = self.config.output_dir
            .join("application/validators")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&validators_dir)
                .map_err(|e| Error::Parse(format!("Failed to create validators dir: {}", e)))?;
        }

        let domain_import = self.config.domain_import_path();

        for entity in entities {
            let entity_pascal = to_pascal_case(&entity.name);
            let entity_snake = to_snake_case(&entity.name);
            let replacer = TemplateReplacer::new(
                entity_pascal.clone(),
                entity_snake.clone(),
                self.config.module.clone(),
                domain_import.clone(),
            );

            let template = SchemaTemplate::schema();
            let content = replacer.replace(template);
            let output_path = validators_dir.join(format!("{}.schema.ts", entity_snake));

            if self.config.dry_run {
                result.dry_run_files.push(output_path);
            } else {
                self.write_file(&output_path, &content, true)?;
                result.files_generated.push(output_path);
            }
        }

        Ok(())
    }

    /// Generate form components
    fn generate_forms(&self, entities: &[crate::webgen::parser::ProtoEntity], result: &mut GenerationResult) -> Result<()> {
        let forms_dir = self.config.output_dir
            .join("presentation/components/forms")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&forms_dir)
                .map_err(|e| Error::Parse(format!("Failed to create forms dir: {}", e)))?;
        }

        let domain_import = self.config.domain_import_path();

        for entity in entities {
            let entity_pascal = to_pascal_case(&entity.name);
            let entity_snake = to_snake_case(&entity.name);
            let replacer = TemplateReplacer::new(
                entity_pascal.clone(),
                entity_snake.clone(),
                self.config.module.clone(),
                domain_import.clone(),
            );

            // Generate create form
            let create_template = FormTemplate::create();
            let create_content = replacer.replace(create_template);
            let create_path = forms_dir.join(format!("{}CreateForm.tsx", entity_pascal));

            if self.config.dry_run {
                result.dry_run_files.push(create_path.clone());
            } else {
                self.write_file(&create_path, &create_content, false)?;
                result.files_generated.push(create_path);
            }

            // Generate edit form
            let edit_template = FormTemplate::edit();
            let edit_content = replacer.replace(edit_template);
            let edit_path = forms_dir.join(format!("{}EditForm.tsx", entity_pascal));

            if self.config.dry_run {
                result.dry_run_files.push(edit_path.clone());
            } else {
                self.write_file(&edit_path, &edit_content, false)?;
                result.files_generated.push(edit_path);
            }
        }

        Ok(())
    }

    /// Generate CRUD pages
    fn generate_pages(&self, entities: &[crate::webgen::parser::ProtoEntity], result: &mut GenerationResult) -> Result<()> {
        let domain_import = self.config.domain_import_path();

        for entity in entities {
            let entity_pascal = to_pascal_case(&entity.name);
            let entity_snake = to_snake_case(&entity.name);
            let replacer = TemplateReplacer::new(
                entity_pascal.clone(),
                entity_snake.clone(),
                self.config.module.clone(),
                domain_import.clone(),
            );

            let pages_dir = self.config.output_dir
                .join("presentation/pages")
                .join(&self.config.module)
                .join(&entity_snake);

            if !self.config.dry_run {
                fs::create_dir_all(&pages_dir)
                    .map_err(|e| Error::Parse(format!("Failed to create pages dir: {}", e)))?;
            }

            // Generate all CRUD pages
            for page in ["list", "detail", "create", "edit"] {
                let template = match page {
                    "list" => PageTemplate::list(),
                    "detail" => PageTemplate::detail(),
                    "create" => PageTemplate::create(),
                    "edit" => PageTemplate::edit(),
                    _ => continue,
                };

                let content = replacer.replace(template);
                let page_pascal = to_pascal_case(page);
                let output_path = pages_dir.join(format!("{}{}Page.tsx", entity_pascal, page_pascal));

                if self.config.dry_run {
                    result.dry_run_files.push(output_path.clone());
                } else {
                    self.write_file(&output_path, &content, false)?;
                    result.files_generated.push(output_path);
                }
            }
        }

        Ok(())
    }

    /// Write file to disk
    fn write_file(&self, path: &PathBuf, content: &str, create_index: bool) -> Result<()> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| Error::write_error(path.clone(), e))?;
        }

        // Check if file exists and force is not set
        if path.exists() && !self.config.force {
            // TODO: Implement custom section preservation
            // For now, just overwrite
        }

        fs::write(path, content)
            .map_err(|e| Error::write_error(path.clone(), e))?;

        if create_index {
            self.update_index_file(path)?;
        }

        Ok(())
    }

    /// Update or create index.ts for exports
    fn update_index_file(&self, path: &Path) -> Result<()> {
        if let Some(dir) = path.parent() {
            let index_path = dir.join("index.ts");
            let module_name = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("export");

            let mut content = if index_path.exists() {
                fs::read_to_string(&index_path)
                    .map_err(|e| Error::write_error(index_path.clone(), e))?
            } else {
                String::new()
            };

            let export_line = format!("export * from './{}';", module_name);
            if !content.contains(&export_line) {
                content.push_str(&export_line);
                content.push('\n');
                fs::write(&index_path, content)
                    .map_err(|e| Error::write_error(index_path.clone(), e))?;
            }
        }

        Ok(())
    }

    /// List entities that would be generated (without generating)
    pub fn list_entities(&self) -> Result<Vec<String>> {
        let proto_dir = self.config.proto_dir();
        let entities = ProtoParser::find_entities(&proto_dir, self.config.entity_filter.as_deref())?;

        Ok(entities.into_iter().map(|e| e.name).collect())
    }

    /// Generate workflow UI components from YAML schemas
    fn generate_workflows(&self, result: &mut GenerationResult) -> Result<()> {
        use crate::webgen::templates::workflows::WorkflowTemplates;

        let schema_dir = self.config.schema_dir();
        let workflows_dir = schema_dir.join("workflows");

        if !workflows_dir.exists() {
            // No workflows directory, skip
            return Ok(());
        }

        // Find all .workflow.yaml files
        let workflow_files = self.find_yaml_files(&workflows_dir, "workflow")?;
        if workflow_files.is_empty() {
            return Ok(());
        }

        let output_dir = self.config.output_dir
            .join("presentation/workflows")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&output_dir)
                .map_err(|e| Error::Parse(format!("Failed to create workflows dir: {}", e)))?;
        }

        for workflow_file in workflow_files {
            match WorkflowParser::parse_file(&workflow_file) {
                Ok(workflow) => {
                    // Generate workflow tracker component
                    let tracker_content = WorkflowTemplates::generate_workflow_tracker(&workflow);
                    let tracker_path = output_dir.join(format!("{}Tracker.tsx",
                        to_pascal_case(&workflow.name)));

                    if self.config.dry_run {
                        result.dry_run_files.push(tracker_path);
                    } else {
                        self.write_file(&tracker_path, &tracker_content, false)?;
                        result.files_generated.push(tracker_path);
                    }

                    // Generate workflow API hooks
                    let api_content = WorkflowTemplates::generate_workflow_api(&workflow);
                    let api_path = output_dir.join(format!("{}Api.ts",
                        to_pascal_case(&workflow.name)));

                    if self.config.dry_run {
                        result.dry_run_files.push(api_path);
                    } else {
                        self.write_file(&api_path, &api_content, false)?;
                        result.files_generated.push(api_path);
                    }
                }
                Err(e) => {
                    eprintln!("Warning: Failed to parse workflow {}: {}",
                        workflow_file.display(), e);
                }
            }
        }

        Ok(())
    }

    /// Generate state machine UI components from hook schemas
    fn generate_state_machines(&self, result: &mut GenerationResult) -> Result<()> {
        use crate::webgen::templates::state_machines::StateMachineTemplates;

        let schema_dir = self.config.schema_dir();
        let hooks_dir = schema_dir.join("hooks");

        if !hooks_dir.exists() {
            // No hooks directory, skip
            return Ok(());
        }

        // Find all .hook.yaml files
        let hook_files = self.find_yaml_files(&hooks_dir, "hook")?;
        if hook_files.is_empty() {
            return Ok(());
        }

        let output_dir = self.config.output_dir
            .join("presentation/state-machines")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&output_dir)
                .map_err(|e| Error::Parse(format!("Failed to create state-machines dir: {}", e)))?;
        }

        for hook_file in hook_files {
            match HookParser::parse_file(&hook_file) {
                Ok(hook_schema) => {
                    // Only generate state machine components if the hook has a state machine
                    if hook_schema.state_machine.is_some() {
                        // Generate state badge component
                        let badge_content = StateMachineTemplates::generate_state_badge(&hook_schema);
                        let badge_path = output_dir.join(format!("{}StateBadge.tsx",
                            to_pascal_case(&hook_schema.model)));

                        if self.config.dry_run {
                            result.dry_run_files.push(badge_path.clone());
                        } else {
                            self.write_file(&badge_path, &badge_content, false)?;
                            result.files_generated.push(badge_path);
                        }

                        // Generate transition buttons
                        let transitions_content = StateMachineTemplates::generate_transition_buttons(&hook_schema);
                        let transitions_path = output_dir.join(format!("{}TransitionButtons.tsx",
                            to_pascal_case(&hook_schema.model)));

                        if self.config.dry_run {
                            result.dry_run_files.push(transitions_path.clone());
                        } else {
                            self.write_file(&transitions_path, &transitions_content, false)?;
                            result.files_generated.push(transitions_path);
                        }

                        // Generate state machine hook
                        let hook_content = StateMachineTemplates::generate_state_machine_hook(&hook_schema);
                        let hook_path = output_dir.join(format!("use{}StateTransitions.ts",
                            to_pascal_case(&hook_schema.model)));

                        if self.config.dry_run {
                            result.dry_run_files.push(hook_path.clone());
                        } else {
                            self.write_file(&hook_path, &hook_content, false)?;
                            result.files_generated.push(hook_path);
                        }

                        // Generate state history component
                        let history_content = StateMachineTemplates::generate_state_history(&hook_schema);
                        let history_path = output_dir.join(format!("{}StateHistory.tsx",
                            to_pascal_case(&hook_schema.model)));

                        if self.config.dry_run {
                            result.dry_run_files.push(history_path.clone());
                        } else {
                            self.write_file(&history_path, &history_content, false)?;
                            result.files_generated.push(history_path);
                        }
                    }
                }
                Err(e) => {
                    eprintln!("Warning: Failed to parse hook {}: {}",
                        hook_file.display(), e);
                }
            }
        }

        Ok(())
    }

    /// Generate routing configuration from entity definitions
    fn generate_routing(&self, entities: &[crate::webgen::parser::ProtoEntity], result: &mut GenerationResult) -> Result<()> {
        use crate::webgen::templates::routing::RoutingTemplates;

        let output_dir = self.config.output_dir
            .join("shared/routing")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&output_dir)
                .map_err(|e| Error::Parse(format!("Failed to create routing dir: {}", e)))?;
        }

        // Parse model schemas to get proper entity definitions for routing
        let schema_dir = self.config.schema_dir();
        let models_dir = schema_dir.join("models");

        let entity_definitions = if models_dir.exists() {
            // Try to get entities from YAML model schemas
            match self.find_yaml_files(&models_dir, "model") {
                Ok(model_files) => {
                    let mut entities = Vec::new();
                    for model_file in model_files {
                        if let Ok(schema) = ModelParser::parse_file(&model_file) {
                            entities.extend(schema.models);
                        }
                    }
                    entities
                }
                Err(_) => vec![],
            }
        } else {
            // Fallback: create minimal entity definitions from proto entities
            entities
                .iter()
                .map(|e| crate::webgen::ast::entity::EntityDefinition {
                    name: e.name.clone(),
                    collection: to_snake_case(&e.name),
                    fields: vec![],
                    relations: vec![],
                    indexes: vec![],
                    soft_delete: false,
                })
                .collect()
        };

        if entity_definitions.is_empty() {
            // No entities to generate routing for
            return Ok(());
        }

        // Generate route definitions
        let routes_content = RoutingTemplates::generate_route_definitions(&entity_definitions, &self.config.module);
        let routes_path = output_dir.join("routes.ts");

        if self.config.dry_run {
            result.dry_run_files.push(routes_path.clone());
        } else {
            self.write_file(&routes_path, &routes_content, false)?;
            result.files_generated.push(routes_path);
        }

        // Generate route components
        let components_content = RoutingTemplates::generate_route_components(&entity_definitions, &self.config.module);
        let components_path = output_dir.join("route-components.ts");

        if self.config.dry_run {
            result.dry_run_files.push(components_path.clone());
        } else {
            self.write_file(&components_path, &components_content, false)?;
            result.files_generated.push(components_path);
        }

        // Generate route configuration
        let config_content = RoutingTemplates::generate_route_config(&entity_definitions, &self.config.module);
        let config_path = output_dir.join("route-config.tsx");

        if self.config.dry_run {
            result.dry_run_files.push(config_path.clone());
        } else {
            self.write_file(&config_path, &config_content, false)?;
            result.files_generated.push(config_path);
        }

        // Generate navigation menu
        let nav_content = RoutingTemplates::generate_navigation_menu(&entity_definitions, &self.config.module);
        let nav_path = output_dir.join("navigation.tsx");

        if self.config.dry_run {
            result.dry_run_files.push(nav_path.clone());
        } else {
            self.write_file(&nav_path, &nav_content, false)?;
            result.files_generated.push(nav_path);
        }

        Ok(())
    }

    /// Generate enhanced CRUD components from YAML model schemas
    fn generate_enhanced_crud(&self, result: &mut GenerationResult) -> Result<()> {
        use crate::webgen::templates::enhanced::{FormTemplates, TableTemplates};

        let schema_dir = self.config.schema_dir();
        let models_dir = schema_dir.join("models");

        if !models_dir.exists() {
            // No models directory, skip
            return Ok(());
        }

        // Find all .model.yaml files
        let model_files = self.find_yaml_files(&models_dir, "model")?;
        if model_files.is_empty() {
            return Ok(());
        }

        let mut all_entities = Vec::new();
        let mut all_enums = Vec::new();

        for model_file in &model_files {
            match ModelParser::parse_file(model_file) {
                Ok(schema) => {
                    all_entities.extend(schema.models);
                    all_enums.extend(schema.enums);
                }
                Err(e) => {
                    eprintln!("Warning: Failed to parse model {}: {}", model_file.display(), e);
                }
            }
        }

        if all_entities.is_empty() {
            return Ok(());
        }

        // Generate for each entity
        for entity in &all_entities {
            let entity_pascal = to_pascal_case(&entity.name);
            let entity_snake = to_snake_case(&entity.name);

            // Generate form components
            let forms_dir = self.config.output_dir
                .join("presentation/components/forms")
                .join(&self.config.module);

            if !self.config.dry_run {
                fs::create_dir_all(&forms_dir)
                    .map_err(|e| Error::Parse(format!("Failed to create forms dir: {}", e)))?;
            }

            let form_fields = FormTemplates::generate_form_fields(entity, &all_enums, true);
            let form_path = forms_dir.join(format!("{}FormFields.tsx", entity_pascal));

            if self.config.dry_run {
                result.dry_run_files.push(form_path.clone());
            } else {
                self.write_file(&form_path, &form_fields, false)?;
                result.files_generated.push(form_path);
            }

            // Generate table columns
            let table_columns = TableTemplates::generate_table_columns(entity, &self.config.module, &entity_snake);
            let table_path = forms_dir.join(format!("{}TableColumns.tsx", entity_pascal));

            if self.config.dry_run {
                result.dry_run_files.push(table_path.clone());
            } else {
                self.write_file(&table_path, &table_columns, false)?;
                result.files_generated.push(table_path);
            }
        }

        Ok(())
    }

    /// Helper to find YAML files by extension pattern
    fn find_yaml_files(&self, dir: &PathBuf, suffix: &str) -> Result<Vec<PathBuf>> {
        let mut found = Vec::new();

        let entries = fs::read_dir(dir)
            .map_err(|e| Error::Parse(format!("Failed to read directory {}: {}", dir.display(), e)))?;

        for entry in entries.flatten() {
            let path = entry.path();
            let is_yaml = path.extension().and_then(|s| s.to_str()) == Some("yaml") ||
                          path.extension().and_then(|s| s.to_str()) == Some("yml");
            let has_suffix = path.file_stem()
                .and_then(|s| s.to_str())
                .map(|s| s.ends_with(suffix))
                .unwrap_or(false);
            if is_yaml && has_suffix {
                found.push(path);
            }
        }

        found.sort();
        Ok(found)
    }

    /// Generate DDD domain layer from YAML model schemas
    fn generate_domain_layer(&self, result: &mut GenerationResult) -> Result<()> {
        use crate::webgen::generators::DomainGenerator;
        use crate::webgen::ast::HookSchema;

        let schema_dir = self.config.schema_dir();
        let models_dir = schema_dir.join("models");
        let hooks_dir = schema_dir.join("hooks");

        if !models_dir.exists() {
            // No models directory, skip
            return Ok(());
        }

        // Find all .model.yaml files
        let model_files = self.find_yaml_files(&models_dir, "model")?;
        if model_files.is_empty() {
            return Ok(());
        }

        let mut all_entities = Vec::new();
        let mut all_enums = Vec::new();

        for model_file in &model_files {
            match ModelParser::parse_file(model_file) {
                Ok(schema) => {
                    all_entities.extend(schema.models);
                    all_enums.extend(schema.enums);
                }
                Err(e) => {
                    eprintln!("Warning: Failed to parse model {}: {}", model_file.display(), e);
                }
            }
        }

        if all_entities.is_empty() {
            return Ok(());
        }

        // Parse hook schemas
        let mut all_hooks: Vec<HookSchema> = Vec::new();
        if hooks_dir.exists() {
            let hook_files = self.find_yaml_files(&hooks_dir, "hook")?;
            for hook_file in &hook_files {
                match HookParser::parse_file(hook_file) {
                    Ok(hook) => all_hooks.push(hook),
                    Err(e) => {
                        eprintln!("Warning: Failed to parse hook {}: {}", hook_file.display(), e);
                    }
                }
            }
        }

        // Create domain generator and generate
        let domain_generator = DomainGenerator::new(self.config.clone());
        let domain_result = domain_generator.generate_all(&all_entities, &all_enums, &all_hooks)?;

        // Update result counts
        result.entities_found = domain_result.entity_count;

        // Merge generated files
        if self.config.dry_run {
            result.dry_run_files.extend(domain_result.dry_run_files);
        } else {
            result.files_generated.extend(domain_result.files_generated);
        }

        Ok(())
    }

    /// Generate presentation layer from YAML model schemas
    fn generate_presentation_layer(&self, result: &mut GenerationResult) -> Result<()> {
        use crate::webgen::generators::PresentationGenerator;
        use crate::webgen::ast::HookSchema;

        let schema_dir = self.config.schema_dir();
        let models_dir = schema_dir.join("models");
        let hooks_dir = schema_dir.join("hooks");

        if !models_dir.exists() {
            return Ok(());
        }

        let model_files = self.find_yaml_files(&models_dir, "model")?;
        if model_files.is_empty() {
            return Ok(());
        }

        let mut all_entities = Vec::new();
        let mut all_enums = Vec::new();

        for model_file in &model_files {
            match ModelParser::parse_file(model_file) {
                Ok(schema) => {
                    all_entities.extend(schema.models);
                    all_enums.extend(schema.enums);
                }
                Err(e) => {
                    eprintln!("Warning: Failed to parse model {}: {}", model_file.display(), e);
                }
            }
        }

        if all_entities.is_empty() {
            return Ok(());
        }

        // Parse hook schemas
        let mut all_hooks: Vec<HookSchema> = Vec::new();
        if hooks_dir.exists() {
            let hook_files = self.find_yaml_files(&hooks_dir, "hook")?;
            for hook_file in &hook_files {
                match HookParser::parse_file(hook_file) {
                    Ok(hook) => all_hooks.push(hook),
                    Err(e) => {
                        eprintln!("Warning: Failed to parse hook {}: {}", hook_file.display(), e);
                    }
                }
            }
        }

        let presentation_generator = PresentationGenerator::new(self.config.clone());
        let presentation_result = presentation_generator.generate_all(&all_entities, &all_enums, &all_hooks)?;

        if self.config.dry_run {
            result.dry_run_files.extend(presentation_result.dry_run_files);
        } else {
            result.files_generated.extend(presentation_result.files_generated);
        }

        Ok(())
    }

    /// Generate application layer from YAML model schemas
    fn generate_application_layer(&self, result: &mut GenerationResult) -> Result<()> {
        use crate::webgen::generators::ApplicationGenerator;
        use crate::webgen::ast::HookSchema;

        let schema_dir = self.config.schema_dir();
        let models_dir = schema_dir.join("models");
        let hooks_dir = schema_dir.join("hooks");

        if !models_dir.exists() {
            return Ok(());
        }

        let model_files = self.find_yaml_files(&models_dir, "model")?;
        if model_files.is_empty() {
            return Ok(());
        }

        let mut all_entities = Vec::new();
        let mut all_enums = Vec::new();

        for model_file in &model_files {
            match ModelParser::parse_file(model_file) {
                Ok(schema) => {
                    all_entities.extend(schema.models);
                    all_enums.extend(schema.enums);
                }
                Err(e) => {
                    eprintln!("Warning: Failed to parse model {}: {}", model_file.display(), e);
                }
            }
        }

        if all_entities.is_empty() {
            return Ok(());
        }

        // Parse hook schemas
        let mut all_hooks: Vec<HookSchema> = Vec::new();
        if hooks_dir.exists() {
            let hook_files = self.find_yaml_files(&hooks_dir, "hook")?;
            for hook_file in &hook_files {
                match HookParser::parse_file(hook_file) {
                    Ok(hook) => all_hooks.push(hook),
                    Err(e) => {
                        eprintln!("Warning: Failed to parse hook {}: {}", hook_file.display(), e);
                    }
                }
            }
        }

        let application_generator = ApplicationGenerator::new(self.config.clone());
        let application_result = application_generator.generate_all(&all_entities, &all_enums, &all_hooks)?;

        if self.config.dry_run {
            result.dry_run_files.extend(application_result.dry_run_files);
        } else {
            result.files_generated.extend(application_result.files_generated);
        }

        Ok(())
    }

    /// Generate infrastructure layer from YAML model schemas
    fn generate_infrastructure_layer(&self, result: &mut GenerationResult) -> Result<()> {
        use crate::webgen::generators::InfrastructureGenerator;

        let schema_dir = self.config.schema_dir();
        let models_dir = schema_dir.join("models");

        if !models_dir.exists() {
            return Ok(());
        }

        let model_files = self.find_yaml_files(&models_dir, "model")?;
        if model_files.is_empty() {
            return Ok(());
        }

        let mut all_entities = Vec::new();
        let mut all_enums = Vec::new();

        for model_file in &model_files {
            match ModelParser::parse_file(model_file) {
                Ok(schema) => {
                    all_entities.extend(schema.models);
                    all_enums.extend(schema.enums);
                }
                Err(e) => {
                    eprintln!("Warning: Failed to parse model {}: {}", model_file.display(), e);
                }
            }
        }

        if all_entities.is_empty() {
            return Ok(());
        }

        let infrastructure_generator = InfrastructureGenerator::new(self.config.clone());
        let infrastructure_result = infrastructure_generator.generate_all(&all_entities, &all_enums)?;

        if self.config.dry_run {
            result.dry_run_files.extend(infrastructure_result.dry_run_files);
        } else {
            result.files_generated.extend(infrastructure_result.files_generated);
        }

        Ok(())
    }
}

/// Result of code generation
#[derive(Debug, Default, Clone)]
pub struct GenerationResult {
    /// Number of entities found
    pub entities_found: usize,
    /// Files that were generated
    pub files_generated: Vec<PathBuf>,
    /// Files that would be generated in dry run
    pub dry_run_files: Vec<PathBuf>,
    /// Number of files skipped
    pub skipped: usize,
}

impl GenerationResult {
    /// Get a summary of the generation result
    pub fn summary(&self) -> String {
        if self.dry_run_files.is_empty() {
            format!(
                "Generated {} files for {} entities",
                self.files_generated.len(),
                self.entities_found
            )
        } else {
            format!(
                "Would generate {} files for {} entities (dry run)",
                self.dry_run_files.len(),
                self.entities_found
            )
        }
    }
}
