//! gRPC client generator
//!
//! Generates TypeScript gRPC client wrappers using nice-grpc-web.

use std::fs;

use crate::webgen::ast::entity::{EntityDefinition, EnumDefinition};
use crate::webgen::config::Config;
use crate::webgen::error::Result;
use crate::webgen::parser::{to_pascal_case, to_snake_case, to_camel_case};
use crate::webgen::generators::domain::DomainGenerationResult;

/// Generator for gRPC client implementations
pub struct GrpcClientGenerator {
    config: Config,
}

impl GrpcClientGenerator {
    /// Create a new gRPC client generator
    pub fn new(config: Config) -> Self {
        Self { config }
    }

    /// Generate gRPC client for an entity
    pub fn generate(
        &self,
        entity: &EntityDefinition,
        _enums: &[EnumDefinition],
    ) -> Result<DomainGenerationResult> {
        let mut result = DomainGenerationResult::new();

        let _entity_pascal = to_pascal_case(&entity.name);
        let grpc_dir = self.config.output_dir
            .join("infrastructure")
            .join("grpc")
            .join("modules")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&grpc_dir).ok();
        }

        // Generate gRPC service file
        let content = self.generate_grpc_service_content(entity);
        let file_path = grpc_dir.join(format!("{}.ts", to_snake_case(&entity.name)));

        result.add_file(file_path.clone(), self.config.dry_run);

        if !self.config.dry_run {
            fs::write(&file_path, content).ok();
        }

        Ok(result)
    }

    /// Generate the main module index that exports all services
    pub fn generate_module_index(
        &self,
        entities: &[EntityDefinition],
    ) -> Result<DomainGenerationResult> {
        let mut result = DomainGenerationResult::new();

        let grpc_dir = self.config.output_dir
            .join("infrastructure")
            .join("grpc")
            .join("modules")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&grpc_dir).ok();
        }

        let content = self.generate_module_index_content(entities);
        let file_path = grpc_dir.join("index.ts");

        result.add_file(file_path.clone(), self.config.dry_run);

        if !self.config.dry_run {
            fs::write(&file_path, content).ok();
        }

        Ok(result)
    }

    /// Generate gRPC service content for an entity
    fn generate_grpc_service_content(&self, entity: &EntityDefinition) -> String {
        let entity_pascal = to_pascal_case(&entity.name);
        let entity_camel = to_camel_case(&entity.name);
        let entity_snake = to_snake_case(&entity.name);
        let module = &self.config.module;

        format!(
r#"/**
 * {entity_pascal} gRPC Client
 *
 * gRPC-web client for {entity_pascal} entity operations.
 * Generated by metaphor-webgen.
 *
 * @module infrastructure/grpc/modules/{module}/{entity_snake}
 */

import {{
  createPromiseClient,
  transport,
}} from 'nice-grpc-web';
import {{
  {entity_pascal}Service,
}} from '@webapp/domain/{module}/service/{entity_pascal}Service';
import type {{
  {entity_pascal},
  Create{entity_pascal}Input,
  Update{entity_pascal}Input,
  {entity_pascal}QueryParams,
  {entity_pascal}FilterParams,
}} from '@webapp/domain/{module}/entity/{entity_pascal}.schema';
import {{ getGrpcChannel, grpcClientFactory }} from '@webapp/infrastructure/grpc';

// ============================================================================
// Proto Service Definition
// ============================================================================

/**
 * {entity_pascal} Service definition
 * This would be replaced by actual proto-generated types
 */
interface {entity_pascal}ServiceDefinition {{
  list: (request: List{entity_pascal}Request) => Promise<List{entity_pascal}Response>;
  get: (request: Get{entity_pascal}Request) => Promise<{entity_pascal}>;
  create: (request: Create{entity_pascal}Request) => Promise<{entity_pascal}>;
  update: (request: Update{entity_pascal}Request) => Promise<{entity_pascal}>;
  delete: (request: Delete{entity_pascal}Request) => Promise<{{}}>;
}}

// ============================================================================
// Request/Response Types
// ============================================================================

interface List{entity_pascal}Request {{
  pagination?: {{
    page?: number;
    pageSize?: number;
  }};
  filter?: {entity_pascal}FilterParams;
  sort?: {{
    field?: string;
    direction?: 'ASC' | 'DESC';
  }};
}}

interface List{entity_pascal}Response {{
  data: {entity_pascal}[];
  total: number;
  page: number;
  pageSize: number;
}}

interface Get{entity_pascal}Request {{
  id: string;
}}

interface Create{entity_pascal}Request extends Create{entity_pascal}Input {{}}

interface Update{entity_pascal}Request {{
  id: string;
  data: Update{entity_pascal}Input;
}}

interface Delete{entity_pascal}Request {{
  id: string;
}}

// ============================================================================
// Client Implementation
// ============================================================================

/**
 * Create {entity_pascal} gRPC client
 */
function create{entity_pascal}Client() {{
  const channel = getGrpcChannel();
  const client = grpcClientFactory.create<{entity_pascal}ServiceDefinition>(
    // @ts-ignore - Proto definition loaded at runtime
    {{}},
    channel,
  );
  return client;
}}

/**
 * {entity_pascal} client singleton
 */
let {entity_camel}ClientInstance: ReturnType<typeof create{entity_pascal}Client> | null = null;

function get{entity_pascal}Client() {{
  if (!{entity_camel}ClientInstance) {{
    {entity_camel}ClientInstance = create{entity_pascal}Client();
  }}
  return {entity_camel}ClientInstance;
}}

// ============================================================================
// Service Implementation
// ============================================================================

/**
 * {entity_pascal} gRPC Service
 * Implements the {entity_pascal}Service interface using gRPC
 */
export const {entity_camel}Service: {entity_pascal}Service = {{
  /**
   * Get {entity_pascal} by ID
   */
  async get(request: Get{entity_pascal}Request): Promise<{entity_pascal}> {{
    const client = get{entity_pascal}Client();
    const response = await client.get(request);
    return response as {entity_pascal};
  }},

  /**
   * List {entity_pascal} entities
   */
  async list{entity_pascal}(params?: {entity_pascal}QueryParams): Promise<{{
    data: {entity_pascal}[];
    total: number;
  }}> {{
    const client = get{entity_pascal}Client();
    const request: List{entity_pascal}Request = {{
      pagination: params?.pagination,
      filter: params?.filter,
      sort: params?.sort ? {{
        field: params.sort.field,
        direction: params.sort.direction || 'ASC',
      }} : undefined,
    }};
    const response = await client.list(request);
    return {{
      data: response.data,
      total: response.total,
    }};
  }},

  /**
   * Create {entity_pascal}
   */
  async create{entity_pascal}(input: Create{entity_pascal}Input): Promise<{entity_pascal}> {{
    const client = get{entity_pascal}Client();
    const request: Create{entity_pascal}Request = input;
    const response = await client.create(request);
    return response as {entity_pascal};
  }},

  /**
   * Update {entity_pascal}
   */
  async update{entity_pascal}(id: string, input: Update{entity_pascal}Input): Promise<{entity_pascal}> {{
    const client = get{entity_pascal}Client();
    const request: Update{entity_pascal}Request = {{ id, data: input }};
    const response = await client.update(request);
    return response as {entity_pascal};
  }},

  /**
   * Delete {entity_pascal}
   */
  async delete{entity_pascal}(id: string): Promise<void> {{
    const client = get{entity_pascal}Client();
    const request: Delete{entity_pascal}Request = {{ id }};
    await client.delete(request);
  }},

  /**
   * Check if {entity_pascal} exists
   */
  async exists(id: string): Promise<boolean> {{
    try {{
      await this.get({{ id }});
      return true;
    }} catch (error) {{
      return false;
    }}
  }},

  /**
   * Count {entity_pascal} entities
   */
  async count(filter?: {entity_pascal}FilterParams): Promise<number> {{
    const response = await this.list{entity_pascal}({{ filter, pagination: {{ pageSize: 1 }} }});
    return response.total;
  }}
}};

export default {entity_camel}Service;
"#
        )
    }

    /// Generate module index content
    fn generate_module_index_content(&self, entities: &[EntityDefinition]) -> String {
        let imports: Vec<String> = entities.iter()
            .map(|e| {
                let entity_camel = to_camel_case(&e.name);
                let entity_snake = to_snake_case(&e.name);
                format!(
                    "import {{ {}Service }} from './{}';",
                    entity_camel, entity_snake
                )
            })
            .collect();

        // Generate the combined service object with all methods
        let service_methods: Vec<String> = entities.iter()
            .map(|e| {
                let entity_pascal = to_pascal_case(&e.name);
                let entity_camel = to_camel_case(&e.name);
                format!(
                    "  // {entity_pascal} methods\n  get{entity_pascal}: {entity_camel}Service.get,\n  list{entity_pascal}: {entity_camel}Service.list{entity_pascal},\n  create{entity_pascal}: {entity_camel}Service.create{entity_pascal},\n  update{entity_pascal}: {entity_camel}Service.update{entity_pascal},\n  delete{entity_pascal}: {entity_camel}Service.delete{entity_pascal},"
                )
            })
            .collect();

        let module = &self.config.module;
        let module_camel = if module == "sapiens" {
            "sapiens".to_string()
        } else {
            to_camel_case(module)
        };

        format!(
"/**
 * gRPC Services for {} module
 *
 * Exports all gRPC service clients for {} entities.
 * Generated by metaphor-webgen.
 */

{}

/**
 * Combined service object that aggregates all entity services
 * This provides a single entry point for all {} operations
 */
export const {}Service = {{
{}
}};

/**
 * Default export - the combined service
 */
export default {}Service;
",
            module,
            module,
            imports.join("\n"),
            module,
            module_camel,
            service_methods.join("\n"),
            module_camel
        )
    }
}
