//! Infrastructure layer generators
//!
//! Generates:
//! - gRPC client implementations
//! - API client implementations (REST fallback)
//! - Repository implementations
//! - Service initialization
//! - External service adapters

mod grpc_client;
mod api_client;
mod repository_impl;
mod service_init;

pub use grpc_client::GrpcClientGenerator;
pub use api_client::ApiClientGenerator;
pub use repository_impl::RepositoryImplGenerator;
pub use service_init::ServiceInitGenerator;

use std::fs;

use crate::webgen::ast::entity::{EntityDefinition, EnumDefinition};
use crate::webgen::config::Config;
use crate::webgen::error::Result;
use crate::webgen::generators::domain::DomainGenerationResult;
use crate::webgen::parser::to_pascal_case;

/// Infrastructure layer generator
pub struct InfrastructureGenerator {
    grpc_client_gen: GrpcClientGenerator,
    api_client_gen: ApiClientGenerator,
    repository_impl_gen: RepositoryImplGenerator,
    service_init_gen: ServiceInitGenerator,
    config: Config,
}

impl InfrastructureGenerator {
    /// Create a new infrastructure generator
    pub fn new(config: Config) -> Self {
        Self {
            grpc_client_gen: GrpcClientGenerator::new(config.clone()),
            api_client_gen: ApiClientGenerator::new(config.clone()),
            repository_impl_gen: RepositoryImplGenerator::new(config.clone()),
            service_init_gen: ServiceInitGenerator::new(config.clone()),
            config,
        }
    }

    /// Generate all infrastructure layer components
    pub fn generate_all(
        &self,
        entities: &[EntityDefinition],
        enums: &[EnumDefinition],
    ) -> Result<DomainGenerationResult> {
        let mut result = DomainGenerationResult::new();

        // Generate for each entity
        for entity in entities {
            // gRPC client (primary)
            let grpc_result = self.grpc_client_gen.generate(entity, enums)?;
            self.merge_result(&mut result, grpc_result);

            // API client (REST fallback - optional, can be disabled)
            let api_result = self.api_client_gen.generate(entity, enums)?;
            self.merge_result(&mut result, api_result);

            // Repository implementation
            let repo_result = self.repository_impl_gen.generate(entity, enums)?;
            self.merge_result(&mut result, repo_result);
        }

        // Generate index files
        self.generate_index_files(entities, &mut result)?;

        // Generate gRPC module index
        let grpc_index = self.grpc_client_gen.generate_module_index(entities)?;
        self.merge_result(&mut result, grpc_index);

        // Generate service initializer
        let service_init_result = self.service_init_gen.generate(entities, enums)?;
        self.merge_result(&mut result, service_init_result);

        Ok(result)
    }

    /// Merge a sub-result into the main result
    fn merge_result(&self, main: &mut DomainGenerationResult, sub: DomainGenerationResult) {
        main.files_generated.extend(sub.files_generated);
        main.dry_run_files.extend(sub.dry_run_files);
    }

    /// Generate index files for infrastructure layer
    fn generate_index_files(
        &self,
        entities: &[EntityDefinition],
        result: &mut DomainGenerationResult,
    ) -> Result<()> {
        let base_dir = self.config.output_dir
            .join("infrastructure")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&base_dir).ok();
        }

        // Generate main index
        let index_content = self.generate_index_content(entities);
        let index_path = base_dir.join("index.ts");

        result.add_file(index_path.clone(), self.config.dry_run);
        if !self.config.dry_run {
            fs::write(&index_path, index_content).ok();
        }

        Ok(())
    }

    fn generate_index_content(&self, entities: &[EntityDefinition]) -> String {
        let exports: Vec<String> = entities.iter()
            .map(|e| {
                let pascal = to_pascal_case(&e.name);
                format!(
                    "export * from './repository/{pascal}RepositoryImpl';",
                    pascal = pascal
                )
            })
            .collect();

        format!(
            "// Infrastructure layer exports for {} module\n// Generated by metaphor-webgen\n// Note: gRPC clients are exported from grpc/modules/{}\n\n{}\n",
            self.config.module,
            self.config.module,
            exports.join("\n")
        )
    }
}
