//! Service initializer generator
//!
//! Generates a centralized service initialization file that registers
//! all entity services with their API client implementations.

use std::fs;
use std::path::PathBuf;

use crate::webgen::ast::entity::{EntityDefinition, EnumDefinition};
use crate::webgen::config::Config;
use crate::webgen::error::Result;
use crate::webgen::generators::domain::DomainGenerationResult;
use crate::webgen::parser::to_pascal_case;

/// Generator for service initialization file
pub struct ServiceInitGenerator {
    config: Config,
}

impl ServiceInitGenerator {
    /// Create a new service init generator
    pub fn new(config: Config) -> Self {
        Self { config }
    }

    /// Generate the service initialization file for all entities
    pub fn generate(
        &self,
        entities: &[EntityDefinition],
        _enums: &[EnumDefinition],
    ) -> Result<DomainGenerationResult> {
        let mut result = DomainGenerationResult::new();

        let init_dir = self.config.output_dir
            .join("infrastructure")
            .join(&self.config.module);

        if !self.config.dry_run {
            fs::create_dir_all(&init_dir).ok();
        }

        let file_path = init_dir.join("initServices.ts");

        // Check if file exists and preserve custom code
        let existing_custom = self.extract_custom_code(&file_path);
        let content = self.generate_init_content(entities, existing_custom);

        result.add_file(file_path.clone(), self.config.dry_run);

        if !self.config.dry_run {
            fs::write(&file_path, content).ok();
        }

        Ok(result)
    }

    /// Extract custom code from existing file if it exists
    fn extract_custom_code(&self, file_path: &PathBuf) -> Option<String> {
        if let Ok(content) = fs::read_to_string(file_path) {
            if let Some(start) = content.find("// <<< CUSTOM") {
                if let Some(end) = content.find("// END CUSTOM") {
                    let custom_start = content[start..].find('\n').map(|i| start + i + 1)?;
                    let custom_content = &content[custom_start..end];
                    if !custom_content.trim().is_empty() {
                        return Some(custom_content.to_string());
                    }
                }
            }
        }
        None
    }

    /// Generate the init file content
    fn generate_init_content(&self, entities: &[EntityDefinition], existing_custom: Option<String>) -> String {
        let module = &self.config.module;

        // Generate imports for services
        let service_imports: Vec<String> = entities.iter()
            .map(|e| {
                let pascal = to_pascal_case(&e.name);
                format!(
                    "import {{ set{pascal}Service }} from '@webapp/domain/{module}/service/{pascal}Service';",
                    pascal = pascal,
                    module = module,
                )
            })
            .collect();

        // Generate imports for API clients
        let api_client_imports: Vec<String> = entities.iter()
            .map(|e| {
                let pascal = to_pascal_case(&e.name);
                format!(
                    "import {{ get{pascal}ApiClient }} from './api/{pascal}ApiClient';",
                    pascal = pascal,
                )
            })
            .collect();

        // Generate service registration calls
        let service_registrations: Vec<String> = entities.iter()
            .map(|e| {
                let pascal = to_pascal_case(&e.name);
                format!(
                    "  set{pascal}Service(get{pascal}ApiClient());",
                    pascal = pascal,
                )
            })
            .collect();

        let custom_section = existing_custom.unwrap_or_default();

        format!(
r#"/**
 * Service Initialization for {module} module
 *
 * This file initializes all domain services with their API client implementations.
 * Import this file once at application startup (e.g., in main.tsx).
 *
 * Generated by metaphor-webgen. Custom code preserved between markers.
 *
 * @module infrastructure/{module}/initServices
 */

// Service setters
{service_imports}

// API client factories
{api_client_imports}

/**
 * Initialize all {module} services with their API client implementations.
 * Call this function once at application startup.
 */
export function init{module_pascal}Services(): void {{
{service_registrations}
}}

// Auto-initialize on import (optional - comment out if you prefer explicit initialization)
init{module_pascal}Services();

// <<< CUSTOM: Add custom service initialization here
{custom_section}// END CUSTOM
"#,
            module = module,
            module_pascal = to_pascal_case(module),
            service_imports = service_imports.join("\n"),
            api_client_imports = api_client_imports.join("\n"),
            service_registrations = service_registrations.join("\n"),
            custom_section = custom_section,
        )
    }
}
