//! Migration-file helpers: ownership detection, filename parsing, and a
//! single-pass on-disk index used to stabilize migration timestamps.
//!
//! Concerns living here, all keyed on filesystem-level inspection of
//! `migrations/*.{up,down}.sql` files:
//!
//! 1. [`is_generator_authored_migration`] — does this file carry the
//!    `-- Generated by metaphor-schema` header? Used by the `--force`
//!    cleanup pass to delete only files the generator owns, and by
//!    [`build_migration_index`] to decide which on-disk migrations are safe
//!    to reuse (hand-written, no-marker files are never reused).
//! 2. [`is_unstable_timestamped_migration`] — does this path match the
//!    timestamp-prefixed migration filename pattern? Used by the
//!    stabilization pass to find generated migrations to remap.
//! 3. [`build_migration_index`] — single-pass scan producing the max
//!    timestamp and a map of generator-authored migration base names to
//!    their on-disk timestamp. Drives the stabilization pass, which is the
//!    SOLE authority for migration identity/timestamp stability — the write
//!    phase is a dumb writer that trusts the stabilized paths.

use std::fs;
use std::path::Path;

/// Whether a migration file looks like one this generator wrote.
///
/// Generated migrations carry a `-- Generated by metaphor-schema` header line
/// emitted by the SQL templates. Hand-written migrations (audit triggers,
/// backfills, ad-hoc data fixes) lack this marker. The cleanup pass uses
/// this signal to delete only files the generator owns, leaving manual ones
/// untouched even when they share the `NNN_*.up.sql` numbering convention.
///
/// We scan only the first few lines so we don't read large migration bodies.
/// If the file can't be read (permissions, race), we conservatively treat it
/// as NOT generator-authored (keep the file).
pub(super) fn is_generator_authored_migration(path: &Path) -> bool {
    let Ok(content) = fs::read_to_string(path) else {
        return false;
    };
    content
        .lines()
        .take(10)
        .any(|line| line.contains("Generated by metaphor-schema"))
}

/// Returns true when `path` is a migration file whose timestamp prefix is
/// regenerated on every run (and therefore won't match an existing file's
/// path even when the same logical migration already exists on disk).
///
/// Pattern: lives under a `migrations/` directory, filename of the form
/// `<14-digit-timestamp>_<identity>.up.sql` or `<...>.down.sql`.
pub(super) fn is_unstable_timestamped_migration(path: &Path) -> bool {
    // Must be inside a directory literally named "migrations".
    let parent_name = path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str());
    if parent_name != Some("migrations") {
        return false;
    }

    let name = match path.file_name().and_then(|n| n.to_str()) {
        Some(n) => n,
        None => return false,
    };
    if !(name.ends_with(".up.sql") || name.ends_with(".down.sql")) {
        return false;
    }
    // Need at least: 14-digit timestamp + '_' + 1 char of identity + extension.
    if name.len() < 16 {
        return false;
    }
    let (prefix, rest) = name.split_at(14);
    if !prefix.chars().all(|c| c.is_ascii_digit()) {
        return false;
    }
    rest.starts_with('_')
}

/// The 14-digit timestamp prefix of a timestamped migration filename, when the
/// name starts with `<14-digits>_`. `20260426220110_create_company_table.up.sql`
/// → `Some("20260426220110")`. `None` for anything not in this form.
pub(super) fn migration_timestamp_prefix(name: &str) -> Option<&str> {
    if name.len() < 16 {
        return None;
    }
    let (prefix, rest) = name.split_at(14);
    if prefix.chars().all(|c| c.is_ascii_digit()) && rest.starts_with('_') {
        Some(prefix)
    } else {
        None
    }
}

/// The base name of a timestamped migration — the identity shared by its
/// up/down pair, with the timestamp prefix and the direction suffix removed.
/// `20260426220110_create_company_table.up.sql` → `create_company_table`;
/// `20260426220007_add_audit_triggers.up.sql` → `add_audit_triggers`.
/// `None` if the name isn't a valid timestamped migration filename.
pub(super) fn migration_base_name(name: &str) -> Option<&str> {
    migration_timestamp_prefix(name)?;
    let rest = name.splitn(2, '_').nth(1)?;
    rest.strip_suffix(".up.sql")
        .or_else(|| rest.strip_suffix(".down.sql"))
}

/// The direction suffix of a timestamped migration: `.up.sql` or `.down.sql`.
/// `None` if the name isn't a valid timestamped migration filename.
pub(super) fn migration_direction(name: &str) -> Option<&'static str> {
    migration_timestamp_prefix(name)?;
    let rest = name.splitn(2, '_').nth(1)?;
    if rest.ends_with(".up.sql") {
        Some(".up.sql")
    } else if rest.ends_with(".down.sql") {
        Some(".down.sql")
    } else {
        None
    }
}

/// Index of the on-disk migrations in a directory, built in a single pass.
///
/// `max_ts` is the latest timestamp present (or `None` when the dir holds no
/// timestamped files). `authored` maps the **base name** of each
/// GENERATOR-AUTHORED migration (its `.up.sql` carries the
/// `-- Generated by metaphor-schema` marker — down files never carry it) to
/// the minimum timestamp under which it appears.
///
/// Stabilization uses this to (a) reuse a stable timestamp for migrations the
/// generator already owns, and (b) never reuse a timestamp from a hand-written
/// (no-marker) migration, which the `--force` cleanup pass must preserve.
#[derive(Debug, Default)]
pub(super) struct MigrationIndex {
    pub(super) max_ts: Option<String>,
    pub(super) authored: std::collections::HashMap<String, String>,
}

/// Single-pass scan of `migrations_dir`. Always returns an index (empty on
/// read failure); callers check `max_ts` to decide whether there is anything
/// to stabilize against.
pub(super) fn build_migration_index(migrations_dir: &Path) -> MigrationIndex {
    let mut index = MigrationIndex::default();
    let Ok(entries) = fs::read_dir(migrations_dir) else {
        return index;
    };
    for entry in entries.flatten() {
        let fname = entry.file_name();
        let Some(name) = fname.to_str() else {
            continue;
        };
        let Some(ts) = migration_timestamp_prefix(name) else {
            continue;
        };
        // Track the maximum timestamp across all timestamped files.
        match &index.max_ts {
            None => index.max_ts = Some(ts.to_string()),
            Some(cur) if ts > cur.as_str() => index.max_ts = Some(ts.to_string()),
            _ => {}
        }
        // Track generator-authored base names → min timestamp. The marker lives
        // only in `.up.sql` files; a down is generator-authored iff its up is.
        let Some(base) = migration_base_name(name) else {
            continue;
        };
        if name.ends_with(".up.sql") && is_generator_authored_migration(&entry.path()) {
            match index.authored.get(base) {
                None => {
                    index.authored.insert(base.to_string(), ts.to_string());
                }
                Some(cur) if ts < cur.as_str() => {
                    index.authored.insert(base.to_string(), ts.to_string());
                }
                _ => {}
            }
        }
    }
    index
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn is_unstable_timestamped_migration_recognises_create_table_up() {
        let p = PathBuf::from("/x/migrations/20260426220110_create_provider_staff_table.up.sql");
        assert!(is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_recognises_create_table_down() {
        let p = PathBuf::from("/x/migrations/20260426220110_create_provider_staff_table.down.sql");
        assert!(is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_recognises_audit_triggers() {
        // audit_triggers migrations also get a fresh timestamp on every regen.
        let p = PathBuf::from("/x/migrations/20260426220007_add_audit_triggers.up.sql");
        assert!(is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_requires_migrations_parent_dir() {
        // Same filename pattern but outside `migrations/` → not a migration.
        let p = PathBuf::from("/x/somewhere_else/20260426220110_create_foo_table.up.sql");
        assert!(!is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_rejects_non_migration_file() {
        let p = PathBuf::from("/x/src/domain/entity/provider_staff.rs");
        assert!(!is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_rejects_short_or_non_numeric_prefix() {
        // Not 14 digits
        assert!(!is_unstable_timestamped_migration(&PathBuf::from(
            "/x/migrations/2026_create_foo_table.up.sql"
        )));
        // Letters in the prefix
        assert!(!is_unstable_timestamped_migration(&PathBuf::from(
            "/x/migrations/20260426220a10_create_foo_table.up.sql"
        )));
    }

    #[test]
    fn migration_timestamp_prefix_parses_14_digit_prefix() {
        assert_eq!(
            migration_timestamp_prefix("20260426220110_create_company_table.up.sql"),
            Some("20260426220110")
        );
        // Too short / non-numeric prefix
        assert_eq!(migration_timestamp_prefix("2026_create_foo.up.sql"), None);
        assert_eq!(
            migration_timestamp_prefix("20260426220a10_create_foo.up.sql"),
            None
        );
    }

    #[test]
    fn migration_base_name_strips_timestamp_and_direction() {
        assert_eq!(
            migration_base_name("20260426220110_create_company_table.up.sql"),
            Some("create_company_table")
        );
        assert_eq!(
            migration_base_name("20260426220110_create_company_table.down.sql"),
            Some("create_company_table")
        );
        assert_eq!(
            migration_base_name("20260426220007_add_audit_triggers.up.sql"),
            Some("add_audit_triggers")
        );
        assert_eq!(migration_base_name("not_a_migration.rs"), None);
    }

    #[test]
    fn migration_direction_detects_up_and_down() {
        assert_eq!(
            migration_direction("20260426220110_create_company_table.up.sql"),
            Some(".up.sql")
        );
        assert_eq!(
            migration_direction("20260426220110_create_company_table.down.sql"),
            Some(".down.sql")
        );
        assert_eq!(migration_direction("not_a_migration.rs"), None);
    }

    #[test]
    fn build_migration_index_records_authored_and_max() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        // Generator-authored (has marker)
        std::fs::write(
            dir.join("20260426220001_create_company_table.up.sql"),
            "-- Generated by metaphor-schema\n",
        )
        .unwrap();
        // Hand-written (no marker) — must NOT be in `authored`
        std::fs::write(dir.join("20240101120000_create_user_table.up.sql"), "-- hand\n").unwrap();
        // A down file (no marker by convention) — its base is authored via the up
        std::fs::write(
            dir.join("20260426220001_create_company_table.down.sql"),
            "-- down\n",
        )
        .unwrap();

        let index = build_migration_index(dir);
        assert_eq!(index.max_ts.as_deref(), Some("20260426220001"));
        assert_eq!(
            index.authored.get("create_company_table").map(|s| s.as_str()),
            Some("20260426220001")
        );
        // Hand-written base is not reused.
        assert!(!index.authored.contains_key("create_user_table"));
    }

    #[test]
    fn build_migration_index_picks_min_among_duplicate_authored() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        std::fs::write(
            dir.join("20260426220135_create_company_table.up.sql"),
            "-- Generated by metaphor-schema\n",
        )
        .unwrap();
        std::fs::write(
            dir.join("20260723180002_create_company_table.up.sql"),
            "-- Generated by metaphor-schema\n",
        )
        .unwrap();
        let index = build_migration_index(dir);
        // Min timestamp wins, deterministically.
        assert_eq!(
            index.authored.get("create_company_table").map(|s| s.as_str()),
            Some("20260426220135")
        );
        assert_eq!(index.max_ts.as_deref(), Some("20260723180002"));
    }

    #[test]
    fn build_migration_index_empty_or_missing_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let index = build_migration_index(tmp.path());
        assert!(index.max_ts.is_none());
        assert!(index.authored.is_empty());
        let index = build_migration_index(std::path::Path::new("/no/such/dir"));
        assert!(index.max_ts.is_none());
        assert!(index.authored.is_empty());
    }
}
