//! Migration-file helpers: ownership detection and timestamp-tolerant
//! identity dedup.
//!
//! Three concerns live here, all keyed on filesystem-level inspection of
//! `migrations/*.{up,down}.sql` files:
//!
//! 1. [`is_generator_authored_migration`] — does this file carry the
//!    `-- Generated by metaphor-schema` header? Used by the `--force`
//!    cleanup pass to delete only files the generator owns.
//! 2. [`is_unstable_timestamped_migration`] — does this path match the
//!    timestamp-prefixed migration filename pattern (i.e. would the next
//!    regen emit it under a *different* timestamp)?
//! 3. [`migration_identity_already_exists`] — does a sibling with the same
//!    `_<identity>.{up,down}.sql` suffix already exist under any timestamp?
//!    Used to skip re-writing the same logical migration when only the
//!    timestamp changed.

use std::fs;
use std::path::Path;

/// Whether a migration file looks like one this generator wrote.
///
/// Generated migrations carry a `-- Generated by metaphor-schema` header line
/// emitted by the SQL templates. Hand-written migrations (audit triggers,
/// backfills, ad-hoc data fixes) lack this marker. The cleanup pass uses
/// this signal to delete only files the generator owns, leaving manual ones
/// untouched even when they share the `NNN_*.up.sql` numbering convention.
///
/// We scan only the first few lines so we don't read large migration bodies.
/// If the file can't be read (permissions, race), we conservatively treat it
/// as NOT generator-authored (keep the file).
pub(super) fn is_generator_authored_migration(path: &Path) -> bool {
    let Ok(content) = fs::read_to_string(path) else {
        return false;
    };
    content
        .lines()
        .take(10)
        .any(|line| line.contains("Generated by metaphor-schema"))
}

/// Returns true when `path` is a migration file whose timestamp prefix is
/// regenerated on every run (and therefore won't match an existing file's
/// path even when the same logical migration already exists on disk).
///
/// Pattern: lives under a `migrations/` directory, filename of the form
/// `<14-digit-timestamp>_<identity>.up.sql` or `<...>.down.sql`.
pub(super) fn is_unstable_timestamped_migration(path: &Path) -> bool {
    // Must be inside a directory literally named "migrations".
    let parent_name = path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str());
    if parent_name != Some("migrations") {
        return false;
    }

    let name = match path.file_name().and_then(|n| n.to_str()) {
        Some(n) => n,
        None => return false,
    };
    if !(name.ends_with(".up.sql") || name.ends_with(".down.sql")) {
        return false;
    }
    // Need at least: 14-digit timestamp + '_' + 1 char of identity + extension.
    if name.len() < 16 {
        return false;
    }
    let (prefix, rest) = name.split_at(14);
    if !prefix.chars().all(|c| c.is_ascii_digit()) {
        return false;
    }
    rest.starts_with('_')
}

/// For a CREATE-TABLE migration filename like
/// `20260426220110_create_provider_staff_table.up.sql`,
/// returns true if any sibling file in the same directory has the same
/// `_create_<table>_table.<up|down>.sql` suffix under a different timestamp.
pub(super) fn migration_identity_already_exists(path: &Path) -> bool {
    let Some(parent) = path.parent() else {
        return false;
    };
    let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
        return false;
    };
    let Some(suffix) = migration_suffix(name) else {
        return false;
    };
    let Ok(entries) = fs::read_dir(parent) else {
        return false;
    };
    entries.flatten().any(|e| {
        let fname = e.file_name();
        let Some(other) = fname.to_str() else {
            return false;
        };
        other != name && other.ends_with(suffix)
    })
}

/// The 14-digit timestamp prefix of a timestamped migration filename, when the
/// name starts with `<14-digits>_`. `20260426220110_create_company_table.up.sql`
/// → `Some("20260426220110")`. `None` for anything not in this form.
pub(super) fn migration_timestamp_prefix(name: &str) -> Option<&str> {
    if name.len() < 16 {
        return None;
    }
    let (prefix, rest) = name.split_at(14);
    if prefix.chars().all(|c| c.is_ascii_digit()) && rest.starts_with('_') {
        Some(prefix)
    } else {
        None
    }
}

/// The logical suffix of a timestamped migration filename — everything after
/// the leading `<14-digit-ts>_`. `20260426220110_create_company_table.up.sql`
/// → `create_company_table.up.sql`. `None` if the name isn't a valid
/// timestamped migration filename.
pub(super) fn migration_suffix(name: &str) -> Option<&str> {
    migration_timestamp_prefix(name)?;
    name.splitn(2, '_').nth(1)
}

/// Scan `migrations_dir` for an existing file whose logical suffix matches
/// `suffix`, returning its 14-digit timestamp prefix (or `None` if no sibling
/// has that suffix). Used to keep a logical migration at a stable timestamp
/// across regenerations.
///
/// When multiple files share the suffix (e.g. legacy duplicate-timestamp
/// corruption left by the old positional-timestamp bug), the **minimum**
/// timestamp is returned, deterministically — independent of `read_dir`
/// iteration order. Under `--force`, the cleanup pass then removes the
/// non-minimum duplicates as stale, repairing the duplication.
pub(super) fn existing_timestamp_for_suffix(migrations_dir: &Path, suffix: &str) -> Option<String> {
    let entries = fs::read_dir(migrations_dir).ok()?;
    let mut min: Option<String> = None;
    for entry in entries.flatten() {
        let fname = entry.file_name();
        let Some(other) = fname.to_str() else {
            continue;
        };
        if migration_suffix(other) != Some(suffix) {
            continue;
        }
        let Some(ts) = migration_timestamp_prefix(other) else {
            continue;
        };
        match &min {
            None => min = Some(ts.to_string()),
            Some(cur) if ts < cur.as_str() => min = Some(ts.to_string()),
            _ => {}
        }
    }
    min
}

/// The lexicographically-maximum (== chronologically-latest) 14-digit
/// timestamp prefix among migration files in `migrations_dir`, or `None`.
pub(super) fn max_migration_timestamp(migrations_dir: &Path) -> Option<String> {
    let entries = fs::read_dir(migrations_dir).ok()?;
    let mut max: Option<String> = None;
    for entry in entries.flatten() {
        let fname = entry.file_name();
        let Some(name) = fname.to_str() else {
            continue;
        };
        let Some(ts) = migration_timestamp_prefix(name) else {
            continue;
        };
        match &max {
            None => max = Some(ts.to_string()),
            Some(cur) if ts > cur.as_str() => max = Some(ts.to_string()),
            _ => {}
        }
    }
    max
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn is_unstable_timestamped_migration_recognises_create_table_up() {
        let p = PathBuf::from("/x/migrations/20260426220110_create_provider_staff_table.up.sql");
        assert!(is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_recognises_create_table_down() {
        let p = PathBuf::from("/x/migrations/20260426220110_create_provider_staff_table.down.sql");
        assert!(is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_recognises_audit_triggers() {
        // audit_triggers migrations also get a fresh timestamp on every regen.
        let p = PathBuf::from("/x/migrations/20260426220007_add_audit_triggers.up.sql");
        assert!(is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_requires_migrations_parent_dir() {
        // Same filename pattern but outside `migrations/` → not a migration.
        let p = PathBuf::from("/x/somewhere_else/20260426220110_create_foo_table.up.sql");
        assert!(!is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_rejects_non_migration_file() {
        let p = PathBuf::from("/x/src/domain/entity/provider_staff.rs");
        assert!(!is_unstable_timestamped_migration(&p));
    }

    #[test]
    fn is_unstable_timestamped_migration_rejects_short_or_non_numeric_prefix() {
        // Not 14 digits
        assert!(!is_unstable_timestamped_migration(&PathBuf::from(
            "/x/migrations/2026_create_foo_table.up.sql"
        )));
        // Letters in the prefix
        assert!(!is_unstable_timestamped_migration(&PathBuf::from(
            "/x/migrations/20260426220a10_create_foo_table.up.sql"
        )));
    }

    #[test]
    fn migration_identity_already_exists_finds_sibling_with_different_timestamp() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        // Existing on disk under one timestamp
        std::fs::write(
            dir.join("20260426220135_create_provider_staff_table.up.sql"),
            "-- existing\n",
        )
        .unwrap();
        // New path the generator is about to write under a different timestamp
        let new_path = dir.join("20260426220110_create_provider_staff_table.up.sql");
        assert!(migration_identity_already_exists(&new_path));
    }

    #[test]
    fn migration_identity_already_exists_returns_false_when_no_sibling() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        // Empty directory — no migration for this table yet
        let new_path = dir.join("20260426220110_create_provider_staff_table.up.sql");
        assert!(!migration_identity_already_exists(&new_path));
    }

    #[test]
    fn migration_identity_already_exists_distinguishes_tables() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        // Existing migration for a DIFFERENT table
        std::fs::write(
            dir.join("20260426220135_create_provider_staff_table.up.sql"),
            "-- existing\n",
        )
        .unwrap();
        // Trying to write a migration for a different table — must not be blocked
        let new_path = dir.join("20260426220110_create_staff_earnings_table.up.sql");
        assert!(!migration_identity_already_exists(&new_path));
    }

    #[test]
    fn migration_identity_distinguishes_up_and_down() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        // Only the .up.sql exists on disk; writing .down.sql should still be allowed
        std::fs::write(
            dir.join("20260426220135_create_provider_staff_table.up.sql"),
            "-- existing\n",
        )
        .unwrap();
        let new_down = dir.join("20260426220110_create_provider_staff_table.down.sql");
        assert!(!migration_identity_already_exists(&new_down));
    }

    #[test]
    fn migration_timestamp_prefix_parses_14_digit_prefix() {
        assert_eq!(
            migration_timestamp_prefix("20260426220110_create_company_table.up.sql"),
            Some("20260426220110")
        );
        // Too short / non-numeric prefix
        assert_eq!(migration_timestamp_prefix("2026_create_foo.up.sql"), None);
        assert_eq!(
            migration_timestamp_prefix("20260426220a10_create_foo.up.sql"),
            None
        );
    }

    #[test]
    fn migration_suffix_strips_timestamp_prefix() {
        assert_eq!(
            migration_suffix("20260426220110_create_company_table.up.sql"),
            Some("create_company_table.up.sql")
        );
        assert_eq!(
            migration_suffix("20260426220007_add_audit_triggers.up.sql"),
            Some("add_audit_triggers.up.sql")
        );
        assert_eq!(migration_suffix("not_a_migration.rs"), None);
    }

    #[test]
    fn existing_timestamp_for_suffix_finds_matching_sibling() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        std::fs::write(
            dir.join("20260426220135_create_company_table.up.sql"),
            "-- existing\n",
        )
        .unwrap();
        // Same suffix under a different (or any) timestamp → returns the on-disk ts.
        assert_eq!(
            existing_timestamp_for_suffix(dir, "create_company_table.up.sql"),
            Some("20260426220135".to_string())
        );
        // No sibling with this suffix
        assert_eq!(
            existing_timestamp_for_suffix(dir, "create_industry_table.up.sql"),
            None
        );
    }

    #[test]
    fn existing_timestamp_for_suffix_picks_min_among_duplicates() {
        // Legacy duplicate-timestamp corruption: same suffix under two
        // timestamps. The result must be deterministic (the minimum),
        // independent of read_dir iteration order.
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        std::fs::write(dir.join("20260426220135_create_company_table.up.sql"), "--\n").unwrap();
        std::fs::write(dir.join("20260723180002_create_company_table.up.sql"), "--\n").unwrap();
        assert_eq!(
            existing_timestamp_for_suffix(dir, "create_company_table.up.sql"),
            Some("20260426220135".to_string())
        );
    }

    #[test]
    fn max_migration_timestamp_returns_latest() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path();
        std::fs::write(dir.join("20260426220001_create_company_table.up.sql"), "--\n").unwrap();
        std::fs::write(dir.join("20260723180002_create_industry_table.up.sql"), "--\n").unwrap();
        std::fs::write(dir.join("20260426220006_add_audit_triggers.up.sql"), "--\n").unwrap();
        // Lexicographic max == chronologically latest for this fixed-width format.
        assert_eq!(
            max_migration_timestamp(dir),
            Some("20260723180002".to_string())
        );
    }

    #[test]
    fn max_migration_timestamp_none_for_empty_or_missing() {
        let tmp = tempfile::tempdir().unwrap();
        assert_eq!(max_migration_timestamp(tmp.path()), None);
        assert_eq!(max_migration_timestamp(std::path::Path::new("/no/such/dir")), None);
    }
}
